### ISSUE TITLE
FF Bug - interiors load slower

### ISSUE THREAD

**Issue by anthoncast** [ThirteenAG/GTAIV.EFLC.FusionFix#105]
This is an actual bug related to this mod, you see, now for some reason, in TBOGT, from what I see in the intro, models from interiors load very slow... This occured many times in GTA IV (With FF or not) and now this occurs in TBOGT very frequently. So maybe it's time to check out this weird bug related to objects loading and popping up in your face. Like, somehow cut-scenes are not that well synchronized as you'd expect. Other GTA games don't have this issue, or if they do, it's not that wild as GTA IV, where this happens a lot, and sometimes it lasts 2, 3, 4 seconds.
![20230722232729_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/139528570/4e077ef3-b226-460f-ae5b-610638f57757)

**Comment by Tomasak** [comment]
can't reproduce, with or without frame limiter or vsync on

**Comment by anthoncast** [comment]
What you mean? I wasn't following, sorry. But yeah, the problem is related more to the models loading a few more seconds than they should, and it's a little bit odd to see this.

**Comment by Tomasak** [comment]
ye, it doesnt happen to me

do you have frame limiter or vsync on? if its off, try with on and reproduce it. maybe loading is broken without fps limit

**Comment by anthoncast** [comment]
Both are activated, frame limiter is at 30, VSync is turned on too. Haven't tried with untied FPS and VSync off, maybe I should try that, but I doubt it'll change something

**Comment by anthoncast** [comment]
w

Yeah, it's still happening. Draw Distance and Detail, despite being at 100 it won't fix this issue. Also, yes, the FPS limit is locked, and VSync is on. Tried setting FPS to 60 and kinda fixed the issue where the Liberty Bank doors go from white to models. But it didn't solve the issue with Tony's apartment loading. Funny is that the way the models load also fit with the song playing, but of course, this is not intentional, and it is not supossed to go like that.


https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/139528570/89d18eee-8581-4bb8-abb2-91d15bea3593

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/139528570/4475b409-38df-4ce4-9d59-7cead90c6b38

**Comment by anthoncast** [comment]
BTW, before the "update folder" update, back in May or something, with or without Fusion, when the cut-scene loaded Tony's apartment, actually, somehow depended on Draw Distance. That means that if you had like, 90 percent or below in Draw Distance, Tony's apartment would load in front of your face, but if Draw Distance was like, more than 90 percent, then Tony's place would be already loaded, and cut-scene would look natural.

I understand that some cut-scenes loaded like this in console, but not every one of them, and yet they loaded faster than in the PC version. And of course, these errors didn't happen in TBOGT.

**Comment by anthoncast** [comment]
Update: Not much. recent update kinda fixed that??? In the first bank scene the doors load only if FPS are locked in 144 (same as my monitor's hz). But when setting lower FPS (60 or 30) this pop up effect is more noticeable. I tried playing with FPS options such as the framerate type and setting. Anyways, nothing worked. Tony's apartment loads fine, but I would like to have it like in the cnosole versions, where it seemed that every interior was already loaded, despite its settings (Detail 10, Distance 21).

**Comment by Tomasak** [comment]
i checked and it seems the case for me too. dunno why, however someone else reported similar or same? issue on latest update

**Comment by anthoncast** [comment]
In IV, TLAD and TBOGT there's a weird render issue where, between cut-scene camera change, models pop up, sometimes turn black. Then Night Shadows cause this issue with the water (makes it flicker depending on how camera is positioned). Now this weird issue combined with those problems makes the game look bad especially when cut-scenes play.

**Comment by Parallellines0451** [comment]
Interiors are loading slowly because you maxed out the distance sliders. Setting both to 100 causes massive pop-in issues especially after abrupt camera movements. I recommend sticking to the default PC values of 25/31 or console's 21/10.

**Comment by anthoncast** [comment]
> Interiors are loading slowly because you maxed out the distance sliders. Setting both to 100 causes massive pop-in issues especially after abrupt camera movements. I recommend sticking to the default PC values of 25/31 or console's 21/10.

Oh, I didn't get notified. Anyways, this issue seems to be fixed in 2.0 now! Kinda, because interior props load the same way as before. And Tony's apartment keeps loading interiors that slowly, even if I use the console settings or PC default values (also this happens in interiors as the one in "Do You Have Protection" mission in IV or the fire station near to Michelle's apartment, or the tunnels that connect Algonquin to Alderney). I prefer using console settings because of the performance and how it looked in my PS3, but still, I would love to see this fixed, I hope you can consider my request!

**Comment by Tomasak** [comment]
Can you redownload 2.0 and check if issue persists? there was something related to img loading fixed and it might have helped here too

**Comment by anthoncast** [comment]
I'm back again, school keeps me busy 😭

And yes, I downloaded and tried again. But I do believe this is a vanilla bug (Tony's apartment props popping up), because the rendering issues from 1.96 now are gone. Still props popping up happens very often in the PC version unlike the consoles for some reasons. For example, look at the PS3 version of TBOGT. The props issue doesn't happen even if graphic values are 21/10/33. PS3: https://youtu.be/Zc8cDrzlXwQ?si=FVRKe6o7fRwkpFmf&t=197
PC: The same clip I uploaded. But without FusionFix, if the sliders are set to 100 the props are already loaded.

Or GTA IV "Do you have protection?"
PS3: https://youtu.be/-pkfq9NYf8Y?si=B7mYdhS2DwY2FLse&t=301
PC: https://youtu.be/L3GwqEOXd-w?si=LZM9kVjy_8kYFTxz&t=288

**Comment by Tomasak** [comment]
Does this still happen?

**Comment by anthoncast** [comment]
Allow me record my game to see if the interiors bug persists on TBOGT, at least the ones caused by Fusion Fix. Maybe I'll open a new issue in the modding list regarding the ones occurring without the mod.

**Comment by Tomasak** [comment]
I have checked if view and detail sliders maxed out and i cant repro this at all, saw whole first cutscene in tbogt, no issue in bank nor in Toni's apt. (I'm using DXVK now from gtaf thread, maybe that helps too)

**Comment by anthoncast** [comment]
Hello again! Yes, I recorded my game yesterday, but then I got busy. But I can confirm that the bug is fixed! At least in 2.4.3, the version I still have. But I have no doubt it's fixed in 2.4.5 as you say. Also yes, I'm using the normal DXVK, and it's all good!
