### ISSUE TITLE
FusionFix Bug Report: Crashing when changing the FPS Limit in main menu.

### ISSUE THREAD

**Issue by anthoncast** [ThirteenAG/GTAIV.EFLC.FusionFix#107]
Here's the situation: You decide to keep the main title and intro to show when you launch the game (So before playing you can set up anything before playing). You're checking out FPS Limit options, you set the highest FPS limit (not necessarily all 144 fps, maybe just 40), but then decide to reduce the FPS, and then... a freeze, you cannot do anything, mouse locks, game just crashes at that point.

This is what happened to me, and it's more noticeable in lastest version, where this happens even faster.
![ezgif-2-d6a24f86b1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/139528570/75020515-76ad-4f21-baff-84b29fd79a9c)
The moment the GIF ends, the moment where it just freezes and crashes.

**Comment by anthoncast** [comment]
My theory about this bug is that, when changing the FPS, as that is a live change to the game, game will crash because it cannot handle the FPS changing so fast?

Which is weird because it only happens in the main screen, but in-game live changes to FPS don't crash the game.

**Comment by ThirteenAG** [comment]
Try again with new version.

**Comment by anthoncast** [comment]
That's great! Thank you AG!
