### ISSUE TITLE
Definition switch has no effect for distance DOF

### ISSUE THREAD

**Issue by sbn708** [ThirteenAG/GTAIV.EFLC.FusionFix#108]
tested on mod version 1.70
![29 07 2023_14 19 07_Fx8or8EIm0_GTAIV](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/78650588/3db59180-3e7d-4436-bb10-d58ea2cf460a)
![29 07 2023_14 19 08_UsON91pcob_GTAIV](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/78650588/1ffd3e71-8782-40e7-b83b-3205d20c1508)

**Comment by Tomasak** [comment]
dupe of #95
