### ISSUE TITLE
FusionFix Mod

### ISSUE THREAD

**Issue by kacperineusz** [ThirteenAG/GTAIV.EFLC.FusionFix#111]
.Hello, I downloaded GTA 4 and installed a mod. I put mod in: steam->properties->installed files->browse->program files->Steam->steamapps->common->GTA IV. I have no changes in the game menu regarding changing the fps limit. Everything is the same as before. What can i do ? help please
![Zrzut ekranu (56)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/91287624/ce6b961d-5a44-44ac-8798-f124f9f6cb50)
![Zrzut ekranu (57)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/91287624/5a4cdffe-b664-4541-a5ed-d67eef726efa)
![Zrzut ekranu (58)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/91287624/85f45e20-7e39-45e5-8854-ffdc21b946e5)
![Zrzut ekranu (59)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/91287624/0a15782c-a8de-4915-99b6-46c62d8151d4)

**Comment by Tomasak** [comment]
based on you pic, you didnt extract mod there 
After extracting mod to GTAIV folder two new folders should appear: plugins and update and also dinput8.dll file

**Comment by kacperineusz** [comment]
The files you're talking about are located here.
![Zrzut ekranu (60)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/91287624/4842e286-a645-4c15-ae6d-37d95e54bf53)

**Comment by CHVKWagnerPrivateModdingCompany** [comment]
check

https://www.youtube.com/watch?v=hZEv6Rcz-iQ

**Comment by kacperineusz** [comment]
> check
> 
> https://www.youtube.com/watch?v=hZEv6Rcz-iQ

thanks bro
