### ISSUE TITLE
Menu Bug (GTA IV - EFLC FusionFix)

### ISSUE THREAD

**Issue by YtaloS** [ThirteenAG/GTAIV.EFLC.FusionFix#112]
I have a bug that when I select an option to change in the game menu, it changes all options at once, example: **(i use GTA: 4 Complete Edition from Steam, downgraded to 1.0.8.0, I already tested it in 1.0.7.0 and the error also occurs).**

![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/105159224/1c040f85-a9e5-41d5-91c4-df847764edb1)
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/105159224/22a631cc-0f9f-468d-9314-ea5f6573e366)
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/105159224/4ba88090-739c-4a30-9b06-1eb700388a8a)

**Comment by ClaudeLib** [comment]
For the downgraded game you should use Zolika's fork of FF, this here only supports CE.

**Comment by Tomasak** [comment]
stop spreading misinformation
pre-ivce branch was update with features backported by zolika. and contains link to compiled asi on info page.

**Comment by YtaloS** [comment]
> stop spreading misinformation pre-ivce branch was update with features backported by zolika. and contains link to compiled asi on info page.
> 
> as for bug. this branch is however not maintained by main ff team, so either zolika or someone else will have to make pull request with fix :)

Ok man, thanks.

**Comment by SangalDigital** [comment]
Hello im new here... how do you fix this issue i have it too..

**Comment by hellowasarge** [comment]
I've got the same problem, too. The game is not modded except downgrader if it's counted as a mod. I reinstalled the game because of not working FF, that is, there is no options at the main menu from features of FF. I downgraded the game and I saw, I managed to solve this problem; however, now I have this main menu bug.

**Comment by YtaloS** [comment]
> I've got the same problem, too. The game is not modded except downgrader if it's counted as a mod. I reinstalled the game because of not working FF, that is, there is no options at the main menu from features of FF. I downgraded the game and I saw, I managed to solve this problem; however, now I have this main menu bug.

Is your GTA the Complete Edition from Steam? if so, you don't need to downgrade, because Fusion Fix doesn't work.

**Comment by YtaloS** [comment]
> I've got the same problem, too. The game is not modded except downgrader if it's counted as a mod. I reinstalled the game because of not working FF, that is, there is no options at the main menu from features of FF. I downgraded the game and I saw, I managed to solve this problem; however, now I have this main menu bug.

Is your GTA the Complete Edition from Steam? if so, you don't need to downgrade, because Fusion Fix doesn't work.
