### ISSUE TITLE
Feature Request - Walking, Jogging and Sprinting Cycle on keyboard fix?

### ISSUE THREAD

**Issue by anthoncast** [ThirteenAG/GTAIV.EFLC.FusionFix#116]
So, when using a controller, there is a cycle when moving, it depends on what you're pressing, that being moving the left stick to walk, holding 'A' to jog and finally, hitting 'A' will make the player sprint. In PC version it was very well adapter, pressing 'W', of course, to make the player walk, or holding 'SHIFT'  so the player sprints, but... what about simply Jogging? I mean, the medium speed of movement. I think it is inconsistent when you play GTA V later, clearly you have three ways to move, but in GTA IV just 2 when using a keyboard?

How about this: Make holding shift to simply run, and hitting shift to just sprint.

**Comment by Attramet** [comment]
You can add additional (second) button for running in game menu settings

**Comment by Tomasak** [comment]
Option was added to enable jogging by default with shift making player run and alt making player walk
