### ISSUE TITLE
Request for model fix Blista Compact & Intruder

### ISSUE THREAD

**Issue by MiesThies** [ThirteenAG/GTAIV.EFLC.FusionFix#117]
The Blista Compact and the Intruder have a third brake light, that doesn't look right, see pictures. Reminds me of the TBoGT vehicles on PC before they were fixed by FF.

I know that Thundersmacker fixed the Blista in this recent mod:
https://www.gtainside.com/gta4/cars/188730-resized-blista-compact/

BUT, that also changes the size and therefore a vehicles.ide change is also needed, which I would prefer to skip.

So maybe these models could be fixed :)

![Intruder](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/de862486-6a20-42d6-8a55-870615794336)
![Blista](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/09762087-8bea-4b72-8bde-3df25434978a)

**Comment by Tomasak** [comment]
removed the light to match gta5 #121
