### ISSUE TITLE
Feature Request - different gamepad icons

### ISSUE THREAD

**Issue by SandeMC** [ThirteenAG/GTAIV.EFLC.FusionFix#118]
I like how Widescreen Fix for NFS games used to have improved gamepad icons. Could something like this be done here - a toggle for whether you want xbox 360 icons(vanilla), [xbox one/series icons](https://gtaforums.com/topic/887527-ash_735s-workshop/page/4/#comment-1071669058), [dualshock icons](https://www.gtagaming.com/360-to-ps4-controller-icons-f30380.html) or [dualsense icons](https://www.nexusmods.com/gta4/mods/286)? They all change the same file - `button_360.wtd` in pc/textures, so I think a toggle is possible (similar to one you have for timecyc).

**Comment by valentyn-l** [comment]
Would love to see this as well!

**Comment by RecklessGlue540** [comment]
I would love this!

**Comment by Tomasak** [comment]
added
