### ISSUE TITLE
[Feature Request] Fix the mouse cursor to the center of the screen

### ISSUE THREAD

**Issue by arinc9** [ThirteenAG/GTAIV.EFLC.FusionFix#122]
Although the Windows mouse cursor is hidden in-game, it won't be fixed to the center of the screen. I have two displays so when I use the scroll wheel in-game, the browser page on the next display moves if I move the hidden mouse cursor to the area of this display which I don't like.

**Comment by Tomasak** [comment]
can you repro with raw mouse input?

**Comment by arinc9** [comment]
After I've reported this issue, an update to FusionFix addressed this but I didn't try it properly to report back here. Now that I did, I can close this issue. And no, whether or not raw mouse input is on or off, I don't experience this issue. To double check, I have launched the game without FusionFix and the issue was there.

Thanks for the ping!
