### ISSUE TITLE
Confused about this AimingZoomFix setting

### ISSUE THREAD

**Issue by KarlGhartler** [ThirteenAG/GTAIV.EFLC.FusionFix#130]
"AimingZoomFix - set to 1 for proper fix, so it behaves like on xbox, set to 2 to have this fixed feature enabled in IV and TLAD, set to -1 to disable this feature. 0 disables the fix, as usual."

I don't understand the difference between option 1 and 2. And it doesn't mention TBOGT which confuses me further.

Does 1 make it only apply to GTA IV but not the expansions? Whats the difference between the "proper fix" and "fixed feature"? etc. Could you clarify the difference between these two settings?

I also don't understand the difference between -1 and 0, but I don't plan to have the fix off so it doesnt matter as much to me.

**Comment by SandeMC** [comment]
https://github.com/GTAmodding/GTAIV-Issues-List/issues/19
