### ISSUE TITLE
FF won't load

### ISSUE THREAD

**Issue by vl9d** [ThirteenAG/GTAIV.EFLC.FusionFix#133]
Launching gta4 after adding from .zip to root does not open the mod. I also had dxvk installed and tried to run it without it but still the same result

**Comment by SandeMC** [comment]
Show your game folder

**Comment by anthoncast** [comment]
If you literally placed FF in "Grand Theft Auto IV" folder from Steam, of course IT WON'T LOAD. If placed in "GTAIV" INSIDE OF "Grand Theft Auto IV", then I don't know. Because Fusion Fix now comes with the Ultimate ASI Loader, and it should load Fusion Fix.
