### ISSUE TITLE
[Feature Request] Toggle for "screen blur" or watercolor effect in Definition

### ISSUE THREAD

**Issue by valentyn-l** [ThirteenAG/GTAIV.EFLC.FusionFix#138]
Could a toggle be added to bring back the screen blur that was present when Definition was off? 

I really dig the watercolor-like aesthetic that it gives to the game on consoles. Not to mention that it hides jaggies really well. Sad to see it decoupled from the Definition setting.

What do you guys think?

**Comment by spidergrear2** [comment]
It was mostly a bug and it looked really bad, consoles look blurry because it's a lower resolution.
If you want to hide the jagged edges you can use the FXAA togle in the mod.

**Comment by valentyn-l** [comment]
> It was mostly a bug and it looked really bad, consoles look blurry because it's a lower resolution. If you want to hide the jagged edges you can use the FXAA togle in the mod.

Really!? I always thought the console versions had a stippled effect applied overtop. Guess not haha. 

I'm already using FXAA, but I'm finding the image far too sharp. Is there a way to perhaps have multiple FXAA passes to soften the image further? Such as FXAA Low - 1 pass, Medium - 2 passes, High - 3 passes, etc.

**Comment by Tomasak** [comment]
definition should get rid of it now :)
