### ISSUE TITLE
FF seems to break GTA IV Complete Edition in Steam

### ISSUE THREAD

**Issue by ArtyIF** [ThirteenAG/GTAIV.EFLC.FusionFix#14]
I just bought GTA 4 Complete Edition in Steam on a sale and decided to install this mod. Unfortunately, it breaks the "Complete Edition" part of the game.

Without FusionFix, the game loads normally - shows two legal notices, the logos and the choice between running GTA 4 and EFLC. However, with FusionFix the game briefly shows the second notice, then briefly the "You are currently not logged in" warning (during which the logo jingle plays, even though the logos aren't shown) and jumps straight to GTA 4.

**Comment by ArtyIF** [comment]
Update: turns out that SkipMenu is on by default. Closing the issue.

**Comment by ThirteenAG** [comment]
You can always start episodes from the pause menu.
