### ISSUE TITLE
Z-Depth with TRANSPARENCY broken for Depth of Field + DoF intensity tied to resolution

### ISSUE THREAD

**Issue by valentyn-l** [ThirteenAG/GTAIV.EFLC.FusionFix#141]
As mentioned on the GTAForums by the member _CurtisG2000_ (https://gtaforums.com/topic/989098-console-visuals-the-complete-edition/?do=findComment&comment=1072195248), the Z-Depth buffer is broken on PC and does not blend the DoF effect with transparencies, as they are treated as opaque by the renderer. 

Also, as you can see from the below examples, the current 1.80 implementation of DoF (and bloom I believe) scales with resolution, thus appearing much finer and smaller on PC than it does on Xbox. I believe the correct behavior is for it to remain the same size independent of resolution.

PC

![pcdof](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/60371520/770c6026-cc01-4340-9eb3-2f6d8329da47)
![pcdof1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/60371520/26404a70-9eca-4ae7-a737-962c7b5d8672)

Xbox 360

![xboxdof](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/60371520/95b40777-4671-43c8-94de-fd9d0aff9679)
![xboxdof1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/60371520/1467be33-5e5c-48f2-b93c-0bc0b5470c2f)

![1 copy](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/60371520/09bb7fc6-5d38-41b9-b8d9-6ef266364e9b)

**Comment by valentyn-l** [comment]
Morre examples of the issue, this time with the car windows, and with Niko's hair not blending with the environment properly.

![20230824115905_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/60371520/2c97a138-5eea-497f-8546-0d0c191efe74)

![20230824115954_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/60371520/a0ad1c4c-8b97-4e6a-a47f-cd27e5e44f89)
![20230824115802_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/60371520/d8d16b87-8766-4ee6-bf4f-cc40c00c79fa)
![20230824115943_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/60371520/7ba49055-17f4-47a1-ad68-b4ca354b677d)

**Comment by sTc2201** [comment]
The hair is not related to depth issues, you're probably using a mod like Trilogy Character Fixes that replaces/modifies some of the hair meshes of certain characters. Hair meshes seem to always break when you export them via openFormats etc..

For comparison, vanilla hair meshes:

![hair1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/41953894/48c57303-9438-4d0b-945d-427671bf0146)
![hair2](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/41953894/70e1515f-f676-4047-9c96-85c1c17685ad)

**Comment by valentyn-l** [comment]
> The hair is not related to depth issues, you're probably using a mod like Trilogy Character Fixes that replaces/modifies some of the hair meshes of certain characters. Hair meshes seem to always break when you export them via openFormats etc..
> 
> For comparison, vanilla hair meshes:
> 
> ![hair1](https://user-images.githubusercontent.com/41953894/263132495-48c57303-9438-4d0b-945d-427671bf0146.png) ![hair2](https://user-images.githubusercontent.com/41953894/263132496-70e1515f-f676-4047-9c96-85c1c17685ad.png)

It's not necessarily an issue with the mod. Whilst yes, I do have that mod installed, what it actually does is make the hair transparent intentionally. What I'm showcasing here however is how the broken Z-Depth is not allowing for correct blending, even with transparent hair.

**Comment by RecklessGlue540** [comment]
This issue can be closed. Turns out, fixing this will introduce other (rather minor but bad) issues.
