### ISSUE TITLE
HUD Radar Map police car + helicopter icon animations tied to framerate

### ISSUE THREAD

**Issue by valentyn-l** [ThirteenAG/GTAIV.EFLC.FusionFix#142]
The police icons on the HUD  radar map have framerate-dependent animations, thus being sped-up at any framerate above 30fps. 

![Radar-GTA4-wanted copy](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/60371520/cb92f0ea-6b51-44bc-b253-8b8e4a6024ec)

**Comment by Tomasak** [comment]
vanilla bug, reported here: https://github.com/GTAmodding/GTAIV-Issues-List/issues/112
