### ISSUE TITLE
Game wont open

### ISSUE THREAD

**Issue by Eric-Sparda** [ThirteenAG/GTAIV.EFLC.FusionFix#143]
I am on Steam version, when I launch the game it launches Rockstar game launcher then closes it and that's it nothing after

**Comment by MagicAl6244225** [comment]
> I am on Steam version, when I launch the game it launches Rockstar game launcher then closes it and that's it nothing after

It's not unusual to have to try a few times to start the game after installing any files, even when nothing is wrong. I find it often it will work on the third try. If not, and if you are installing FusionFix in a clean, unmodded game, [verify the integrity of your game](https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB) then be sure you have placed the FusionFix files (plugins folder, update folder, dinput8.dll) in the GTAIV folder that contains GTAIV.EXE

**Comment by Eric-Sparda** [comment]
Yep thx mate, I verified the integrity of game files and it launched thx a lot
