### ISSUE TITLE
Menu fps limiter not showing?

### ISSUE THREAD

**Issue by InvisibleCoding** [ThirteenAG/GTAIV.EFLC.FusionFix#145]
I've downgraded to 1.0.7.0  

But when I go to options I don't see "frame limiter" option

Is there any fix for that?

**Comment by MagicAl6244225** [comment]
FusionFix releases in this repository require Grand Theft Auto IV: Complete Edition v1.2.0.30 and newer.

**Comment by InvisibleCoding** [comment]
> @InvisibleCoding learn to read

Someone broke your feelings bud?

**Comment by Tomasak** [comment]
>downgraded
ye no
