### ISSUE TITLE
AimingZoomFix in TBoGT not working in 1.20.59 (FIXED + Additional fixes)

### ISSUE THREAD

**Issue by ThatArpGuy** [ThirteenAG/GTAIV.EFLC.FusionFix#149]
No matter what value I change that setting to, it doesn't work. I have DXVK installed + this trainer: https://www.gtainside.com/en/gta4/trainers/161465-simple-native-trainer-for-steam-v1-2-0-43-fixed/

Side note: I have 2 copies of IV Complete Edition, one downgraded to 1.0.7.0 and the other latest RSGC version. Anyone know why when I open a menu it responses are late? Scrolling through options is fine, but pressing on one doesn't work, even if you spam it.

**Comment by Tomasak** [comment]
Cannot reproduce on CE. Even used all files from the trainer link (tbh only scripthook.dll, aCompleteEditionHook.asi and trainer*.asi/ini are required for trainer, dsound.dll is alternative asi loader and ff ships with ual, but it still works), even with dxvk installed.

**Comment by ThatArpGuy** [comment]
> On my end, the “TBoGT aiming zoom” bug only reäppears with FusionFix v1.80, whilst it doesn’t happen with v1.79
Where can I get v1.79? I only see 1.77.

**Comment by easonwong-de** [comment]
@ThatArpGuy Oh, my bad. Should be v1.77.

**Comment by ThatArpGuy** [comment]
I fixed every issue. 

1. Simple Native Trainer and other menus started working again without any input lags after **installing this**: https://www.lcpdfr.com/downloads/gta4mods/g17media/26726-compatibility-patch-for-gta-iv-complete-edition/

3. FusionFix (v1.8.0 and below) started working after **replacing dsound.dll**, with one downloaded straight from here: https://www.dll-files.com/dsound.dll.html

Thanks for help, and hopefully this helps some people too. Maybe I'll create a new "issue" here as a fix to this.

**Comment by Tomasak** [comment]
you shouldnt use the dsound at all. 
One from trainer you downloaded previously is old asi loader, and this one is just generic windows one. So you should just remove it from your IV folder

**Comment by ThatArpGuy** [comment]
Well replacing dsound.dll worked fixed the issue so.
