### ISSUE TITLE
Misplaced building model

### ISSUE THREAD

**Issue by valsorai** [ThirteenAG/GTAIV.EFLC.FusionFix#15]
There is a piece of a building on the rails near hove beach that shouldn't be there
![Screenshot (302)](https://user-images.githubusercontent.com/67951508/88452670-eb6a0e80-ce60-11ea-80df-911dca908c16.png)
The only mods that I got installed are:
-Asi loader
-Fusion fix
-ColAccel
-Custom Timecyc (CleanIV)

**Comment by ThirteenAG** [comment]
Doesn't happen in my game.

**Comment by valsorai** [comment]
I met this issue a few weeks ago, reinstalled the game, installed fusion fix again, at first the building was gone but after I spent few days playing, I found this building again in the exact same place I saw it before. I can't imagine what could cause this issue. Could it be because I am playing in TBOGT? Or is it because I use ColAccel?

**Comment by ThirteenAG** [comment]
Could be ColAccel, try deleting the cache files from root folder and regenerate them.

**Comment by valsorai** [comment]
Thank you this solved the issue
