### ISSUE TITLE
"Motion Blur" Setting is inversed

### ISSUE THREAD

**Issue by MiesThies** [ThirteenAG/GTAIV.EFLC.FusionFix#151]
When set to "on" it is actually "off" and vice versa. Probably bc of how the "definition" setting worked before it was renamed. Not a big deal, especially if you're into FF, but still, I don't think the current state is optimal. 

![GTAIV_2023_08_30_13_04_52_322](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/92cdaada-92c7-429b-a4fd-3991f38c24f7)

![GTAIV_2023_08_30_13_04_49_126](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/48aebd58-e293-4f74-a14d-bd6c8dcdb783)

**Comment by Tomasak** [comment]
This is known and will be fixed with next shader update :)
