### ISSUE TITLE
[Bug]Street lights and road reflections flicker at night when drunk.

### ISSUE THREAD

**Issue by Rsao123** [ThirteenAG/GTAIV.EFLC.FusionFix#153]
This bug will appear every time after going to drink with friends at night, street lights and road reflections and shadows will flicker, can it be fixed?

**Comment by Rsao123** [comment]
I have two gameplay videos that demonstrate this bug, only when drinking at night

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143761055/bff3a2ea-1569-4d16-b1f5-192e478e9167


https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143761055/04d737c6-0bb6-4d24-8399-d04e2367489c

**Comment by Rsao123** [comment]
My game version is 1.2.0.59 and I already have the latest FF installed

**Comment by SandeMC** [comment]
Can confirm this happens.

**Comment by Tomasak** [comment]
2.0 should fix this

**Comment by TheJasonGallant** [comment]
This was was never fixed for me.

**Comment by IVorza** [comment]
> This was was never fixed for me.

Same for me.
