### ISSUE TITLE
Auto-centering the camera when the character is running in GTA 4 (EFLC)

### ISSUE THREAD

**Issue by ChattyFeed** [ThirteenAG/GTAIV.EFLC.FusionFix#154]
Auto-centering the camera while running makes it very difficult to look around. Please, I would really like you to fix this problem! It makes it very difficult for me and other people to play on the forums!!!

Автоцентрирование камеры при беге очень мешает осматриваться по сторонам. Пожалуйста, я бы очень хотел что бы эту проблему вы исправили! Очень мешает играть как мне так и другим людям на форумах

**Comment by Tomasak** [comment]
vanilla issue, not to be written here

**Comment by AFrameWorker** [comment]
This is kind of an issue for a lot of players though. I personally would much more appreciate a GTA SA style onfoot camera that allows you to actually look around your character properly. Please do reconsider.
