### ISSUE TITLE
LCPD Buffalo (police3) model fix suggestion

### ISSUE THREAD

**Issue by MiesThies** [ThirteenAG/GTAIV.EFLC.FusionFix#157]
https://www.gtainside.com/en/gta4/cars/181342-fixed-lcpd-buffalo/

This mod claims to fix some model issues with the above-mentioned car. From the mod's page:
- Fixed misplaced antennas
- Fixed lights emissive textures
- New paint UV mapping so it matches the Stanier's and Merit's ones.
- Higher quality police livery
- Other minor fixes 

Maybe the fixes of this mod could be included in FF in as well.

Edit: Of course, I know that the lights emissive textures are already fixed by FF.

**Comment by SandeMC** [comment]
Already mentioned here https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/147

**Comment by MiesThies** [comment]
I see, sorry!
