### ISSUE TITLE
What do RainDropsBlur and ShadowFilter do?

### ISSUE THREAD

**Issue by SandeMC** [ThirteenAG/GTAIV.EFLC.FusionFix#158]
There's no description next to it and no way to toggle in-game, so it's hard to compare.

Include some description on the readme.md plz

**Comment by Parallellines0451** [comment]
It fixes black water droplets on the screen and restores the refraction effect from consoles; it's most noticeable at night around bright lights.

**Comment by SandeMC** [comment]
What about `ShadowFilter`? It says it's a toggle in settings, but... where?.. What is it

**Comment by MagicAl6244225** [comment]
> What about `ShadowFilter`? It says it's a toggle in settings, but... where?.. What is it?

Coming soon. It will give you more options to change the appearance of shadows.

**Comment by SandeMC** [comment]
Got it.
