### ISSUE TITLE
v1.2.0.43.CE + FusionFix v1.89 = SRCP10 error

### ISSUE THREAD

**Issue by r3538987** [ThirteenAG/GTAIV.EFLC.FusionFix#159]
After update, there is mentioned error on this location https://webmshare.com/play/N7oPN
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/33725345/603f9257-ff30-4eb1-b795-ac8526428512)

plugins folder:
- GTAIV.EFLC.FusionFix.asi
- GTAIV.EFLC.FusionFix.ini
- GTAIV.XboxRainDroplets.asi
- GTAIV.XboxRainDroplets.ini
- IV.EFLC.ColAccel.asi

update folder: 
- aside shader files there are these https://i.imgur.com/xBgmaBY.png 

I think on that location usually helicopters do spawn.

**Comment by r3538987** [comment]
WEBM shows location. In that particular video TBoGT is completed. Free roaming. 
Will check rest TLAD and GTA IV, in same spot.

**Comment by Tomasak** [comment]
Managed to reproduce on tbogt, issue it  ambblkhawk.sco in TBOGT.FusionFix.img
Didnt check TLAD, IV is working fine

**Comment by r3538987** [comment]
Tried in IV, and yap, there is no crash at that spot.

**Comment by Tomasak** [comment]
tlad is fine too. Olanov is checking the issue :)

**Comment by justdumbgamer** [comment]
I'm also having hard crash during play TBoGT.
Game crashes near the Firfly Island while driving a helicopter.

**Comment by BlancX10** [comment]
I have the same problem in TBoGT, driving on the Algonquin Bridge: Crash and the SRCP10 Error.

**Comment by Tomasak** [comment]
should be fixed now, wait for archive to be compiled
