### ISSUE TITLE
gta_wire.sps renders differently in comparison to prior versions. If wires overlap becomes bit messy. 

### ISSUE THREAD

**Issue by r3538987** [ThirteenAG/GTAIV.EFLC.FusionFix#163]
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/33725345/d65a7141-7b26-4e2e-9f82-555a7cea0d7c)

**Comment by r3538987** [comment]
Guess new look is more precise towards consoles. 
( https://gtaforums.com/topic/934545-fusionfix/?do=findComment&comment=1072209579 )

Despite quality got downgraded, in my opinion.

**Comment by Parallellines0451** [comment]
It was reverted.
