### ISSUE TITLE
IV, smoke coming from one of the building at Northwood. 

### ISSUE THREAD

**Issue by r3538987** [ThirteenAG/GTAIV.EFLC.FusionFix#164]
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/33725345/ec4dc337-09fc-41d9-8b21-95f47b6f2f29)

**Comment by r3538987** [comment]
TBoGT doesn't have this.

**Comment by Attramet** [comment]
Save corruption probably, start a new game and check if issue is gone

**Comment by r3538987** [comment]
Can confirm, on new save file you don't have this.
