### ISSUE TITLE
[Bug]Bahama Mamas texture error in TBOGT

### ISSUE THREAD

**Issue by Rsao123** [ThirteenAG/GTAIV.EFLC.FusionFix#166]
The exterior of Bahama Mamas in Grand Theft Auto IV is work good.
![20230908093926_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143761055/547bbe60-ce78-4eb2-869f-cce010f2ca5b)
But The exterior of the club in The Ballad of Gay Tony is broken.
![20230908090910_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143761055/aeb4532a-e0b3-4e15-a6e3-6943b7cf9dce)
Can this be fixed？

**Comment by Tomasak** [comment]
Fixed in various fixes

**Comment by Rsao123** [comment]
But various fixes seem to be incompatible with FusionFix, because the shadow of the street lights disappears after installing various fixes,so hope FusionFix will fix it
![20230908162748_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143761055/5e274826-c1d5-4d8c-a225-b3a20ab25a79)

**Comment by Attramet** [comment]
You have a choice, either you use lampposts with fixed light coronas, but without shadows, or you use original lampposts with broken light coronas, but with shadows that may be broken in some places.
The lack of shadows from lampposts is not even a bug, but it’s like it was on consoles
