### ISSUE TITLE
[Bug]I noticed that the lights would flicker at night at certain locations.

### ISSUE THREAD

**Issue by Rsao123** [ThirteenAG/GTAIV.EFLC.FusionFix#167]
Street lights flicker near Ray Boccino's restaurant.
![20230908095256_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143761055/8a577b72-9ea5-4d6d-9683-adfd4c27f8cd)

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143761055/237c5f98-6a76-46e9-90f9-f43ae18b3252

This bug will also occur near gun shops in Chinatown.
![20230908095313_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143761055/4d100602-45c5-4873-9a78-d3e0a700d0a5)

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143761055/d9601460-e9d7-4d06-bd1f-3a3544369ce3

**Comment by Rsao123** [comment]
is used FusionFix v1.94.

**Comment by ThirteenAG** [comment]
Can you reproduce the problem, lower the draw distance sliders and see if it helps?

Also, after that, try installing Project2DFX and see if it happens with it.

**Comment by Rsao123** [comment]
I lower the View Distance and Detail Distance to 70,it work good，no flicker.


https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143761055/b657d76c-b2ea-4528-b9e3-380623536b3a


Then I installed Project2DFX, and even though I turned the draw distance to 100, it still worked normally good.

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143761055/8a48283c-890b-4457-9206-49fddedb4635

**Comment by Haru23x** [comment]
I'm having the same issue.

**Comment by Lethality5001** [comment]
> Is there a way to fix this bug without installing Project2DFX? I don't like the lighting effect of 2DFX

You can, just disable the mod's features. Basically project 2dfx just increases the corona limits. 
You should have it like this : 
RenderLodLights = 1
CoronaRadiusMultiplier = 1.0
SlightlyIncreaseRadiusWithDistance = 1
CoronaFarClip = 0
DisableDefaultLodLights = 0
DisableCoronasWaterReflection = 2

**Comment by ThirteenAG** [comment]
v2.0-beta already has corona limiter included.

**Comment by Lethality5001** [comment]
> v2.0-beta already has corona limiter included.

let me guess, v2.0 the one that isnt compatible with any other necessary fix mods for gtaiv? I heard about the beef and idc about it, i want this game fixed

**Comment by ThirteenAG** [comment]
No idea what you're talking about. v2.0 has all the same code as currently available in master branch.
We're waiting for new shader improvements to make a full 2.0 release.

**Comment by Lethality5001** [comment]
> No idea what you're talking about. v2.0 has all the same code as currently available in master branch. We're waiting for new shader improvements to make a full 2.0 release.

Oh you def dont know what im refering to, perhaps source code rings a bell :)) C'mon, kiss each other say sorry to each other idc, but unite already and fix gta 4

**Comment by ThirteenAG** [comment]
> > No idea what you're talking about. v2.0 has all the same code as currently available in master branch. We're waiting for new shader improvements to make a full 2.0 release.
> 
> Oh you def dont know what im refering to, perhaps source code rings a bell :)) C'mon, kiss each other say sorry to each other idc, but unite already and fix gta 4

I don't, and I don't owe you anything and certainly don't need you to tell me what to do. Feel free to fix everything yourself, if you need it so much.

**Comment by Lethality5001** [comment]
> > > No idea what you're talking about. v2.0 has all the same code as currently available in master branch. We're waiting for new shader improvements to make a full 2.0 release.
> > 
> > 
> > Oh you def dont know what im refering to, perhaps source code rings a bell :)) C'mon, kiss each other say sorry to each other idc, but unite already and fix gta 4
> 
> I don't, and I don't owe you anything and certainly don't need you to tell me what to do. Feel free to fix everything yourself, if you need it so much.

Then why would u say u dont know what im talking about xD If u are making the mods incompatible at least cover everything the game has issues with

**Comment by Lethality5001** [comment]
> No idea what you're talking about. v2.0 has all the same code as currently available in master branch. We're waiting for new shader improvements to make a full 2.0 release.

Also why removing source code, considering this is a FREE Gta 4 fix mod..Perhaps we have reason to believe u put malware in next updates? We have the right of knowing if u put malware or not, dont we?

**Comment by Tomasak** [comment]
2.0 should fix this
