### ISSUE TITLE
[Feature Request] Restore M_M_GunNut_01 gun dealer

### ISSUE THREAD

**Issue by MiesThies** [ThirteenAG/GTAIV.EFLC.FusionFix#169]
The restored traffic cops in the toll booths reminded me of this part of ResponsivePlus / PotentialGrim:

"The unused arms dealers (M_M_GunNut_01) now replaced the hipster bouncers (M_Y_Bouncer_01) as the arms dealers of the underground gun shops of Broker and Alderney."

I know, ResponsivePlus as a whole has been suggested already and denied, except for the typos in cargrp.dat and carols.dat, but I think this particular part of the mod, could be a fine addition to FF.

**Comment by Tomasak** [comment]
its planned for future version :)

**Comment by vavrinko** [comment]
Make this optional please. I tried a mod that restores this and I must say the Gun Nut NPC looks overdone for me :/

**Comment by Tomasak** [comment]
Added in 2.0
