### ISSUE TITLE
[Bug] DXVK Breaks the night lights render distance

### ISSUE THREAD

**Issue by MilesFox92** [ThirteenAG/GTAIV.EFLC.FusionFix#171]
When I run the plugin with DXVK - lights at night only render when I am standing really close to them, or put my camera closer.

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/92983157/0f32ecce-b34e-43f9-b51a-fd70477825f8

**Comment by RageGreeny** [comment]
Same issue, even without DXVK.

**Comment by RageGreeny** [comment]
Is not fixed by using 2dfx either.

**Comment by johndoeazsx** [comment]
I had that same issue, what fixed it for me was doing a completely fresh install by deleting the Grand Theft Auto IV folder in steam\steamapps\common and reinstalling. It doesn't effect any save files or anything, just have to reinstall any mods you had.

**Comment by Tomasak** [comment]
Should be fixed with 2.0
