### ISSUE TITLE
GTA FusionFix Crashing Issue

### ISSUE THREAD

**Issue by GhostX1863** [ThirteenAG/GTAIV.EFLC.FusionFix#172]
Im having problems with FusionFix when i install FusionFix my game crashes after a few minutes and i get this error 
fatal error invalid resource detected-please reinstall the game fatal error scrp10

**Comment by Tomasak** [comment]
if its in tbogt, update fusionfix

**Comment by GhostX1863** [comment]
> if its in tbogt, update fusionfix

its already updated

**Comment by Tomasak** [comment]
is it crashing randomly or on certain spot/time/mission?

**Comment by ThirteenAG** [comment]
Upload a crash dump.

**Comment by GhostX1863** [comment]
> is it crashing randomly or on certain spot/time/mission?

randomly
