### ISSUE TITLE
Train tracks' mesh casts a shadow onto cars, but not onto the street.

### ISSUE THREAD

**Issue by MiesThies** [ThirteenAG/GTAIV.EFLC.FusionFix#173]
Sorry if it has been discussed before: 

![GTAIV_2023_09_09_13_04_50_077](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/bb7b98db-3b39-4f63-bd33-89b1ef264f63)

**Comment by Rsao123** [comment]
me too
![20230911193959_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143761055/3465f069-39fe-46e5-8b18-68ac74d45402)

**Comment by MiesThies** [comment]
What I also noticed, is that the mesh, which is casting the shadow, is not visible from below (though it is from above). Interestingly, this is only in front of Roman's apartment, farther up Mohawk Ave, it is visible from one point (see Picture 1).

Also apparently the mesh only doesn't cast a shadow right in front of the apartment, but a few feet farther, it does. You can see, that on the left side, there is no mesh shadow and on the right side there is (Picture 2).

![GTAIV_2023_09_11_16_49_19_579](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/b036e9eb-79ab-436d-b97c-8df9b524d960)
![GTAIV_2023_09_11_16_58_42_651](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/50ec8849-c3b8-4334-b8ba-a2343c32b9c6)

**Comment by MiesThies** [comment]
Again different area, depending on the angle, the mesh shadow looks even weirder, like white-ish.

![GTAIV_2023_09_11_20_13_21_228](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/ccff31ab-7f37-4a0f-a97d-13bd54a1661c)
![GTAIV_2023_09_11_20_13_30_562](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/31b4e972-53ba-497d-abe5-74611ef26da1)

**Comment by MiesThies** [comment]
Also on patch 1080 with FF 1.96 (ported by Zolika), the mesh shadow appears to be normal in front of Roman's apartment. Maybe it's a CE thing?

![GTAIV_2023_09_12_16_25_39_133](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/7eb9c43a-1978-4103-8766-2b1356a0653f)

**Comment by Tomasak** [comment]
More objects had shadows restored, these reported too. 2.0 should fix this

**Comment by MiesThies** [comment]
I think it was only partly fixed so far, unfortunately. I just made some new screenshots with 2.0 and there are still plenty of areas, where the shadow appears to be incorrect. TBH, the amount of missing mesh shadow probably is even higher than the amount of correct mesh shadows :D

Don't get me wrong, I totally dig the new update, it's f*cking fire!! Just wanna help to make it even more perfect :)

![GTAIV_2023_10_31_15_02_43_584](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/e93cf600-b859-41fc-b448-be6f0b05f47b)

![GTAIV_2023_10_31_15_03_31_245](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/b13e739a-3991-4ac3-93ba-94c48b855c0c)

![GTAIV_2023_10_31_15_05_05_819](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/ca304800-4ef4-4c2c-8f80-bf31b5c158d1)

![GTAIV_2023_10_31_15_02_20_990](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/0e1d20da-bd82-4d92-b36e-b6543eb9bec4)

![GTAIV_2023_10_31_15_02_12_960](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/fbbd076b-1cde-460c-b1ee-27aa4b7a6de5)

![GTAIV_2023_10_31_15_01_32_518](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/094eea1f-4c13-43b1-b085-844504db956b)

![GTAIV_2023_10_31_15_06_17_256](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/59f6e101-f2c8-42e4-90ad-7ce7a19236d6)

**Comment by Tomasak** [comment]
Never ending story, will try hunt down more names later

**Comment by Tomasak** [comment]
Are all shadows now present on 2.1?

**Comment by MiesThies** [comment]
> Are all shadows now present on 2.1?

So I tested it and the good news is: You're getting a lot closer, lol :)

The bad news, if you consider it that, is that it's not perfect, yet.
I tracked down the locations for you:

Here, the shadow on the ground is perfect,
![GTAIV_2023_11_25_21_53_37_125](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/49445976-9e46-4f4e-8a4c-4d3abe0f0e80)

but the mesh between the tracks is missing:
![GTAIV_2023_11_25_21_53_00_823](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/5eead289-e0e2-4007-afbb-9c2695c1779c)


Under the Algonquin-Dukes-Expressway bridge, the train tracks have mesh,
![GTAIV_2023_11_25_21_55_02_099](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/9255dc58-c607-46ea-9164-b1ef824f068b)

but the shadow on the ground is missing:
![GTAIV_2023_11_25_21_54_58_017](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/98fe0ee5-5dc3-4d38-b705-76371a7c1f31)


Here is just some more random locations, where the shadow is missing:
![GTAIV_2023_11_25_21_57_43_351](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/f050882a-9684-4dc1-b9e7-4f03b271e7e1)
![GTAIV_2023_11_25_21_59_27_719](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/8cd94766-03cc-4fcd-a243-8fc5654c4dff)
![GTAIV_2023_11_25_22_00_03_493](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/bda44f6e-6b40-470f-86f5-7d9912a4c756)
![GTAIV_2023_11_25_22_01_10_903](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/cb2155b4-9e4a-4d09-b4e6-34a3496b0b29)
![GTAIV_2023_11_25_22_02_23_384](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/3f338515-5a9c-42d4-93e3-aaec94c9e734)


While driving around, I stumbled upon this, which looks weird and just wanted to let you know:
![GTAIV_2023_11_25_22_01_11_510](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/0bccae4d-0b5d-488a-9b75-e8d491dbd725)
![GTAIV_2023_11_25_22_01_36_828](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/c52f83d0-fb60-443e-9f13-e86e7d103482)

It looks like something with the trees' and the tracks doesn't mix too well (look at the trees' shadows)
For reference, this was on 1080 with the following settings:
![GTAIV_2023_11_25_22_01_55_362](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/fce1037f-80a0-4d13-b63b-feb2
![GTAIV_2023_11_25_22_02_00_899](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/eb20a225-8a27-41ba-bf50-b0c88f38bebf)
e51dace4)

Sorry for all the work, but thank you for doing it! :)

**Comment by MiesThies** [comment]
I'm sorry to still bug you with this, but I cannot make peace with the train track's mesh and shadows.

There's still plenty of inconsistencies. Some examples:

1. Hove beach near Roman's apartment: 
On the ground there is a shadow of a mesh (1st pic, red circle on the street, 1.1 pic), but when you look up, you can not see the mesh, that must produce that shadow. Altough when you're standing on top of the train tracks, you can see, that the mesh is there (2nd pic). It just seems to be invisible from the ground at this location. Also the parallel lines in the middle of each train track (red circle top left and right) do not produce any shadow on the ground in this location, even though they do so in other locations (3rd pic, first red circle from the right).

1st pic
![1  (Groß)](https://github.com/user-attachments/assets/f820414c-62a3-444f-8ede-fb0c7a21b96e)

1.1 pic
![1 1](https://github.com/user-attachments/assets/fec2f363-ed54-427b-b15b-4c19ebd83e3a)

2nd pic
![2](https://github.com/user-attachments/assets/545c39af-66df-4888-8728-9ad7a7d5ecb7)


2. Oneida Ave, Hove Beach
The mesh shadow on the left abruptly stops (3rd pic, first red circle from the left). It is correct, as when you look at it from below (4th pic) and above (5th pic), you see that the actual mesh that produces the shadow also stops. But it does look weird ending so abruptly.
Also there appear to be two different kinds of mesh, one diamond shaped and one cube shaped (3rd pic, second red circle). Looks weird, too.

3rd pic
![3 (Groß)](https://github.com/user-attachments/assets/a06a0495-6819-47df-bc4c-053e63cdd0ba)

4th pic
![4](https://github.com/user-attachments/assets/ecbc7931-32f9-488c-a5bf-abbf8fd73fab)

5th 
![5 (Groß)](https://github.com/user-attachments/assets/cc211a01-4f42-434e-899d-9cc197d32f2f)


3. Hove Beach station
Similar to the aforementioned, at a certain point the mesh stops, pic 7 (and therefore the shadow stops, pic 6).

6th pic
![6](https://github.com/user-attachments/assets/13e124f7-732b-4f84-9171-578fd5f1a185)

7th pic
![7 (Groß)](https://github.com/user-attachments/assets/e654a24a-bf06-4892-a6ac-d5e92e28c4aa)


Also, when you stand on the lower platform and look up, you cannot see any mesh, pic 8, but when you look on the ground, you can see the mesh's shadow.

8th pic
![8th](https://github.com/user-attachments/assets/6c2cefe7-ad2b-46bd-a70c-eae2c903067e)

9th pic
![9th](https://github.com/user-attachments/assets/a4fe437f-0fd9-4ef5-b9e8-387ea669187f)

and some more missing mesh (or collision) and inconsistent shadows:
![10th](https://github.com/user-attachments/assets/fec1a11c-b566-4f4b-8df3-1f29d5705e76)
![GTAIV_2024_08_21_20_35_27_976](https://github.com/user-attachments/assets/41465966-2b30-4064-a06e-644e89243b52)
![GTAIV_2024_08_21_20_36_02_640 (Groß)](https://github.com/user-attachments/assets/6d78dff6-c130-4191-9eee-a540f462b367)
![GTAIV_2024_08_21_20_36_34_185](https://github.com/user-attachments/assets/b5aa7ac6-d956-4fa9-8450-adf6c8b5fafb)


I knoooooow this has probably no priority for you and rightly so, but it grinds my gears so much lol, I'd be so thankful if this was fixed :)

**Comment by Tomasak** [comment]
various fixes should take care of that
