### ISSUE TITLE
Last thing left to fix to make it perfect

### ISSUE THREAD

**Issue by LLIXXXIR** [ThirteenAG/GTAIV.EFLC.FusionFix#174]
This mod is a great, impressive piece of work. So many details have been restored, everything is done with such high quality, with love for your project. And, perhaps, the only thing left to fix to make it perfect are the shadows. Of course, I think that work is underway on them, because in the latest updates there was work with shadows, and I am captain of obviousness, but nevertheless I want to write about it. So with filtering the pre1060 became much more beautiful, but everything else remained from the 12043 shadows, shadows that do not stand up to any criticism. They have a disgusting drawing distance (the shadow of a transport is completely drawn at a distance of about 2 meters), the shadow begins to be drawn at a distance from the object, an incomprehensible situation with the shadow of the metro grid (written in previous issues) and so on. I even made a poor video with examples. Here you either restore the shadows completely from 1040, which sounds difficult (I don’t understand this), or correct these. Overall, good luck with this, and thanks for the opportunity to experience the game as it was intended.

Sorry for my English
Video: https://youtu.be/ofqdwgGb97I?si=zhQ1bYkWEOgasHn4

**Comment by Parallellines0451** [comment]
Only very high shadows have fixed peter-panning / depth bias for now.
