### ISSUE TITLE
Unable to toggle options individually

### ISSUE THREAD

**Issue by Legacy7K** [ThirteenAG/GTAIV.EFLC.FusionFix#176]
After installing the mod i cant seem to toggle any of the options individually. Once I change 1 option, the rest change also.

**Comment by ICantReadYourMind** [comment]
what version of the game are you on

**Comment by Legacy7K** [comment]
tried on both 10.7.0 and 1.0.8.0

**Comment by Legacy7K** [comment]
Does this mean i cant use scripthook mods along with fusion? ive seen that scripthook doesnt work with any version higher that 1.0.8.0

**Comment by Tomasak** [comment]
Thats a lie. You just get scripthook.dll from https://gtaforums.com/topic/390582-c-script-hook/
aCompleteEditionHook.asi from here https://www.lcpdfr.com/downloads/gta4mods/g17media/26726-compatibility-patch-for-gta-iv-complete-edition/
and asi loader which is part of fusion fix (dinput8.dll)

its all even mentioned on the gtaforums page
