### ISSUE TITLE
A nice and important change

### ISSUE THREAD

**Issue by Dr1Ft3RXII** [ThirteenAG/GTAIV.EFLC.FusionFix#177]
I would like to ask you to add an option to choose between PC and console trees, the same when it comes to reflections and changing the language in the menu as in previous titles, along with languages ​​that have not been officially added but were made by the community

**Comment by SandeMC** [comment]
You can already change the language via Steam - Properties though.

**Comment by Tomasak** [comment]
Console trees are bundled with console visuals mod and is not planned to be included in FF. Language of game can be changed thru RGL/Steam or language loader mod
