### ISSUE TITLE
[Bug]In TBOGT，After installing FusionFix, Yusuf's gold uzi became transparent.

### ISSUE THREAD

**Issue by Rsao123** [ThirteenAG/GTAIV.EFLC.FusionFix#178]
In the Mission "Caught With Your Pants Down",Yusuf's gold uzi became transparent.
![20230912161856_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143761055/7a7f4f0e-9f10-42bd-af9d-d20e6805d8b4)
After uninstalling FusionFix, it became normal.
![20230912161454_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143761055/cd11440f-c203-42e1-9bde-fbc036e338d1)

**Comment by Parallellines0451** [comment]
It has broken textures (or rather textures with transparency). Various Fixes contains a fix for that.
You can even notice that parts of it are transparent in vanilla because transparency was only broken in certain shaders when EFLC launched on PC.

**Comment by Rsao123** [comment]
I installed Various.Fixes 1.6 and FusionFix1.96, Gold UZI is still transparent, maybe the new FF is not compatible with VF?

**Comment by vavrinko** [comment]
> I installed Various.Fixes 1.6 and FusionFix1.96, Gold UZI is still transparent, maybe the new FF is not compatible with VF?
Works ok for me. I have the latest Fusion Fix 1.96, VariousFixes 1.60 and I also use TBoGT texture update 0.3
https://gtaforums.com/topic/760761-eflcrel-pc-quality-texture-update/

![20231020191314_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/96373757/733ce8a4-b05f-4451-8911-26e20a785242)

One of the things is fixing it.
