### ISSUE TITLE
Depth of Field doesn't seem to work

### ISSUE THREAD

**Issue by hirvi666** [ThirteenAG/GTAIV.EFLC.FusionFix#179]
Issue is in the title. Pretty sure it worked for a bit. but now it doesn't and the screen is pretty flicky. During fog the screen looks normal but otherwise the DoF appears to be missing. Turning it on and off doesn't affect it at all.
![20230912163957_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/138400442/d8fc1b03-9aee-4233-9523-a04183de2d61)
![20230912164012_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/138400442/b70d15ba-5199-4060-a267-1314470e63c0)

**Comment by hirvi666** [comment]
Damn, well that explains it. Thanks.

**Comment by ThirteenAG** [comment]
We could add it to timecyc later, now that there's an option to disable it, but it's not decided yet.
