### ISSUE TITLE
Document ENB compatibility 

### ISSUE THREAD

**Issue by drandarov-io** [ThirteenAG/GTAIV.EFLC.FusionFix#180]
I was trying to get FusionFix to work with ENB on 1.2.0.59:
- Without any changes the shaders break and everything looks wrong (black nights, wrong shaders during day)
- When deleting only the `update\common\shaders` folder, the game crashes before the main menu with a resource error
- When additionally deleting the `update\GTAIV.EFLC.FusionFix` folder, most things seem to work, but I'm not sure what features are lost (at least the main menu changes are lost)

As additional notes. This is the present load order (I believe):
- I'm using the `d3d9.dll` and `d3d9_enb.dll` bundled with this [mod](https://www.nexusmods.com/gta4/mods/145), but replaced all shaders with [IceEnhancer 3.0](https://www.nexusmods.com/gta4/mods/178)
- `dax.dll` gets loaded through `enbseries.ini`
- `dax.dll` loads `d3d9_dxvk.dll` through `DX9Settings.ini`

I'm unsure if this is the right way or what conflicts may arise from this, so I feel like this should be documented.

**Comment by Parallellines0451** [comment]
ENB is not compatible with modded shaders.

**Comment by SandeMC** [comment]
ENB is also absolutely not an essential for GTA IV.

**Comment by drandarov-io** [comment]
ENB is in no way essential, but I don't think it'd be wrong to document compatibility with certain "popular" modification.

**Comment by Tomasak** [comment]
with amount of shaders changed, there will be more brokeness than features even if you hack in ENB to work with edited shaders.

**Comment by t-ro86** [comment]
> ENB is also absolutely not an essential for GTA IV.

You serious?! Without ENB IV looks like outdated piece of s++t!
Colors, adaptation, *bloom*, lights, *ssao ssil* skylighting... etc

GTAIV.EFLC.FusionFix is a GREAT WORK, better than all R* patches, but I prefer enb series.

**Comment by Parallellines0451** [comment]
> > ENB is also absolutely not an essential for GTA IV.
> 
> You serious?! Without ENB IV looks like outdated piece of s++t! Colors, adaptation, _bloom_, lights, _ssao ssil_ skylighting... etc
> 
> GTAIV.EFLC.FusionFix is a GREAT WORK, better than all R* patches, but I prefer enb series.

Please refer to [this](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/180#issuecomment-1716089794)
