### ISSUE TITLE
[Bug]Why the light in Alderney's safe house looks strange?like it doesn't have shadows

### ISSUE THREAD

**Issue by Rsao123** [ThirteenAG/GTAIV.EFLC.FusionFix#184]
Is this a bug? Can it be fixed?FusionFix v1.96 and Various.Fixes v1.60 are installed.
![20230914154642_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143761055/10f1494c-bde5-4da8-b52c-06ce0ff4b84c)
![20230914154737_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143761055/b2ebcd74-2b72-4e13-9833-f1d2a52d44ea)

**Comment by spidergrear2** [comment]
well that's how it's meant to look
