### ISSUE TITLE
[Question] Fusion Overloader doesn't seem to work for other mods for me

### ISSUE THREAD

**Issue by drandarov-io** [ThirteenAG/GTAIV.EFLC.FusionFix#185]
Maybe I'm misunderstanding something:
- I have copied all files from the FusionFix install (plugins, update, dinput8.dll). They also work without a problem
- When I copy files from another mod (in this case Various Fixes) they don't seem to get loaded

My file structure is the following:
```
├───common
│   ├───data
│   │   │   frontend_menus.xml
│   │   │   frontend_pc.dat
│   │   │
│   │   └───maps
│   │           scenarios.ipl
│   │
│   └───shaders
                  ... SHORTENED SHADERS FOLDER
│
├───GTAIV.EFLC.FusionFix
│   │   GTAIV.EFLC.FusionFix.img
│   │   GTATrees.img
│   │
│   ├───IV
│   │       GTAIV.FusionFix.img
│   │
│   ├───TBOGT
│   │       TBOGT.FusionFix.img
│   │
│   └───TLAD
│           TLAD.FusionFix.img
│
├───pc
│   ├───data
│   │   └───maps
│   │       ├───east
│   │       │       queens_e.ide
│   │       │       queens_w.wpl
│   │       │
│   │       ├───generic
│   │       │       procobj.ide
│   │       │
│   │       └───interiors
│   │           ├───generic
│   │           │       bars_1.ide
│   │           │       indust_1.ide
│   │           │
│   │           └───mission
│   │                   level_1.ide
│   │
│   └───textures
│           coronas.wtd
│           stipple.wtd
│
├───TBoGT
│   ├───common
│   │   └───data
│   │           frontend_menus.xml
│   │
│   └───pc
│       └───data
│           └───maps
│               ├───east
│               │       queens_m.wpl
│               │
│               └───interiors
│                       e2_int_7.ide
│
├───TLAD
│   ├───common
│   │   └───data
│   │           frontend_menus.xml
│   │           frontend_pc.dat
│   │
│   └───pc
│       └───data
│           └───maps
│               └───east
│                       bronx_e2.wpl
│
└───Various Fixes
    │   VariousFixesIV.img
    │
    ├───IV
    │       IVWPL.img
    │
    ├───TBoGT
    │       TBoGTWPL.img
    │       VariousFixesTBoGT.img
    │
    └───TLAD
            TLADWPL.img
            VariousFixesTLAD.img
```

Copying the content of the Various Fixes folder to the root also does not change the result.
Am I doing something wrong?

I am checking with this sign for example which should look like the screenshot below:
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/13102251/1bd932d2-7b1a-4f25-b747-e0ab62d1c718)
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/13102251/669ea269-5bcb-43d9-802d-1a35ab1d2969)

**Comment by drandarov-io** [comment]
Will try

**Comment by r3538987** [comment]
> Will try. Apart from that: Is there any way to log loaded files? That'd make debugging a lot easier.

Think there are no logs this, ?yet? 
You can see how game loads files with ProcessMonitor, but it will create HUGELY big list. 

-
On my side, latest FusionFix load latest VariosFixes without problems.

-
May I ask how you made this file tree, looks fancy? Mine DirectoryOpus app can create these as well, but without additional lines which do indeed increase readability.

**Comment by drandarov-io** [comment]
> May I ask how you made this file tree, looks fancy? Mine DirectoryOpus app can create these as well, but without additional lines which do indeed increase readability.

It's really just the `tree` command (`C:\Windows\System32\tree.com`). `tree /F` will print all files, but there is virtually no configuration or parameters, so only useful for a limited number of files.

**Comment by ThirteenAG** [comment]
@drandarov-io try latest UAL from github, I believe that issue should be resolved.

**Comment by Tomasak** [comment]
UAL got another bunch of updates for paths, might be fixed now, reopen if not
