### ISSUE TITLE
These small fonts caused this. I could not scroll the rest of it in the Stats.

### ISSUE THREAD

**Issue by LaupaMag338** [ThirteenAG/GTAIV.EFLC.FusionFix#187]
https://streamable.com/m6p9tz

**Comment by Tomasak** [comment]
there is workaround for this: either use gamepad, or first let the game scroll thru the stat screen and then you can freely scroll on your mouse wheel.

im not sure if this isn't actually a vanilla bug

**Comment by LaupaMag338** [comment]
> im not sure if this isn't actually a vanilla bug
I don't think so. This small fonts caused this thing, If I delete the fontend_pc.dat. It would be back to normal and then you won't see extra options added by FusionFix.

**Comment by pataukslis** [comment]
put [this](https://www.mediafire.com/file/3r03rrkv8imhovr/frontend_pc.dat/file) in your Grand Theft Auto IV\update\common\data

**Comment by Tomasak** [comment]
fixed in 2.4.9
