### ISSUE TITLE
Does FusionFix affect performance in any plausible way?

### ISSUE THREAD

**Issue by Sasha-gamer2011** [ThirteenAG/GTAIV.EFLC.FusionFix#188]

**Comment by spidergrear2** [comment]
i've heard some time ago that fixed bloom and DoF scaling are more demanding because it uses more samples, probably shadows also affects performance.

**Comment by Tomasak** [comment]
Reports says intel igpus have FPS hit with Z fighting fix and new DOF can be more demanding, so can PCSS shadows
