### ISSUE TITLE
Why is Social Club enabled after I install FusionFix?

### ISSUE THREAD

**Issue by NanoFlowGaming** [ThirteenAG/GTAIV.EFLC.FusionFix#189]
For some reason, when I installed it, there's now Social Club and I can't have autosaves now unless I remove FusionFix. I followed all steps, like installing Ultimate ASI Loader and stuff like that.

If it helps, I'm using crossover on a M2 Macbook running macOS Monterey 12.5 (I did the DLL override). I'm also using GTA 4 The Complete Edition v1.2.0.43

I can provide additional information if needed.

**Comment by NanoFlowGaming** [comment]
Fixed it bu simply using older version of FusionFix.

**Comment by SaucySauce** [comment]
What version of Fusion Fix worked?
