### ISSUE TITLE
Flickering lights/lights only on near player

### ISSUE THREAD

**Issue by RayKnack** [ThirteenAG/GTAIV.EFLC.FusionFix#190]
I’ve narrowed it down to something in update>common>shaders>win32_30_nv8
its like lights only turn on when I’m very very close to them, and also turning on any of the new features in the graphics or display options, turns all options on.

**Comment by sushitea** [comment]
Having this issue as well. Particularly horrible at the **Booth Tunnel** where it is completely dark both 2 meters behind and in front of you. Red objective markers also don't light up until I'm close to them, as well as some traffic lights. 
I'll be uninstalling this mod for now unfortunately.

**Comment by Tomasak** [comment]
Should be fixed on 2.0
