### ISSUE TITLE
Just a Summary of remaining noticeable GTA IV bugs :

### ISSUE THREAD

**Issue by MehranAkbarii** [ThirteenAG/GTAIV.EFLC.FusionFix#194]
**High FPS Issues:**
Elevator camera issue during the mission Late Checkout
Helicopter Glitch in the last mission "Out of commission"
Broken motorcycle controls on high FPS
**Anti aliasing:**
Lack of good AA cause object edges shimmering from long distances while moving (Even when using DSR and FXAA and reshade's post-progressing AA shaders)
**Other Issues:**
~~Lod popups~~ [partialy fixed in latest shaders collection patch ](https://github.com/Parallellines0451/GTAIV.ShaderFixesCollection/tree/2d2c16b6a9f9db4ab1580ef1623d9f5681f3d82b)
~~Statue of Happiness LOD~~ [look same in console version](https://github.com/GTAmodding/GTAIV-Issues-List/issues/14#issuecomment-526543310)
Texture pop-ins in high detail distances
~~Lights/car reflections flickering~~ [fixed ](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/194#issuecomment-1732688810)
There is no foam near the shore
Silent prison guards
**Settings and GUI bugs:**
The controller texture in the controller settings is missing in main menu while it is OK in pause menu
Can't invert mousewheel weapon scrolling behavior
These small fonts caused this. I could not scroll the rest of it in the Stats. **(Fusion Fix Bug)**

**Comment by JackSound01** [comment]
Also, In TBoGT transparent Gold-Uzi in Yusuf's mission

**Comment by MehranAkbarii** [comment]
> Also, In TBoGT transparent Gold-Uzi in Yusuf's mission

Yes one of the known fusion fix bugs

**Comment by NotEvenFlinched** [comment]
Helicopter Glitch in the last mission "Out of commission"
Broken motorcycle controls on high FPS
These are fixed in ZolikaPatch

**Comment by MagicAl6244225** [comment]
> Also, In TBoGT transparent Gold-Uzi in Yusuf's mission

Rockstar made both the gold uzi and gold phone cutscene props transparent and did something with an emissive shader to make them appear solid. Why? Who knows. It doesn't work with the new shaders. They look solid if we change the models' shaders to be the same as the gameplay gold uzi model, which also gives them shininess they were missing.

**Comment by Zorklis** [comment]
^Summery*

**Comment by Lethality5001** [comment]
> **High FPS Issues:** Elevator camera issue during the mission Late Checkout Helicopter Glitch in the last mission "Out of commission" Broken motorcycle controls on high FPS **Anti aliasing:** Lack of good AA cause object edges shimmering from long distances while moving (Even when using DSR and FXAA and reshade's post-progressing AA shaders) **Other Issues:** Lod popups Statue of Happiness LOD Texture pop-ins in high detail distances Lights/car reflections flickering There is no foam near the shore **Settings and GUI bugs:** Can't invert mousewheel weapon scrolling behavior These small fonts caused this. I could not scroll the rest of it in the Stats. **(Fusion Fix Bug)**

Actually the car lights ( or backlights ) are due to the corona limit within the game. Use project 2dfx and disable the mod's additions of distant LODs. Basically u just use the increased limit, it fixed my issue with that

**Comment by MehranAkbarii** [comment]
> > **High FPS Issues:** Elevator camera issue during the mission Late Checkout Helicopter Glitch in the last mission "Out of commission" Broken motorcycle controls on high FPS **Anti aliasing:** Lack of good AA cause object edges shimmering from long distances while moving (Even when using DSR and FXAA and reshade's post-progressing AA shaders) **Other Issues:** Lod popups Statue of Happiness LOD Texture pop-ins in high detail distances Lights/car reflections flickering There is no foam near the shore **Settings and GUI bugs:** Can't invert mousewheel weapon scrolling behavior These small fonts caused this. I could not scroll the rest of it in the Stats. **(Fusion Fix Bug)**
> 
> Actually the car lights ( or backlights ) are due to the corona limit within the game. Use project 2dfx and disable the mod's additions of distant LODs. Basically u just use the increased limit, it fixed my issue with that

but I didnt like this mod visuals , I just wanted a fix without changing something else

**Comment by MehranAkbarii** [comment]
> > **High FPS Issues:** Elevator camera issue during the mission Late Checkout Helicopter Glitch in the last mission "Out of commission" Broken motorcycle controls on high FPS **Anti aliasing:** Lack of good AA cause object edges shimmering from long distances while moving (Even when using DSR and FXAA and reshade's post-progressing AA shaders) **Other Issues:** Lod popups Statue of Happiness LOD Texture pop-ins in high detail distances Lights/car reflections flickering There is no foam near the shore **Settings and GUI bugs:** Can't invert mousewheel weapon scrolling behavior These small fonts caused this. I could not scroll the rest of it in the Stats. **(Fusion Fix Bug)**
> 
> Actually the car lights ( or backlights ) are due to the corona limit within the game. Use project 2dfx and disable the mod's additions of distant LODs. Basically u just use the increased limit, it fixed my issue with that

thanks fixed by removing ini file thanks

**Comment by Tomasak** [comment]
Most of stuff was fixed or have active opened issue specifically.
