### ISSUE TITLE
TBoGT Cutscene glitch (popping or something)

### ISSUE THREAD

**Issue by Lethality5001** [ThirteenAG/GTAIV.EFLC.FusionFix#196]
During cutscenes sometimes in Tbogt u see some weird kind of glitching, not sure exactly how to describe it but i will post a video of it
Its like some sort of flickering but not exactly, will show vid here

Most obvious at 0:45 but happens throughout the video too
Its happening even at first Tony mission too

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/145836476/a03c94de-db24-413f-908f-8026c9a1198d

**Comment by Paule145** [comment]
I have the same issue, and it's also happening in IV (didn't check TLAD, but I think it has this bug too)

**Comment by Lethality5001** [comment]
> I have the same issue, and it's also happening in IV (didn't check TLAD, but I think it has this bug too)

I didn't had this during TLAD and i played the game pretty much at 4k resolution, haven't tested on IV since i already re-completed it but i did some testings and i think going down to 1080p sort of improved it? Im not sure because sometimes it may happen sometimes it may not, depends on the cutscene.  A mission where its very obvious is "Corner Kids" but then again, u can encounter it multiple times

**Comment by Paule145** [comment]
I tried everything to fix this (lowering resolution, graphics settings and etc.), but nothing worked.  Beginning cutscene in "Blog This!..." has those flickering when camera changes position, so I used this mission for testing purposes. Maybe some new shaders causing this, but it definitely came with the mod (btw I changed stipple file to original one, and flickering still remains)

**Comment by Lethality5001** [comment]
so when removed fusionfix it came back to normal?

**Comment by Lethality5001** [comment]
> I tried everything to fix this (lowering resolution, graphics settings and etc.), but nothing worked. Beginning cutscene in "Blog This!..." has those flickering when camera changes position, so I used this mission for testing purposes. Maybe some new shaders causing this, but it definitely came with the mod (btw I changed stipple file to original one, and flickering still remains)

when u removed the fusionfix it came back to normal?

**Comment by Lethality5001** [comment]
@ThirteenAG @Parallellines0451 fix

**Comment by anthoncast** [comment]
In vanilla version there is an issue with these shadows popping up in front of you whenever the camera changes. Haven't seen no one reporting the same, but if you check out some other walkthroughs you can notice this. In Fusion Fix models go from black to normal textures, I've reported this issue with models popping up, and worse is that they depend on FPS. The lower the fps the slower the models pop up or flicker.

**Comment by Lethality5001** [comment]
> In vanilla version there is an issue with these shadows popping up in front of you whenever the camera changes. Haven't seen no one reporting the same, but if you check out some other walkthroughs you can notice this. In Fusion Fix models go from black to normal textures, I've reported this issue with models popping up, and worse is that they depend on FPS. The lower the fps the slower the models pop up or flicker.

its weird because tlad and IV didnt have this issue, but seems more prominent on 4k res

**Comment by Paule145** [comment]
Without fusion fix cutscenes looks fine. It just one of 103 files from shaders folder which causes this bug, but idk which one

**Comment by Lethality5001** [comment]
> Without fusion fix cutscenes looks fine. It just one of 103 files from shaders folder which causes this bug, but idk which one

that is weird, maybe because of shaderfixes?
@Parallellines0451

**Comment by Paule145** [comment]
I think "deferred_lighting.fxc" from this mod causes flickering in cutscenes. I changed it to original file in three folders (win32_30, win32_30_atdix10 and win32_30_nv8), and there is no flickering in cutscenes, but the lighting is broken after that. Lowering fps in cutscenes also didn't help. I don't think it's fixable without deleting mod from game files, at least for now.

**Comment by Lethality5001** [comment]
> I think "deferred_lighting.fxc" from this mod causes flickering in cutscenes. I changed it to original file in three folders (win32_30, win32_30_atdix10 and win32_30_nv8), and there is no flickering in cutscenes, but the lighting is broken after that. Lowering fps in cutscenes also didn't help. I don't think it's fixable without deleting mod from game files, at least for now.

are u playing in 4k or 1080p? Also for me its only happening in tbogt only the rest are fine, maybe needs a shaderfixes hotfix push? @Parallellines0451

**Comment by Paule145** [comment]
1080p

**Comment by Tomasak** [comment]
Fix is being worked on, should be pushed with next update

**Comment by Lethality5001** [comment]
> Fix is being worked on, should be pushed with next update

fix by whom? Fusionfix or shaderfixes? Thirteen made it intentionally break with zolika mods which are essential to play the game...

**Comment by Lethality5001** [comment]
> Fix is being worked on, should be pushed with next update

he deleted my comment Lmfao, screenshoted, Will that update be pushed by fusion or the shaderfixes guy?

**Comment by ThirteenAG** [comment]
Are you done? Want to continue to spout nonsense, do it elsewhere.

**Comment by Lethality5001** [comment]
> Are you done? Want to continue to spout nonsense, do it elsewhere.

why'd u delete the comment? I asked who is gonna push out the fix, whats wrong with that big ego, small human?

**Comment by Parallellines0451** [comment]
It will be fixed in the next FusionFix update. Your comment was deleted because you were harassing someone over false accusations. Your bug report was noted and we are working on a fix; I hope that's the end of it.

**Comment by Lethality5001** [comment]
> It will be fixed in the next FusionFix update. Your comment was deleted because you were harassing someone over false accusations. Your bug report was noted and we are working on a fix; I hope that's the end of it.

will it be launched separately on shaderfixes?

**Comment by Parallellines0451** [comment]
It's not a shader problem, it's the game that sends improper values to the shaders; but we found a decent enough workaround.

**Comment by Lethality5001** [comment]
> It's not a shader problem, it's the game that sends improper values to the shaders; but we found a decent enough workaround.

and that will still work with other NecessaRY to play the game with mods ? Without breaking anything -__- ?

**Comment by ThirteenAG** [comment]
In general, if two mods patch the same place in game code, it will not work, if they don't, then it will work.

**Comment by Lethality5001** [comment]
well obviously there wasn't any patch for this related issue so should work

**Comment by Tomasak** [comment]
Should be fixed on 2.0
