### ISSUE TITLE
[Bug] Some Main Menu Issues...

### ISSUE THREAD

**Issue by RecklessGlue540** [ThirteenAG/GTAIV.EFLC.FusionFix#199]
The Console Gamma toggle shows up ingame but not in the main menu
Main Menu:
![GTAIV 09_26_2023 17_21_02](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143945383/c432a78a-671a-44a8-aa5a-87d62aeb0f96)

Ingame
![GTAIV 09_26_2023 17_22_14](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143945383/a6d4ffc8-10dd-40d2-b728-65bf06dfc5a1)

The controller texture in the controller settings is also missing
Main Menu:

![GTAIV 09_26_2023 17_21_10](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143945383/73810db7-8db2-49f3-8c45-3422b5704826)

Ingame:

![GTAIV 09_26_2023 17_22_23](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143945383/47edd92d-26d1-41e9-8e94-0a6ea9872067)

Same goes for the surround sound setup textures
Main Menu:
![GTAIV 09_26_2023 17_41_57](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143945383/d6c71c52-91ff-4169-a3f6-cde414b08b1e)
Ingame:

![GTAIV 09_26_2023 17_42_30](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143945383/91e35969-6e7e-40da-8972-1b0efb24e176)

**Comment by Tomasak** [comment]
gamma is on purpose not shown in main menu to copy how brightness, contrast... is not there too (as you cant see how the option changes the game)
rest seem to be vanilla issues iirc

**Comment by RecklessGlue540** [comment]
> gamma is on purpose not shown in main menu to copy how brightness, contrast... is not there too (as you cant see how the option changes the game) 

Oh riight... (though a simple gamma slider would be nicer than one single preset that may be too dark on some monitors - just a  small suggestion)

> rest seem to be vanilla issues iirc

The controller texture seems to show up using FusionFix v1.80 (Haven't tested older FusionFix versions, but it probably works), but then it breaks on v1.94 and up (It's not related to the text scaling).
It is indeed a vanilla issue (A strange one) since i've tested 1.0.4.0 (Works fine here), 1.0.7.0, 1.0.8.0, and 1.2.0.59, and it didn't show up (Only after installing FusionFix v1.80 it worked on all three patches, surprisingly).
As for the surround setup textures they don't show up in the main menu in any of the above versions regardless of FusionFix being installed or not (So it was probably an oversight by Rockstar).

**Comment by RecklessGlue540** [comment]
Alright, now, as of FusionFix 2.0, the controller texture shows up in both in-game and main menu.
Still, the surround setup textures still don't show up in main menu...
