### ISSUE TITLE
Building lights have a fade-in animation when pressing C to look back 

### ISSUE THREAD

**Issue by Lethality5001** [ThirteenAG/GTAIV.EFLC.FusionFix#200]
when quickly looking at certain buildings during night-time they sort of fade in, is that normal? Shouldn't the lights not fade in so much everytime u do some quicker movements?

**Comment by Rsao123** [comment]
It seems that drawing distance too high can cause this problem

**Comment by anthoncast** [comment]
Actually no. It happens A LOT

**Comment by Lethality5001** [comment]
> Actually no. It happens A LOT

and is that normal?

**Comment by Lethality5001** [comment]
Future fix? @Parallellines0451

**Comment by Tomasak** [comment]
it's an intended way of optimization

**Comment by RecklessGlue540** [comment]
> Not normal, this didn't happen if PS3 version. Only on PC

It happens on both consoles. Like Tomasak said, it's for optimization. All versions do this. 
Late, I know.

**Comment by anthoncast** [comment]
> > Not normal, this didn't happen if PS3 version. Only on PC
> 
> It happens on both consoles. Like Tomasak said, it's for optimization. All versions do this. Late, I know.

I think I got it wrong. I thought it referred to the sky light popping up, just like what I reported in other topic. As English is not my main language I got things wrong I'm sorry

**Comment by RecklessGlue540** [comment]
> > > Not normal, this didn't happen if PS3 version. Only on PC
> > 
> > 
> > It happens on both consoles. Like Tomasak said, it's for optimization. All versions do this. Late, I know.
> 
> I think I got it wrong. I thought it referred to the sky light popping up, just like what I reported in other topic. As English is not my main language I got things wrong I'm sorry

Would love seeing this issue being higher priority... It's one of the most annoying as of now...

**Comment by anthoncast** [comment]
> Would love seeing this issue being higher priority... It's one of the most annoying as of now...

Compared to the other games, pressing the button to look behind has more issues. Quick mention to San Andreas, because for some reason something similar happens now, not sure if it's because my gpu or anything, but just like IV, stuff on screen pops up, in this case the whole map (SA), in IV the shadows issue as always. :(

**Comment by Tomasak** [comment]
> > > Not normal, this didn't happen if PS3 version. Only on PC
> > 
> > 
> > It happens on both consoles. Like Tomasak said, it's for optimization. All versions do this. Late, I know.
> 
> I think I got it wrong. I thought it referred to the sky light popping up, just like what I reported in other topic. As English is not my main language I got things wrong I'm sorry

so wait whats the issue?
I notice the shadow pop in when pressing look back button, which was described by you in gtaf topic.
nothing wrong with sky light. Any vid representing this issue?

**Comment by RecklessGlue540** [comment]
> > > > Not normal, this didn't happen if PS3 version. Only on PC
> > > 
> > > 
> > > It happens on both consoles. Like Tomasak said, it's for optimization. All versions do this. Late, I know.
> > 
> > 
> > I think I got it wrong. I thought it referred to the sky light popping up, just like what I reported in other topic. As English is not my main language I got things wrong I'm sorry
> 
> so wait whats the issue? I notice the shadow pop in when pressing look back button, which was described by you in gtaf topic. nothing wrong with sky light. Any vid representing this issue?

https://www.youtube.com/watch?v=7rGNkm5Pqx0
This is the real issue.
I don't think sky lighting is affected, tho I can say for sure that Shadows on the trees, water chunks (maybe, not sure?) and shadows disappear when the camera is changed abruptly.

**Comment by anthoncast** [comment]
> I notice the shadow pop in when pressing look back button, which was described by you in gtaf topic.
nothing wrong with sky light. Any vid representing this issue?

Hi, sorry again for the con_fusion_ (pun intended?). Yes, I referred to that shadow issue, I said sky light issue because, well, I thought it was part of the problem for appearing over the shadows for a millisecond. Sorry again :(

**Comment by Tomasak** [comment]
since its vanilla issue it would be better to be opened in issue list. team is aware of this bug but as said, its prolly hard to fix :/
