### ISSUE TITLE
[Question | Suggestion] Is it possible to add Resolution scale for gta 4 like in gta 5?

### ISSUE THREAD

**Issue by AdilTL** [ThirteenAG/GTAIV.EFLC.FusionFix#201]
https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fanmenvyu3lv41.png

**Comment by Rsao123** [comment]
You can turn on NVIDIA's DSR

**Comment by SA64BD** [comment]
this would be a good feature ngl

**Comment by RecklessGlue540** [comment]
SSAA 2x added in 2.4 basically. Acts as Anti aliasing.

**Comment by Tomasak** [comment]
currently not possible, but at least SSAA 2x now is implemented
