### ISSUE TITLE
[IV] At some part of the map a light/shadow appears and disspears depending on how you look

### ISSUE THREAD

**Issue by Lethality5001** [ThirteenAG/GTAIV.EFLC.FusionFix#202]
in Alderney near the safehouse during night time there is a shadow that disspears and reappears depending how you look 

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/145836476/da9ba84c-34e4-45ff-809a-1340f32f785b

**Comment by Lethality5001** [comment]
tbh when it disspears looks cooler, ig thats how it was meant to be lol

**Comment by anthoncast** [comment]
No it wasn't.

**Comment by Tomasak** [comment]
looks like vanilla issue, please reopen  here https://github.com/GTAmodding/GTAIV-Issues-List/issues
