### ISSUE TITLE
GTA IV - CE - "It`s your call" mission bug. 

### ISSUE THREAD

**Issue by AlexandrR29** [ThirteenAG/GTAIV.EFLC.FusionFix#206]
I`m use GTA IV CE, with last Steam patch and cracked exe. Version of the Fusion Fix - 1.96.

In the Its your call" mission, after Albanian gangs coming to casino, we must calling Roman. But game, softlocked and we get infinytie phone calls, and story cutscene want start.

Im trying use FPS limit and without them - behavior want changed.

**Comment by Tomasak** [comment]
No crack support
