### ISSUE TITLE
PLEASE HELP.

### ISSUE THREAD

**Issue by dabz1** [ThirteenAG/GTAIV.EFLC.FusionFix#208]
Hello Sergei we are doing a build for GTA4. We want to save your console shadows, your shaders soft shadows and proper reflections on the transport, in the new version has become impossible to replace most of the shaders, in the case if you replace the water shader on its own water disappears, this is a huge disadvantage, because the alternative shader looks many times better than the original. It is also not compatible with any ENB preset that replaces shaders. Please give your contact to contact you.

**Comment by dabz1** [comment]
Contacts 
Discord1- Adrian Twentis
Discord2  - lazovy#0868

**Comment by Parallellines0451** [comment]
- ENB is not compatible with modded shaders and it will most likely never be updated; it's closed source software and we can't do anything about it
- All shaders are dependent on each other due to specific fixes (mainly the z-fighting fix), so do not use only some of them or mix them with shaders gotten from other places; it's all or nothing

**Comment by dabz1** [comment]
> * ENB is not compatible with modded shaders and it will most likely never be updated; it's closed source software and we can't do anything about it
> * All shaders are dependent on each other due to specific fixes (mainly the z-fighting fix), so do not use only some of them or mix them with shaders gotten from other places; it's all or nothing

It worked, but the cantilevered shadows and softness disappeared afterwards. Shrubs and tree leaves shone through the buildings. The water also had no reflections and was transparent. Can you tell me what shaders are responsible for the softness of shadows? And on what shaders depends shader water.
