### ISSUE TITLE
Not a big issue

### ISSUE THREAD

**Issue by Dfk234** [ThirteenAG/GTAIV.EFLC.FusionFix#212]
But can newer versions of fusion fix work on GTA IV version 1.0.7.0 and the standalone ELFC

**Comment by RecklessGlue540** [comment]
The next update will introduce backwards compatibility with 1.0.7.0 and 1.0.8.0. As for Standalone EFLC, no idea.
You can try merging the DLCs together in standalone IV using this if you want (In case standalone EFLC won't be supported):
https://gtaforums.com/topic/881495-launch-episodes-as-dlcs-in-gta-iv
Are you using the retail version (the one on DVDs)? If so, you could probably use steam or something to get the Complete Edition for free.

**Comment by Tomasak** [comment]
2.0 should work with eflc and iv 1.1.2.0/1.1.3.0 1.0.7.0/1.0.8.0 respectively
