### ISSUE TITLE
EmissiveShaderFix crashes when loading inbetween DLC's.

### ISSUE THREAD

**Issue by Syoudous** [ThirteenAG/GTAIV.EFLC.FusionFix#22]
Started using the fix sometime earlier this year without issues (thank you for the mod!) but updated later with a crash loading in-between different saves.

1.) Let game load normally, letting mod skip intro (**SkipIntro** = **1**) & menu (**SkipMenu** = **1**).
2.) Pause -> Game -> Load (or New) -> Play in any other DLC or IV.
3.) Game will crash after a few seconds.

Workarounds:
1.) Applying **EmissiveShaderFix** to **0**.

...or...

2.) Applying **SkipMenu** to **0** and loading the game you want after.

Latest Steam, The Complete Edition.

**Comment by FireNight101428** [comment]
To Syoudous,
I applied the following scripts but the game still crashed switching inbetween DLC's. Any suggestions? Plz help 😰!

**Comment by Syoudous** [comment]
After some lengthy on and off playing I think this may have been an issue on my behalf through file conflictions. But I am entirely unsure if this is the case. I'll leave this up temporarily if anyone else has success from this or if there is indeed an issue here.

**Comment by FireNight101428** [comment]
I fix it when I quickly delete the comment. It cause crash because I installed a .asi file that can fix tbogt pause menu music and tbogt radio station. But the files I installed are told by doing mistake so... Yeah Sorry to ping you :)

**Comment by Syoudous** [comment]
I'm closing this as I suspect the issue was on my behalf and not the mod itself. Seems to be running as intended if you don't interfere with the files and copy the files as intended. My bad!
