### ISSUE TITLE
[Feature Request] Make the damage crosshair visible when free aiming using a gamepad

### ISSUE THREAD

**Issue by RecklessGlue540** [ThirteenAG/GTAIV.EFLC.FusionFix#222]
The damage crosshair won't show up when free aiming on controllers, however it does on mouse (Obviosly). 
Making it visible also on gamepads would be a significant improvement, as it behaves the same on consoles.
Some footage here: https://imgur.com/a/3J87mbM

**Comment by sTc2201** [comment]
>as it behaves the same on consoles.

I don't know what console version of GTA IV you played, but showing ped health on free aim hasn't been a thing either on console.

Recorded on xenia emulator:
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/41953894/c7ab0065-cba0-4abb-87d0-b2439b8cb23b)

**Comment by RecklessGlue540** [comment]
> as it behaves the same on consoles.

It behaves the same as on PC. That's what I meant.

**Comment by RecklessGlue540** [comment]
> but showing ped health on free aim hasn't been a thing either on console.

Bump 😄 , but I've tested the multiplayer mode of the Xbox 360 version over on the netplay fork of Xenia Canary recently, and the damage crosshair actually shows up when free aiming there. It was just not an SP thing ever it seems...
