### ISSUE TITLE
[Request] Make loading time optional like skip intro

### ISSUE THREAD

**Issue by vavrinko** [ThirteenAG/GTAIV.EFLC.FusionFix#228]
I know it might sound weird, but the loading screens are a big part of this game's nostalgia for me. The images, the music...
The latest Fusion fix makes the loading super fast, which is super cool. But could it be made optional like the intro and skip menu feature?

Pretty please. :)

**Comment by RecklessGlue540** [comment]
> thats not a problem, just go into plugins folder, and open the .ini file with notepad, and set skipintro and skipmenu to 0

No. Actually the latest updates improved the initial loading times by a lot. Almost instant loading.

**Comment by vavrinko** [comment]
> > I know it might sound weird, but the loading screens are a big part of this game's nostalgia for me. The images, the music... The latest Fusion fix makes the loading super fast, which is super cool. But could it be made optional like the intro and skip menu feature?
> > Pretty please. :)
> 
> thats not a problem, just go into plugins folder, and open the .ini file with notepad, and set skipintro and skipmenu to 0

I meant the loading from the menu into the save. Where the character art changes on the white background. Pink for TBoGT. It's not a problem the loading is fast now.

It's just like it to be optional. The loading screen is part of the gta4 vibe for me . XD

**Comment by RecklessGlue540** [comment]
> It's just like it to be optional. The loading screen is part of the gta4 vibe for me . XD

The loading on pc was pretty much always sleeping for way too long compared to the console versions that loaded as soon as every asset was loaded. It's now fixed to behave as the console versions. So it's more accurate this way.

**Comment by D7x8** [comment]
I got the same issue, it's annoying bc I load strait into the dlc and I really wanna play the main story

**Comment by Tomasak** [comment]
Open main menu -> game -> turn off skip menu

**Comment by FlyTheDream12345** [comment]
I have the same issue. The loading is so fast that the intro music won't finish playing. I think that we can have an option to slow down the loading speed so we can watch and listen to the intro. That's an important part of the game's vibe.
