### ISSUE TITLE
[Suggestion] Rename the Distant Blur setting to "Depth Of Field Level" or merge it with the Depth of Field setting

### ISSUE THREAD

**Issue by Markie98** [ThirteenAG/GTAIV.EFLC.FusionFix#229]
It took me a while to realize Distant Blur controls the strenght of Depth Of Field and they're tied meaning if one of them is off the other won't work.

**Comment by juicermv** [comment]
Maybe alternatively just decouple them somehow? Distance Blur quality seems to also affect DoF quality in cutscenes.

**Comment by Tomasak** [comment]
Option was merged for less confusion.
