### ISSUE TITLE
Game crashes when going to one spot.

### ISSUE THREAD

**Issue by Payne99** [ThirteenAG/GTAIV.EFLC.FusionFix#23]
The mod works fine, until, I go to that location where I marked in the map, the game just constantly crashes, no errors, no nothing, just takes me straight to desktop. I don't know why is that happening, but maybe you know how to deal with this?

Here's the location where I marked it:

![20201014181449_1](https://user-images.githubusercontent.com/72877389/96009979-f756e280-0e49-11eb-83c3-27cc8887aa66.jpg)

**Comment by Payne99** [comment]
Wait, I noticed it this by myself. Apparently there was suppose to be a car wash. And looking at the map It didn't appear for some reason. And when coming near by It crashes the game of course. Is there anyway how to fix this? Without starting a new game? Because I progressed so much and I don't want to start over, maybe that issue will reappear again.. And I didn't get that issue in IV, even though I installed this mod when I started progressing in second island.

**Comment by ThirteenAG** [comment]
No idea.

**Comment by Tomasak** [comment]
try removing colcachetlad.dat or w.e in root folder (where GTAIV.exe is) and playing then

**Comment by GoingToAruba** [comment]
I tested the area while using FusionFix's default settings and didn't experience any issues. Like Tomasak said, the issue is probably ColAccel related.
