### ISSUE TITLE
The game crashes during cutscenes after installing fusion fix

### ISSUE THREAD

**Issue by HeLiOn--PrImE** [ThirteenAG/GTAIV.EFLC.FusionFix#230]
This issue occurred during the intro cutscenes for TLAD and DBOGT. I have played TLAD entirely with this patch and it occurred on 2 more times during the story (although I don't remember those 2 cutscenes anymore)

The behavior can be seen in the video I attached through the link.
The fusion fix mod was installed over a clean game. No other mods were installed.
The issue does not occur before installing Fusion Fix.

Here is the video with the behavior: https://www.youtube.com/watch?v=oSY50Mw4YxU

PC specs: 
Intel Core i7 8700K
Nvidia GeForce RTX 2080 Super (8 GB)
32 GB DDR4
2560x1080 144 Hz Display

**Comment by ThirteenAG** [comment]
If you rename update folder temporarily, does it still happen with just asi?

**Comment by ThirteenAG** [comment]
After that test, try with this asi.
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13233498/GTAIV.EFLC.FusionFix.zip)

**Comment by HeLiOn--PrImE** [comment]
> After that test, try with this asi. [GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13233498/GTAIV.EFLC.FusionFix.zip)

I tried the asi file first, and it didn't work. 
But renaming the update folder did (I tested it with the current version asi, that still has the cutscene fix).

**Comment by ThirteenAG** [comment]
I would assume one of img archives is responsible, can you pinpoint which one?

**Comment by HeLiOn--PrImE** [comment]
> I would assume one of img archives is responsible, can you pinpoint which one?

It will take some time, but I'll get back to you after I tested all of them.

**Comment by HeLiOn--PrImE** [comment]
> I would assume one of img archives is responsible, can you pinpoint which one?

I identified 6 img files. I'll list them below along with the testing result:

GTAIV.EFLC.FusionFix\GTAIV.EFLC.FusionFix.img - failed;
GTAIV.EFLC.FusionFix\FusionLights.img - failed;
GTAIV.EFLC.FusionFix\FusionTrees.img - failed;
GTAIV.EFLC.FusionFix\TBOGT\TBOGT.FusionFix.img - failed;
GTAIV.EFLC.FusionFix\TLAD\TLAD.FusionFix - passed;
GTAIV.EFLC.FusionFix\IV\GTAIV.FusionFix - passed.

Each one of these files were tested separately.
I also tested the files that passed together, to make sure there aren't any potential conflicts.
Please let me know if you need me to do further tests.

**Comment by ThirteenAG** [comment]
So it's like, if any img is loaded in TBOGT, this happens? Because in IV and TLAD folders, they are not loaded in TBOGT.

**Comment by HeLiOn--PrImE** [comment]
> So it's like, if any img is loaded in TBOGT, this happens? Because in IV and TLAD folders, they are not loaded in TBOGT.

I received similar crashes during my TLAD playthrough, but I don't seem to be able to reproduce them now.
I just went through the entire TLAD intro with all the files loaded.

**Comment by ThirteenAG** [comment]
We're preparing something for you to try next, hold on. I can't reproduce it at all.

**Comment by ThirteenAG** [comment]
Ok, so this asi has img loading capability disabled.
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13238296/GTAIV.EFLC.FusionFix.zip)

Install it, then move `update/GTAIV.EFLC.FusionFix` to `TBoGT/GTAIV.EFLC.FusionFix`.
Open `TBoGT\common\data\images.txt` and insert this at the top of that file
```
GTAIV.EFLC.FusionFix/GTAIV.EFLC.FusionFix
GTAIV.EFLC.FusionFix/FusionLights
GTAIV.EFLC.FusionFix/FusionTrees
GTAIV.EFLC.FusionFix/TBOGT/TBOGT.FusionFix
```
Make sure these are loaded in game, e.g. check if cars have working lights. And see if the bug is still there.

**Comment by ThirteenAG** [comment]
Also, before you try that, reproduce that bug, and on stuck cutscene open task manager, select process, right click on it, select Create memory dump file, and upload here.

**Comment by HeLiOn--PrImE** [comment]
> Also, before you try that, reproduce that bug, and on stuck cutscene open task manager, select process, right click on it, select Create memory dump file, and upload here.

I generated the dump file as requested, but it's too large to upload here, so I uploaded it to my drive:
https://drive.google.com/file/d/1diW3J3XUYYj-Roirz0ElZyjfjq0r263I/view?usp=sharing

I also tried the new asi file you sent. It didn't crash during the cut scene, but a lot of models didn't load because of your modifications. I'm not sure if this is intended.
![20231102144641_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/10486881/c8585ffc-5763-4e8e-aa42-31b194fa4eaf)
![20231102144939_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/10486881/076a7b35-efe4-4469-b11e-a8ee39acd5de)

What's weird is that I uploaded the original asi back, and it ran through the cutscene without causing a crash. 
Cars had head lights and tail lights working, so I'm assuming the files loaded correctly...

**Comment by ThirteenAG** [comment]
I don't understand, did you move `TBoGT/GTAIV.EFLC.FusionFix` folder and edited the txt, right? That way it doesn't crash now, with any asi?

**Comment by HeLiOn--PrImE** [comment]
> I don't understand, did you move `TBoGT/GTAIV.EFLC.FusionFix` folder and edited the txt, right? That way it doesn't crash now, with any asi?

Yes. This is where I moved the folder: 
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/10486881/3fad1244-65b1-40fc-be85-fbbc480991ed)

**Comment by ThirteenAG** [comment]
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13240754/GTAIV.EFLC.FusionFix.zip)
Well, at least we know that the hook that loads custom imgs is responsible, I've tried to move it to another place, maybe it will help somehow, let's try.

**Comment by ThirteenAG** [comment]
And if that doesn't work:
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13240890/GTAIV.EFLC.FusionFix.zip)

**Comment by HeLiOn--PrImE** [comment]
> And if that doesn't work: [GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13240890/GTAIV.EFLC.FusionFix.zip)

The first one didn't work, but this one did.
No crash through the entire TBOGT intro.

**Comment by ThirteenAG** [comment]
I see, but with second one, imgs are actually not loaded, can you confirm that?

**Comment by HeLiOn--PrImE** [comment]
> I see, but with second one, imgs are actually not loaded, can you confirm that?

The cars seem to have the lights on. Is there anything else I should be looking for?
I don't have too much experience with this particular game...

![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/10486881/f7d0894b-95fd-4467-8e95-0ecf99b90c5d)

**Comment by ThirteenAG** [comment]
Nah, you should look at the DLC specific cars, like when you start the episode and enter the car, it won't have textures light up.

**Comment by HeLiOn--PrImE** [comment]
> Nah, you should look at the DLC specific cars, like when you start the episode and enter the car, it won't have textures light up.

I can see now. Yeah, not everything is loaded
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/10486881/d241395f-eb14-4bea-a0f8-792aab870214)

**Comment by ThirteenAG** [comment]
So please check again with loading via .txt method, does it work and does it cause the cutscene bug?

**Comment by ThirteenAG** [comment]
And just as a wild guess, test with this: 
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13241235/GTAIV.EFLC.FusionFix.zip)

**Comment by HeLiOn--PrImE** [comment]
> So please check again with loading via .txt method, does it work and does it cause the cutscene bug?

So I moved the FFLC.FusionFix folder into TBoGT and added those 4 lines back into the text file
The game loads the images and no crash occurs during the cutscene.
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/10486881/82d29ed5-a36a-40b8-989c-684144945d2a)

Going to test the latest asi you sent.

**Comment by ThirteenAG** [comment]
Ok, and another one 
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13241419/GTAIV.EFLC.FusionFix.zip)

If none of that works, I have another idea I can implement tomorrow, and send you here.

**Comment by HeLiOn--PrImE** [comment]
> Ok, and another one [GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13241419/GTAIV.EFLC.FusionFix.zip)
> 
> If none of that works, I have another idea I can implement tomorrow, and send you here.

Both fixes tested using the hook method (I hope I'm calling it right).
The first one resulted in a crash, but the second one didn't. And models were loaded.

**Comment by ThirteenAG** [comment]
Oh, finally, let's do one more test: 
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13241685/GTAIV.EFLC.FusionFix.zip)

**Comment by HeLiOn--PrImE** [comment]
> Oh, finally, let's do one more test: [GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13241685/GTAIV.EFLC.FusionFix.zip)

This one worker as well as the last one.
No crash, and images were loaded.

![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/10486881/9e57ad2e-0fe7-44d2-a3a2-25164945f194)

**Comment by ThirteenAG** [comment]
Mystery solved I guess, what happened here, is that very old version of fusion fix had only one img, and I took some code from exe that loads update.img as a base:
```c
  if ( (unsigned __int8)sub_40B590("update:/update.img", 0) )
  {
    sub_A96170(255);
    sub_A95AA0("update:/update.img", 1, -1);
    sub_A96170(0);
  }
  ```
And it loaded that img in the same place as the code above. Problem with that, we couldn't replace TBOGT cars that way, so img loading had to be moved elsewhere, where it works. It ended up in IMGLIST parser, and the code in that function doesn't use `sub_A96170(255);` and `sub_A96170(0);`. Since it worked fine for pretty much everyone, it was left the way it initially was. Until now.
