### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Hravec** [ThirteenAG/GTAIV.EFLC.FusionFix#233]
With FusionFix installed the game starts to launch but in a few moments it closes itself (almost as if the mod was detected) 
The Rockstar games launcher says "launching" swiftly followed by "quitting" and Steam starts the launch process until it stops. The game appears in task manager for a split second.

I don't know what I am doing wrong as there is seemingly nothing that I could've done wrong during the installation. I am sorry if this is just a stupid issue on my part as I am not very knowledgeable, I just wanted to have a better experience playing GTA 4

**Comment by MagicAl6244225** [comment]
RGL and Steam can take a few tries to start anyway. If it's not working after 3 or 4 tries then it could be an issue with game or mod installation. Use Steam to verify integrity (this will remove any mod files that might be in folders other than the plugins and update folders) and try removing all added .asi and .dll files from the root game folder and plugins folder so you can install and try one at a time to find the problem.

**Comment by ThirteenAG** [comment]
It's not related, without any mods it launches successfully ~3 out of 5 times from steam.
https://support.rockstargames.com

**Comment by Hravec** [comment]
After retrying a bunch of times and reinstalling both the game and FusionFix I believe it is the ASI loader (dinput8.dll) that is causing the issues. I tried installing it seperatelly yet that didn't change anything. 
What did change though, somewhere throughhout the process is that steam is now sending me to [this ](https://steamcommunity.com/sharedfiles/filedetails/?id=2330937567) website after failing the game launch. 
Without FusionFIx the game launches effortlessly every time, but with it installed it takes a while longer and in the end it sends me to [the aforementioned website](https://steamcommunity.com/sharedfiles/filedetails/?id=2330937567)

**Comment by ThirteenAG** [comment]
You believe? I just told you that it fails to launch even WITHOUT any mods, literally installed fresh steam copy and it took me 2 minutes to reproduce:

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/4904157/c25137f0-f9d6-4ada-ab23-af6772b00f5e

That's without asi loader, without any commandline, without any launch parameters or anything.

**Comment by HonScottoSolo** [comment]
> After retrying a bunch of times and reinstalling both the game and FusionFix I believe it is the ASI loader (dinput8.dll) that is causing the issues. I tried installing it seperatelly yet that didn't change anything. What did change though, somewhere throughhout the process is that steam is now sending me to [this ](https://steamcommunity.com/sharedfiles/filedetails/?id=2330937567) website after failing the game launch. Without FusionFIx the game launches effortlessly every time, but with it installed it takes a while longer and in the end it sends me to [the aforementioned website](https://steamcommunity.com/sharedfiles/filedetails/?id=2330937567)

It is because R.G. updated the game by disabling mods and multiplayer with the complete edition's new and last release of the game. Listen to @ThirteenAG. He is telling the truth. But if you wanted to mod it would require to down grade to a different version of the game. Do you research please.

**Comment by Hravec** [comment]
Update:
I uninstalled the game AND deleted the folder, which was left behind and reinstalled it. After this it finally started to work. 
I am sorry for any inconvenience I have caused, because it seems as though it was truly an issue on my part
