### ISSUE TITLE
[Question] Reflections are too... reflective?

### ISSUE THREAD

**Issue by Markie98** [ThirteenAG/GTAIV.EFLC.FusionFix#236]
With FusionFix installed, some things in the game look overly reflective to me, relative to both the vanilla PC version and console versions of the game. It's like roads go from matte to glossy and cars go from glossy to metallic. I tested the game completely vanilla and then completely vanilla plus FusionFix only to be sure it's not anything else causing it and the difference is clear. Concrete looks like varnished wood under certain lighting conditions and cars look like they just came out of the car warsher all the time. Maybe that's more technically correct and how it was supposed to be but I'm just wondering.

![GTAIV_2023_11_04_17_17_44_757](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/40475028/b0442932-13db-4382-97c6-223296128424)

**Comment by spidergrear2** [comment]
this is normal console behaviour.

**Comment by vavrinko** [comment]
> With FusionFix installed, some things in the game look overly reflective to me, relative to both the vanilla PC version and console versions of the game. It's like roads go from matte to glossy and cars go from glossy to metallic. I tested the game completely vanilla and then completely vanilla plus FusionFix only to be sure it's not anything else causing it and the difference is clear. Concrete looks like varnished wood under certain lighting conditions and cars look like they just came out of the car warsher all the time. Maybe that's more technically correct and how it was supposed to be but I'm just wondering.
> 
> ![GTAIV_2023_11_04_17_17_44_757](https://user-images.githubusercontent.com/40475028/280490681-b0442932-13db-4382-97c6-223296128424.png)

https://gtaforums.com/topic/991995-in-game-timecyc-editor/

Use this to edit the Global Reflection Value in your timesync.dat. That's what is responsible for the reflections.  Edit to your liking.

**Comment by Markie98** [comment]
> https://gtaforums.com/topic/991995-in-game-timecyc-editor/
> 
> Use this to edit the Global Reflection Value in your timesync.dat. That's what is responsible for the reflections. Edit to your liking.
Very nice, I had no idea that existed, thank you! I'll probably just keep it however FusionFix sets it for normal gameplay but I'll definitely experiment with that.

**Comment by vavrinko** [comment]
AFAIK Fusion does not change the reflection value. But the fixed shaders make the reflection stronger. Like it was on consoles. So if you change just that it won't affect Fusion fixes at all.

**Comment by Markie98** [comment]
Isn't FusionShaders part of FusionFix now? I just meant the mod in general changing the reflections.

**Comment by Tomasak** [comment]
Yes, it is intended behavior to match console look. Also Corona reflections were reduced a bit, which could potentionally mitigate the overall reflectiveness/shininess

**Comment by MOnkeMan5009** [comment]
tbh i want better reflections. like glossy or something. like on console 100%. So fusionfix has console reflections right?

**Comment by snarks567** [comment]
I like that the resolution of the reflections has been fixed. However I prefer the old PC reflection behavior as each car would have a different level of reflectiveness, some would look brand new, others would look old and dirty. Fusion Fix makes everything look brand new and shiny, I really wish I could turn it off.
