### ISSUE TITLE
you are not currently signed in

### ISSUE THREAD

**Issue by luigi98nes** [ThirteenAG/GTAIV.EFLC.FusionFix#237]
when i installed fusion fix on gta iv (i use steamunlocked version btw), i get this message, what do i do?

**Comment by RecklessGlue540** [comment]
Pirated copies are not supported.

**Comment by Zorklis** [comment]
Even on the steam version this message appears, it's just an old remnant of GFWL version. Still hoping for R* to remove entirely

**Comment by RecklessGlue540** [comment]
It doesn't seem to happen on the plain Rockstar Launcher version. 
I however have both skip intro and skip menu disabled.

**Comment by ThirteenAG** [comment]
RGL is just too slow to load, wait a second and it will proceed.

**Comment by Meesmoth** [comment]
If there's only a way to get rid of RGL check.....especially in 3rd-world countries where internet isn't 100% stable.

Downgrading is still a better option, it allows you for offline play as well.

**Comment by RecklessGlue540** [comment]
> RGL is just too slow to load, wait a second and it will proceed.

Literally this...

**Comment by RecklessGlue540** [comment]
Hey @ThirteenAG, I think this might be the cause:
https://gtaforums.com/topic/934545-fusionfix/?do=findComment&comment=1072268692

**Comment by Tomasak** [comment]
Only official copies are supported. If you are so keen on using pirated one, be sure to check proper sources for proper crack

**Comment by RecklessGlue540** [comment]
> Only official copies are supported. If you are so keen on using pirated one, be sure to check proper sources for proper crack

I use an official copy myself. It was just for these people, who for some reason don't want to buy this game...
