### ISSUE TITLE
[BUG] Phone cable transparent in cutscenes.

### ISSUE THREAD

**Issue by vavrinko** [ThirteenAG/GTAIV.EFLC.FusionFix#239]
Ok so it isn't a big issue. But the latest Fusion Fix causes the cables on telephones go transparent.

With FF 2.0
![20231105205801_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/96373757/2cf9a711-beca-4601-a362-bad2babe7832)

without FF
![20231105205426_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/96373757/ff141028-4b68-41e9-b60a-801c7119fdb2)

It's a minor annoyance, but could it be fixed?

It's the cs_cord.wdr or cs_cordclear.wdr in pc/anim/cutprops.img and the problem occurs only with the shaders installed.

**Comment by hammerfist11** [comment]
can confirm this happens.

**Comment by RecklessGlue540** [comment]
> can confirm this happens.

Actually, damn. This was fixed in Various Fixes the day this issue was reported iirc...
The Team likely forgot to close this...
Anyway, solution is install Various Fixes...
