### ISSUE TITLE
v1.96 can still work normally, v2.0 requires gfwl and cannot be archived, please update and modify, thank you

### ISSUE THREAD

**Issue by george5497** [ThirteenAG/GTAIV.EFLC.FusionFix#242]
v1.96 can still work normally, v2.0 requires gfwl and cannot be archived, please update and modify, thank you

**Comment by Nub865** [comment]
The same issue happens on my Steam version

**Comment by ThirteenAG** [comment]
Nonsense.

**Comment by george5497** [comment]
> 廢話。

Has anyone passed away in your family? 

Be careful what you say

**Comment by ThirteenAG** [comment]
You're the one saying `v2.0 requires gfwl`, which is not true and nonsensical, since gfwl is a dead service not related to this project in any way.

**Comment by george5497** [comment]
> You're the one saying `v2.0 requires gfwl`, which is not true and nonsensical, since gfwl is a dead service not related to this project in any way.

No matter what or what happens, do you speak politely on the Internet? Don’t think that the Internet can’t find you.
