### ISSUE TITLE
v2.0 doesn't work on wine, but v1.96 does

### ISSUE THREAD

**Issue by mozartilize** [ThirteenAG/GTAIV.EFLC.FusionFix#243]
Hi, I'm using Lutris wine-ge-8-22 and the newest 2.0 version doesn't work. Switch to v1.96 and it's working now.
GTA IV v1.2.0.32 DODI repack.

**Comment by Tomasak** [comment]
Only official copies are supported. If you are so keen on using pirated one, be sure to check proper sources for proper crack
