### ISSUE TITLE
Nothing seemed to change.

### ISSUE THREAD

**Issue by kernaldave** [ThirteenAG/GTAIV.EFLC.FusionFix#25]
Hi,

I downloaded and followed the install instruction, but it seem to have done nothing.  When I extracted the fusion fix, I had it replace any existing files.  This was a fresh/first install of the game, through stream and so through the Rock* launcher, with no back version mods  or work arounds.  When I click on the Fusion fix disc image in the common folder it says it is corrupted and appear to come that way from the Download.  Any help would be appreciated.

Thank you
David

**Comment by Naworm** [comment]
With Vanilla Fixes it will work ;)
link (hard to find the mod only) : https://www.moddb.com/mods/gta-iv-vanilla-fixes-ultimate-bugfix-megamod/downloads/gtaiv-vanilla-fixes-ultimate-bugfix-megamod

**Comment by Naworm** [comment]
Hello,
You forgot to add the ASI Loader, please follow the installation tutorial :
https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix#installation
