### ISSUE TITLE
[issue] Pedestrians or players will occasionally land on the tracks while getting on or off the subway.

### ISSUE THREAD

**Issue by HAYASHIDASEIYAKU** [ThirteenAG/GTAIV.EFLC.FusionFix#253]
It usually happens when the train is about to start. If you get off the train at this time, you may be standing in unexpected places.

Since there is no physical collision between pedestrians during the animation, their speed of getting on and off the train is very slow, and it is not uncommon to see people leaving the train and landing directly on the tracks.

**Comment by Tomasak** [comment]
please reopen in https://github.com/GTAmodding/GTAIV-Issues-List/issues
as this is vanilla bug
