### ISSUE TITLE
CTD when shooting with any weapon in high traffic areas 

### ISSUE THREAD

**Issue by EC-Mg51** [ThirteenAG/GTAIV.EFLC.FusionFix#255]
Whenever shooting around areas with high traffic/lot of peds the game freezes then CTD. I've been doing a lot of testing before posting and am 99% sure this comes from FusionFix because I don't have any mods installed and as soon as I remove it there seems to be no crash anymore. Any idea if there is a specific feature from FusionFix that might be the culprit?

**Comment by ThirteenAG** [comment]
Provide a crash dump. Create `CrashDumps` folder in root, reproduce, upload content here.

**Comment by RecklessGlue540** [comment]
> Whenever shooting around areas with high traffic/lot of peds the game freezes then CTD. I've been doing a lot of testing before posting and am 99% sure this comes from FusionFix because I don't have any mods installed and as soon as I remove it there seems to be no crash anymore. Any idea if there is a specific feature from FusionFix that might be the culprit?

Did you change any budgets in there? That can also cause crashing...

**Comment by EC-Mg51** [comment]
Thanks for the response, both budgets are left unchanged (0) so I don't think it is coming from this.
Here is the CrashDumps log I just got after reproducing the exact same CTD: 

[GTAIV.exe.20231115194329.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13368469/GTAIV.exe.20231115194329.log)

**Comment by ThirteenAG** [comment]
Dump file is necessary, not the log.

**Comment by EC-Mg51** [comment]
Sorry the Dump file is a little over 25mb so I've uploaded it here if it's okay: https://we.tl/t-NRzZNxKDLa

**Comment by ThirteenAG** [comment]
I don't think it's related to Fusion Fix, because the crash happens inside game's function `CTaskComplexSearchForPedOnFoot::createFirstSubTask` after it failed to allocate memory with `atPool::allocate(CTask::ms_pPool)`.

However, check with this version, does it make a difference?
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13368749/GTAIV.EFLC.FusionFix.zip)

Also, in which are this can be reproduced?

**Comment by ThirteenAG** [comment]
It's same crash, just in a different place, try to reproduce with this version: 
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13369100/GTAIV.EFLC.FusionFix.zip)

**Comment by EC-Mg51** [comment]
Just tried, it still crashes under the exact same circumstances, this time it was around Star Junction, again with a high traffic jam. It didn't record a Dump file though because the crash didn't quit the game this time, the screen was just frozen, but I expect it was the same as the previous ones I sent, with a different place. What do you reckon the problem is about?

**Comment by ThirteenAG** [comment]
> What do you reckon the problem is about?

Nothing I can think of directly, try renaming update folder to something else and launch with just asi, does it still happen?

> EDIT: No idea if it is related to this at all but one thing I noticed is that sometimes the game crashes right at launch, here is a Dump file of this if it can be of any help: https://we.tl/t-Q4yLhw41PH

Some kind of RGL bug, it happens for everyone, and currently I'm trying to report it to R* support, but they keep refusing to acknowledge it.

**Comment by EC-Mg51** [comment]
Unfortunately this keeps happening even with the folder renamed or removed. I tried to start a new game to make sure this wasn't a save corruption but it still occurs under the same circumstances, although it took me a bit longer to reproduce because there was less traffic on the first island at night. 
I just tested the _popcycle.dat file_ to increase the number of peds and cars then switching back to the original values, and the crashes seemed to happen much more quickly when increasing those, so I suspect the CTD is somehow related to cars and/or peds. You said there was a problem with the game's function failing to allocate memory for something, could it be memory reaching a limit somehow?

**Comment by ThirteenAG** [comment]
Yes, the CTask pool is full, but there's nothing directly affecting the number of peds or cars in this fix. Can you share your popcycle.dat so I could quickly reproduce the issue on my end?

**Comment by EC-Mg51** [comment]
This is so weird. I honestly thought the problem was from this fix but if it isn't I'm at a complete loss. 
Here is the unchanged/original popcycle I've been using all along while testing and having CTDs: https://we.tl/t-ays3XbzR07
And here's the one I just used with increased cars and peds density, which resulted in CTD happening much more quickly: https://we.tl/t-erQLkURSZo

**Comment by ThirteenAG** [comment]
> This is so weird. I honestly thought the problem was from this fix but if it isn't I'm at a complete loss.

With update removed, the asi is still there, so if you remove that and it still happens, then it's not fix's bug.
I can't seem to reproduce it, even with your popcycle.

**Comment by EC-Mg51** [comment]
Yes I think the problem comes from the game itself and not the fix because I just uninstall/reinstalled the game without Fusion Fix and the exact same issue happened. I even tried to completely delete the Rockstar folder from My documents where all the saves are located to start with a completely clean game, but the CTD occured while playing the first mission, while shooting with the shotgun in Bohan, Fortside. 
At this point I have no idea what to do, the game is unplayable with these crashes. But thanks a lot for your help, I really appreciate it.

**Comment by ThirteenAG** [comment]
Maybe try to remove settings file, or insert any folder name to CustomUserProfilePath in the ini:
`CustomUserProfilePath = save`, which will redirect settings to a new folder.

**Comment by EC-Mg51** [comment]
Okay I actually think deleting the settings file from the AppData/Local Rockstar folder did something! I played for about 10-15 mins with the increased popcycle.dat I sent you earlier. It seems to be working with the settings I am sending you as a screenshot below. However if I turn up the Detail Distance option to 100 the CTD starts to happen again, do you have any idea why? Anyway I have to thank you again because this is getting somewhere. 

![20231116073344_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/150619946/f5b686d5-ff29-4e74-a3d1-1045064334e6)

**Comment by ThirteenAG** [comment]
No idea, I tested with all sliders at 100, doesn't happen to me.

**Comment by ThirteenAG** [comment]
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13373173/GTAIV.EFLC.FusionFix.zip)
You can also try with this version, but I doubt it will make a difference.

**Comment by EC-Mg51** [comment]
Believe it or not, but it does seem to work with all sliders at 100 with this version. Was there something particular changed/added to it? 
I'll be doing further testing later with the game to make absolutely sure, but as of right now I played for about another 10min shooting like crazy in high traffic/peds areas and didn't encounter CTDs in places where I used to. Thanks for helping me with this, it was starting to drive me mad. I'll keep you updated here.

**Comment by ThirteenAG** [comment]
I increased the pool size from 1200 to 2400, but it's unclear if it's safe to do so. Could introduce crashes in other places, could just work.

**Comment by ThirteenAG** [comment]
I was told that it should be safe to increase this pool, so I'll include it in the next fusion fix version. Use the one attached here for now.

**Comment by EC-Mg51** [comment]
That's great news! In any case as I said I'll be playing and doing testing more later so I will keep this thread updated if anything happens. In the meantime, thanks a lot for the help and for actually providing a solution to this.

**Comment by ThirteenAG** [comment]
Okay, better use version from here then: https://ci.appveyor.com/project/ThirteenAG/gtaiv-eflc-fusionfix/build/artifacts

**Comment by EC-Mg51** [comment]
I've been playing for about 2 hours with the latest fix you attached, mostly exploring and doing some missions, and didn't encounter any crash so far except for a single one that happened at the far end of East Borough Bridge when going into the first island and switching quickly between the cinematic / aerial cameras while driving a car. 
This might not be related to the CTDs I had before or Fusion Fix at all, but if you want to check it here is a link to it: https://we.tl/t-xLnF2xtIRD

**Comment by EC-Mg51** [comment]
On a side note, could you please add the possibility to not skip the intro and menu when launching the game? I found the option was not present in the ini file of the latest version. I tried to add it back but it doesn't seem to work.

**Comment by ThirteenAG** [comment]
> This might not be related to the CTDs I had before or Fusion Fix at all, but if you want to check it here is a link to it: https://we.tl/t-xLnF2xtIRD

It's also ped related, the game passes nullptr intead of valid m_pDrawableReference, but in this case I don't know why it happens.

> On a side note, could you please add the possibility to not skip the intro and menu when launching the game? I found the option was not present in the ini file of the latest version. I tried to add it back but it doesn't seem to work.

You can do it in the Game options.

**Comment by EC-Mg51** [comment]
I'm not using any commandline.txt file or any added command through Steam. Had about 5 or 6 hours of gameplay since last time and a single crash occured around East Island City, a minute or so after finishing a mission involving some heavy shooting (Portrait of a Killer). I don't think this is much of a concerning issue though considering it's happening quite scarcely for now, but still, I'm keeping a sharp eye in case this happens again.

**Comment by EC-Mg51** [comment]
Okay so I got 2 CTDs, both happening after an hour of gameplay while entering a car or getting on a bike. Here are the dump files if you feel like checking: https://we.tl/t-flync6RD4n

**Comment by LWLonelY** [comment]
> [GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13373173/GTAIV.EFLC.FusionFix.zip) 您也可以嘗試使用此版本，但我懷疑它會有所作為。
I am #288
This version is working
But what ini file does this version use?
I tried to use GTAIV.EFLC.FusionFix.ini from 2.0 but it doesn't work

**Comment by ThirteenAG** [comment]
Fusion fix is at version 2.1, options are toggled in main menu.
