### ISSUE TITLE
Quick question about building dynamic shadows?

### ISSUE THREAD

**Issue by vavrinko** [ThirteenAG/GTAIV.EFLC.FusionFix#257]
Hi.
I just wanna ask whether there is a plan to include dynamic shadows for buildings and trees in the fix sometimes in the future.
Some of dynamic objects shadows look like they are floating in the air from certain angles.

**Comment by RecklessGlue540** [comment]
Possible, however that would completely break the optimization... In that case, DXVK should be mandatory to avoid stressing your system...

**Comment by vavrinko** [comment]
I also noticed that console dynamic shadows don't show the rider on motorbikes. NPC not PC.
I'm just pointing it out, if you guys would be able to fix that in the future it would be awesome :)
