### ISSUE TITLE
GTAIV.EFLC.FusionShaders?

### ISSUE THREAD

**Issue by Zorklis** [ThirteenAG/GTAIV.EFLC.FusionFix#258]
So is everything in [GTAIV.EFLC.FusionShaders
](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders) included in FusionFix or is it an add-on type thing? If it's the latter, add it into the description.

**Comment by RecklessGlue540** [comment]
Yes, FusionFix uses the shaders from there...

**Comment by Zorklis** [comment]
@RecklessGlue540 your comment didn't explain my question. Yes it uses some of their shader fixes (or all of them? but then that's not very clear)
It's just confuses me how - https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/releases/tag/V210 
says "*Requires FusionFix 2.0." and then has the download available, so it's add-on with extra fixes?

**Comment by RecklessGlue540** [comment]
> @RecklessGlue540 your comment didn't explain my question. Yes it uses some of their shader fixes (or all of them? but then that's not very clear) It's just confuses me how - https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/releases/tag/V210 says "*Requires FusionFix 2.0." and then has the download available, so it's add-on with extra fixes?

Before, Fusion Shaders were named Shader Fixes Collection. 
As more fixes that required changing code inside the GTAIV.exe itself rolled out (mainly the Z-fighting fix), it was better to integrate said code into FusionFix itself as that's the main project that aims to fix this game. 
Eventually, Shader Fixes Collection became a part of FusionFix, hence why they renamed Shader Fixes Collection to Fusion Shaders.
So any fix or change that Fusion Shaders might get over time, will be eventually merged into next FusionFix updates as well...
So nothing will stay add-on forever...

**Comment by juicermv** [comment]
> @RecklessGlue540 your comment didn't explain my question. Yes it uses some of their shader fixes (or all of them? but then that's not very clear) It's just confuses me how - https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/releases/tag/V210 says "*Requires FusionFix 2.0." and then has the download available, so it's add-on with extra fixes?

When you install FusionFix, you also get FusionShaders included. It's really not that hard. It's literally in the files.

**Comment by Zorklis** [comment]
Okay so it's included in Fusion Fix but FF can be outdated quite quick it seems
GTAIV.EFLC.FusionFix v2.0 released on November 2nd.
GTAIV.EFLC.FusionShaders V210 released November 14th and seems to contain more up to date changes
![explorer_ZEdkjDmFq5](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/85455465/cdf8466d-7783-46b2-aca9-6c624f62bfc6)

**Comment by Zorklis** [comment]
> It's really not that hard. It's literally in the files.

I'm just pointing out the confusing phrasing "*Requires FusionFix*"
Anyways I guess FusionFix contains some of the FusionShaders until further testing or it gets merged into the project and FS is the full deal.
