### ISSUE TITLE
Will different sensitivity with Mousefix = 1 and Mousefix = 0 ever be fixed

### ISSUE THREAD

**Issue by nonoash** [ThirteenAG/GTAIV.EFLC.FusionFix#263]
I raised this issue already with other people that Mousefix = 1 increase the mouse sensitivity drastically compared to mousefix = 0
A few weeks ago, issues got closed and recevied a GitHub notification that the problem was solved with 2.0... which is clearly wrong.

I just want to know if it can ever be fixed or is it how mousefix = 1 is compensating the deadzone effect by increase the sensitivity?

It's ok if there's no proper solution to this problem, I'll just move on instead of hanging on to potential hopes every once in a while.

**Comment by ThirteenAG** [comment]
What do you suggest needs to be done? I think it makes sense that with deadzone mouse movement is faster, the more deadzone the slower the movement is.

**Comment by ThirteenAG** [comment]
Half of that code wasn't made by me, so I don't know what's going on with it. I do see that the sensitivity slider doesn't affect mouse movement at all for some reason, and I'm pretty sure it should not be that way.

> Seems there's confusion about the problem hence why it wasn't fix or fixable.

Nobody is really looked into it.

**Comment by ThirteenAG** [comment]
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13427194/GTAIV.EFLC.FusionFix.zip)
Can you try this 2.1 build and see if it's any better?
It's hard for me to notice sensitivity difference, but I've added some code that decreases sensitivity if slider is less than 10, increases if slider is more than 10.

**Comment by Tomasak** [comment]
New RAW input option was added and mouse fix was removed, sniper seems to be behaving better now, comment for unlock if persist
