### ISSUE TITLE
[Request] Toggle for improved bloom shader

### ISSUE THREAD

**Issue by Arctic94** [ThirteenAG/GTAIV.EFLC.FusionFix#267]
I've noticed bloom has very harsh edges with a cross-like pattern, looks very nice on small specular highlights like water and in general looks ok on low/medium contrast scenery but in many cases looks like plain ghosting of an object by the harsh-edge nature of the shader and probably an oversight by the developers aiming for 720p back in the day or/and lack of more advance algorithms, anyways looks very distracting playing on modern resolutions.
 
Would be nice for a plus or improved bloom toggle for a more natural/rounded/less harsh-edges looking bloom,
in most cases is very noticeable on high contrast situations.

![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/46092549/6ddfec51-b1a6-45ab-9303-1af62ebc019b)
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/46092549/b0f5cae4-ea42-4e17-9180-f16a989f9698)
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/46092549/15a0ee77-065c-44b8-b5eb-497098ce24bc)
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/46092549/9e927de5-7d09-4050-9f1c-b97f5e23c9fd)

**Comment by RecklessGlue540** [comment]
Hmm. I'm not actually sure if this is caused by the Bloom, or the Definition Stipple Filter...
I do notice this quite often... Especially when running up some stairs in Middle Park, it will look like Niko's edges are transparent, the stairs being partially seen through him...
