### ISSUE TITLE
[CE issue] Unable to select 4K resolution with Nvidia DSR or AMD VSR.

### ISSUE THREAD

**Issue by ClaudeLib** [ThirteenAG/GTAIV.EFLC.FusionFix#27]
Unless I set my desktop to 4K beforehand. Probably unable to go beyond the desktop resolution. 1.0.7.0 does not have this issue.

**Comment by Naworm** [comment]
Try to disable theses options, worked for me with NVIDIA UHD DSR :
![image](https://user-images.githubusercontent.com/48997616/106789360-7323a780-6652-11eb-9ccb-3b31e5a887bc.png)

**Comment by Tomasak** [comment]
Can anyone reproduce this issue? I can run it at 4K with DSR just fine
