### ISSUE TITLE
[Request] Limit Adjuster

### ISSUE THREAD

**Issue by MrGarapablo** [ThirteenAG/GTAIV.EFLC.FusionFix#271]
Good evening, I would like to know if it would be very complicated to implement a Limit Adjuster to FusionFix, since the only two options are not compatible with the Complete Edition.

**Comment by Tomasak** [comment]
Get 2.1
 add ExtendedLimits=1 under BudgetedIV
try if your required limits are adjusted

dont forget to try on new game! (its even better to flush saves for some mods)

**Comment by MrGarapablo** [comment]
> Get 2.1 add ExtendedLimits=1 under BudgetedIV try if your required limits are adjusted
> 
> dont forget to try on new game! (its even better to flush saves for some mods)

Thanks for the reply! Sadly, it didn't work. I'm trying to add more lines into handling.dat but after 50 or so new lines, the game crashes while loading the game. It doesn't matter if I try a new game or trying to load an old savegame.

**Comment by MrGarapablo** [comment]
> Get 2.1 add ExtendedLimits=1 under BudgetedIV try if your required limits are adjusted
> 
> dont forget to try on new game! (its even better to flush saves for some mods)

Amazing! It worked! Thank you so much for the quick replay and fix!

**Comment by ARScorpion** [comment]
> Get 2.1 add ExtendedLimits=1 under BudgetedIV try if your required limits are adjusted
> 
> dont forget to try on new game! (its even better to flush saves for some mods)

There is any way to increase limit of .cuts files I really need help
