### ISSUE TITLE
FusionFix specific settings don't save

### ISSUE THREAD

**Issue by lokasz** [ThirteenAG/GTAIV.EFLC.FusionFix#272]
No setting added by FusionFix is saved after the game restarts.

**Comment by RecklessGlue540** [comment]
Only thing I can think of is that your GTAIV's directory is read-only.
Right click the game's folder, proprieties, security , edit, check modify, done.

**Comment by Tomasak** [comment]
try creating empty GTAIV.EFLC.FusionFix.cfg file in plugins subfolder

**Comment by ThirteenAG** [comment]
What's the game version (rgl/steam) and game path?

**Comment by jaypolanco96** [comment]
Uncheck Read-Only in the properties setting for the GTA IV directory then do the same for the plugins folder where GTAIV.EFLC.FusionFix config files are then run game as administrator. Change the fusion fix settings you want to keep and then next time you play GTA IV you should have all your FusionFix settings saved.
