### ISSUE TITLE
Power lines don't cast shadows

### ISSUE THREAD

**Issue by juicermv** [ThirteenAG/GTAIV.EFLC.FusionFix#273]
Pretty self-explanatory. I've noticed that power lines and wires don't seem to cast any shadows at all.
This is especially noticeable in Alderny since it has a ton of random electric wiring all over its streets.

**Comment by RecklessGlue540** [comment]
This tweak should enable them:
https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/tree/main/other_assets/Opaque%20Wires/
They weren't included here, because this tweak also makes the power lines more jagged, since the blur is removed.

**Comment by juicermv** [comment]
Wouldn't it be possible to make the normal transparent version cast shadows too though? Genuinely asking here

**Comment by Tomasak** [comment]
Sadly its intended behaviour and only solution was already posted which comes with drawbacks
