### ISSUE TITLE
GTA IV Complete Edition (1.2.0.43) Doesn't Launch

### ISSUE THREAD

**Issue by bagassw-exe** [ThirteenAG/GTAIV.EFLC.FusionFix#274]
After extracting all files from zip to GTA IV complete edition folder, game doesn't launch but if i delete dinput8.dll (which is asi loader include in fusion fix) it launches. Am I doing wrong during installation?

**Comment by bagassw-exe** [comment]
[CrashDumps.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13465687/CrashDumps.zip)
This is my crashdump file as you suggested to make folder CrashDumps in game's root folder, Thank you..

**Comment by ThirteenAG** [comment]
Widescreen fix is not compatible with this version. Will be fixed, but nobody tests that version.

[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13465862/GTAIV.EFLC.FusionFix.zip)

**Comment by bagassw-exe** [comment]
Thank you so much, it works now..🙏🔥
