### ISSUE TITLE
Still cannot sign in to SocialClub with FF 2.1

### ISSUE THREAD

**Issue by Nub865** [ThirteenAG/GTAIV.EFLC.FusionFix#276]
Title, legit Steam copy, SocialClub & RGL installed, asks to create a gamer profile and when clicking OK or pressing Enter nothing happens. Pre 2.0 builds have no such issues

**Comment by ThirteenAG** [comment]
Screenshot?

**Comment by Tomasak** [comment]
did you try waiting a bit if SC manages to log itself in?

**Comment by pc-v2** [comment]
spam enter and wait or disable skip intro
