### ISSUE TITLE
[Issue] Game crashes when in a police chase with ExtendedLimits = 1 parameter

### ISSUE THREAD

**Issue by MrGarapablo** [ThirteenAG/GTAIV.EFLC.FusionFix#277]
Good evening.

I have tested the new BudgetedIV option, ExtendedLimits = 1, and it works perfectly, I can use a new handling.cfg file with more than 100 lines and the game starts without problems.

The problem is that, when starting a chase with the police or crashing into a police car, the game crashes. I have tried with a fully vanilla installation without mods, except for FusionFix 2.1 and the ExtendedLimits = 1 parameter, and the same thing happens, when I crash with the police or have a search level, the game crashes. Attached is the crash dump generated after the crash.
[CrashDumps.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13467924/CrashDumps.zip)

**Comment by ThirteenAG** [comment]
There was a typo of sorts, you can try the build from here: https://ci.appveyor.com/project/ThirteenAG/gtaiv-eflc-fusionfix/build/artifacts

Should work now.
