### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by CLaudioLamar** [ThirteenAG/GTAIV.EFLC.FusionFix#28]
Clean install of the game... put the files in the root directory of the game but nothing changed... Am I doing something wrong ? I'm confused. After the install I'm supposed to run the game as normal right ?

**Comment by m0v34x** [comment]
+

**Comment by m0v34x** [comment]
1.0.7.0
[asilog.txt](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/5782925/asilog.txt)
[asilog.txt](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/5782929/asilog.txt)
[ScriptHook.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/5782932/ScriptHook.log)

**Comment by Naworm** [comment]
Yep seems not working on legal copies.

**Comment by Naworm** [comment]
> Yep seems not working on legal copies.

Ok, lil' update, It's only working with GTA IV Vanilla Fixes.

**Comment by Naworm** [comment]
Hello,
Please make sur that you do not forgot to add the ASI Loader, follow the installation procedure:
https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix#installation
