### ISSUE TITLE
Cannot even start the game with this mod on Steam's IV

### ISSUE THREAD

**Issue by kryllyn** [ThirteenAG/GTAIV.EFLC.FusionFix#282]
Hello, 
after downloading this mod and unpacking it in root game folder, the game starts but screens only black screen and cursor suggest that this game is loading but after even 15 minutes - there's nothing new on the screen. Only freezed game as black window.

This is fresh installation of GTA IV CE from Steam

**Comment by ThirteenAG** [comment]
I don't know, you're the first one with such problem. Maybe try windowed mode?

**Comment by Jenking1** [comment]
I have the same issue, but with non-Steam just Rockstar Launcher. Fresh install, copied the contents of the zip into the game directory, and the game doesn't start (black screen, loading cursor, not responding in task manager). Tried with both 2.0 and 2.1, set skip intro/menu to 0 as well as windowed in case it was something to do with that.

Tried 1.96 and the game launches fine! Haven't had a chance to test much further in

**Comment by RecklessGlue540** [comment]
> I have the same issue, but with non-Steam just Rockstar Launcher. Fresh install, copied the contents of the zip into the game directory, and the game doesn't start (black screen, loading cursor, not responding in task manager). Tried with both 2.0 and 2.1, set skip intro/menu to 0 as well as windowed in case it was something to do with that.
> 
> Tried 1.96 and the game launches fine! Haven't had a chance to test much further in

My RGL works fine....

**Comment by Tomasak** [comment]
if issue persist please open new issue with memorydump/crashdump
