### ISSUE TITLE
Feature request: PlayStation 3 controller prompts

### ISSUE THREAD

**Issue by Panzermann11** [ThirteenAG/GTAIV.EFLC.FusionFix#286]
For the next update, I'd like to suggest an option to switch between Xbox 360 and PlayStation 3 button prompts. This would come in handy for those who are playing the game using a DualShock 3, or newer PS controllers through an external program.

**Comment by Tomasak** [comment]
already issue opened for it #118

**Comment by Panzermann11** [comment]
I'm specifically talking about the official PS3 prompts, seen [here.](https://tcrf.net/Grand_Theft_Auto_IV/Unused_Textures#PS3_Controller_Icons)

**Comment by RecklessGlue540** [comment]
> The PC version of this game contains the file buttons_ps3.wtd, and frontend_ps3.wtd which is located in pc\textures. 

I don't know who reported that. It's false information. PC version only contains buttons_360.wtd and frontend_360.wtd which are used by default. Maybe they were there on the retail release, but latest CE does not contain them anymore.

**Comment by Tomasak** [comment]
> > The PC version of this game contains the file buttons_ps3.wtd, and frontend_ps3.wtd which is located in pc\textures.
> 
> I don't know who reported that. It's false information. PC version only contains buttons_360.wtd and frontend_360.wtd which are used by default. Maybe they were there on the retail release, but latest CE does not contain them anymore.

it did contain in preCE releases. CE removed all ps3 files

also when it would be added, it would be then very easy to add other gamepads to select from

**Comment by Panzermann11** [comment]
Something to mention in case the feature is going to be implemented, in the PS3 version, the colors of the phone buttons and the power colors in QUB3D are different to match the PS3's button colors. The call button is a light blue like PS3's X button instead of green like Xbox's A button.
