### ISSUE TITLE
The game crashes when I shoot

### ISSUE THREAD

**Issue by LWLonelY** [ThirteenAG/GTAIV.EFLC.FusionFix#288]
game version:1.2.0.59
FusionFix version:2.0
CrashDumps:[CrashDumps.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13520655/CrashDumps.zip)
with mod:[Realistic Traffic and Pedestrian Mod for GTAIV, EFLC and The Complete Edition](https://www.gtainside.com/en/gta4/mods/139138-realistic-traffic-and-pedestrian-mod-for-gtaiv-eflc-and-the-complete-edition/)

When I use the real traffic and pedestrian mods without FusionFix everything works fine and I can shoot without crashing
But when used with FusionFix it crashes whenever shoot.

**Comment by ThirteenAG** [comment]
The game is hitting ctask limit and crashes.
https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/288

**Comment by Tomasak** [comment]
retest with clean game and report back if crash continues.
