### ISSUE TITLE
[REQ] Key to toggle DoF 

### ISSUE THREAD

**Issue by pc-v2** [ThirteenAG/GTAIV.EFLC.FusionFix#289]
If I remember correctly, [P] is used to toggle ~~depth of field~~ definition inside the game, I think changing it to toggle DoF much better for fusion fix

**Comment by MagicAl6244225** [comment]
Do people even use this? In GTAV P is used to Pause. Why is one graphics setting mapped to a hotkey?

**Comment by Tomasak** [comment]
i dont see a reason for this, to me it seems to be debug leftover.
