### ISSUE TITLE
[Suggestion] Ability to increase stream memory in .ini file

### ISSUE THREAD

**Issue by dacbe0701** [ThirteenAG/GTAIV.EFLC.FusionFix#290]
I really need to increase stream memory to thread memory issues (due to modded higher textures, high poly models). For 1.0.8.0 and below iirc this can probably be done using the limit adjuster, but for the Complete Edition this is simply not possible.

**Comment by dacbe0701** [comment]
> Is that not set in the stream.ini file inside of the "pc" folder?

Unfortunately, no

**Comment by RecklessGlue540** [comment]
Increasing Game Heap limit could help. But It's only in IVTweaker.
Would be nice having it here as well...
