### ISSUE TITLE
Alternative Dialogues causing bugs in mission Blow You Up

### ISSUE THREAD

**Issue by KINGJIN2008** [ThirteenAG/GTAIV.EFLC.FusionFix#291]
when alt dialogues is off, playboy x doesn't follow niko, the mission fails.
only when it's on, he will follow niko to the apartment
but when niko send x to his place, the mission will fail even when alt dialogues is on
i can't send video cause it's too large
[C6A713EF.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13541170/C6A713EF.zip)

here's my save file

**Comment by ThirteenAG** [comment]
Thanks, pass that mission with current release and alt. dialogues on, then you can use the latest release from here
https://ci.appveyor.com/project/ThirteenAG/gtaiv-eflc-fusionfix/build/artifacts
I think the rest of them should be fine.

**Comment by arinc9** [comment]
@ThirteenAG I think this is an issue on the vanilla steam build of GTA IV. I've replied to this relevant Reddit thread.

https://www.reddit.com/r/GTA/comments/1894mza/i_facing_an_issuebug_in_blowing_your_cover/

**Comment by ThirteenAG** [comment]
It's not, it's a bug within v2.1, so it's best to use 2.2 for a new game, or upgrade with alt. dialogues set to on.

**Comment by arinc9** [comment]
Thanks, I was just editing my comment that, if I understand you correctly, the mission abruptly ends because of the variable on the save which was set by FusionFix v2.1.

**Comment by ThirteenAG** [comment]
Yes, unfortunately.

**Comment by NoelCosta** [comment]
Which variable though? maybe we can just edit the save file?

**Comment by Darksider13** [comment]
> It's not, it's a bug within v2.1, so it's best to use 2.2 for a new game, or upgrade with alt. dialogues set to on.

I haven't heard of FusionFix until today and I've been playing with an almost entirely vanilla build (save for this [Radio Downgrader mod](https://www.nexusmods.com/gta4/mods/234?tab=description&BH=3) from Nexus). Haven't touched FusionFix and I've been experiencing this same exact bug. Able to replicate it down to the letter. It's absolutely present in the vanilla steam build.

**Comment by ThirteenAG** [comment]
> > It's not, it's a bug within v2.1, so it's best to use 2.2 for a new game, or upgrade with alt. dialogues set to on.
> 
> I haven't heard of FusionFix until today and I've been playing with an almost entirely vanilla build (save for this [Radio Downgrader mod](https://www.nexusmods.com/gta4/mods/234?tab=description&BH=3) from Nexus). Haven't touched FusionFix and I've been experiencing this same exact bug. Able to replicate it down to the letter. It's absolutely present in the vanilla steam build.

That one just bundles fusion fix within.
