### ISSUE TITLE
all config options appear to be linked together

### ISSUE THREAD

**Issue by MattHardwick34** [ThirteenAG/GTAIV.EFLC.FusionFix#294]
hard to explain but config options all appear to be linked to the same change/value - for example I changed framerate to 75 and every single new config option now has a value of 75 - if I try to change shadow filter to off, every option will be set to off and so on... picture explains better than I can: 

![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/36822930/1ef48fd6-5e6e-4c3d-9945-dac80bcfbbc6)
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/36822930/0202fe75-2767-4e31-923a-4fa59c803e25)
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/36822930/9a924851-5eca-44d9-8235-60cdf60de055)
 
 latest GTA4 version from steam, and latest FF downloaded today.

**Comment by ThirteenAG** [comment]
That can only happen if asi is not loaded.

**Comment by MattHardwick34** [comment]
I removed everything and started from scratch and it's working now - I guess some file didn't update properly or got replaced/corrupted.
