### ISSUE TITLE
[Question] What is the difference between ScriptCutsceneFpsLimiter and CutsceneFpsLimiter?

### ISSUE THREAD

**Issue by suyash691** [ThirteenAG/GTAIV.EFLC.FusionFix#295]
The readme mentions of two fps limiters for cutscenes (CutsceneFpsLimiter and the ScriptCutsceneFpsLimiter which is given as an alternate to using the FOV based fix)

**Comment by RecklessGlue540** [comment]
ScriptCutsceneFovLimit limits the FOV for scripted cutscenes to prevent them zooming too much at high framerates.
ScriptCutsceneFpsLimit limits the FPS for scripted cutscenes. Limiting this at 30 makes the above useless.
CutsceneFpsLimit limits the FPS for real cutscenes.
