### ISSUE TITLE
Fix Z-Fighting issues

### ISSUE THREAD

**Issue by GOOGORO** [ThirteenAG/GTAIV.EFLC.FusionFix#296]
I did not install the texture module, and this kind of broken screen appeared after a while. Is it related to the Z-Fighting repair, or is it a problem with the game itself.

![GTAIV 2023-12-07 02-28-56](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/150298483/a4de931a-10a5-4c21-9204-a2aa2ffee42d)
![GTAIV 2023-12-07 02-29-23](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/150298483/6902d3cd-df95-4e08-ba09-96dd106b2851)
![GTAIV 2023-12-07 02-29-54](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/150298483/fda82ccd-dcb9-4e54-95f5-02c398fcbaad)
![GTAIV 2023-12-07 02-27-18](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/150298483/ac38ac98-a8b7-4d02-8f8d-158a9c7c03b6)
![GTAIV 2023-12-07 02-28-53](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/150298483/5724f346-a72b-4211-83ca-8b485d7b4200)

**Comment by RecklessGlue540** [comment]
> I would like to ask if the Z-Fighting repair is related to the broken picture when the texture module is not installed.

Wut? Not at all. Look here: https://www.youtube.com/watch?v=sAfKfvAIsXw

The bug you have is related to the road texture mods that you have.
GTA IV breaks when road textures are 2048x2048 or higher. See here: https://gtaforums.com/topic/934545-fusionfix/?do=findComment&comment=1070929544

**Comment by nastyyaboi** [comment]
what is the autism is this

**Comment by GOOGORO** [comment]
> > 請問Z-Fighting修復是否與未安裝紋理模組時畫面破損有關？
> 
> 呃？一點也不。看這裡：[https://www.youtube.com/watch?v =sAfKfvAIsXw](https://www.youtube.com/watch?v=sAfKfvAIsXw)
> 
> 您遇到的錯誤與您擁有的道路紋理模組有關。 當道路紋理為 2048x2048 或更高時，GTA IV 會崩潰。請參閱此處： https: [//gtaforums.com/topic/934545-fusionfix/ ?do=findComment&comment=1070929544](https://gtaforums.com/topic/934545-fusionfix/?do=findComment&comment=1070929544)

I see! Many high-definition textures, including vehicles, should be unusable. How can I distinguish between 2048x2048 files? Or is there a better solution? Thank you.

**Comment by WhiteTree97** [comment]
go kys

**Comment by Tomasak** [comment]
game/pc cannot keep up with loading assets, which are clearly custom
