### ISSUE TITLE
stuck in loading black screen

### ISSUE THREAD

**Issue by zahediparsa** [ThirteenAG/GTAIV.EFLC.FusionFix#297]
After installing the fusionFix on the complete edition and starting it for the first time, game launches but it's stuck in a black screen, where the mouse cursor is the loading type and it's stuck there forever.

**Comment by ThirteenAG** [comment]
I even asked to test with different build here: https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/282#issuecomment-1835804728
No reply, so I guess it's not a big deal.

**Comment by zahediparsa** [comment]
it was solved by doing this (https://imgur.com/Ez9kLSr) minus the "run as administrator" and it worked.

**Comment by ThirteenAG** [comment]
What monitor do you have?
