### ISSUE TITLE
Loading pigeons / stunt jumps crashes the game

### ISSUE THREAD

**Issue by BorbingoBoy** [ThirteenAG/GTAIV.EFLC.FusionFix#3]
Using this mod, there's a random chance for the next pigeon / stunt jump that loads to crash the game if at least one other pigeon / stunt jump has already been exterminated / completed in a given session. They can happen consistently, though a different order can help prevent crashing. For example, if pigeons around have been exterminated in a specific order before reaching the pigeon on the bridge above Acter, approaching it crashes the game.
Not to be confused with the bug that crashes the game where exterminating a pigeon may randomly crash the game. Disabling the mod solved the issue.

INI contents:

[MAIN]
RecoilFix = 1
DefinitionFix = 1
EmissiveShaderFix = 1
HandbrakeCamFix = 1
AimingZoomFix = 1
FlickeringShadowsFix = 1

[FRAMELIMIT]
FpsLimit = 0
CutsceneFpsLimit = 50
ScriptCutsceneFovLimit = 20

[MISC]
DefaultCameraAngleInTLAD = 0
PedDeathAnimFixFromTBOGT = 1
DisableCameraCenteringInCover = 1

[EXPERIMENTAL]
LodShift = 0.0
LodForceDistance = 0

**Comment by ThirteenAG** [comment]
I don't think I even remotely touch anything related to that. Crashdump and crash log might be necessary.
