### ISSUE TITLE
Game won't even launch with the 2.2 version.

### ISSUE THREAD

**Issue by WhiteTree97** [ThirteenAG/GTAIV.EFLC.FusionFix#300]
I'm using the Steam version. 
Here's my Crash dump
[CrashDumps.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13621209/CrashDumps.zip)

**Comment by Meriato** [comment]
Have you tried launching it a second time and so on? Sometimes the game won't open on the first try.

**Comment by ThirteenAG** [comment]
Yes, that's indeed the one caused by RGL, it has nothing to do with fusion fix.
I reported it to support a month ago, they blamed everything but RGL, then claimed I have my system infected by the virus and closed the ticket.

**Comment by Nub865** [comment]
> Yes, that's indeed the one caused by RGL, it has nothing to do with fusion fix. I reported it to support a month ago, they blamed everything but RGL, then claimed I have my system infected by the virus and closed the ticket.

Then maybe you should **finally** remove that functionality that you implemented yourself since v2.0? I'm talking about XLiveLess (not sure), the thing in the .ini [USERPROFILE] CustomUserProfilePath

None of your v2.0+ builds work at all, screw this
