### ISSUE TITLE
Forever loading on TLAD mission "Off Route"

### ISSUE THREAD

**Issue by xAphex** [ThirteenAG/GTAIV.EFLC.FusionFix#303]
When starting **Off Route** mission in **TLAD**, after the cutscene the game goes into loading screen and never stops loading unless you ALT+F4 the game.

Here is the issue being discussed on Reddit with some fixes but a FisionFix would be appreciated if possible:
https://www.reddit.com/r/GTA4/comments/g5jywf/endless_loading_on_tlad_mission_off_route/

Thank you

**Comment by ThirteenAG** [comment]
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13626504/GTAIV.EFLC.FusionFix.zip)
Can you try this build, see if it makes any difference?

**Comment by xAphex** [comment]
> [GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13626504/GTAIV.EFLC.FusionFix.zip) Can you try this build, see if it makes any difference?

Nope, its still loading forever.

**Comment by ThirteenAG** [comment]
I was able to reproduce, but can't with this build.

**Comment by xAphex** [comment]
> I was able to reproduce, but can't with this build.

List of everything im using with GTA 4:
1. FusionFix v2.2
2. [FusionShaders v210](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders)
3. [DXVK 2.3](https://github.com/doitsujin/dxvk)
4. [Radio Downgrader 1.80](https://www.nexusmods.com/gta4/mods/234)

hopefully its not one of these causing the issue, but i will continue testing.

**Comment by ThirteenAG** [comment]
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13627017/GTAIV.EFLC.FusionFix.zip)
Try this, if still doesn't work, then I'm out of ideas. Could be few different things that are causing it.

Does it get stuck every time for you?

**Comment by xAphex** [comment]
> [GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13627017/GTAIV.EFLC.FusionFix.zip) Try this, if still doesn't work, then I'm out of ideas. Could be few different things that are causing it.
> 
> Does it get stuck every time for you?

Nope, still persists.

But i put fps limit to 50fps before going into mission and that fixed it.

Thanks for the quick replies and support ❤️

**Comment by xAphex** [comment]
Maybe my **commandline.txt** had something to do with it:
```
-refreshrate 144
-width 1920
-height 1080
-nomemrestrict
-norestrictions
-noprecache
-novblank
-frameLimit 0
-percentvidmem 100
-availablevidmem 12288
```

**Comment by RecklessGlue540** [comment]
Do not use noprecache with DXVK.
framelimit and novblank won't do nothing either.
DXVK is also known to increase loading times but I only got that on the old patches.

**Comment by ThirteenAG** [comment]
@xAphex Can you reproduce with the build I sent here, open task manager when the game is stuck on loading, create a dump file of gtaiv process, and upload somewhere? Important to do it with the build above, and due to the game not crashing, dmp file will be rather large.

**Comment by xAphex** [comment]
> @xAphex Can you reproduce with the build I sent here, open task manager when the game is stuck on loading, create a dump file of gtaiv process, and upload somewhere? Important to do it with the build above, and due to the game not crashing, dmp file will be rather large.

sorry for late reply got busy with work.

i already fixed the issue like i stated above, how can i reproduce it again?

**Comment by xAphex** [comment]
> Do not use noprecache with DXVK. framelimit and novblank won't do nothing either. DXVK is also known to increase loading times but I only got that on the old patches.

no issue with loading times at all with my game, but i will remove the commandlines u mentioned and see what happens.
thanks

**Comment by ThirteenAG** [comment]
> i already fixed the issue like i stated above, how can i reproduce it again?

No idea.

**Comment by xAphex** [comment]
@ThirteenAG OK, while playing **TBOGT**, at mission **Momma's Boy** after the first cutscene the game loads forever.

this time i managed to create a process dump while it was loading: https://ufile.io/ijax1bo3

it's compressed to .7z cause its 2.6GB, if that's an issue i can upload it full.

thank you

**Comment by ThirteenAG** [comment]
It that something that happens only with Fusion Fix? Or only with high fps? All the time or randomly? Can you confirm?

**Comment by xAphex** [comment]
> It that something that happens only with Fusion Fix? Or only with high fps? All the time or randomly? Can you confirm?

i havent tried without fusionfix, but the fix is always to limit fps to 50-60.

thats why i provided the dump this time, maybe u can analyze it to see what exactly is causing the problem.

i can always limit the fps to 50 during cutscenes and have no problems whatsoever, its just for the sake of others that dont know about the problem and cant find a fix.

**Comment by ThirteenAG** [comment]
I can see where it gets stuck, but not sure what to do with it.

**Comment by xAphex** [comment]
> I can see where it gets stuck, but not sure what to do with it.

what exactly gets stuck? if you dont mind me asking

**Comment by ThirteenAG** [comment]
```
>	win32u.dll!_NtUserPeekMessage@24()	Unknown	Non-user code. Symbols loaded without source information.
 	user32.dll!_PeekMessage()	Unknown	Non-user code. Symbols loaded without source information.
 	user32.dll!PeekMessageA()	Unknown	Non-user code. Symbols loaded without source information.
 	gameoverlayrenderer.dll!60323012()	Unknown	Non-user code. Cannot find or open the PDB file.
 	[Frames below may be incorrect and/or missing, no symbols loaded for gameoverlayrenderer.dll]		Annotated Frame
 	GTAIV.exe!00630ebf()	Unknown	Non-user code. Cannot find or open the PDB file.
 	GTAIV.exe!008b3242()	Unknown	Non-user code. Cannot find or open the PDB file.
 	GTAIV.exe!00b769d1()	Unknown	Non-user code. Cannot find or open the PDB file.
```

**Comment by ThirteenAG** [comment]
I think I've found a workaround for this, at least from a couple of tests I can see the game loads after skipping cutscene, and without workaround it doesn't, all with ~3000 fps during loading. Here is a test version:
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13898369/GTAIV.EFLC.FusionFix.zip)

@xAphex

**Comment by RecklessGlue540** [comment]
> I think I've found a workaround for this, at least from a couple of tests I can see the game loads after skipping cutscene, and without workaround it doesn't, all with ~3000 fps during loading. Here is a test version: [GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13901257/GTAIV.EFLC.FusionFix.zip)
> 
> @xAphex

The "fix" seems to be messing with the loading bar speeds... Would be nice if it was fixed back to the patch 1.0.4.0 speed (just like the PS3 version's 30fps speed) regardless of framerate...

Secondly, the loading times from the menu to "loading..." now depend on the framerate again if the limiter is used. 
Before, the game loaded instantly, then the "loading..." speeds were (and still seem to be) affected by the framerate. They'd have to be separated somehow, and making both instances load as soon as ready regardless of fps, I think.

Here's the issue I'd posted before about this, in any case: https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/302

**Comment by ThirteenAG** [comment]
Game gets stuck in an infinite loop without a frame limiter, I could repro it even with 60 fps, didn't happen at 30, but who knows, more tests needed.
That in turn increases loading times, but there's nothing I can do about that. Ideas are welcome.

**Comment by xAphex** [comment]
@ThirteenAG I tried again with FusionFix v2.5.0, same problem. (**TBOGT**, at mission **Momma's Boy**)

Here's a newer dump, maybe it shows something different this time: https://ufile.io/qpsohqgp

**Comment by ThirteenAG** [comment]
What about Off Route? I only ever tested that one. If I can repro with Momma's Boy, I'll take a look.
Judging by the mem dump, it's a different function that hangs.

**Comment by ThirteenAG** [comment]
Also try 2.4.6 - v2.4.9, would be interesting to know if any of them "fixes" it.
