### ISSUE TITLE
Does anyone knows the file for console gamma? 

### ISSUE THREAD

**Issue by Mrsuss60** [ThirteenAG/GTAIV.EFLC.FusionFix#305]
i just want the console gamma, other stuff makes my game laggy

**Comment by spidergrear2** [comment]
disable the rest of the stuff in the menu settings and keep the console gamma.

**Comment by Mrsuss60** [comment]
> disable the rest of the stuff in the menu settings and keep the console gamma.

some settings can't be disabled!

**Comment by RecklessGlue540** [comment]
Can you give an example?
PCSS Shadows: Massive performance hit. Can be easily avoided...
Depth Of Field: Massive performance hit especially at higher resolutions. Can be disabled or lower the res and see if it gets better... Or lower the Distant Blur setting. That lowers it's intensity. Medium is PC default with definition off.
Normal Shadows: Can be easily set to high to avoid the performance hit... Not recommended to use with PCSS.
Console Gamma: No performance hit
Bloom: Barely any hit but it still scales with the resolution...
Motion Blur: Can be easily avoided... It hits a bit.
Z-Fighting Fix: This is everything. Impacts performance a bit depending on hardware, but essential.
Additionally, use the [Console Light Models](https://gtaforums.com/topic/989098-console-visuals-the-complete-edition/) to help. These won't cast shadows and performance is massively improved. Make sure to delete FusionLights.img from FF if you want to use them.

**Comment by Mrsuss60** [comment]
yeah unfortunately I have a shitty GT 710 
that's why I'm only asking for that beautiful console gamma setting  

> Can you give an example? PCSS Shadows: Massive performance hit. Can be easily avoided... Depth Of Field: Massive performance hit especially at higher resolutions. Can be disabled or lower the res and see if it gets better... Or lower the Distant Blur setting. That lowers it's intensity. Medium is PC default with definition off. Normal Shadows: Can be easily set to high to avoid the performance hit... Not recommended to use with PCSS. Console Gamma: No performance hit Bloom: Barely any hit but it still scales with the resolution... Motion Blur: Can be easily avoided... It hits a bit. Z-Fighting Fix: This is everything. Impacts performance a bit depending on hardware, but essential. Additionally, use the [Console Light Models](https://gtaforums.com/topic/989098-console-visuals-the-complete-edition/) to help. These won't cast shadows and performance is massively improved. Make sure to delete FusionLights.img from FF if you want to use them.
> 
> Unless you use an ancient laptop with integrated graphics... nothing is guaranteed to work on these without performance issues.

yeah unfortunately I have a shitty GT 710 
that's why I'm only asking for that beautiful console gamma setting

**Comment by Mrsuss60** [comment]
> Can you give an example? PCSS Shadows: Massive performance hit. Can be easily avoided... Depth Of Field: Massive performance hit especially at higher resolutions. Can be disabled or lower the res and see if it gets better... Or lower the Distant Blur setting. That lowers it's intensity. Medium is PC default with definition off. Normal Shadows: Can be easily set to high to avoid the performance hit... Not recommended to use with PCSS. Console Gamma: No performance hit Bloom: Barely any hit but it still scales with the resolution... Motion Blur: Can be easily avoided... It hits a bit. Z-Fighting Fix: This is everything. Impacts performance a bit depending on hardware, but essential. Additionally, use the [Console Light Models](https://gtaforums.com/topic/989098-console-visuals-the-complete-edition/) to help. These won't cast shadows and performance is massively improved. Make sure to delete FusionLights.img from FF if you want to use them.
> 
> Unless you use an ancient laptop with integrated graphics... nothing is guaranteed to work on these without performance issues.

do you know how can I edit the gamma in the game files?

**Comment by RecklessGlue540** [comment]
ragepostfx.fxc
This shader also includes the Depth Of Field.
Editing shaders requires coding knowledge.
Try using these settings:

Video Mode: 1280x720
Texture Quality: Medium
Reflection Resolution: Medium
Water Quality: Medium
Shadow Quality: Medium
Night Shadows: Medium or Off
View Distance: 21
Detail Distance: 10
Vehicle Density: 33
FXAA: On
Console Shadows: On
VSync: Off
FPS Limiter: 30

Depth Of Field: On
Distant Blur: Medium
Bloom: On
Motion Blur: On
Console Gamma: On
Definition: Classic or Extra
TreeFX: Console or PC

Download Console Visuals and paste the Console Lights' update folder from it to GTAIV's main directory. (Only if you use Night Shadows. Not needed if not.)

**Comment by Mrsuss60** [comment]
> ragepostfx.fxc This shader also includes the Depth Of Field. Editing shaders requires coding knowledge. Try using these settings:
> 
> Video Mode: 1280x720 Texture Quality: Medium Reflection Resolution: Medium Water Quality: Medium Shadow Quality: Medium Night Shadows: Medium or Off View Distance: 21 Detail Distance: 10 Vehicle Density: 33 FXAA: On Console Shadows: On VSync: Off FPS Limiter: 30
> 
> Depth Of Field: On Distant Blur: Medium Bloom: On Motion Blur: On Console Gamma: On Definition: Classic or Extra TreeFX: Console or PC
> 
> Download Console Visuals and paste the Console Lights' update folder from it to GTAIV's main directory. (Only if you use Night Shadows. Not needed if not.)

i can't use 2.0 and above versions of fusionfix because it caused the "sign in to social club to save" error 
so i have an older version that has only console gamma and fxaa and definition fix etc 
.
this is what in the ini file : 
[MAIN]
SkipIntro = 1
SkipMenu = 0
BorderlessWindowed = 0
RecoilFix = 1
DefinitionFix = 1
EmissiveShaderFix = 1
AimingZoomFix = 1
[SHADOWS]
FlickeringShadowsFix = 0                   // known issue: disables player's shadow from headlights
ExtraDynamicShadows = 0                  // 1: restores some missing shadows  |  2: also adds vegetation shadows  |  3: forces all shadows to appear
DynamicShadowForTrees = 0
[FRAMELIMIT]
FpsLimitPreset = 3                         // used by main menu toggle, do not modify
FrameLimitType = 2                         // 1: realtime (thread-lock)  |  2: accurate (sleep-yield), uses less resources
FpsLimit = 0                               // used when FPS Limit menu toggle is set to ON
CutsceneFpsLimit = 60
ScriptCutsceneFovLimit = 20
[MISC]
FXAA = 0
ConsoleGamma = 0
DefaultCameraAngleInTLAD = 0
PedDeathAnimFixFromTBOGT = 1
DisableCameraCenteringInCover = 1
MouseFix = 1
ScreenFilter = 7                           // used by main menu toggle, do not modify
[BudgetedIV]
VehicleBudget = 144000000                      // may cause issues, set to e.g. 260000000 to increase budget limit
PedBudget = 0                              // may cause issues
.
i think the version is from 7/20/2023!

**Comment by RecklessGlue540** [comment]
> i can't use 2.0 and above versions of fusionfix because it caused the "sign in to social club to save" error

Never ends......

**Comment by Mrsuss60** [comment]
> > i can't use 2.0 and above versions of fusionfix because it caused the "sign in to social club to save" error
> 
> Never ends......

I'm in real suffering lol

**Comment by MagicAl6244225** [comment]
If you're not going to use FusionFix you can implement your own gamma adjustment with a utility like Gamma Control at https://desktopnerds.com/gamma-control-4/ and with a test pattern like found here https://www.ephotozine.com/article/gamma-value-monitor-check-23405 to adjust your display to a target gamma of 2.6 or whatever you like. I picked 2.6 because it's standard for digital cinema vs. the 2.2 PC standard. Gamma Control can switch between two settings with hotkeys you define in that app.

**Comment by Mrsuss60** [comment]
> If you're not going to use FusionFix you can implement your own gamma adjustment with a utility like Gamma Control at https://desktopnerds.com/gamma-control-4/ and with a test pattern like found here https://www.ephotozine.com/article/gamma-value-monitor-check-23405 to adjust your display to a target gamma of 2.6 or whatever you like. I picked 2.6 because it's standard for digital cinema vs. the 2.2 PC standard. Gamma Control can switch between two settings with hotkeys you define in that app.

sorry for not replying early
Thanks a lot, man!! 
I will try this and see if it works
