### ISSUE TITLE
Feature request: Fix radio song playing order after loading

### ISSUE THREAD

**Issue by Panzermann11** [ThirteenAG/GTAIV.EFLC.FusionFix#306]
An issue I remember being reported outside of FusionFix is that the game seems to prioritise EFLC music when loading a saved game, meaning it'll always play EFLC songs first, then IV tracks after, most notably in stations like Vladivostok FM. On top of that, the radio stations appear to reset upon starting a mission. This is more noticeable on looping stations, such as Electro-Choc and The Classics.

Can it be made so that the game will play IV songs first when loading on an IV save, and EFLC songs on EFLC saves, and stations don't reset upon starting a mission? Alternatively, maybe randomise between IV and EFLC tracks when loading a save?

**Comment by RecklessGlue540** [comment]
Sounds like hell to fix. But nice one.

**Comment by Imflyin2023** [comment]
> An issue I remember being reported outside of FusionFix is that the game seems to prioritize EFLC music when loading a game, meaning it'll always play EFLC songs first, then IV tracks after, most notably in stations like Vladivostok FM. On top of that, the radio stations appear to reset upon starting a mission. This is more noticeable on looping stations, such as Electro-Choc and The Classics.
> 
> Can it be made so that the game will play IV songs first when loading on an IV save, and EFLC songs on EFLC saves, and stations don't reset upon starting a mission? Alternatively, maybe randomize between IV and EFLC tracks when loading a save?


What does this have to do with Fusion Fx? and the game accidentally includes songs from IV or EFLC, and there is a mod with which you can make sure that songs from EFLC are not played in IV and vice versa

**Comment by Panzermann11** [comment]
> > An issue I remember being reported outside of FusionFix is that the game seems to prioritize EFLC music when loading a game, meaning it'll always play EFLC songs first, then IV tracks after, most notably in stations like Vladivostok FM. On top of that, the radio stations appear to reset upon starting a mission. This is more noticeable on looping stations, such as Electro-Choc and The Classics.
> 
> > Can it be made so that the game will play IV songs first when loading on an IV save, and EFLC songs on EFLC saves, and stations don't reset upon starting a mission? Alternatively, maybe randomize between IV and EFLC tracks when loading a save?
> 
> What does this have to do with Fusion Fx? and the game randomly plays songs from IV or EFLC, and there is a mod that separates songs from IV and EFLC.
> 
> I think there is no point in this issue.

What I mean is that when you load a save, the game will always play the EFLC-exclusive songs first. And I found the issue I was referring to: https://github.com/GTAmodding/GTAIV-Issues-List/issues/62
I'm specifically asking if a fix for this can be implemented through FusionFix.

**Comment by Imflyin2023** [comment]
> > > An issue I remember being reported outside of FusionFix is that the game seems to prioritize EFLC music when loading a game, meaning it'll always play EFLC songs first, then IV tracks after, most notably in stations like Vladivostok FM. On top of that, the radio stations appear to reset upon starting a mission. This is more noticeable on looping stations, such as Electro-Choc and The Classics.
> > 
> > 
> > > Can it be made so that the game will play IV songs first when loading on an IV save, and EFLC songs on EFLC saves, and stations don't reset upon starting a mission? Alternatively, maybe randomize between IV and EFLC tracks when loading a save?
> > 
> > 
> > What does this have to do with Fusion Fx? and the game randomly plays songs from IV or EFLC, and there is a mod that separates songs from IV and EFLC.
> > I think there is no point in this issue.
> 
> What I mean is that when you load a save, the game will always play the EFLC-exclusive songs first. This is the issue I was referring to: [GTAmodding/GTAIV-Issues-List#62](https://github.com/GTAmodding/GTAIV-Issues-List/issues/62)
> 
> I'm specifically asking if a fix for this can be implemented through FusionFix.

This is not happening for me, I just tried to start a new game and Vladivostok FM, San Juan Sounds, Electro-Choc and The Beat 102.7 are playing songs from IV, although L.C.H.C is playing a mix from EFLC

**Comment by Panzermann11** [comment]
> This is not happening for me, I just tried to start a new game and Vladivostok FM, San Juan Sounds, Electro-Choc and The Beat 102.7 are playing songs from IV, although L.C.H.C is playing a mix from EFLC
You didn't clearly hear what I was saying, don't you? I said: **when you load a saved game, the game plays the EFLC songs first, then it plays IV songs on the radio.**

**Comment by Panzermann11** [comment]
> This is not happening for me, I just tried to start a new game and Vladivostok FM, San Juan Sounds, Electro-Choc and The Beat 102.7 are playing songs from IV, although L.C.H.C is playing a mix from EFLC

You didn't clearly hear what I was saying, don't you? I said: when you load a save game, the game plays EFLC songs on the radio first, then it plays IV songs.

**Comment by Imflyin2023** [comment]
> > This is not happening for me, I just tried to start a new game and Vladivostok FM, San Juan Sounds, Electro-Choc and The Beat 102.7 are playing songs from IV, although L.C.H.C is playing a mix from EFLC
> 
> That issue didn't mention that this only occurs on a saved game. Oh, and sorry. Accidentally hit the close issue button.

Have you forgotten that when you save, it rewinds the radio stations for about 10-15 minutes? I'm telling you, it's not a problem of the game.

**Comment by Panzermann11** [comment]
> Have you forgotten that when you save, it rewinds the radio stations for about 10-15 minutes? I'm telling you, it's not a problem of the game.

Urgh. What I meant is, this only happens when you load a saved game.

**Comment by Imflyin2023** [comment]
> > Have you forgotten that when you save, it rewinds the radio stations for about 10-15 minutes? I'm telling you, it's not a problem of the game.
> 
> You don't understand what I said earlier, don't you? I said this happens when you **load a saved game**.

I understood everything perfectly, you don't understand

**Comment by Panzermann11** [comment]
> I understood everything perfectly, you don't understand, and leave me alone

Ugh... If that's what you want, then fine. I tried my best to explain as specifically as I could. It's no use discussing with you if you keep on being like this.

**Comment by Imflyin2023** [comment]
> > I understood everything perfectly, you don't understand, and leave me alone
> 
> Ugh... If that's what you want, then fine. I tried my best to explain as specifically as I could. It's no use discussing with you if you keep on being like this.

What should I understand? I know perfectly well what is written in the description of the post, and I have told you many reasons why this is happening.

**Comment by Panzermann11** [comment]
> What should I understand? I know perfectly well what is written in the description of the post, and I have told you many reasons why this is happening.

Sigh... Perhaps I should've elaborated more on the post. I meant **saved games**, not **new games**.

**Comment by Panzermann11** [comment]
> What should I understand? I know perfectly well what is written in the description of the post, and I have told you many reasons why this is happening.

Conversation's over. Can we please move on before things start to get worse now?
