### ISSUE TITLE
Run time error when click on any email in game

### ISSUE THREAD

**Issue by NevnT** [ThirteenAG/GTAIV.EFLC.FusionFix#309]
![ryte](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/153543029/bbf211b6-8749-4493-969b-279613399b87)

After installing FusionFix, I can't open any email in-game, this run time error always pops up, and the game crashes.
If I removed FusionFix, everything works again.

Tired:
reinstall all the VC++ runtime redistributable from Microsoft
reinstall the game

**Comment by ThirteenAG** [comment]
Crash dump?

**Comment by NevnT** [comment]
[
[CrashDumps.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13650420/CrashDumps.zip)
](url)
Here's the file, thank you, sir.

**Comment by ThirteenAG** [comment]
> [CrashDumps.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13650420/CrashDumps.zip)
> 
> Here's the file, thank you, sir.

Install latest https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/latest
Next version will include that by default.

**Comment by NevnT** [comment]
Everything runs smoothly! Thank you again!

**Comment by NevnT** [comment]
update
Seems like Windows sees the 6.7 version of ASI Loader file as "Trojan:Win32/Wacatac.B!ml" and deletes it automatically.

**Comment by ThirteenAG** [comment]
You can report false positive via Microsoft website, they usually respond quickly.
