### ISSUE TITLE
Feature Request: Use json as opposed to ini

### ISSUE THREAD

**Issue by alextwothousand** [ThirteenAG/GTAIV.EFLC.FusionFix#31]
INI is sort of a dying standard, and switching to JSON or TOML would be much preferable.

I would be more than happy to make a PR if all contributors are for the idea.

**Comment by ermaccer** [comment]
What would be the benefit of using JSON? INI is a simple format to both read and write, it is also easier to edit manually.

**Comment by alextwothousand** [comment]
As JSON is more widespread, it has become a standard for most program’s configuration.

**Comment by thethiny** [comment]
INI is simpler to write, simpler to understand, simpler to read, and you can do it in Notepad. JSON is for Object Serialization for programs to read and understand objects. There are barely objects in ASIs created by modders 'round the world, so it would kill a user-friendly aspect of ASILoader. Besides, INI is the standard on Windows, so I see 0 benefit to switching over to a complex-to-users format. Imagine asking a user to add a new boolean, and watching them mess up their commas and brackets. Would be funny to spend hours a day telling people about "fixing the _bug_".

**Comment by alextwothousand** [comment]
What about TOML? Or at least allow us to add a preprocessor directive to embed either INI or TOML?

**Comment by hazelnot** [comment]
I literally don't see the point of this, pretty much all Windows and a ton of Linux apps use ini files for configuration, and I've only see JSON used for network-related stuff. Literally what would the benefit of switching config file formats be?

**Comment by thethiny** [comment]
JSON/YAML is only used for network-related stuff and machine learning, and that's probably it I guess. INI is a standard "Configuration" file.
While JSON might be good for you, you can refer to [this article](https://www.lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language/) to see why it's not user friendly.

**Comment by alextwothousand** [comment]
I know why it’s not user friendly. People don’t understand curly braces.

OK, that’s fine.
