### ISSUE TITLE
[ISSUE] Crash while browsing the web, occurred on LCPD page.

### ISSUE THREAD

**Issue by HAYASHIDASEIYAKU** [ThirteenAG/GTAIV.EFLC.FusionFix#310]
[CrashDumps.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13644678/CrashDumps.zip)
some time, a crash in the double-arm climbing motion occurs.

**Comment by HAYASHIDASEIYAKU** [comment]
[plugins.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13644737/plugins.zip)

**Comment by ThirteenAG** [comment]
Is there a way to contact you on discord?

**Comment by ThirteenAG** [comment]
[dinput8.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13645102/dinput8.zip)
Also try this version of asi loader, does it make any difference?

**Comment by HAYASHIDASEIYAKU** [comment]
> Is there a way to contact you on discord?

hayashida5170
