### ISSUE TITLE
"update" folder prevents the game from saving

### ISSUE THREAD

**Issue by Sh0ckV** [ThirteenAG/GTAIV.EFLC.FusionFix#312]
everytime I boot up the game or try to save, it asks me to sign in to social club. the cause for it is the update folder.

**Comment by Sh0ckV** [comment]
just the folder btw
even if i delete everything inside the folder i still get the error. please help cuz i really wanna try the new version of the mod :D

**Comment by ThirteenAG** [comment]
Buy the game on steam or RGL then.

**Comment by Sh0ckV** [comment]
ouch

**Comment by bardan1** [comment]
so no fix damn

**Comment by Sh0ckV** [comment]
if you have the legit version try disabling skipmenu and intro. i have the pirated version so yeah i'll never get it to work.

**Comment by SaucySauce** [comment]
> if you have the legit version try disabling skipmenu and intro. i have the pirated version so yeah i'll never get it to work.

I think in another issue the user commented using an older release won't do the pirated verification.

**Comment by Sh0ckV** [comment]
yeah the pre 2.0 versions work just fine but the new features are too cool to miss
