### ISSUE TITLE
Cutscene overlays get cropped in ultrawide

### ISSUE THREAD

**Issue by ReneSchimmelpfennig** [ThirteenAG/GTAIV.EFLC.FusionFix#315]
In ultrawide, the camera overlay in the cutscene of the mission Escuela of the Streets (and all other cutscenes that feature such overlays) is cropped and the text on the sides is lost. Also, the black bars in cutscenes should probably be optional.

**Comment by RecklessGlue540** [comment]
The next version will feature Pillarbox and Letterbox options in the menu, so you can disable these.
You are right about the camera overlays. Let's wait for an ultrawide adaptation for these textures.
