### ISSUE TITLE
[ISSUE] Rain splash shader on surfaces only works sometimes and it rains indoors

### ISSUE THREAD

**Issue by stinkysavid** [ThirteenAG/GTAIV.EFLC.FusionFix#320]
The rain splashing shader for me only works when I'm going into the pause menu, in the actual game it vanishes. There are rare occasions where it shows up briefly. And by briefly I mean never longer than a few seconds before stopping again. It is very strange and I have not found any solution, even freshly installing GTA IV and only installing FusionFix doesn't work. I am running the latest CE build through Steam. Additionally, it rains inside of buildings.

![20231216175002_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/139765167/05b2752b-ea1f-4d3c-9f10-4e74c7c82586)
![20231216175023_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/139765167/b5fdb229-65bf-4029-93e3-f2495a9eb6f3)

**Comment by RecklessGlue540** [comment]
You're using ScriptHook, that's why. It screws up the rain collision detection.

> even freshly installing GTA IV and only installing FusionFix doesn't work.

Let me guess. Your game crashes when you try and boot up the game when using FF.

You seem to have a fairly modded game otherwise...

**Comment by stinkysavid** [comment]
I use ScriptHook for TrafficLoad but I am being genuine and honest when I say that I tried it on a clean and fresh install. I just didn't have a screenshot of a clean install handy because I have been playing through the story with a vehicle mod and if you remove them partway through the story it causes severe compatibility issues with your save file. And no, my game never crashes lol. I'm not new to modding and I know how to set the game's mods up. I will try without ScriptHook on a new save and see if it works. Probably won't be for another day or two when I finish the main story and want to move onto the DLCs but I will update you when the time comes. Or I'll just get Traffic Control System instead of TrafficLoad since the former doesn't require ScriptHook and is a DLL. In fact, I'll do both for the sake of troubleshooting.

**Comment by RecklessGlue540** [comment]
Well, traffic loaders are not a good way of combatting the taxi bug at all. 
Use FusionFix's budget limit adjuster.
Change the vehicle budget to 120000000 and you're done. No need for traffic loaders.

**Comment by stinkysavid** [comment]
Not only did that work but not having an extra DLL loading fixed a huge number of LOD issues I was having too. Thanks a million. I'm gonna leave this post up in case other people make the same mistakes if that's ok by you

**Comment by RecklessGlue540** [comment]
In any case, if those "lod" issues arise again, try lowering that budget slightly.

About leaving this open, I'd say it's down more to the Fusion Team. They decide.
But since the issue is not at all related to original game bugs or FusionFix introduced ones, I'd say leave it closed.
It's well known Scripthook causes this bug.
It's been there since it's beginning back in 2009...
