### ISSUE TITLE
[Feature Request] Z-fighting fix as an optional feature

### ISSUE THREAD

**Issue by SandeMC** [ThirteenAG/GTAIV.EFLC.FusionFix#321]
I don't know to which scale is z-fighting fix integrated into the shader code, but I personally think it should be optional for the sole reason of it's performance impact (or, at least Parallellines said it was pretty demanding if I recall right). I know the solution is generally to just not play on ancient GPU's, but if it's possible to make it optional, why not do it for the few that want the extra framerate and don't care that much about the z-fighting.

**Comment by SandeMC** [comment]
Also, offtopic, but y'all really need somebody to manage the issues (assigning tags and closing complete/unsolvable issues actively)

**Comment by Tomasak** [comment]
i tested on old ass ATI (not even AMD) radeon GPU, the FPS loss was there, but not anything marginal. So no

**Comment by SandeMC** [comment]
After some testing, yeah, that seems to be the case. Disabling every other option actually ends up giving even better performance than 1.96. Sorry, then.
