### ISSUE TITLE
[1.0.7.0] TLAD Noise Effect hardly noticeable

### ISSUE THREAD

**Issue by purplebar0** [ThirteenAG/GTAIV.EFLC.FusionFix#322]
According to [PCGW](https://www.pcgamingwiki.com/wiki/Grand_Theft_Auto_IV#Film_grain_noise_texture_size_depends_on_water_quality_setting), FusionFix fixes the issue of water quality changing the Noise Effect resolution. However, from testing, it was still quite high, making the noise hard to spot.

Please close this issue in case this is a misunderstanding, given that readme lists "restoring console noise effect".

**Comment by SandeMC** [comment]
You may have misunderstood something. The noise scaling on PC originally was affected by the resolution (iirc). The effect was restored to be normal, but it was affected by the Water Quality setting - that's fixed too. In the end you have what should be more or less, the intended noise effect.

**Comment by purplebar0** [comment]
> You may have misunderstood something. The noise scaling on PC originally was affected by the resolution (iirc). The effect was restored to be normal, but it was affected by the Water Quality setting - that's fixed too. In the end you have what should be more or less, the intended noise effect.
> 
> Could you send the Xbox 360 noise for comparison?

Given your explanation, I am fairly certain that I misunderstood the resolution fix. I may have remembered the days I was playing the game without mods on modest graphical settings.

As for whether it corresponds to console visuals, I don't know as I never played the game on X360/PS3. My point was that I assumed the effect was supposed to be more noticeable according to the PCGW article, and wasn't sure if the fix mentioned on PCGW corresponded to the one in the list.

**Comment by SandeMC** [comment]
The issue on PCGW is of an unfixed issue - the fixed result is what you should see in the actual game. If you don't have any complaints, feel free to close the issue.

**Comment by RecklessGlue540** [comment]
That seems like shitposting imo.
Out of all the issues that could end up there, someone chose to add the "noise effect being affected by water quality" issue...
On the vanilla game it's affected by both resolution and water quality settings. It doesn't make much sense to add just one...
FusionFix fixes both = It works as intended.
If someone knows how to edit PCGW pages, please, delete that issue. It just adds more useless confusion.

**Comment by SandeMC** [comment]
It's not shitposting and it should be there according to PCGW editing rules. Adding it there was decided by a senior editor and he's fully compliant to the editing rules. Any big vanilla issue *must* be mentioned on the page. FusionFix fixing it doesn't mean that it shouldn't be mentioned - it's just a solution to the issue, but the issue itself should still be mentioned.

PCGW is not a modding guide.

**Comment by purplebar0** [comment]
Given that there's nothing to change here as far as I can tell, I am closing the issue.
