### ISSUE TITLE
[1.0.7.0] TLAD additional menu options not present

### ISSUE THREAD

**Issue by purplebar0** [ThirteenAG/GTAIV.EFLC.FusionFix#323]
Given that TLAD has slightly different menu options than other games (notably, Noise Effect), it seems like FusionFix isn't replacing them in this episode to include its additional options, either due to differing file paths or a lack of edit.

Given that I have a slightly exotic setup (loose files in `update` are symbolic links, IMGs are not, but everything appears to work from testing), I suspect it may have to do with my specific setup, so I'd appreciate if someone checked if they had the same issue.

**Comment by SandeMC** [comment]
On 1.0.8.0, the option exists and works. Probably to do with your symbolic link setup, try to make the common/data folder not a symbolic link.
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/70141395/a3d4f44e-41ae-49f9-b0c3-930be0935f12)

**Comment by Tomasak** [comment]
Latest FF installed on latest game version, noise effect is present. Must be an issue with your installation
