### ISSUE TITLE
[Bug] Timecycle modifiers scramble randomly when near interiors

### ISSUE THREAD

**Issue by RecklessGlue540** [ThirteenAG/GTAIV.EFLC.FusionFix#325]
For some reason, being **near** any kind of interior, will bug out the timecyle modifying. 
And for some other strange reason, this only happens in DirectX9. It does not happen as prominently (or at all?) with DXVK. 
This issue was introduced back when FF 2.0 was released.

D3D9:

https://streamable.com/23dzy8
https://streamable.com/74g09a

DXVK:

https://streamable.com/whpjyq
https://streamable.com/wztp79

Mods I use are not changing anything related. Tested it before, vanilla. (I don't know if Project 2DFX may cause anything...) 
This was the first issue I experienced with FF 2.0 (FF only back then) as it also happens in the intro cutscene when the cook looks at the ice.

**Comment by Parallellines0451** [comment]
Can you provide any more info? Do you have SkipIntro or SkipMenu enabled? We still aren't able to reproduce this and have seen at least one more case of it aside from yours.

**Comment by RecklessGlue540** [comment]
No, I don't use those. It also started to happen with DXVK in some areas and have no idea how it's triggered.

**Comment by hammerfist11** [comment]
out of curiosity, does this still happen with latest versions?

**Comment by RecklessGlue540** [comment]
> out of curiosity, does this still happen with latest versions?

Yes, it does.

**Comment by hammerfist11** [comment]
> > out of curiosity, does this still happen with latest versions?
> 
> Yes, it does. Forget about the API difference though. It's just... it's very random. Do you have this issue btw?

nah im just curious since it's quite major and i couldn't reproduce, do you have an nvidia or amd gpu?

**Comment by RecklessGlue540** [comment]
> > > out of curiosity, does this still happen with latest versions?
> > 
> > 
> > Yes, it does. Forget about the API difference though. It's just... it's very random. Do you have this issue btw?
> 
> nah im just curious since it's quite major and i couldn't reproduce, do you have an nvidia or amd gpu?

happens on both Nvidia and AMD for me...

**Comment by hammerfist11** [comment]
Might have something to do with the game version being used, external software from your side or something of that sort. 

Since if it happens on both AMD and Nvidia cards it's a software issue that's unrelated to the specs of the machine being used. So in theory, reproducing it should be entirely possible yet I, and others, cannot reproduce it.

**Comment by RecklessGlue540** [comment]
> Might have something to do with the game version being used, external software from your side or something of that sort. 
> 
> Since if it happens on both AMD and Nvidia cards it's a software issue that's unrelated to the specs of the machine being used. So in theory, reproducing it should be entirely possible yet I, and others, cannot reproduce it.
> 
> Is this issue constantly present, or only happens rarely?

It can happen out of the blue... Tho pretty often.

**Comment by hammerfist11** [comment]
does this happen with default timecycle as well, or only the modified ones?

**Comment by hammerfist11** [comment]
> Actually seems to happen even vanilla... weird

wouldn't be surprised if RGL has something to do with this then. I own the game yet i prefer to use _unofficial_ methods to run the game.

**Comment by Daxy7** [comment]
Because timecycmodifiers 1-3 use presets in interiors, so the gradients remain the same. Here's a test mod that fixes all the interiors, made in 2021, via editing "Skyline Timecyc 1.3" on YouTube. Test by going into a Burger Shot or hospital. There's a stark difference.

[timecyc-interiors-fix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14814459/timecyc-interiors-fix.zip)

**Comment by RecklessGlue540** [comment]
> Because timecycmodifiers 1-3 use presets in interiors, so the gradients remain the same. Here's a test mod that fixes all the interiors, made in 2021, via editing "Skyline Timecyc 1.3" on YouTube. Test by going into a Burger Shot or hospital. There's a stark difference.
> 
> [timecyc-interiors-fix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14814459/timecyc-interiors-fix.zip)

Can you tell exactly which parameter is supposed to fix it?

**Comment by Daxy7** [comment]
In general, i used this one pattern for mostly all except lightning cause i don't know how the arbitrary values work, unlike maker of `Skyline Timecyc.` Shadows and natural light source casts are added, but affecting the main interior apperance, so it's jarring in that way, I agree. I couldn't even get FusionFix to work, some conflict, so i searched every issue and found this, just to help out y'all.
```
testname          -1.0       -1.0         -1.0         -1.0      255 255 255   0   1.0  255 255 255   0   1.0  255   0   0   0   0.0       1.00       0   0   0   0    0   0   0   0    1.0       0   -100.0      -1.0         -3.2         1.9               0.5              -1.0            2.4        128 128 128  255 255 255       0.0       -1.0      1.2        0.2            -1.0        -1.0       -1.0         -1.0      -1.0    -1.0       -1.0          -1.0        -1.0       -1.0        0.0        0.0         0.0          -1.0        -1.0         -1.0            -1.0           -1.0            -1.0        -1.0       -1.0              0               
```
Make of that what you will.
