### ISSUE TITLE
[Feature Request] Vehicle specific motion blur

### ISSUE THREAD

**Issue by Spueh** [ThirteenAG/GTAIV.EFLC.FusionFix#326]
I'm not sure if this is a big ask or not, but would it be possible to add another toggle for motion blur in the settings that only enables it while driving at high speeds in a vehicle? I really like that effect but I'm not a fan of motion blur normally. I appreciate this mod a lot, must have for GTA 4!

**Comment by RecklessGlue540** [comment]
I'd think a Motion Blur Strength toggle like in GTA V would be much better...
