### ISSUE TITLE
[Question] What does the DirectInput toggle actually do?

### ISSUE THREAD

**Issue by juicermv** [ThirteenAG/GTAIV.EFLC.FusionFix#327]
There's a DirectInput toggle in the controller settings of the game. But what does it actually do? Afaik both the Dualshock 4 and Dualsense use DirectInput instead of XInput but if I try to use them with the toggle on and SteamInput off they just straight up don't work. Should this toggle perhaps be removed? Or fixed?

**Comment by RecklessGlue540** [comment]
Xinput is for Xbox controllers exclusively.
DirectInput is afaik for every other controller.
Dualshock 3-4 and Dual sense controllers need additional drivers afaik.

**Comment by SandeMC** [comment]
I can confirm that it's broken when trying to use my Dualshock 3 (with any option in DsHidMini). Was thinking it's aa problem with the dualshock 3, but seems to occur with dualshock 4 too

**Comment by RecklessGlue540** [comment]
> I can confirm that it's broken when trying to use my Dualshock 3 (with any option in DsHidMini). Was thinking it's aa problem with the dualshock 3, but seems to occur with dualshock 4 too

Does it work fine vanilla?

**Comment by RecklessGlue540** [comment]
> This is a vanilla option, and no I'm pretty sure it still didn't work in vanilla

I know it was there...
But damn if it's vanilla. Toronto were on crack alright when they ported this. 😞
