### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by yxngicyx** [ThirteenAG/GTAIV.EFLC.FusionFix#328]
on a fresh install [from steam], no downgrades, no other mods, after having extracted all files/folders from the archive to gta iv's root, when launching, the screen just goes black and i can't even close it until i restart my pc.

**Comment by Zorklis** [comment]
Your pc specs?

**Comment by yxngicyx** [comment]
> Your pc specs?

ryzen 7 7700
rog strix b650e-i
32gb 6000mhz cl36
rx 7900 xt 20gb
2tb pcie 4.0
1000watts corsair sf1000L
nzxt z63

**Comment by ThirteenAG** [comment]
Open task manager when the game is "stuck", select process, and click Create memory dump file. Upload it somewhere and post here. The file will be quite large.

**Comment by Tomasak** [comment]
2.3.1 was released to fix crashing on startup for some people. please try and report if its fixed, or upload crashdump if issue persists.
