### ISSUE TITLE
Game freezes and crashes randomly with FusionFix installed

### ISSUE THREAD

**Issue by googleooer** [ThirteenAG/GTAIV.EFLC.FusionFix#329]
I already tried updating to the latest FusionFix version, but it just doesn't work.

I have to drive with a black guy in a car, and when I get to the bridge that takes you to another island it just freezes and crashes. It's not very consistent, sometimes it crashes as soon as I pass the toll booth, sometimes it crashes like 10-20 seconds after that

**Comment by googleooer** [comment]
I just tried reinstalling the game completely and installing the latest version of fusionfix afterwards and it still didn't work

**Comment by googleooer** [comment]
Doesn't crash in vanilla. I don't think it's related to alternate voicelines like the other issues, it has to do with loading the island maybe?

**Comment by SandeMC** [comment]
Can't replicate (if it's actually Blow Your Cover). Might be related to https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/pull/301?

**Comment by googleooer** [comment]
I reinstalled the game entirely, did the mission and then reinstalled the mod. It worked fine for a while, but it crashed randomly in a street near the in-game equivalent of Times Square. Is there some sort of log file I can send or view to find out what's going on?

**Comment by ThirteenAG** [comment]
Create CrashDumps folder in root, reproduce and upload content.

**Comment by googleooer** [comment]
I made one and nothing appeared when the game crashed

**Comment by googleooer** [comment]
I did the following and the game hasn't crashed so far (30 minutes into this session so far)

1. Set my secondary monitor as my main monitor
2. Launched the game. It opened on my secondary monitor since it's set as my main monitor now

Maybe the issue was related to moving the windowed game to another monitor via Win+Shift+Arrow?

**Comment by ThirteenAG** [comment]
> I made it (one in the Grand Theft Auto IV folder and one in the GTAIV folder because I didn't know which folder you were referring to as the root folder) and nothing appeared when the game crashed

Root folder is where exe and asi loader are. There's no way it doesn't generate a crash dump after the crash, can't help without one anyway.

**Comment by yxngicyx** [comment]
the game does not even launch for me, had used 2.0, 2.2 & 2.3, all of them just results in the game not launching [im on steam, no downgrades and fresh install btw]. only 1.96 works for me, the few times the 2.0+ versions worked for me was when i reinstalled, but i would still get the same issue of it not launching after restarting my computer...

**Comment by googleooer** [comment]
> Root folder is where exe and asi loader are. There's no way it doesn't generate a crash dump after the crash, can't help without one anyway.

it didn't crash, it just froze forever

**Comment by yxngicyx** [comment]
> > Root folder is where exe and asi loader are. There's no way it doesn't generate a crash dump after the crash, can't help without one anyway.
> 
> it didn't crash, it just froze forever and I had to manually end it via the task manager, it didn't generate anything

same thing happening to me, on windows 11, maybe there's an issue with windows 11?

**Comment by googleooer** [comment]
> same thing happening to me, on windows 11, maybe there's an issue with windows 11?
Are you running the game on a secondary monitor or at an uncommon resolution (e.g 1600 x 1200)?

Here's what my setup was when it was constantly crashing:

- iPad Pro as my main monitor (1600x1200), regular display as my secondary monitor (1440x900).
- When launching GTA IV, I would move the window to my secondary monitor with Win+Shift+Arrow
- After playing for a while, it would crash

To fix it, I just set the monitor I wanted to play the game in as my main monitor so the game launched there, and I set the game's resolution to said monitor's resolution.

**Comment by yxngicyx** [comment]
> > same thing happening to me, on windows 11, maybe there's an issue with windows 11?
> 
> Are you running the game on a secondary monitor or at an uncommon resolution (e.g 1600 x 1200)? Here's what my setup was when it was constantly crashing:
> 
> * iPad Pro as my main monitor (1600x1200), regular display as my secondary monitor (1440x900).
> * When launching GTA IV, I would move the window to my secondary monitor with Win+Shift+Arrow
> * After playing for a while, it would crash
> 
> To fix it, I just set the monitor I wanted to play the game in as my main monitor so the game launched there, and I set the game's resolution to said monitor's resolution.

nope, playing on a single 1440p 32 inch 165hz freesync monitor, resolution settings in-game is native... idk what to do anymore to get this working

**Comment by ThirteenAG** [comment]
Are you sure the same does not happen with a clean game?

**Comment by yxngicyx** [comment]
> Are you sure the same does not happen with a clean game?

yes doesn't happen with clean game

**Comment by ThirteenAG** [comment]
Open task manager when the game is "stuck", select process, and click Create memory dump file. Upload it somewhere and post here. The file will be quite large.

**Comment by yxngicyx** [comment]
> Open task manager when the game is "stuck", select process, and click Create memory dump file. Upload it somewhere and post here. The file will be quite large.

https://drive.google.com/file/d/1Ztbxso2EghZGhB_yYb2j57eYqbGvfWkN/view?usp=sharing

**Comment by ThirteenAG** [comment]
> > Open task manager when the game is "stuck", select process, and click Create memory dump file. Upload it somewhere and post here. The file will be quite large.
> 
> https://drive.google.com/file/d/1Ztbxso2EghZGhB_yYb2j57eYqbGvfWkN/view?usp=sharing

```
>	ntdll.dll!_NtWaitForMultipleObjects@20()	Unknown	Non-user code. Symbols loaded without source information.
 	KERNELBASE.dll!_WaitForMultipleObjectsEx@20()	Unknown	Non-user code. Symbols loaded without source information.
 	KERNELBASE.dll!_WaitForMultipleObjects@16()	Unknown	Non-user code. Symbols loaded without source information.
 	d3d9.dll!ThreadAffinitizedWorkerThread<enum ProxyWindowCommands>::PostCommand()	Unknown	Non-user code. Symbols loaded without source information.
 	d3d9.dll!ProxyWindow::CreateProxyWindow(struct HWND__ *,struct tagRECT const &,enum ProxyWindowBehavior)	Unknown	Non-user code. Symbols loaded without source information.
 	d3d9.dll!CSwapChain::InitBindResources(bool,struct _SECURITY_DESCRIPTOR *)	Unknown	Non-user code. Symbols loaded without source information.
 	d3d9.dll!CSwapChain::CreateWindowed(unsigned int,unsigned int,enum _D3DFORMAT,unsigned int,enum _D3DMULTISAMPLE_TYPE,unsigned long,int,int,int,int,int,int)	Unknown	Non-user code. Symbols loaded without source information.
 	d3d9.dll!CSwapChain::Reset(struct _D3DPRESENT_PARAMETERS_ *,struct D3DDISPLAYMODEEX const *,int,int)	Unknown	Non-user code. Symbols loaded without source information.
 	d3d9.dll!CSwapChain::Init(struct _D3DPRESENT_PARAMETERS_ *,struct D3DDISPLAYMODEEX const *,long *,int,int)	Unknown	Non-user code. Symbols loaded without source information.
 	d3d9.dll!CBaseDevice::Init()	Unknown	Non-user code. Symbols loaded without source information.
 	d3d9.dll!CEnum::CreateDeviceImpl(unsigned int,enum _D3DDEVTYPE,struct HWND__ *,unsigned long,struct _D3DPRESENT_PARAMETERS_ *,struct D3DDISPLAYMODEEX const *,struct IDirect3DDevice9Ex * *,struct _D3D9ON12_ARGS *)	Unknown	Non-user code. Symbols loaded without source information.
 	d3d9.dll!CEnum::CreateDevice()	Unknown	Non-user code. Symbols loaded without source information.
 	NahimicOSD.dll!77ef7e27()	Unknown	Non-user code. Cannot find or open the PDB file.
 	[Frames below may be incorrect and/or missing, no symbols loaded for NahimicOSD.dll]		Annotated Frame
 	gameoverlayrenderer.dll!7a9dbfc8()	Unknown	Non-user code. Cannot find or open the PDB file.
 	GTAIV.EFLC.FusionFix.asi!7bd393f4()	Unknown	Non-user code. Cannot find or open the PDB file.
```

First of all, can you try without NahimicOSD.dll, whatever this is?
If it works without, then we can look further.

**Comment by yxngicyx** [comment]
> > > Open task manager when the game is "stuck", select process, and click Create memory dump file. Upload it somewhere and post here. The file will be quite large.
> > 
> > 
> > https://drive.google.com/file/d/1Ztbxso2EghZGhB_yYb2j57eYqbGvfWkN/view?usp=sharing
> 
> ```
> >	ntdll.dll!_NtWaitForMultipleObjects@20()	Unknown	Non-user code. Symbols loaded without source information.
>  	KERNELBASE.dll!_WaitForMultipleObjectsEx@20()	Unknown	Non-user code. Symbols loaded without source information.
>  	KERNELBASE.dll!_WaitForMultipleObjects@16()	Unknown	Non-user code. Symbols loaded without source information.
>  	d3d9.dll!ThreadAffinitizedWorkerThread<enum ProxyWindowCommands>::PostCommand()	Unknown	Non-user code. Symbols loaded without source information.
>  	d3d9.dll!ProxyWindow::CreateProxyWindow(struct HWND__ *,struct tagRECT const &,enum ProxyWindowBehavior)	Unknown	Non-user code. Symbols loaded without source information.
>  	d3d9.dll!CSwapChain::InitBindResources(bool,struct _SECURITY_DESCRIPTOR *)	Unknown	Non-user code. Symbols loaded without source information.
>  	d3d9.dll!CSwapChain::CreateWindowed(unsigned int,unsigned int,enum _D3DFORMAT,unsigned int,enum _D3DMULTISAMPLE_TYPE,unsigned long,int,int,int,int,int,int)	Unknown	Non-user code. Symbols loaded without source information.
>  	d3d9.dll!CSwapChain::Reset(struct _D3DPRESENT_PARAMETERS_ *,struct D3DDISPLAYMODEEX const *,int,int)	Unknown	Non-user code. Symbols loaded without source information.
>  	d3d9.dll!CSwapChain::Init(struct _D3DPRESENT_PARAMETERS_ *,struct D3DDISPLAYMODEEX const *,long *,int,int)	Unknown	Non-user code. Symbols loaded without source information.
>  	d3d9.dll!CBaseDevice::Init()	Unknown	Non-user code. Symbols loaded without source information.
>  	d3d9.dll!CEnum::CreateDeviceImpl(unsigned int,enum _D3DDEVTYPE,struct HWND__ *,unsigned long,struct _D3DPRESENT_PARAMETERS_ *,struct D3DDISPLAYMODEEX const *,struct IDirect3DDevice9Ex * *,struct _D3D9ON12_ARGS *)	Unknown	Non-user code. Symbols loaded without source information.
>  	d3d9.dll!CEnum::CreateDevice()	Unknown	Non-user code. Symbols loaded without source information.
>  	NahimicOSD.dll!77ef7e27()	Unknown	Non-user code. Cannot find or open the PDB file.
>  	[Frames below may be incorrect and/or missing, no symbols loaded for NahimicOSD.dll]		Annotated Frame
>  	gameoverlayrenderer.dll!7a9dbfc8()	Unknown	Non-user code. Cannot find or open the PDB file.
>  	GTAIV.EFLC.FusionFix.asi!7bd393f4()	Unknown	Non-user code. Cannot find or open the PDB file.
> ```
> 
> First of all, can you try without NahimicOSD.dll, whatever this is? If it works without, then we can look further.

seems to be working now, uninstalled the sonic suite studio, but there's still the 'NahimicService' that runs on startup in processes tho... but so far the game is working good with fusionfix v2.3

**Comment by ThirteenAG** [comment]
I don't really know what causes this dll to make the game stuck in an infinite loop, would be nice to fix it somehow.

**Comment by yxngicyx** [comment]
> I don't really know what causes this dll to make the game stuck in an infinite loop, would be nice to fix it somehow.

do you know how i could prevent the nahimicservice process to stop running/ kill it completely? although the modded game is good now, having uninstalled the sonic suite, it bothers me to have this process running

**Comment by ThirteenAG** [comment]
I don't know, should be possible to uninstall it by regular means, or just disable it in Task Manager -> Startup Apps.

**Comment by SandeMC** [comment]
> I don't really know what causes this dll to make the game stuck in an infinite loop, would be nice to fix it somehow.
Happens with multiple injectables, actually. Maybe some timeout or delays for some startup functions could mitigate it, but no clue.

**Comment by Tomasak** [comment]
2.3.1 was released to fix crashing on startup for some people. please try and report if its fixed, or upload crashdump if issue persists.
