### ISSUE TITLE
[TLaD] Crash when jumping into walls with FF 2.3

### ISSUE THREAD

**Issue by Nub865** [ThirteenAG/GTAIV.EFLC.FusionFix#330]
Title. Steam v1.2.0.59 CE. I suppose you don't test your own releases well because you have "Skip Menu" turned to Off by default and that only loads the base GTA IV game. But how would you know? There must be someone else to report it to you. Attaching the crash dumps. FusionFix 2.0++ has been a dumpster fire already and it gets worse

[GTAIV.exe.20231219013129.dmp](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13709422/GTAIV.exe.20231219013129.dmp)
[GTAIV.exe.20231219013129.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13709427/GTAIV.exe.20231219013129.log)

**Comment by ThirteenAG** [comment]
Nobody is forcing you to be here. Come back when you can afford to buy the game.
