### ISSUE TITLE
Game won't launch in the most recent version of fusion fix + 2.0 doesn't load

### ISSUE THREAD

**Issue by VooneexxB** [ThirteenAG/GTAIV.EFLC.FusionFix#334]
i'm trying to launch fusionfix in the most recent version, and it just doesn't open. In the task manager, it appears for some time and then just disappears.

I tried 2.0 and it worked, but when it loads up, it starts to ask to login in social club. When i try to choose "Yes", nothing happens. When i choose "No", it starts to load the game with all the characters appearing and all, the normal loading, but then nothing loads up.

**Comment by Nub865** [comment]
That only happens with illegal pirated copies. We don't support pirated copies because we are Russian buyfags and we have unlimited cash to throw at broken games

**Comment by ThirteenAG** [comment]
I can only fix something I can reproduce.

**Comment by Alexis-Gillet** [comment]
Hi, same problem here with a legal version from Rockstar Games Launcher.

**Comment by ThirteenAG** [comment]
> Hi, same problem here with a legal version from Rockstar Games Launcher.

What problem? If it crashes, upload a crash dump.

**Comment by Alexis-Gillet** [comment]
The game crash at launch, here is the dump : https://we.tl/t-ipS0M3vN4r

**Comment by ThirteenAG** [comment]
> The game crash at launch, here is the dump : https://we.tl/t-ipS0M3vN4r

That's not a crash dump, that's just a dump of a process that's stuck. Identical to another user's problem with `NahimicOSD.dll`

Get rid of it and it will work.

**Comment by ThirteenAG** [comment]
Alternatively try this build:
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13748248/GTAIV.EFLC.FusionFix.zip)
I've blacklisted this dll, but I can't test the result.

**Comment by Tomasak** [comment]
2.3.1 was released to fix crashing on startup for some people. please try and report if its fixed, or upload crashdump if issue persists.

**Comment by Alexis-Gillet** [comment]
Issue fixed ! Thank you for your reactivity and your fix ! :)
