### ISSUE TITLE
Please tell me how to use ENB, Dxvk and Reshade at the same time

### ISSUE THREAD

**Issue by GOOGORO** [ThirteenAG/GTAIV.EFLC.FusionFix#335]
After I use the new version GTAIV.EFLC.FusionFix, the three cannot be used at the same time.
I know how to set up the old version. Please tell me how to set up the new version. Thank you.

**Comment by SandeMC** [comment]
This project doesn't provide support for ENB and DXVK works just fine.

**Comment by Tomasak** [comment]
ENB by its nature cannot work with fusion fix as it is designed for different shaders. as for dxvk and reshade, use reshade for vulkan with dxvk.
