### ISSUE TITLE
How to be compatible with DXVK？

### ISSUE THREAD

**Issue by LeeRico** [ThirteenAG/GTAIV.EFLC.FusionFix#337]
Installing DXVK in versions after 2.0, the game runs out at the rockstar logo

**Comment by LeeRico** [comment]
[CrashDumps.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13722527/CrashDumps.zip)

**Comment by ThirteenAG** [comment]
```
    Backtrace:
        =>0x13462C94 in unknown (+0x13462c94) (0x1661FCB8) 
          0x769DB660 GetMessageW+0x0 in USER32.dll (+0x3b660) (0x1661FCC4) 
          0x67A91DF4 dummy_debug_proc+0x124 in graphics-hook32.dll (+0x1df4) (0x1661FD24) 
          0x7513FCC9 BaseThreadInitThunk+0x19 in KERNEL32.DLL (+0x1fcc9) (0x1661FD34) 
          0x771F7C6E RtlGetAppContainerNamedObjectPath+0x11e in ntdll.dll (+0x67c6e) (0x1661FD90) 
          0x771F7C3E RtlGetAppContainerNamedObjectPath+0xee in ntdll.dll (+0x67c3e) (0x1661FDA0) 
```

**Comment by LeeRico** [comment]
@ThirteenAG I don't understand what to do.

**Comment by ThirteenAG** [comment]
graphics-hook32.dll crashes, what do you expect me to do?

**Comment by LeeRico** [comment]
@ThirteenAG I just tried reinstalling the game and it worked its way into the game, but now I'm having a new problem where the game stops running when I manually load an archive or start a new game within the game!
[CrashDumps.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13734930/CrashDumps.zip)

**Comment by LeeRico** [comment]
@ThirteenAG I'm sorry to waste your time, but I love this mod and want it to work!

**Comment by ThirteenAG** [comment]
You're using cracked version, other mods, 1.2.0.43 instead of latest patch, and expect it to work?

**Comment by LeeRico** [comment]
@ThirteenAG I see, I started with the steam version but it wouldn't go into the game so I patched in the crack and got into the game properly, now I'll try the steam version again.

**Comment by LeeRico** [comment]
@ThirteenAG Sorry again for wasting your time.

**Comment by anthoncast** [comment]
Why using a pirated version tho? Steam's better
