### ISSUE TITLE
Game crashes on the mission Easy as Can Be

### ISSUE THREAD

**Issue by coach-deavers** [ThirteenAG/GTAIV.EFLC.FusionFix#338]
The game crashes shortly after driving away from the alley in the mission Easy as Can Be, only mod installed is FusionFix 2.3 on latest steam version. 
[CrashDumps.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13723665/CrashDumps.zip)

EDIT: After some more playing I was able to pass the mission without any issue, no idea what I did differently the last time, but it crashed at least 4 times before.

**Comment by ThirteenAG** [comment]
It crashes in the function CTaskInfoManager::isTaskActive, which could be related to other limits we increase to fix different crashes. If you're willing to test more, I can make new test build later.

**Comment by coach-deavers** [comment]
The game doesn't even crash at all anymore during the mission, and I've tried 3 times. It might of just been bad luck before.
