### ISSUE TITLE
fusionfix v2.3 gives terrible fps and, freezes and crashes randomly (sometimes while shooting)

### ISSUE THREAD

**Issue by addictedtoiv** [ThirteenAG/GTAIV.EFLC.FusionFix#339]
here is the crashdump text -

Unhandled exception at 0x00896F59 in GTAIV.exe (+0x566f59): 0xC0000005: Access violation reading location 0x00000030.
    Register dump:
        EAX: 0x1C6537A0  EBX: 0x1B7137E8  ECX: 0x00000000  EDX: 0x1C64DD30  
        EDI: 0x1B7136D0  ESI: 0x00000000  EBP: 0x1BA407E4  EIP: 0x00896F59  
        ESP: 0x022FEF40  EFL: 0x00210206  
        
        CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   
        ES: 0x0000002B   DS: 0x0000002B   
        
        ST00: 0x00000000 0xEBEDB100 0x00004000 0xCD000000  [ 0.000000 -574702556232270083216375808.000000 0.000000 -134217728.000000 ]
        ST01: 0x00000000 0xFFA3CD00 0x00003FFE 0xE6000000  [ 0.000000 -nan 0.000000 -151115727451828646838272.000000 ]
        ST02: 0x00000000 0xED82E600 0x00004000 0x2B000000  [ 0.000000 -5063888026910777955550494720.000000 0.000000 0.000000 ]
        ST03: 0x00000000 0xFF4E2B00 0x00003FFE 0xDC000000  [ 0.000000 -274044235896609667406211065759907446784.000000 0.000000 -144115188075855872.000000 ]
        ST04: 0x00000000 0xEEACDC00 0x00004000 0x78000000  [ 0.000000 -26748692684793285119548850176.000000 0.000000 10384593717069655257060992658440192.000000 ]
        ST05: 0x00000000 0xF9C07800 0x00003FFE 0xD6000000  [ 0.000000 -124919360748890638141091120670572544.000000 0.000000 -35184372088832.000000 ]
        ST06: 0x00000000 0xFC6ED600 0x00004000 0x00000000  [ 0.000000 -4960428351945881732243931352518361088.000000 0.000000 0.000000 ]
        ST07: 0x00000000 0x00000000 0x00000000 0x002B0000  [ 0.000000 0.000000 0.000000 0.000000 ]
        
        XMM00: 0x3F800000 0x00000000 0x00000000 0x00000000  [ 1.000000 0.000000 0.000000 0.000000 ]
        XMM01: 0x42AC0000 0x00000000 0x00000000 0x00000000  [ 86.000000 0.000000 0.000000 0.000000 ]
        XMM02: 0x42ACE7AA 0x00000000 0x00000000 0x00000000  [ 86.452469 0.000000 0.000000 0.000000 ]
        XMM03: 0x3F800000 0x00000000 0x00000000 0x00000000  [ 1.000000 0.000000 0.000000 0.000000 ]
        XMM04: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM05: 0x42700000 0x00000000 0x00000000 0x00000000  [ 60.000000 0.000000 0.000000 0.000000 ]
        XMM06: 0x3CA3D70A 0x00000000 0x00000000 0x00000000  [ 0.020000 0.000000 0.000000 0.000000 ]
        XMM07: 0x4B000000 0x00000000 0x00000000 0x00000000  [ 8388608.000000 0.000000 0.000000 0.000000 ]
        
    Stack dump:
        0x022FEF40:  1B7136D0 00A7EE12 1B7137E8 00000000 00000000 1B7136D0
        0x022FEF58:  0086FA5D 0086FB09 763C9900 022FF8D0 763C9910 022FF8A8
        0x022FEF70:  022FEF74 00000000 00000000 00000000 00000000 00000000
        0x022FEF88:  00000000 00000000 00000000 00000000 00000000 00000000
        0x022FEFA0:  00000000 00000000 00000000 00000000 00000000 00000000
        0x022FEFB8:  00000000 00000000 00000000 00000000 00000000 00000000
        0x022FEFD0:  00000000 00000000 00000000 00000000 00000000 00000000
        0x022FEFE8:  00000000 00000000 00000000 00000000 00000000 00000000
        0x022FF000:  00000000 00000000 00000000 00000000 00000000 00000000
        0x022FF018:  00000000 00000000 00000000 00000000 00000000 00000000
        base: 0x02200000   top: 0x022FEF40   bottom: 0x02300000
        
    Backtrace (may be wrong):
        =>0x00896F59 in GTAIV.exe (+0x566f59) (0x022FEF40) 
          0x00A7EE12 in GTAIV.exe (+0x74ee12) (0x022FEF54) 
          0x0086FA5D in GTAIV.exe (+0x53fa5d) (0x022FEF58) 
          0x0086FB09 in GTAIV.exe (+0x53fb09) (0x022FEF5C) 
          0x763C9900 GetNumaHighestNodeNumber+0x10 in KERNEL32.DLL (+0x19900) (0x022FEF60) 
          0x022FF8D0 in unknown (+0x22ff8d0) (0x022FEF64) 
          0x763C9910 TerminateProcess+0x0 in KERNEL32.DLL (+0x19910) (0x022FF97C) 
          0x6A645A49 in wintypes.dll (+0x55a49)

**Comment by ThirteenAG** [comment]
You didn't even upload a crash dump, nor any other information about game version and whatnot.

**Comment by r3538987** [comment]
> You didn't even upload a crash dump, nor any other information about game version and whatnot.

Maybe this could be right time to try implement report template? Where people will be forced provide at least some minimal info about their setup and problem.

**Comment by ThirteenAG** [comment]
> Maybe this could be right time to try implement report template? Where people will be forced provide at least some minimal info about their setup and problem.

It's in the works.

**Comment by hammerfist11** [comment]
out of curiosity what specs do you have?
