### ISSUE TITLE
[ISSUE] Camera angle issues in the theater.

### ISSUE THREAD

**Issue by HAYASHIDASEIYAKU** [ThirteenAG/GTAIV.EFLC.FusionFix#341]
in magician knife acrobatics, the camera will focus on a chair in the front. It will be like this if there is a ped there.

![12210_20231221203208_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/150517131/bc90294b-2751-4fd4-9552-a6e870d53c0b)

**Comment by anthoncast** [comment]
Yeah I experienced this too, and I thought the same, it's the NPC's fault

**Comment by Tomasak** [comment]
unless its caused really by fusion fix, please reopen here https://github.com/GTAmodding/GTAIV-Issues-List/issues
