### ISSUE TITLE
Crashing on startup on latest build / Graphics menu issues

### ISSUE THREAD

**Issue by juicermv** [ThirteenAG/GTAIV.EFLC.FusionFix#344]
Game opens for a while on a black screen after launch and then just crashes. Legit Steam copy, built the asi myself from the latest commit (#343) at the time of writing. Crash dump attached.
[GTAIV.exe.20231222172037.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13753811/GTAIV.exe.20231222172037.zip)

Edit: Forgot to mention, I have Project2DFX and ColAccel installed as well.

**Comment by ThirteenAG** [comment]
Can't you launch with debugger and see where and why? I won't be able to help without reproducing this.
Crashdump indicates that it crashes in BeginScene when it tries to call one of the natives.

**Comment by ThirteenAG** [comment]
Alternatively try with this build
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13754059/GTAIV.EFLC.FusionFix.zip)

**Comment by juicermv** [comment]
> Can't you launch with debugger and see where and why? I won't be able to help without reproducing this.
> Crashdump indicates that it crashes in BeginScene when it tries to call one of the natives.

Sure I could, here's the thing. This stopped happening after I restarted my PC. I have no idea how to reproduce this again.

**Comment by ThirteenAG** [comment]
Well, I've moved beginscene code to start working much later in the build above, so hopefully that will avoid a crash on startup.

**Comment by juicermv** [comment]
> Well, I've moved beginscene code to start working much later in the build above, so hopefully that will avoid a (possible) crash on startup.

Alright, can't reproduce at the moment so idk. Either way, another issue has appeared, some options now straight up do not render, only god knows why,
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/34755463/9265b677-17fe-4af9-9ea7-9f9ab0d3501e)

**Comment by juicermv** [comment]
This is the same build as the one that was previously crashing btw. I'll see whether this happens on the built you sent over here

**Comment by ThirteenAG** [comment]
I think your settings are corrupted.

**Comment by juicermv** [comment]
I deleted ProfileSettings and ControlMap.dat in Documents\Rockstar Games\GTA IV. Didn't help.

**Comment by ThirteenAG** [comment]
Maybe they are in appdata.

**Comment by juicermv** [comment]
I deleted everything in  `\AppData\Local\Rockstar Games\GTA IV\Settings` and it just reset my settings, but they still aren't rendering. Maybe it's something to do with the menu files in the overloader? I'll try to reinstall them.
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/34755463/2b263193-1c6a-428b-ac5c-dfb1a9cf6b84)

**Comment by ThirteenAG** [comment]
No idea, check in-game maybe?

**Comment by juicermv** [comment]
Same result in-game. This is after replacing `frontend_menus.xml` with the latest version from the repo btw. I'll try to maybe re-validate the files on Steam or something.
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/34755463/fcc034b7-7240-42c8-90a1-b1dfe1a8a923)

**Comment by juicermv** [comment]
Alright so I've just renamed the asi of FusionFix so it doesn't get loaded, and launched the game. I can fully edit the settings now so I can only assume this is caused by something in the code. Maybe something with the settings loader? I wish there was some clear way to reproduce this but I'll try to look through the code for a possible culprit.
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/34755463/425d363d-9e1f-476f-bff7-7f479e121e46)

**Comment by juicermv** [comment]
Alright so this seems to happen... everywhere. I can modify the normal settings and they'll start rendering (this doesn't persist after relaunching the game) and I can't modify the sliders at all.
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/34755463/fbb54050-c884-4a53-967a-d1b8ba6c6d46)

**Comment by juicermv** [comment]
Tried a bit of debugging but most of my breakpoints don't get called and adding stuff to the watchlist isn't any help. At this point i'll try just completely reinstalling everything and see what happens.
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/34755463/18a5b980-117a-4e8d-a919-42f977083415)

**Comment by juicermv** [comment]
A complete reinstall has fixed the issue for now.

**Comment by Tomasak** [comment]
So does the issue still persist, or can this be closed as done? New version was released to mitigate some of the startup crashing with certain overlays from third party apps.

**Comment by juicermv** [comment]
Again I have no idea how to reproduce this so as long as it doesn't come up again I guess it's fixed
