### ISSUE TITLE
[Question] Why does my FPS suddenly get halved just by driving a bit forward?

### ISSUE THREAD

**Issue by smashishere** [ThirteenAG/GTAIV.EFLC.FusionFix#345]
Here is a clip which shows the issue: https://clipchamp.com/watch/jxEB8MOZUWO

I'm getting like 70-80 fps and then I move a bit forward and then it drops to 40fps, I move back a little and it goes back to 70-80fps. Nothing really changes in the view for the fps to drop so much, is this normal?

Only using fusionfix on the latest steam version.

**Comment by SandeMC** [comment]
Evil wizard is eating your frames

**Comment by smashishere** [comment]
> Evil wizard is eating your frames
> 
> Honestly though, this is weird. Does it persist between restarts?

yes and it happens all around the map, its like I enter a certain cell of the map which has performance issues and then I enter another cell which doesnt have that issue.

**Comment by danirepio** [comment]
So... What's the solution? Looks like I have the same issue
