### ISSUE TITLE
[Feature Request] Driving Camera Focus option, relative to Player/Vehicle

### ISSUE THREAD

**Issue by Shockwave508** [ThirteenAG/GTAIV.EFLC.FusionFix#346]
In my opinion, a longstanding issue with GTAIV is how the third-person driving camera is always centered relative to the player's position in the driver's seat, rather than being centered to the vehicle itself, like in III/VC/SA/V. If there is enough room in the options menu, and depending on ASI scripting limitations, would it be possible to add a Driving Camera Focus option, to toggle between centering to Player/Vehicle?

**Comment by ThirteenAG** [comment]
https://github.com/gennariarmando/iv-centered-vehicle-cam

**Comment by Shockwave508** [comment]
Never knew about this! Thanks for pointing me in the right direction.
