### ISSUE TITLE
[Feature Request] Add Steam Controller to available gamepad prompts.

### ISSUE THREAD

**Issue by Shockwave508** [ThirteenAG/GTAIV.EFLC.FusionFix#347]
While Valve's proprietary Steam Controller is no longer being produced, some modern games may detect Steam Deck inputs as those from the legacy hardware. And Steam Controller profiles do show up from time to time. Would it be possible to add a Steam Controller option for the gamepad button prompts, so those who use it aren't left out?

![ss_d2f5e7325666df6119ff1d42be73bac9594c5b1e 1920x1080](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/32436386/037d5de7-0c9b-429b-96dd-c2f5d3aab8d5)

**Comment by Tomasak** [comment]
added in 2.4
