### ISSUE TITLE
Unable to toggle individual FusionFix settings

### ISSUE THREAD

**Issue by dumdoo** [ThirteenAG/GTAIV.EFLC.FusionFix#354]
### Game version this happens in

v1.2.0.43

### What area of the game

When I toggle a option added by FusionFix in the settings menu, it applies the same option (at least visually) to all other FusionFix settings in the same category.

Using FusionFix v2.3.

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/51958309/336c7244-7dc3-4dd7-bcdb-c44cb37d9085

### What should happen

I should be able to choose individual values for each option. Each value should be appropriate/correspond to that option.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Tomasak** [comment]
Either buy legit game, or at least find a way to obtain a better drmless copy.
