### ISSUE TITLE
GTA4: Game crashing on Manny mission Escuela of the Streets v 1.0.7.0

### ISSUE THREAD

**Issue by Bleek82** [ThirteenAG/GTAIV.EFLC.FusionFix#358]
### Game version this happens in

v1.2.0.59

### What area of the game

In Bohan, the first Manny mission Escuela of the Streets. It crashes on the first cut scene at the community center (but I can skip the cut scene) and it crashed again after shooting up the dealers at the warehouse and leaving out the back door in the warehouse. It crashes when the door opens, boots me out of the game.
The Complete Edition was purchased off Steam and downgraded for modding. 

### What should happen

I should be able to view the entire cut scene. In the warehouse I should be able to exit the back door after killing the gang. 

### CrashDumps and logs

[GTAIV.exe.20231224150503.dmp](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13762764/GTAIV.exe.20231224150503.dmp)
[GTAIV.exe.20231224150503.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13762765/GTAIV.exe.20231224150503.log)
[GTAIV.exe.20231224142946.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13762766/GTAIV.exe.20231224142946.log)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
1.0.7.0 is not supported.
