### ISSUE TITLE
Game crashing at Startup

### ISSUE THREAD

**Issue by Mlink234** [ThirteenAG/GTAIV.EFLC.FusionFix#359]
### Game version this happens in

v1.2.0.59

### What area of the game

the game is crashing at the startup loading screen

### What should happen

i dont use any other mods its a fresh and clean steam install of the Complete Edition and is just installed Fusionfix, but its  starting without any problems after i remove fusion fix

### CrashDumps and logs

[GTAIV.exe.20231225143748.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13766225/GTAIV.exe.20231225143748.log)

### Last working version

v2.0

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
The log file is of no use, you need to upload crash dump. Did you actually try the latest appveyor build also?

**Comment by Mlink234** [comment]
i dont now if its the latest one i just installed the mod from here :https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix

here is the crashdump: https://drive.google.com/file/d/1pvY4NfLvHt4Wz7UvtXMqe7lpSrxTRLVq/view?usp=drive_link

**Comment by ThirteenAG** [comment]
There's literally a link to in a check box in your post

> Checklist

> Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.

**Comment by ThirteenAG** [comment]
Crash dump link is inaccessible.

**Comment by Mlink234** [comment]
ok i give it try
sorry u can now access the file

**Comment by Mlink234** [comment]
i tried the new build and ist crashing to
https://drive.google.com/file/d/1B8tCawPZ5_T3ZTwBvNgp3Uo1jV7FTQ5w/view?usp=sharing

**Comment by ThirteenAG** [comment]
I see, let me prepare a fix.

**Comment by ThirteenAG** [comment]
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13766425/GTAIV.EFLC.FusionFix.zip)
Please try this build.

**Comment by Mlink234** [comment]
didnt work :( keeps crashing 
https://drive.google.com/file/d/15ZjG8WiZ9rhg-O6B24h6GHF1PsHNkQ54/view?usp=sharing

**Comment by ThirteenAG** [comment]
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13766521/GTAIV.EFLC.FusionFix.zip)
Okay, what about this one?

**Comment by Mlink234** [comment]
sorry, same here 
https://drive.google.com/file/d/1bnrZawL2wosD2drj7k6lZ9CNtNUnGgL2/view?usp=sharing

**Comment by ThirteenAG** [comment]
That's strange. Test this one, I disabled the crashing code, check if it crashes anywhere else.

[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13766548/GTAIV.EFLC.FusionFix.zip)

**Comment by Mlink234** [comment]
ok now the games is working, thank you so much,
im going to test the game a while and i hope no more crashing

**Comment by ThirteenAG** [comment]
I will need you test more in a bit.

**Comment by Mlink234** [comment]
Ok

**Comment by ThirteenAG** [comment]
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13766593/GTAIV.EFLC.FusionFix.zip)

**Comment by Mlink234** [comment]
its working

**Comment by ThirteenAG** [comment]
Oh, interesting. Thanks for the report, I'll push the fix to dev build shortly.

**Comment by Mlink234** [comment]
great thanks you ^^ should i close this issue?

**Comment by ThirteenAG** [comment]
It will be closed automatically.
