### ISSUE TITLE
Game won't launch after installing FusionFix 1.0.7.0

### ISSUE THREAD

**Issue by MrPugWasTaken** [ThirteenAG/GTAIV.EFLC.FusionFix#360]
### Game version this happens in

v1.2.0.30

### What area of the game

So I decided to try and install FusionFix again after uninstalling it due to already having ZolikaPatch and FusionFix kept crashing my game randomly.

Now, upon clicking playGTAIV.exe, it doesn't even launch, no EULA, nothing pops up. The game just decides to not appear ever, thus because of this my game doesn't generate a crashdump like it usually does.

### What should happen

It should launch

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by D0M1997** [comment]
Same here, I'm on 1.0.8.0

**Comment by Tomasak** [comment]
Games tampered by third party are not supported. Best is to verify cache via steam/rgl and start with clean game.
