### ISSUE TITLE
GTA 4 FPS Drop Shaders

### ISSUE THREAD

**Issue by AOXsystems** [ThirteenAG/GTAIV.EFLC.FusionFix#361]
### Game version this happens in

v1.2.0.59

### What area of the game

Hello, I v been testing performance on my laptop (i5 8gen
mx250 4gb gddr5, 16gb ram)
. Using only DXVK i get around 30-35fps

Resolution 1920x1080, Textures on high. shadow mid, rest low.. draw distance, detail distance around 50...

With fusion v2.3 installed by default, I get around 12-15fps. Changing options doesn't make a lot of difference except changing resolution from 1920x1080 to 1280x720. 

 v1.73 gives 30fps.
 v1.8 30fps+
 v1.96 - 19fps
 v2.3/32 - 14fps

 Upon installing multiple versions something introduced in **194/196** is causing this.

### Your Hardware configuration

i5 8gen
nvidia mx 250 4gb
16gb ram
m2 512gb

### Does IV run better without FF installed?

A bit better, but without any shadows game looks bad

### Graphics backend (3D API)

DXVK

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.

**Comment by AOXsystems** [comment]
What Iv tried next

Installed latest version with good fps 1.8.
Replaced all updates folder with 2.31
Fps in benchmark 30+

Then i swapped GTAIV.EFLC.FusionFix.asi
that  caused drop 30+ fps to 15-18fps

Settings were same(the ones that exist in both versions)
FXAA, DOF disabled. 
Shadow sharp

**Comment by RecklessGlue540** [comment]
Z-fighting fix was said to degrade performance with Intel integrated GPUs.

**Comment by Tomasak** [comment]
i myself saw 5 FPS degradation with FF installed on core2quad with some 4000 series amd radeon hd gpu, and all of its new options disabled - Depth Of Field, shadow filter set to sharp, tree lighting set to PC. You could also disable dynamic trees shadows from ini - DynamicShadowForTrees = 1 to 0 and maybe ExtraDynamicShadows = 1 set to 0

**Comment by hammerfist11** [comment]
this seems to just be a necessary thing with fusion fix im afraid. Some improvements will come at the cost of performance. You have a very old system, you might want to consider upgrading.
