### ISSUE TITLE
Is it possible to add a sitting mechanic? 

### ISSUE THREAD

**Issue by Bleek82** [ThirteenAG/GTAIV.EFLC.FusionFix#362]
### What should happen

I notice when going to the strip club with a friend they can sit in a chair, I want to sit down too. Is it possible to add a sitting mechanic for the user? Instead of mapping a sitting animation to a button, just create a sitting prompt on items (chairs, stools, benches, etc.) throughout the game that can trigger a sitting animation, like when you lay down to save or sit down to watch TV.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by spidergrear2** [comment]
i don't really think that's important to the main game

**Comment by RecklessGlue540** [comment]
Feel free to suggest these small things to Liberty Tweaks. It's not yet compatible with CE as IV-SDK.NET is still old patch dependant, but it's author wanted to expand the compatibility.
I already suggested this.

**Comment by Tomasak** [comment]
this is out of scope of this mod
