### ISSUE TITLE
Game dont start when I try to open.

### ISSUE THREAD

**Issue by nehighborGOD** [ThirteenAG/GTAIV.EFLC.FusionFix#364]
### Game version this happens in

v1.2.0.59

### What area of the game

When I try launch the game doesn't start if someone can  give me a fix it would be helping me thanks.
(And when I use a lower version the game start but the mod dont work i use The Complete Edition 1.0.7.0)

### What should happen

Game should start.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
Reports without crashdumps will be closed.
