### ISSUE TITLE
Add RealityIV 2.0 as an screen filter option along with the current timecyc

### ISSUE THREAD

**Issue by kelvinf462** [ThirteenAG/GTAIV.EFLC.FusionFix#366]
### What should happen

RealityIV 2.0 is a really cool timecyc mod that gives the game almost a enb treatment to its looks and doesnt affect performance, the mod can be checked here https://www.gtagaming.com/realityiv-2-0-f25401.html.
I was wondering if it is possible to add this modded timecyc as a new screen filters option, if so could someone guide me so i could do this addition to fusion fix and possibly open a pull request, thanks

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
Out of scope for this mod, sorry. RealityIV also has it's own shaders and on top of that it's own issues in some cutscenes...

**Comment by MagicAl6244225** [comment]
You can't use the shaders included with RealityIV 2.0 in combination with FusionFix shaders but the other RealityIV files could be installed in the update folder, just don't use the RealityIV shaders folder.

**Comment by RecklessGlue540** [comment]
> You can't use the shaders included with RealityIV 2.0 in combination with FusionFix shaders but the other RealityIV files could be installed in the update folder, just don't use the RealityIV shaders folder.

You'll definitely lose some of it's effects doing that, but yes, still works...

**Comment by kelvinf462** [comment]
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/154650048/a330a15f-bf2f-4979-810c-19d76c05cbb4)
I didnt added the shadders, only the timecyc files, and the game became all white, after removing the GTAIV.EFLC.FusionFix.ini and GTAIV.EFLC.FusionFix.asi, the realityIV worked properly, only then i got the idea of adding the timecyc as a filter option,  i didnt even tried the realityIV shaders to be honest

**Comment by Tomasak** [comment]
> Out of scope for this mod, sorry. RealityIV also has it's own shaders and on top of that it's own issues in some cutscenes...

this
