### ISSUE TITLE
Jagged Lines and Shimmering Edges 

### ISSUE THREAD

**Issue by kelvinf462** [ThirteenAG/GTAIV.EFLC.FusionFix#367]
### What should happen

This games lack of anti aliasing hurts my eyes, i already tried everything that i can think off, from:
- Using nvidias control panel antialiasing, which had zero effect
- [injectSMAA](https://mrhaandi.blogspot.com/p/injectsmaa.html) by mrhaandi
- some enbs
- Nvidias Dynamic Super Resolution, which in 4k helped but it didnt resolved the issue

I saw some youtube videos of the game looking super smooth but I never managed to get those results.
Is there a known solution for this or is better just to accept and deal with it?

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
Not really a way to completely eliminate the aliasing, not at low resolutions.
4K should work quite well... along with SMAA...
Native SMAA will be in one of the next updates. Along with another rather performance taxing method...

Only fully effective way to eliminate aliasing is MSAA. Tho I wouldn't expect it to be implemented. It's kinda impossible.

**Comment by kelvinf462** [comment]
I own a 1080p 21:9 monitor and a 4k 16:9 TV, and I noticed that the main problem is running the game at native resolution.
When playing on the 4k tv at native resolution the game is almost just aliased as the 1080p monitor. But when I upscale the the monitor from 1080p to 4k the games becomes smoother, and on the TV upscaling from 4k to 8k I cant play because of the perfomance, my Ryzen 5 5600 and GTX 3070 cant handle it.

**Comment by kelvinf462** [comment]
Are you guys familiarized with https://github.com/aliasIsolation/aliasIsolation?
Alien Isolation suffers from the same visual issues that GTA IV has with the jagged lines.
This alias Isolation is an injector that aims to fix those issues on alien, it would be great if something of this nature were done for GTA IV

**Comment by RecklessGlue540** [comment]
> Are you guys familiarized with https://github.com/aliasIsolation/aliasIsolation? Alien Isolation suffers from the same visual issues that GTA IV has with the jagged lines. This alias Isolation is an injector that aims to fix those issues on alien, it would be great if something of this nature were done for GTA IV

Read about Alien on PCGW. Looks like it's a DirectX11 game. Meanwhile GTAIV is stuck on DirectX9... I doubt this thing would be easy or even practical to do.

**Comment by Tomasak** [comment]
2.4.0 added SMAA and SSAA (SSAA is HW heavy)
