### ISSUE TITLE
 [Feature Request] Incorporate other mods onto this one 

### ISSUE THREAD

**Issue by Sagatt** [ThirteenAG/GTAIV.EFLC.FusionFix#369]
### What should happen

If possible incorporate other mods that you recommend onto this package, so we have a all-in-one definitive and easy to install package to fix the game whenever we need to, check fusion fix (fixes) and also other stuff such as DXVK, console visuals, Grand Theft Auto IV and Episodes From Liberty City: Characters Fixes and also the Vehicle Pack 2.0 - 15th Anniversary Edition, thanks!

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
> ### What should happen
> If possible incorporate other mods that you recommend onto this package, so we have a all-in-one definitive and easy to install package to fix the game whenever we need to, check fusion fix (fixes) and also other stuff such as DXVK, console visuals, Grand Theft Auto IV and Episodes From Liberty City: Characters Fixes and also the Vehicle Pack 2.0 - 15th Anniversary Edition, thanks!
> 
> ### Checklist
> * [x]  Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
> * [x]  [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

DXVK is another project, completely unrelated to GTAIV. Doubt it's devs would allow that anyway.
Console Visuals... It's already just a few clicks away... just choose what you want and it's ready. Not to mention it's out of scope for a project limited to just fixes.
The Vehicle Pack is also out of scope for this project.
Character Fixes and Various Fixes are also in the same boat.

What you're suggesting is a modpack. Modpacks are quite hard to maintain. 
And it's also kinda useless, since at this point, most things that **matter** are already drag and drop.

**Comment by Sagatt** [comment]
> > ### What should happen
> > If possible incorporate other mods that you recommend onto this package, so we have a all-in-one definitive and easy to install package to fix the game whenever we need to, check fusion fix (fixes) and also other stuff such as DXVK, console visuals, Grand Theft Auto IV and Episodes From Liberty City: Characters Fixes and also the Vehicle Pack 2.0 - 15th Anniversary Edition, thanks!
> > ### Checklist
> > 
> > * [x]   Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
> > * [x]   [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.
> 
> DXVK is another project, completely unrelated to GTAIV. Doubt it's devs would allow that anyway. Console Visuals... It's already just a few clicks away... just choose what you want and it's ready. Not to mention it's out of scope for a project limited to just fixes. The Vehicle Pack is also out of scope for this project. Character Fixes and Various Fixes are also in the same boat.
> 
> What you're suggesting is a modpack. Modpacks are quite hard to maintain. And it's also kinda useless, since at this point, most things that **matter** are already drag and drop.

Console visuals include:
- Trees
- Suits
- Loading Screen
- Fences
- Pedestrians
- Anims
- HUD
- Lights

- The Vehicle Pack is just a bunch of textures and it's already 100% complete, just a matter of incorporating
- Character Fixes is also done
- EFLC Map changes is also done

Work in progress:
- Various Fixes (This is the only one being updated to date)

**Comment by Tomasak** [comment]
not planned, no need to bloat size of this mod
