### ISSUE TITLE
the game doesnt even start when i have fusionfix

### ISSUE THREAD

**Issue by alinivar** [ThirteenAG/GTAIV.EFLC.FusionFix#371]
### Game version this happens in

v1.2.0.59

### What area of the game

when i try launching the game it just doenst launch at all

### What should happen

it just doesnt start up

### CrashDumps and logs

[GTAIV.exe.20231229205948.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13796566/GTAIV.exe.20231229205948.log)

### Last working version

2.3.1 

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by alinivar** [comment]
:[

**Comment by ThirteenAG** [comment]
You can open your log file and see what crashes:
```
        =>0x565339AB ML_64201+0x207b in MirillisActionVulkanLayer.dll (+0x139ab) (0x0966E568) 
          0x601824FC in d3d9.dll (+0xd24fc) (0x0966E598) 
          0x60184C94 in d3d9.dll (+0xd4c94) 
```

**Comment by ThirteenAG** [comment]
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13796921/GTAIV.EFLC.FusionFix.zip)
Does it work with this build?

**Comment by alinivar** [comment]
> [GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13796921/GTAIV.EFLC.FusionFix.zip) Does it work with this build?

i removed dxvk and then added your file, it works now

**Comment by ThirteenAG** [comment]
can you recheck with dxvk?
