### ISSUE TITLE
Does PCSS Shadows suposed to drop this much FPS? Also game not launching with -percentvidmem 100 commandline

### ISSUE THREAD

**Issue by kelvinf462** [ThirteenAG/GTAIV.EFLC.FusionFix#372]
### Game version this happens in

v1.2.0.59

### What area of the game

Anywhere, my game drops around 40 fps when PCSS shadows are on, and also stutters a lot. Its suposed to be this demanding?
and my game wont launch with -percentvidmem 100 commandline

### Your Hardware configuration

CPU: Ryzen 5 5600
Ram: 16GB 3000MHz DDR4
GPU: RTX 3070
Gaming at 4K using Nvidia DSR

### Game capture

![softer](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/154650048/a2624b47-39c4-41bd-b29c-6165b494fba5)
![pcss](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/154650048/9f1e98f0-325b-4afb-a3a0-21b290ddcbbe)
Without FF
![without ff](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/154650048/e83af949-f8a1-42e0-bdf2-f765eaec62e4)

### Does IV run better without FF installed?

Yes

### Graphics backend (3D API)

DXVK

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.

**Comment by RecklessGlue540** [comment]
> Anywhere, my game drops around 40 fps when PCSS shadows are on, and also stutters a lot. Its suposed to be this demanding?

Big yes. Use softest at most for good performance.

**Comment by Tomasak** [comment]
ad PCSS yes
ad -percentvidmem: what is this even supposed to do?

**Comment by RecklessGlue540** [comment]
> ad PCSS yes
> ad -percentvidmem: what is this even supposed to do?

It controls how much of GPU memory is available to GTAIV. Probably setting that to like, 80 would leave the rest for the system and other things to use.

-reservedApp and a number is the same thing, but for system ram.

**Comment by Tomasak** [comment]
why setting it to 100% then, i see no point in using it. and if you want to lower it, why not use -availablevidmem and lower that below system vram

**Comment by kelvinf462** [comment]
I using the current settings on GTA IV v1.0.8.0 with [zolika's version of FF](https://github.com/Zolika1351/GTAIV.EFLC.FusionFix) and its workin fine 
```
-windowed
-nomemrestrict
-norestrictions
-noprecache
-percentvidmem 100
-availablevidmem 8032
-width 5120
-height 2160
```
but when i try using the lastest FF with complete edition it doesnt launch.
I added -percentvidmem 100 as a recomendation that I saw on youtube video about fixing dxvk along -availablevidmem 8032

**Comment by Ash-735** [comment]
Try with latest version of Fusion Fix, there were some minor performance tweaks that have gained back around 7-10fps on my side
