### ISSUE TITLE
The mirrors in Maisonette 9 are broken

### ISSUE THREAD

**Issue by coach-deavers** [ThirteenAG/GTAIV.EFLC.FusionFix#373]
### Game version this happens in

v1.2.0.59

### What area of the game

Inside the Maisonette 9 bathrooms the mirrors are broken.
![20231229231601_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/79233125/f8e11644-68e2-4748-b8b2-61ea4c15540b)

### What should happen

There should be a reflection

### Last working version

1.96

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by RecklessGlue540** [comment]
Can you try with latest build? Some mirror offsets were adjusted...

**Comment by Tomasak** [comment]
fixed in 2.4
