### ISSUE TITLE
FusionFix not work after Windows Reset

### ISSUE THREAD

**Issue by Medveghev** [ThirteenAG/GTAIV.EFLC.FusionFix#374]
### Game version this happens in

v1.2.0.59

### What area of the game

FusionFix was working perfectly before my windows got broken, after I reset my windows, reinstall steam and locate the game folder, Fusionfix did not work. I can still see FusionFix menu options like skip intro, bloom, motion blur, console shadow, shadow filter, FOV, etc. But their toggles become ON and OFF only and have no effects in game.
I tried to reinstall FusionFX, but the issue still persist.

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/155215352/7ae64780-a430-4b53-be54-50c94d198a0a

### What should happen

It should be working because before i reset my windows, this mod is working perfectly.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by RecklessGlue540** [comment]
Do you have a legal copy of the game? From Steam or whatever? Plain RGL has no issues tho.

**Comment by Medveghev** [comment]
@RecklessGlue540 I don't know, before I reset my windows FF works perfectly with DXVK, but now this happens. playing GTA IV without FusionFix feels not right.

**Comment by Medveghev** [comment]
@ThirteenAG  Does the menu is supposed to change even if the asi is not loaded?
Any suggestions? because i did not change/delete/move any files in GTA IV directory.
Is there any requirement to run asi loader (dinput8.dll)? like vcredist/netframework or anything?

**Comment by 2Col** [comment]
Same issue for me. Fresh Windows 10, v1.2.0.59, FusionFix v2.4.2

**Comment by ThirteenAG** [comment]
> Same issue for me. Fresh Windows 10, v1.2.0.59, FusionFix v2.4.2

Do you have discord?

**Comment by TKStraw** [comment]
> Same issue for me. Fresh Windows 10, v1.2.0.59, FusionFix v2.4.2

Same thing here, launching through RGL, but I have Windows 11. Options all show up, but nothing takes effect and all those options change when I try to change one like in the video.

**Comment by IvanRizky81** [comment]
Any update for this ? i recently bought a new laptop running on Win 11 and i got the same issue but the issue isn't present on my old Win 10 laptop. And i did some testing too and Version 1.8.0 can work but all version after 2 doesn't work

**Comment by ThirteenAG** [comment]
> Any update for this ? i recently bought a new laptop running on Win 11 and i got the same issue but the issue isn't present on my old Win 10 laptop. And i did some testing too and Version 1.8.0 can work but all version after 2 doesn't work

Everything works if you install the game from steam and run from steam, on a clean windows. Other than that can't say more, don't know why it may not work.

**Comment by IvanRizky81** [comment]
But that's the thing my Win 11 is also a fresh install, The game is the first thing i install through Steam on my new laptop everything is still clean. Right now i'm still wondering what did i miss and why the only version of FusionFix that worked on my laptop is v1.8.0

**Comment by ThirteenAG** [comment]
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/4904157/035b7c48-694e-4860-98d0-b73f3751667a)

This is what dependencies show is missing on clean windows 10 install. After I install dx runtime from https://www.microsoft.com/en-us/download/details.aspx?id=35
The asi loads correctly.
