### ISSUE TITLE
Intro theme song not playing in versions 2.0 above

### ISSUE THREAD

**Issue by GoatSevens** [ThirteenAG/GTAIV.EFLC.FusionFix#375]
### Game version this happens in

v1.2.0.59

### What area of the game

Although there's an option to skip the intro, I like to listen to that short jingle but since 2.0, the intro theme can no longer be heard. I did reinstall the game and only installed the latest version of Fusion Fix but no luck, only in version 1.96 the intro theme can be heard.

### What should happen

The intro theme should start playing right after the legal screens.

### Last working version

v1.96

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Tomasak** [comment]
you mean you cant heard the intro jingle despite having skip intro set to 0?
If that's the case, did you install console visuals console loading screen in past? one version came with inproper dat file blocking the song from being heard

**Comment by GoatSevens** [comment]
Yes, I did install console visuals loading screens in the past but I updated it to the latest version. But even without console visuals overall, no music can be heard, even if fusion fix is installed alone.

**Comment by Tomasak** [comment]
try renaming the update folder if its really not some file breaking the sound, since i cant reproduce this issue

**Comment by GoatSevens** [comment]
Yep it was some file in the update folder. It was solved by updating Console Visuals. Thanks for the help.
