### ISSUE TITLE
SkipMenu not available anymore

### ISSUE THREAD

**Issue by UD73** [ThirteenAG/GTAIV.EFLC.FusionFix#376]
### What should happen

Could you please reinstate the SkipMenu option in the .ini file otherwise only GTAIV will be automatically loaded, it is not possible to choose between EFLC GAMES and IV. Thanks.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by ThirteenAG** [comment]
No. You can switch that option in game menu, episodic save is loaded automatically if it was last saved, episode selection is available from in game menu as well.
