### ISSUE TITLE
2.4.1 causes injection issues on Proton

### ISSUE THREAD

**Issue by brianx87** [ThirteenAG/GTAIV.EFLC.FusionFix#380]
### Game version this happens in

v1.2.0.59

### What area of the game

Launching the game causes an injection error.

"GFWLProtectionDisabler2019.asi" is the first dialog.

### What should happen

It shouldn't crash as previous versions worked. The game is downgraded to 1.0.8 with a modlist installed running on Steam Deck with Proton, previous FusionFix 2.3 and 2.3.1 versions worked perfectly.

Upon removing the GFWLProtectionDisabler2019.asi for testing the game doesn't launch and error dialogs appear for all installed asi files. Downgrading back to FusionFix 2.3.1 works fine
![Screenshot_20240102_030350](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/11686648/7a8e5564-c7f9-441a-9597-558b02f966ad)
![Screenshot_20240102_030425](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/11686648/16da3d58-7737-49c5-b425-4cd7cc185823)

### CrashDumps and logs

No idea how to do that on Linux

### Last working version

v2.3.1

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
Previous versions are not supported, and if you use Fusion Fix on that version, it requires XLiveless(rename asi loader to xlive.dll) and [XLiveless Addon](https://github.com/GTAmodding/XLivelessAddon/releases).

**Comment by ThirteenAG** [comment]
There should be a button to continue on that dialog, but I guess proton doesn't show it properly.
