### ISSUE TITLE
Dancing minigame in TBoGT doesn't show buttons when using a controller

### ISSUE THREAD

**Issue by coach-deavers** [ThirteenAG/GTAIV.EFLC.FusionFix#381]
### Game version this happens in

v1.2.0.59

### What area of the game

In the dancing minigame in TBoGT after it says hold, it doesn't show button prompts when using a controller.
![20240101213238_2](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/79233125/322d48a0-ea95-428f-b1f9-69f2f9c43914)

### What should happen

There should be button prompts for the triggers.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
Thanks, we forgot to put dancing.wtd to TBoGT subfolder ¯\_(ツ)_/¯. Will be fixed in the next release today.
