### ISSUE TITLE
Black screen when SMAA is enabled. 

### ISSUE THREAD

**Issue by gamerr7357** [ThirteenAG/GTAIV.EFLC.FusionFix#383]
### Game version this happens in

v1.2.0.59

### What area of the game

After loading the game with SMAA enabled, only the HUD is visible.  The problem disappears after using the ALT + TAB shortcut. I am using version v2.4.2.

### What should happen

There should be no black screen.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by RecklessGlue540** [comment]
Attach a screenshot.

**Comment by Tomasak** [comment]
Does issue persist on 2.4.5?
