### ISSUE TITLE
Only shows Xbox Button Prompts when selecting PlayStation 5

### ISSUE THREAD

**Issue by Scoobsbro** [ThirteenAG/GTAIV.EFLC.FusionFix#384]
### Game version this happens in

v1.2.0.59

### What area of the game

Before I installed this mod my PlayStation button prompts where already there, now after I installed the mod the button prompts are all Xbox. I can't change them even if I try to change by selecting the PlayStation 5 gamepad icons.

### What should happen

I should be able to see my PlayStation buttons

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Ash-735** [comment]
So from what I'm gathering, you already had a butrtons_360.wtd that was edited to have PlayStation buttons? If so then yes, Fusion Fix ships with a new buttons_360.wtd with 8 different controllers in it, you select them by going to the CONTROLS tab, selecting Controller Options, and then selecting Controller Style from here instead.

**Comment by Scoobsbro** [comment]
> So from what I'm gathering, you already had a butrtons_360.wtd that was edited to have PlayStation buttons? If so then yes, Fusion Fix ships with a new buttons_360.wtd with 8 different controllers in it, you select them by going to the CONTROLS tab, selecting Controller Options, and then selecting Controller Style from here instead.

I redownloaded GTA IV and added this mod with a couple of performance mods that shouldn't be conflicting with buttons_360.wtd. However if I select PlayStation 5 as my gamepad icon it doesn't work.
![20240122182803_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/155496926/550fcfc2-fdf4-48cb-83f8-463c1b4761ed)


 It just changes any "ON" button on settings to "PlayStation 5"
![20240122182831_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/155496926/8c36873b-3b3f-4f0b-8311-9d55c51eb481)

**Comment by ThirteenAG** [comment]
That means asi is not loaded.
