### ISSUE TITLE
Game does not start at all with FusionFix

### ISSUE THREAD

**Issue by Pepkata92** [ThirteenAG/GTAIV.EFLC.FusionFix#386]
### Game version this happens in

v1.2.0.59

### What area of the game

When I try to start the game it won't start at all. No message, no nothing. I have the Steam version.
![Untitled](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/155521241/7ef82518-5a61-49be-9891-9b1b7bf41b1d)

### What should happen

The game should start from the play button in Steam game library.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Ash-735** [comment]
Sounds like the Rockstar Launcher crash where it just refuses to start the game, best advice is to try again, and keep trying until it starts properly. To be certain it's that though you should provide a crash dump if you know how to do that.

**Comment by Pepkata92** [comment]
> Sounds like the Rockstar Launcher crash where it just refuses to start the game, best advice is to try again, and keep trying until it starts properly. To be certain it's that though you should provide a crash dump if you know how to do that.

Yea, I've tried many times the game starts only after a computer restart and just 1 time. When I quit the game I need to restart my pc again to boot the game and even that method is not a solution. Sometimes the game don't start at all even after I've restarted my PC, no error messages and no issues just the game loads from Steam and Rockstar Launcher loads for couple of seceonds and nothing happens.

**Comment by ThirteenAG** [comment]
You have not attached a crash log AND a crash dump, and it's unclear if this something that happens without fusion fix too, so there's no way to tell what's happening.

**Comment by Pepkata92** [comment]
> You have not attached a crash log AND a crash dump, and it's unclear if this something that happens without fusion fix too, so there's no way to tell what's happening.

I've tried the game without fusion fix and it starts fine everytime. Anyway can you tell me how to find where is the crash log and the crash dump, thanks.

**Comment by ThirteenAG** [comment]
https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/new?assignees=&labels=&projects=&template=bug.yml

**Comment by Pepkata92** [comment]
[asilog.txt](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13845767/asilog.txt)
[GTAIV.exe.20240103163720.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13845768/GTAIV.exe.20240103163720.log)

Do this files work for finding the problem?

**Comment by ThirteenAG** [comment]
```
// -- GTA IV ASI LOADER LOG -- //
//-- (C) Alexander Blade 2008 -- //
```
Having two asi loaders is not supported, I'm pretty sure.

**Comment by Pepkata92** [comment]
> ```
> // -- GTA IV ASI LOADER LOG -- //
> //-- (C) Alexander Blade 2008 -- //
> ```
> 
> Having two asi loaders is not supported, I'm pretty sure.

This is how my GTA IV Folder looks like
![Untitled](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/155521241/8c14d431-225b-4328-a82d-c29b09989765)

**Comment by RecklessGlue540** [comment]
> > ```
> > // -- GTA IV ASI LOADER LOG -- //
> > //-- (C) Alexander Blade 2008 -- //
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Having two asi loaders is not supported, I'm pretty sure.
> 
> This is how my GTA IV Folder looks like ![Untitled](https://private-user-images.githubusercontent.com/155521241/294720328-8c14d431-225b-4328-a82d-c29b09989765.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1ODA4MzYsIm5iZiI6MTcwNDU4MDUzNiwicGF0aCI6Ii8xNTU1MjEyNDEvMjk0NzIwMzI4LThjMTRkNDMxLTIyNWItNDMyOC1hODJkLWMyOWIwOTk4OTc2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQyMjM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODZlMWQ0ZjM2MzdlNjNjMWJmMjhmZGQ4MTM5NDcwMWM2NjlkMjU4MTQwZjI4YjZmNzc1ZjQzNzU0NzI4NjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lgvbopNGW9fLXdT57UYJhtSogLyznA3--Lq2jg_ife8)

That's eye sore. You shouldn't put all those d3d11, d3d10core dlls from DXVK... they don't do anything. Keep only d3d9.dll.
And you have 3 asi loaders... Nothing is expected to work like that... you should only use the dinput8.dll and that's it. Delete xlive and dsound dlls.

**Comment by Pepkata92** [comment]
> > > ```
> > > // -- GTA IV ASI LOADER LOG -- //
> > > //-- (C) Alexander Blade 2008 -- //
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Having two asi loaders is not supported, I'm pretty sure.
> > 
> > 
> > This is how my GTA IV Folder looks like ![Untitled](https://private-user-images.githubusercontent.com/155521241/294720328-8c14d431-225b-4328-a82d-c29b09989765.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1ODA4MzYsIm5iZiI6MTcwNDU4MDUzNiwicGF0aCI6Ii8xNTU1MjEyNDEvMjk0NzIwMzI4LThjMTRkNDMxLTIyNWItNDMyOC1hODJkLWMyOWIwOTk4OTc2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQyMjM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODZlMWQ0ZjM2MzdlNjNjMWJmMjhmZGQ4MTM5NDcwMWM2NjlkMjU4MTQwZjI4YjZmNzc1ZjQzNzU0NzI4NjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lgvbopNGW9fLXdT57UYJhtSogLyznA3--Lq2jg_ife8)
> 
> That's eye sore. You shouldn't put all those d3d11, d3d10core dlls from DXVK... they don't do anything. Keep only d3d9.dll. And you have 3 asi loaders... Nothing is expected to work like that... you should only use the dinput8.dll and that's it. Delete xlive and dsound dlls.

Thanks, that really helped! That was the issue, everything work fine now 👍
