### ISSUE TITLE
Crash when climbing specific fence in the map

### ISSUE THREAD

**Issue by GolfinhoVoador** [ThirteenAG/GTAIV.EFLC.FusionFix#387]
### Game version this happens in

v1.2.0.59

### What area of the game

When I climb [this fence (link to a video)](https://drive.google.com/file/d/1ZSTnfU_tSuHCkDd0hndqofK5dBaJ-9ky/view?usp=sharing), my game crashes. Here's the [savedata](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13822756/SGTA412.zip).
Here's a few screenshots:
![location](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/50271451/9ecdc2b4-021d-46f8-b8c0-e8a8075a6d14)
![calm before the storm](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/50271451/c0fcc295-260b-4288-b456-b7796668d37c)
![crash](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/50271451/ed58e196-7bd0-4cf5-a996-2b429d6e8792)

### What should happen

You should climb the fence normally, like god intended.

### CrashDumps and logs

[GTAIV.exe.20240103163720.dmp.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13822709/GTAIV.exe.20240103163720.dmp.zip)
[GTAIV.exe.20240103163720.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13822711/GTAIV.exe.20240103163720.log)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Ash-735** [comment]
I've just tried to replicate it on my side and sadly the bug is not happening, so it looks like the crash dump will need to be looked at, those fences do seem to trigger the camera change and cinematic jump animation though so it might be an error there.

**Comment by ThirteenAG** [comment]
Crash dump doesn't make a lot of sense, I would suggest to do a clean install of the game first. There were reports of this exact issue here: https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/298
And it was related to a bug in asi loader, which is now fixed. So I'm not sure why it can not be reproduced.

**Comment by ThirteenAG** [comment]
In theory it could be related to CTask pool limit, but in order to confirm I would need a reliable way to reproduce.

**Comment by GolfinhoVoador** [comment]
> In theory it could be related to CTask pool limit, but in order to confirm I would need a reliable way to reproduce.

Unfortunately thats the only way I could reproduce it, and It happened 100% of the times, I'll try to reinstall the game.

**Comment by GolfinhoVoador** [comment]
Didn't happen with/without fusion fix this time, I'll see if it happens when I add more mods.

**Comment by ThirteenAG** [comment]
Yeah, if you notice that something specific causes that, let us know. Maybe it's some anims, since the climbing action uses them.

**Comment by GolfinhoVoador** [comment]
> Yeah, if you notice that something specific causes that, let us know. Maybe it's some anims, since the climbing action uses them.

I didn't have that installed last time I did this, only radio restoration and fusion fix

**Comment by GolfinhoVoador** [comment]
Not happening with every mod I had installed before, something probably got corrupted before. I'm gonna close this for now.

**Comment by Brew-MacMillan** [comment]
I had this problem too, but I was using some different mods. I think console anims triggered this problem from console visuals. I'm not using anims mod right now.

**Comment by RecklessGlue540** [comment]
> I had this problem too, but I was using some different mods. I think console anims triggered this problem from console visuals. I'm not using anims mod right now.

I don't think the console animations have anything related to the climbing anims...

**Comment by Brew-MacMillan** [comment]
> > I had this problem too, but I was using some different mods. I think console anims triggered this problem from console visuals. I'm not using anims mod right now.
> 
> I don't think the console animations have anything related to the climbing anims...

It may not be related, but it may have triggered the problem. ThirtheenAG said this could happen.
