### ISSUE TITLE
Gta IV lost and damned crash: SRCP10

### ISSUE THREAD

**Issue by Swordman14** [ThirteenAG/GTAIV.EFLC.FusionFix#388]
### Game version this happens in

v1.2.0.59

### What area of the game

It happens in the second drive of the first mission, after going to the bar. Just follow the gps route and when you get to a certain street (cant remember the name) it crashes. Strangely enough, it doesnt crash if you skip intro and menu and press Escape when the game asks for your Live account: It loads the first mission from the main campaign, and if you start TlaD, it wont crash

### What should happen

The mission should continue as normal. Doesnt crash without fusion fix

### CrashDumps and logs

Crash dump: https://mega.nz/file/Pd9DFb5S#9h4XZLtNhKZBI2y9iq8NHMOkTwvhtsl-WO2Nvz8COAY
Log:
Unhandled exception at 0x00C93BE0 in GTAIV.exe (+0x3be0): 0xC0000005: Access violation writing location 0x00000000.
    Register dump:
        EAX: 0x00000001  EBX: 0x7E204400  ECX: 0xF4B69022  EDX: 0x02C60000  
        EDI: 0x00000000  ESI: 0x1E9C4DB4  EBP: 0x1F261220  EIP: 0x00C93BE0  
        ESP: 0x00BDE5AC  EFL: 0x00210246  
        
        CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   
        ES: 0x0000002B   DS: 0x0000002B   
        
        ST00: 0x00000000 0x80000000 0x0000BF81 0x00000000  [ 0.000000 -0.000000 0.000000 0.000000 ]
        ST01: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        ST02: 0x00000000 0x00000000 0x00000000 0x80000000  [ 0.000000 0.000000 0.000000 -0.000000 ]
        ST03: 0x00000000 0x80808000 0x00003FE6 0x00000000  [ 0.000000 -0.000000 0.000000 0.000000 ]
        ST04: 0x00000000 0x80000000 0x00003FFF 0x00000000  [ 0.000000 -0.000000 0.000000 0.000000 ]
        ST05: 0x00000000 0x80000000 0x00004003 0x00000000  [ 0.000000 -0.000000 0.000000 0.000000 ]
        ST06: 0x00000000 0x80000000 0x00003FFB 0x00000000  [ 0.000000 -0.000000 0.000000 0.000000 ]
        ST07: 0x00000000 0x80000000 0x00003FFB 0x002B0000  [ 0.000000 -0.000000 0.000000 0.000000 ]
        
        XMM00: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM01: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM02: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM03: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM04: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM05: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM06: 0x3F800000 0x00000000 0x00000000 0x00000000  [ 1.000000 0.000000 0.000000 0.000000 ]
        XMM07: 0x4B000000 0x00000000 0x00000000 0x00000000  [ 8388608.000000 0.000000 0.000000 0.000000 ]
        
    Stack dump:
        0x00BDE5AC:  01E86200 BF7BC093 BE2C910B 3D898C92 00000000 3E21F8E2
        0x00BDE5C4:  BF7A5130 BE0CB889 3FC40151 3DB5ECB7 BDFF03C6 3F7CFCD5
        0x00BDE5DC:  00BDE600 C45E00CE 1BD27360 00520045 004F0052 00200052
        0x00BDE5F4:  00520043 005400CD 00430049 0020004F 00450044 00470020
        0x00BDE60C:  00410054 00490020 003A0056 00530020 00430052 00310050
        0x00BDE624:  00000030 00000000 00000000 00000000 00000000 00000000
        0x00BDE63C:  00000000 00000000 00000000 00000000 00000000 00000000
        0x00BDE654:  00000000 00000000 00000000 00000000 00000000 00000000
        0x00BDE66C:  00000000 00000000 00000000 00000000 00000000 00000000
        0x00BDE684:  00000000 00000000 00000000 00000000 00000000 00000000
        base: 0x00AE0000   top: 0x00BDE5AC   bottom: 0x00BE0000
        
    Backtrace (may be wrong):
        =>0x00C93BE0 in GTAIV.exe (+0x3be0) (0x00BDE5A8) 
          0x01E86200 in GTAIV.exe (+0x11f6200) (0x00BDE5AC) 
          0xBF7BC093 in unknown (+0xbf7bc093) (0x00BDE5B0) 
          0xBE2C910B in unknown (+0xbe2c910b) (0x00BDE5B4) 
          0x3D898C92 RelaunchChromeBrowserWithNewCommandLineIfNeeded+0xfda87b in libcef.dll (+0x59f8c92) (0x00BDE5B8) 
        
    

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
That seems like something similar to this: https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/159

Perhaps another sco is somehow responsible.

**Comment by Barveitur** [comment]
Same problem like Sworman14. First mission and second mission in the same gps route: https://www.youtube.com/watch?v=rl2b6rfXU9w Maybe he has the same problem in the same place.

**Comment by ThirteenAG** [comment]
I've asked someone to reproduce, and it doesn't happen. Do you have any other mods, especially sco mods?

**Comment by Barveitur** [comment]
In my case i have the following mods:

- Complete Edition Vehicle Texture Pack
- Rivers of blood v4.3 HD with Realistic Euphoria Ragdoll Overhaul
- Radio Downgrader
- Call of Duty Modern Warfare(2019) weapons sound for GTA 4

Any incompatibility? Is so weird because is only in that place at least for me.

**Comment by Swordman14** [comment]
> I've asked someone to reproduce, and it doesn't happen. Do you have any other mods, especially sco mods?

I used to have the Radio Downgrader as well, but as soon as the crash happened, i deleted it and just reinstalled Fusion Fix. I am now reinstalling the game to try with a clean fusion fix install

**Comment by ThirteenAG** [comment]
Hard to tell with compatibility, shouldn't be a problem, but it's a resource error, not code, so you have to find out which resource.

**Comment by Swordman14** [comment]
> Hard to tell with compatibility, shouldn't be a problem, but it's a resource error, not code, so you have to find out which resource.

No luck, it still crashes in the same part. Any recommendation?

**Comment by ThirteenAG** [comment]
Try to remove img archives inside update folder, see if it changes anything?

**Comment by Tomasak** [comment]
How did you clean your game install? Maybe you have some residues of DXVK or other asi mods, that wont get removed by RGL/Steam when only verifying game cache

**Comment by Swordman14** [comment]
> How did you clean your game install? Maybe you have some residues of DXVK or other asi mods, that wont get removed by RGL/Steam when only verifying game cache

I unistalled the game from steam and deleted the entire folder

**Comment by Barveitur** [comment]
I found the problem. The mod "Radio Downgrader" have his own FusionFix version so when you merge all the folders you're damaging the lastest FusionFix version. In this case, the problem is the Radio Downgrader mod.
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/31813114/f3ee3968-201e-41ad-8f8a-1cc8ff7b99fa)

**Comment by Swordman14** [comment]
> I found the problem. The mod "Radio Downgrader" have his own FusionFix version so when you merge all the folders you're damaging the lastest FusionFix version. In this case, the problem is the Radio Downgrader mod. ![image](https://private-user-images.githubusercontent.com/31813114/294249384-f3ee3968-201e-41ad-8f8a-1cc8ff7b99fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODgzNDMsIm5iZiI6MTcwNDM4ODA0MywicGF0aCI6Ii8zMTgxMzExNC8yOTQyNDkzODQtZjNlZTM5NjgtMjAxZS00MWFkLThmOGEtMWNjOGZmN2I5OWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE3MDcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNzJkNDRmMDg2NmEzNTEzNmM2MTk2MTcxYjcyNmFlZjk1YjY1NDg5YTU5NmZmYjA3MjE0ZmVjZTA0NDA3OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P0gPahHE9_qYL7VeY-PlQ5pKN0Bml5ZIN7cX7phR_o0)

Cant be that, since it crashes without the Radio Downgrader mod as well

**Comment by Swordman14** [comment]
> Try to remove img archives inside update folder, see if it changes anything?

Deleting the GTAiV.EFLC.FusionFix folder (the only folder with img in the update folder) fixes it. It doesnt crash,  but i guess I miss pretty much everything

**Comment by ThirteenAG** [comment]
> > Try to remove img archives inside update folder, see if it changes anything?
> 
> Deleting the GTAiV.EFLC.FusionFix folder (the only folder with img in the update folder) fixes it. It doesnt crash, but i guess I miss pretty much everything

Can you check which one img exactly is causing that? That'd be helpful.

**Comment by Swordman14** [comment]
Alright, been trying a bit more. Looks like disabling the Live account saves and rockstar cloud system fixes it. It doesnt crash anymore

**Comment by ThirteenAG** [comment]
Huh.

**Comment by Swordman14** [comment]
The reason i found out about this crash in the first place is because my save got corrupted and had to start all over again. Maybe that corrputed save screwed with the mod? I dont know

**Comment by SandeMC** [comment]
> How did you clean your game install? Maybe you have some residues of DXVK or other asi mods, that wont get removed by RGL/Steam when only verifying game cache

DXVK is one thing that can't trigger game crashes with a message.

**Comment by Swordman14** [comment]
I experimented a bit more. Turns out, it was the Radio Downgrader mods fault. Using the optional files for no expansion songs in gta iv corrupts your tlad save file: you can save, but not load that save. That corrupted save screws something up: if you have that corrupted save in your files, it will always crash at that same place. Very weird. The solution I found for now, is to use the radio downgrader withouy any of the optional files (and updating its fusion fix, of course)

**Comment by ThirteenAG** [comment]
@Tomasak don't you have some radio restorer that doesn't corrupt saves?

**Comment by SandeMC** [comment]
> I experimented a bit more. Turns out, it was the Radio Downgrader mods fault. Using the optional files for no expansion songs in gta iv corrupts your tlad save file: you can save, but not load that save. That corrupted save screws something up: if you have that corrupted save in your files, it will always crash at that same place. Very weird. The solution I found for now, is to use the radio downgrader withouy any of the optional files (and updating its fusion fix, of course)

Use [this](http://downgraders.rockstarvision.com/) radio downgrader. It has an option for split radios, and I cannot reproduce the issue with that.

**Comment by gramsngrams** [comment]
Can confirm it is the down grader corrupting the save file. Deleted the save file and started new game with down grader still installed and all is well.
