### ISSUE TITLE
Screen Filter is broken if you change DLC's while in-game

### ISSUE THREAD

**Issue by SandeMC** [ThirteenAG/GTAIV.EFLC.FusionFix#391]
### Game version this happens in

v1.2.0.59

### What area of the game

If you go to IV first, then load in a savefile from TBoGT, the screen filter is broken, and changing the setting seems to only apply ontop of the original screen filter somehow?

Loading from IV to TBoGT:

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/70141395/9c360526-7ab0-4d27-ab16-ced755648108

Loading to TBoGT from the start:
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/70141395/a254a1e0-da13-438c-b11c-ceeb3e5dd9bf)

### What should happen

Screen Filter should be reset when loading into a DLC, it seems

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [x] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by MagicAl6244225** [comment]
Can't reproduce the issue. Your second screenshot appears to be a different time of day than your video and the orange color may be due to sunrise.
