### ISSUE TITLE
[Feature Request] Separate VehicleBudget values for base IV and EFLC

### ISSUE THREAD

**Issue by SandeMC** [ThirteenAG/GTAIV.EFLC.FusionFix#395]
### What should happen

If you’re modding the vehicles, you naturally need to increase the vehicle budget to accommodate with vehicles.img value in bytes (also please change the note in the .ini, the number is provides is overexxagerated even; just tell people to set it to the full size of all vehicles loaded in in bytes or anything). Thing is, TBoGT and TLAD have more vehicles (modded and whatnot). So, naturally, you want to increase the budget to accommodate for that too. The problem is that you end up dedicating unnecessary budget to IV that way, as IV itself doesn’t need it (and that creates engine sounds issues) - TBoGT/TLAD do.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by MagicAl6244225** [comment]
The same amount of budget should be fine for all modes because it's not about the size of all assets that exist in the game files but only the amount that are streamed into the player's immediate environment at one time.

What the correct budget amount is will continue to be a subject of experimentation, but the right amount should should be right in all three games. For myself I've settled on a budget of 120000000. YMMV.

**Comment by SandeMC** [comment]
If you set it any lower than the full size of all assets that are in or replace vehicles.img, you will get dupe vehicles in the traffic - sometimes in a row. The budget dedicates how many unique vehicles it can stream into the game from my understanding.

Back to the root of the problem - my vehicle budget which works perfectly for IV (as it's pretty much the size of all modded vehicles), does not work that well for TBoGT. Increasing it makes engine sounds broken more often

**Comment by RecklessGlue540** [comment]
> If you set it any lower than the full size of all assets that are in or replace vehicles.img, you will get dupe vehicles in the traffic - sometimes in a row. The budget dedicates how many unique vehicles it can stream into the game from my understanding.
> 
> Back to the root of the problem - my vehicle budget which works perfectly for IV (as it's pretty much the size of all modded vehicles), does not work that well for TBoGT. Increasing it makes engine sounds broken more often.
> 
> As for why it's specifically vehicles.img - isn't that obvious? Traffic issues become less and less unique the more distant the value is from the size of vehicles.img. Specifically adding files to that img is what causes the problem.
> 
> "should be right for all three games" problem - TBoGT has more vehicles. 

What vehicle density option do you use? Because It plays a big part as well. More vehicles equals more variety as well if budgets are high.
Things are pretty fine with the console defaults which is 33. 
I use 120000000 as well just like MagicAI. I also use the same value for the Ped budget, tho I still get streaming issues from time to time. Probably disabling the ped budget altogether would help me with that.

**Comment by SandeMC** [comment]
> What vehicle density option do you use? Because It plays a big part as well. More vehicles equals more variety as well if budgets are high.
> Things are pretty fine with the console defaults which is 33. 
> I use 120000000 as well just like MagicAI. I also use the same value for the Ped budget, tho I still get streaming issues from time to time. Probably disabling the ped budget altogether would help me with that.

Density plays little part - value's irrelevant to how many vehicles exist in the world, it's how many unique vehicles will actually get loaded in - setting the budget high enough allows every vehicle to spawn at least once. Even if your density is 10 or 100 you'll get the same amount of unique vehicles.

**Comment by Ash-735** [comment]
I have mine set to 144000000 and things work great across everything, being honest if anymore work was going to be put into this in future then it'd be for a better overall solution instead of having to rely on manual numbers being input into an INI, if we ever find a way to to get this process calculated automatically with a high point cap then that would be preferable.

**Comment by MagicAl6244225** [comment]
> If you set it any lower than the full size of all assets that are in or replace vehicles.img, you will get dupe vehicles in the traffic - sometimes in a row. The budget dedicates how many unique vehicles it can stream into the game from my understanding.
> 
> Back to the root of the problem - my vehicle budget which works perfectly for IV (as it's pretty much the size of all modded vehicles), does not work that well for TBoGT. Increasing it makes engine sounds broken more often.
> 
> As for why it's specifically vehicles.img - isn't that obvious? Traffic issues become less and less unique the more distant the value is from the size of vehicles.img. Specifically adding files to that img is what causes the problem.
> 
> "should be right for all three games" problem - TBoGT has more vehicles.

Setting the vehicle budget too high is noted to cause engine sounds to not load or load late, which suggests an oversized vehicle budget reservation squeezes the audio budget that we don't have an adjustment for. Unfortunately there isn't a way to make the whole game use more total memory, so if you set a budget for one thing high enough it will break other things. It makes sense to use the lowest possible vehicle budget that avoids the taxi bug without causing problems.

According to NTAuthority, author of the original RIL.Budgeted mod, the game's default budget is 40000000, which is less than half the file size of default vehicles.img. Realizing that made me reconsider the old advice to match the budget size to file size, and consider that open-world games fundamentally work by streaming in what's needed at the moment and unloading what isn't. You'll never see all of the vehicles in the game at one time. The highest limit of vehicles spawning anywhere at any time, in popcycle.dat, is 72 (combined traffic and parked), which even if there were no duplicates would be fewer than half the models in the game.

72 of 177 total vehicles means, if there were no other limits or exceptions, you could see 40% of the vehicles in the game at once. It so happens the 40MB default budget is about 35% of the combined file sizes of default IV and TBoGT vehicles.img. The consistency of this supports thinking the budget is meant to be based on the most that can happen at one time.

**Comment by SandeMC** [comment]
Interesting.

**Comment by Otheucarvalho** [comment]
I have mine set to 144000000 and things work great across everything too


> I have mine set to 144000000 and things work great across everything, being honest if anymore work was going to be put into this in future then it'd be for a better overall solution instead of having to rely on manual numbers being input into an INI, if we ever find a way to to get this process calculated automatically with a high point cap then that would be preferable.
