### ISSUE TITLE
[Feature Request] Adding “New” and “Load” buttons to the title screen (or its options)

### ISSUE THREAD

**Issue by SandeMC** [ThirteenAG/GTAIV.EFLC.FusionFix#396]
### What should happen

Sometimes when testing mods, I want to start a new TLAD or TBoGT game (for example). Problem is, I have to load into a save file via the start button first to actually have access to the load menu. Any way to implement it here? (addition to https://github.com/GTAmodding/GTAIV-Issues-List/issues/123)

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by Tomasak** [comment]
you already asked for it here #331

**Comment by SandeMC** [comment]
oh jeez what's with me lately

sorry 🙏
