### ISSUE TITLE
[Feature Request] "Multiplayer" & "Do not pause when unfocused"

### ISSUE THREAD

**Issue by AliceTS1337** [ThirteenAG/GTAIV.EFLC.FusionFix#40]
Let's start with the more simple request, I'd like to have the game keep running in the background even if I'm alt+tabbed while in borderless windowed. 

As for the more advanced request;
For a while now, I've been wanting to re-enable multiplayer and to create my own sort of "unofficial social club backend" that would deal with multiplayer storage data, such as lobby data, ranked data and player data. The more I worked on this, the more I realized that Rockstar actually did seem to attempt to officially enable multiplayer, on their own social club services. There are so many strings in the game that show evidence of this, as well as having pretty much full Social Club integration to the game where even my in-game name (when launching into a MP game via LAN) will be my Social Club name. Seeing as Rockstar didn't proceed with this development and just removing the multiplayer options from the phone entirely, I decided I'd try and make my own data server. However, due to my lack of networking skills, I might not be able to properly fulfill this task.

So I'm here, to ask the professionals instead. Would you be interested in re-enabling multiplayer, as well as to create a backend server to deal with the networking and data required to get multiplayer to work again? I firmly believe there are a lot of people wanting this, and making use of the already existing Social Club integration would be neat and seamless, as if it was official. It'd also prevent pirates from playing multiplayer as you'd need to have a SC account, as well as owning the game in order to access Multiplayer.

While I'm aware that this request may seem crazy, I'm willing to ask either way, for the community.

**Comment by prototype464** [comment]
+1 on the suggestion of multiplayer, this is needed!
