### ISSUE TITLE
Please help my gta 4 is not opening

### ISSUE THREAD

**Issue by nehighborGOD** [ThirteenAG/GTAIV.EFLC.FusionFix#401]
### Game version this happens in

v1.2.0.59

### What area of the game

the game is not opening

### What should happen

game should open

### CrashDumps and logs

[GTAIV.exe.20240101154933.dmp](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13890616/GTAIV.exe.20240101154933.dmp)
[GTAIV.exe.20240101154933.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13890617/GTAIV.exe.20240101154933.log)
[GTAIV.exe.20240101155823.dmp](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13890618/GTAIV.exe.20240101155823.dmp)
[GTAIV.exe.20240101155823.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13890619/GTAIV.exe.20240101155823.log)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
Crash dumps are not from v1.2.0.59, closing.

**Comment by nehighborGOD** [comment]
> Crash dumps are not from v1.2.0.59, closing.

bro idk what version i have but when i install your patch it dont work help me please

**Comment by nehighborGOD** [comment]
> Crash dumps are not from v1.2.0.59, closing.

and i just search a patch too because when i install a lower version of 2.0 the game open but your patch dont work idk if thats the problem but please help me brother

**Comment by nehighborGOD** [comment]
> > > Crash dumps are not from v1.2.0.59, closing.
> > 
> > 
> > and i just search a patch of 1.0.0.7 because when i install a lower version of 2.0 the game open but your patch dont work idk if thats the problem but please help me brother
> 
> Is your copy legal? Like Steam or RGL? You may be suffering from [this issue](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/355) then...
yea my copy is legal but my open after i put the patch and that mod of the 1.0.0.7

**Comment by nehighborGOD** [comment]
> > > Crash dumps are not from v1.2.0.59, closing.
> > 
> > 
> > and i just search a patch of 1.0.0.7 because when i install a lower version of 2.0 the game open but your patch dont work idk if thats the problem but please help me brother
> 
> Is your copy legal? Like Steam or RGL? You may be suffering from [this issue](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/355) then...

i can share you that mod if you want to see
