### ISSUE TITLE
Giving cash to buskers will cause the phone to become unusable until entering certain buildings.

### ISSUE THREAD

**Issue by HAYASHIDASEIYAKU** [ThirteenAG/GTAIV.EFLC.FusionFix#405]
### Game version this happens in

v1.2.0.59

### What area of the game

All entertainers, not beggars.

The interaction keys are malfunctioning.

### What should happen

It can be used after the interaction.
PS:If possible, can you change the direction of the throw so that it is thrown in front of the character?

### Last working version

2.4.7

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Tomasak** [comment]
vanilla bug, please reopen issue here: https://github.com/GTAmodding/GTAIV-Issues-List/issues
