### ISSUE TITLE
Had to downgrade to 1.0.7.0 to get this to work

### ISSUE THREAD

**Issue by pqraz** [ThirteenAG/GTAIV.EFLC.FusionFix#41]
I did a fresh steam install of GTA 4 complete edition with patch 1.2.0.43 and installed FusionFix. I had expected it to work as the installation guide says 'Install Grand Theft Auto IV Complete Edition (v1.2.0.30 and above required)' but FusionFix wasn't working at all so I was pretty confused. I had to downgrade to 1.0.7.0 using this guide 
https://steamcommunity.com/sharedfiles/filedetails/?id=2438808634
To get FusionFix to work. I think the installation guide should be changed given this.

**Comment by pqraz** [comment]
I just realized there is this version of fusion fix
https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/blob/pre-ivce/readme.md
This is probably the version included in the downgrader I linked above.
Still, I dont think the version of fusionfix for 'v.1.2.0.30 and above' works on the latest version - 1.2.0.43.

**Comment by snowboundmage2** [comment]
Can confirm, latest fusionfix don't work on latest gta4, aka 1.2.0.43

**Comment by pqraz** [comment]
Hey I originally posted this but closed it after trying it on a clean install and having it successfully work (on the latest gta 4 downloaded through steam). You might have other mods installed causing an incompatibility.
