### ISSUE TITLE
Slowdowns on loading screens

### ISSUE THREAD

**Issue by oregano12** [ThirteenAG/GTAIV.EFLC.FusionFix#410]
### Game version this happens in

v1.2.0.30

### What area of the game

I played most of the game using FusionFix 2.4.2 without facing any problem, but after updating to version 2.4.8 I started having issues with the load screens. Basically the load bar will now move much slower than it should and the game will take a few more seconds to load then it did before I updated FusionFix.

### Your Hardware configuration

CPU: Intel i7-8750H 2.20GHz, 2208 Mhz
16GB RAM
GPU: GTX 1060 6GB

### Game capture

When loading a game from the main menu:
https://streamable.com/gx78m4

When starting a new game:
https://streamable.com/knmedt

### Last working version

2.4.2

### Graphics backend (3D API)

DXVK

### Any other notes or things you've tried

Another issue I got after updating to FusionFix 2.4.8 is that Niko will also write his response e-mails much slower, painfully slow in fact. I only got to see this issue one time and unfortunately I couldn't get a recording, will see about opening a new issue for this if I manage to capture the issue.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the slowdown.

**Comment by RecklessGlue540** [comment]
> Basically the load bar will now move much slower than it should

This is intended. It's supposed to be a fix for the absurd loading bar speeds. It's still incomplete tho... As it moves very slow...

For the other two issues, which are loading being a bit slower, and frame rate tanking when writing emails, can you please try using the latest FusionFix version 2.4.9 with 1.2.0.59? I think those are both fixed now.

**Comment by oregano12** [comment]
Thanks for the fast response. Got version 2.4.9 and can confirm the e-mail issue has been solved. Loading still seems a bit inconsistent but its definitely much better than before.

**Comment by RecklessGlue540** [comment]
> Thanks for the fast response. Got version 2.4.9 and can confirm the e-mail issue has been solved. Loading still seems a bit inconsistent but its definitely much better than before.

Yeah, leaving the UnlockFramerateDuringLoadscreens enabled will improve load times it seems...

**Comment by ThirteenAG** [comment]
Latest version has softlocking workaround isolated to only when it happens, so the rest of loading times and whatnot should be the same as before.
