### ISSUE TITLE
game crash on startup after updating fusionfix to latest version

### ISSUE THREAD

**Issue by Hugs288** [ThirteenAG/GTAIV.EFLC.FusionFix#411]
### Game version this happens in

v1.2.0.59

### What area of the game

loading screen "loading - portrait of a killer" then crashes

in the latest git build it doesnt even reach the black loading screen

edit: i just tried to update again after finishing portrait of the killer and it wont even make it to the black loading scree now

### What should happen

shouldnt crash

### CrashDumps and logs

[GTAIV.exe.20240119185739.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13991070/GTAIV.exe.20240119185739.log)

crashdump is too large for github upload

### Last working version

im not 100% sure, but it was downloaded december 27

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
Then upload crashdump elsewhere and post a link to it. Just the log is not at all useful.

**Comment by RecklessGlue540** [comment]
> ### Game version this happens in
> v1.2.0.59
> 
> ### What area of the game
> loading screen "loading - portrait of a killer" then crashes
> 
> in the latest git build it doesnt even reach the black loading screen
> 
> edit: i just tried to update again after finishing portrait of the killer and it even make it to the black loading scree now
> 
> ### What should happen
> shouldnt crash
> 
> ### CrashDumps and logs
> [GTAIV.exe.20240119185739.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13991070/GTAIV.exe.20240119185739.log)
> 
> crashdump is too large for github upload
> 
> ### Last working version
> im not 100% sure, but it was downloaded december 27
> 
> ### Checklist
> * [x]  Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
> * [x]  [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
> * [x]  Include logs or screenshots of issue.

Please test with a newer build. Could have been fixed for all we know...

**Comment by Hugs288** [comment]
https://drive.google.com/file/d/1t5eo8aU5PQwY9BGbg2Yp-FDm9GJN5Ma_/view?usp=sharing

here is the dump file

**Comment by Hugs288** [comment]
@RecklessGlue540 i tried with the latest git version also

**Comment by ThirteenAG** [comment]
https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/v6.7.0/Ultimate-ASI-Loader.zip
https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/v6.6.0/Ultimate-ASI-Loader.zip

Replace dinput8.dll with one of these, does it work that way?

**Comment by wmrichard** [comment]
Thanks for your reply. I also had this issue.  I am using Steam Deck with Steam OS. Version 2.4.9 and 2.5.0 broke things for me, last version that worked was 2.4.8. I am able to use the current latest version ( 2.5.0 ) with the Ultimate-ASI-Loader 6.7.0.

**Comment by ThirteenAG** [comment]
> Thanks for your reply. I also had this issue. I am using Steam Deck with Steam OS. Version 2.4.9 and 2.5.0 broke things for me, last version that worked was 2.4.8. I am able to use the current latest version ( 2.5.0 ) with the Ultimate-ASI-Loader 6.7.0.

Can you upload crash dump as well?

**Comment by wmrichard** [comment]
[GTAIV.exe.20240120155635.dmp](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13998311/GTAIV.exe.20240120155635.dmp)
[GTAIV.exe.20240120155635.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13998312/GTAIV.exe.20240120155635.log)


Sure, this is the CrashDump when using 2.5.0 with the shipped Ultimate-Asi-Loader version.

**Comment by ThirteenAG** [comment]
I'm not sure what's happening, crash dump shows the game crashing, not asi loader. Can you try this version and see if it's working with it?
[dinput8.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13998352/dinput8.zip)

**Comment by wmrichard** [comment]
> I'm not sure what's happening, crash dump shows the game crashing, not asi loader. Can you try this version and see if it's working with it? [dinput8.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13998352/dinput8.zip)

Game is running fine with this version.

**Comment by ThirteenAG** [comment]
[dinput8.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13998398/dinput8.zip)
What about this?

**Comment by ThirteenAG** [comment]
Weird, it's because I removed this condition:
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/4904157/514d9dde-81be-41cd-83e2-628c6f738199)

Which doesn't cause any problems on windows, but somehow breaks on linux. I will add symlinks to this check and update the release.

**Comment by ThirteenAG** [comment]
> Also working.

Can you also clarify what's inside your update folder? I just tried to reproduce and it doesn't happen to me.

**Comment by ThirteenAG** [comment]
I just don't understand what passes `exists` check, but fails `is_file` or `is_symlink` check.

**Comment by ThirteenAG** [comment]
Well, only one way to find out: 
[dinput8.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13998573/dinput8.zip)
I switched the condition to not is_directory.

**Comment by ThirteenAG** [comment]
So it is a folder with extension, huh.

**Comment by ThirteenAG** [comment]
Oh, that makes sense actually. If the game tried to open this script.img file, and finds a folder instead, `exists` check will return true.
And then it won't open real script.img, and also will fail to open script.img folder inside update, leading to crash.

**Comment by Hugs288** [comment]
hi, im just about to try the dinput files

i am using windows

**Comment by Hugs288** [comment]
> https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/v6.7.0/Ultimate-ASI-Loader.zip https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/v6.6.0/Ultimate-ASI-Loader.zip
> 
> Replace dinput8.dll with one of these, does it work that way?

version 6.7.0 seems to works fine

**Comment by ThirteenAG** [comment]
Do you have a folder named as one of the files as well?

**Comment by Hugs288** [comment]
what files?

**Comment by ThirteenAG** [comment]
>  I have the following folder: /update/common/data/cdimages/script.img . This folder is empty, note script.img is a folder.

The crash is fixed, I'm just trying to see if you have the same thing here. Instead of a file inside update folder, there's a folder inside update folder named exactly as the file.

**Comment by Hugs288** [comment]
there are 2 folders in my cdimages folder, they are named script.img and scripts.img

**Comment by ThirteenAG** [comment]
I see, so all good now.

**Comment by Hugs288** [comment]
great, thanks you for the quick response and keeping this amazing game alive :)

im guessing you will upload a fixed version soon?

**Comment by ThirteenAG** [comment]
Already uploaded!
