### ISSUE TITLE
[Feature Request] Borderless Fullscreen mode and Do Not Pause On Minimize with a separated Constrain Mouse Pointer setting

### ISSUE THREAD

**Issue by RecklessGlue540** [ThirteenAG/GTAIV.EFLC.FusionFix#412]
### What should happen

I think these are essential things to have nowadays....
The existing Do Not Pause On Minimize command doesn't work properly in all cases / or it is outright broken lol... 
It'd be ideal if we had an option for this in the menu, along with a separate Constrain Mouse Pointer option like in RDR2... (since I've heard the game still locks the cursor into the window even with -noBlockOnLostFocus command).

Borderless Fullscreen is also essential if we want to play the game in a native 1080p resoultion on a 4k display for example. Also for latency reduction purposes by leaving VSync completely disabled. (Mainly for Windows 11 Users)
Furthermore, the Display modes could be merged into one "Display Mode" setting like in Max Payne 3, RDR2 or GTAV...

Max Payne 3's FusionFix could also benefit from these features....

Feel free to close if these are not possible / feasible. The only game I've seen to date, that has Borderless Fullscreen as an option is the recent Like A Dragon Gaiden: The Man Who Erased His Name... And that has a brilliant PC port but also has newer technology, obviously.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
> You don't want Borderless anything for Dx9 games. It adds a lot of latency. Because DirectFlip is only supported for Dx10 & newer.

Well, borderless windowed is already there...
Is DirectFlip for borderless fullscreen specifically?

**Comment by lextra2** [comment]
> Does Borderless Fullscreen absolutely require DirectFlip to work?
No. But DirectFlip is needed to get Borderless Fullscreen to work with the same low latency of Exclusive Fullscreen.

**Comment by RecklessGlue540** [comment]
> No. But DirectFlip is needed to get Borderless Fullscreen to work with the same low latency of Exclusive Fullscreen.

Yeah, well, Max Payne 3's FF could still have it then...
