### ISSUE TITLE
[Bug] Specific building fades out weirdly [Fixed by starting new savegame but motion blur is weird and shadows]

### ISSUE THREAD

**Issue by MOnkeMan5009** [ThirteenAG/GTAIV.EFLC.FusionFix#413]
### Game version this happens in

v1.2.0.59

### What area of the game

The bridge to the top of the map, where you go from the poor small island area to the middle island, the one where near playboy mansion is

### What should happen

The building fades out weirdly while others dont i think its just a specific one. I havent noticed anything else besides that, and first time to happen now. Did a clean reinstall, and added fusionfix and variousfixes thats all. 

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/157163279/5fbe5e76-57f3-49da-9836-b500b2a0ab1a

### CrashDumps and logs

None

### Last working version

v2.0 didn't have this issue from what i remember

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Tomasak** [comment]
might be save game corruption seeing the black smoke there. Try either new game (preferably flushing all save games) or dling some save game from gtasnp and try on that.
I myself cant reproduce this.

**Comment by MOnkeMan5009** [comment]
> might be save game corruption seeing the black smoke there. Try either new game (preferably flushing all save games) or dling some save game from gtasnp and try on that. I myself cant reproduce this.

Yep thanks, that completely fixed it, started a new game. But the question is, will always have to start a new game whenever huge updates to fusionfix will arrive?

**Comment by RecklessGlue540** [comment]
> > might be save game corruption seeing the black smoke there. Try either new game (preferably flushing all save games) or dling some save game from gtasnp and try on that. I myself cant reproduce this.
> 
> Yep thanks, that completely fixed it, started a new game. But the question is, will always have to start a new game whenever huge updates to fusionfix will arrive?

Likely... Depends on the features...

**Comment by MOnkeMan5009** [comment]
> > > might be save game corruption seeing the black smoke there. Try either new game (preferably flushing all save games) or dling some save game from gtasnp and try on that. I myself cant reproduce this.
> > 
> > 
> > Yep thanks, that completely fixed it, started a new game. But the question is, will always have to start a new game whenever huge updates to fusionfix will arrive?
> 
> Likely... Depends on the features...

Since you're here, i did the rivatuner stuff and capped at  60, but motion blur is still the same, shadows and sirens ig..i noticed police siren looks a bit weird from the side, was this always how it was meant to be?


https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/157163279/731b127c-4b00-406e-ba93-30b7ce95dd0f

**Comment by Tomasak** [comment]
FusionFix doesnt touch files that could potentionally break save games. You could have used other mods that touch map files in past, Various fixes broke saves in past iirc. Same goes for colaccel
As for other bugs, please first compare with game without fusionfix installed and then open new issue here if its cause by fusion fix, or open issue in https://github.com/GTAmodding/GTAIV-Issues-List/issues if it happens in vanilla
