### ISSUE TITLE
Jagged edges when moving ingame 

### ISSUE THREAD

**Issue by okwannabe** [ThirteenAG/GTAIV.EFLC.FusionFix#414]
### Game version this happens in

v1.2.0.59

### What area of the game

pretty much every time when moving in game , the lamp posts are jagged and not smooth.

### What should happen

jagged edges should be fixed if at all possible.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Ash-735** [comment]
What AA option are you using?

**Comment by okwannabe** [comment]
> What AA option are you using?

smaa and aa at 16x

**Comment by Im-Kan** [comment]
@okwannabe how do you fix it?
