### ISSUE TITLE
[Bug] Shadows disspearing 

### ISSUE THREAD

**Issue by MOnkeMan5009** [ThirteenAG/GTAIV.EFLC.FusionFix#415]
### Game version this happens in

v1.2.0.59

### What area of the game

Any area with buildings preferably

### What should happen

Going further away with no clip for example makes shadows disspear way too early from the player and it looks a bit weird, also a lot of poppings and late-texture loading. I dont remember this being on 2.0 or 1.9

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/157163279/bdce4b36-fcb1-4c14-87f3-dfe58ec5097b

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/157163279/3763fb21-20ef-42dc-b2e1-f1c894a2adb7

### Last working version

v1.9-2.0

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by RecklessGlue540** [comment]
> ### Game version this happens in
> v1.2.0.59
> 
> ### What area of the game
> Any area with buildings preferably
> 
> ### What should happen
> Going further away with no clip for example makes shadows disspear way too early from the player and it looks a bit weird, also a lot of poppings and late-texture loading. I dont remember this being on 2.0 or 1.9
> 
>  8mb.video-8tS-svYchRf4.mp4 
>  8mb.video-C4f-A30WJt6O.mp4 
> ### CrashDumps and logs
> _No response_
> 
> ### Last working version
> v1.9-2.0
> 
> ### Checklist
> * [x]  Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
> * [x]  [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
> * [x]  Include logs or screenshots of issue.

This is intended. Shadow distance cannot be increased without introducing major issues, so a custom fading system was applied to them instead.

**Comment by MOnkeMan5009** [comment]
> > ### Game version this happens in
> > v1.2.0.59
> > ### What area of the game
> > Any area with buildings preferably
> > ### What should happen
> > Going further away with no clip for example makes shadows disspear way too early from the player and it looks a bit weird, also a lot of poppings and late-texture loading. I dont remember this being on 2.0 or 1.9
> > 8mb.video-8tS-svYchRf4.mp4
> > 8mb.video-C4f-A30WJt6O.mp4
> > ### CrashDumps and logs
> > _No response_
> > ### Last working version
> > v1.9-2.0
> > ### Checklist
> > 
> > * [x]   Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
> > * [x]   [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
> > * [x]   Include logs or screenshots of issue.
> 
> This is intended. Shadow distance cannot be increased without introducing major issues, so a custom fading system was applied to them instead.

okay..altho i am pretty sure this didn't happen in previous fusionfix versions..anyway, what about the buildings disspearing and poppings? i am very sure that didnt happen before.. even had a whole thread about it for a specific building

**Comment by RecklessGlue540** [comment]
> okay..altho i am pretty sure this didn't happen in previous fusionfix versions..anyway, what about the buildings disspearing and poppings? i am very sure that didnt happen before.. even had a whole thread about it for a specific building

I'm pretty sure that's the game's VRAM manager. This is done for optimization reasons and cannot be changed. Usually happens when looking back. Consoles do the same... you could maybe try putting -nomemrestrict in a commandline and see if it does anything...
The shadows do the same for some reason and those are not intended to pop in when instantly looking back. Been that way since at least 1060, and it is yet to be fixed.

**Comment by MOnkeMan5009** [comment]
> > okay..altho i am pretty sure this didn't happen in previous fusionfix versions..anyway, what about the buildings disspearing and poppings? i am very sure that didnt happen before.. even had a whole thread about it for a specific building
> 
> I'm pretty sure that's the game's VRAM manager. This is done for optimization reasons and cannot be changed. Usually happens when looking back. Consoles do the same... you could maybe try putting -nomemrestrict in a commandline and see if it does anything... The shadows do the same for some reason and those are not intended to pop in when instantly looking back. Been that way since at least 1060, and it is yet to be fixed.

hmm i still believe some stuff was better in previous versions...anyway. Do you know at least the fix for that disspearing building?

**Comment by MOnkeMan5009** [comment]
https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/157163279/70d88f40-ba5f-4b92-b7d5-7fad845d78a6

Also look at this, do you know how to fix this while using motion blur? even without look how the shadow of the car at the back flickers weirdly @RecklessGlue540

**Comment by RecklessGlue540** [comment]
> 8mb.video-qje-pWKtGWWh.mp4 
> Also look at this, do you know how to fix this while using motion blur? even without look how the shadow of the car at the back flickers weirdly @RecklessGlue540

This is because the game stutters. For some reason, these effects depend on the frame times...
I don't have it on my RX 6700 now. Tho I did have it on my old GTX 1060 3GB...
You could try capping your frames and see if fixes anything. Also cap your frames through RivaTuner.

**Comment by MOnkeMan5009** [comment]
> > 8mb.video-qje-pWKtGWWh.mp4
> > Also look at this, do you know how to fix this while using motion blur? even without look how the shadow of the car at the back flickers weirdly @RecklessGlue540
> 
> This is because the game stutters. For some reason, these effects seem to depend on the frame times... I don't have it on my RX 6700 now. Tho I did have it on my old GTX 1060 3GB... You could try capping your frames and see if fixes anything. Also cap your frames through RivaTuner.

well i have it capped at 60 through the in game menu, should i do that with rivatuner as well? i am running 4k 144hz

**Comment by RecklessGlue540** [comment]
Rivatuner locks it better. Caps frame times as well

**Comment by MOnkeMan5009** [comment]
> Rivatuner locks it better. Caps frame times as well

and do i have to run it everytime? or i can just set it once and done?

**Comment by RecklessGlue540** [comment]
Just set a profile for gtaiv.exe and cap at 60.

**Comment by MOnkeMan5009** [comment]
I did, however the shadow thingy is still there not sure if its intended, sirens are affected by it too, the cop siren of the car u driving

**Comment by RecklessGlue540** [comment]
> I did, however the shadow thingy is still there not sure if its intended, sirens are affected by it too, the cop siren of the car u driving

How do the sirens look?
The shadows gradually fading in is intended. Their [pop-in when looking back pressing C](https://gtaforums.com/topic/990300-gta-iv-weird-shadows-behaviour-in-1080-and-not-present-in-1040/) is not however.

**Comment by MOnkeMan5009** [comment]
> > I did, however the shadow thingy is still there not sure if its intended, sirens are affected by it too, the cop siren of the car u driving
> 
> How do the sirens look? The shadows gradually fading in is intended. Their [pop-in when looking back pressing C](https://gtaforums.com/topic/990300-gta-iv-weird-shadows-behaviour-in-1080-and-not-present-in-1040/) is not however.


https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/157163279/6863bb8a-4365-4726-b784-6988b3897fde

this is how. Look at the sirens

**Comment by MOnkeMan5009** [comment]
Also hope that C bug will get fixed eventually

**Comment by RecklessGlue540** [comment]
> > > I did, however the shadow thingy is still there not sure if its intended, sirens are affected by it too, the cop siren of the car u driving
> > 
> > 
> > How do the sirens look? The shadows gradually fading in is intended. Their [pop-in when looking back pressing C](https://gtaforums.com/topic/990300-gta-iv-weird-shadows-behaviour-in-1080-and-not-present-in-1040/) is not however.
> 
>  8mb.video-9nF-ljooA4MC.mp4 
> this is how. Look at the sirens

Pretty sure everything "moving" is affected...
Have you tried MSI afterburner and Riva btw?

**Comment by MOnkeMan5009** [comment]
> > > > I did, however the shadow thingy is still there not sure if its intended, sirens are affected by it too, the cop siren of the car u driving
> > > 
> > > 
> > > How do the sirens look? The shadows gradually fading in is intended. Their [pop-in when looking back pressing C](https://gtaforums.com/topic/990300-gta-iv-weird-shadows-behaviour-in-1080-and-not-present-in-1040/) is not however.
> > 
> > 
> > 8mb.video-9nF-ljooA4MC.mp4
> > this is how. Look at the sirens
> 
> Pretty sure everything "moving" is affected... Have you tried MSI afterburner and Riva btw? I can see some stutters in the video above...

Yes i have, and i locked it to 60 fps. if there was any stutter at the beginning thats how shadowplay does when its hooked to record ig

**Comment by Parallellines0451** [comment]
None of these issues are caused by FF, they are all vanilla.

- Shadow draw distance is indeed quite low in GTA IV
- Building "pop-in" is due to the game's limited streaming budget
- Motion blur stuttering is caused by unstable frametimes
- Police car lights and glass materials in general are affected by motion blur because they don't write to the stencil buffer

You should not set the view & detail distance sliders to 100 as that causes extreme pop-in issues, I recommend at most 32/70.
If you can't keep stable frametimes you should disable motion blur or possibly look into using DXVK.

**Comment by MOnkeMan5009** [comment]
> None of these issues are caused by FF, they are all vanilla.
> 
> * Shadow draw distance is indeed quite low in GTA IV
> * Building "pop-in" is due to the game's limited streaming budget
> * Motion blur stuttering is caused by unstable frametimes
> * Police car lights and glass materials in general are affected by motion blur because they don't write to the stencil buffer
> 
> You should not set the view & detail distance sliders to 100 as that causes extreme pop-in issues, I recommend at most 32/70. If you can't keep stable frametimes you should disable motion blur or possibly look into using DXVK.

hmm, and can it be possible technically to increase those limits? I know some gta 5 mod that after quite a long time achieved to do that for disspearing textures when game was modded too much, being implemented from FiveM. Just as an example. Anyway, hope stuff like distances and limits could be increased in the future

**Comment by RecklessGlue540** [comment]
> > None of these issues are caused by FF, they are all vanilla.
> > 
> > * Shadow draw distance is indeed quite low in GTA IV
> > * Building "pop-in" is due to the game's limited streaming budget
> > * Motion blur stuttering is caused by unstable frametimes
> > * Police car lights and glass materials in general are affected by motion blur because they don't write to the stencil buffer
> > 
> > You should not set the view & detail distance sliders to 100 as that causes extreme pop-in issues, I recommend at most 32/70. If you can't keep stable frametimes you should disable motion blur or possibly look into using DXVK.
> 
> hmm, and can it be possible technically to increase those limits? I know some gta 5 mod that after quite a long time achieved to do that for disspearing textures when game was modded too much, being implemented from FiveM. Just as an example. Anyway, hope stuff like distances and limits could be increased in the future

First two, probably not...
Third one... It was made so that it scales properly with the framerate. The "jitter" is a side effect..
Fourth one.. there was an attempt to fix it, but fixing it introduced other issues so thats likely how it's going to stay, unfortunately.
