### ISSUE TITLE
setting menu crashes game 

### ISSUE THREAD

**Issue by charlesmckee47** [ThirteenAG/GTAIV.EFLC.FusionFix#416]
### Game version this happens in

v1.2.0.59

### What area of the game

get an error about not logging in and then load into the game and try to go to setting and the game crashes after entering a sub menu 

### What should happen

it shouldn't crash

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by charlesmckee47** [comment]
cant find log files

**Comment by RecklessGlue540** [comment]
Steam or RGL? Have you tried creating a CrashDumps folder?

**Comment by charlesmckee47** [comment]
rgl and no and im not able to use task manger as it crashes too fast

**Comment by charlesmckee47** [comment]
also no on making folder

**Comment by charlesmckee47** [comment]
[GTAIV.exe.20240120165125.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13999295/GTAIV.exe.20240120165125.log)

**Comment by RecklessGlue540** [comment]
Provide the .dmp as well. 
I use the RGL version myself and have no issues whatsoever.

**Comment by charlesmckee47** [comment]
https://drive.google.com/drive/folders/1I8qxDjF0LEbKW-T1XZHA0X5LBCo8vqww?usp=drive_link here is dmp

**Comment by ThirteenAG** [comment]
The link doesn't work. You can attach minidump here inside zip archive.

**Comment by charlesmckee47** [comment]
[
[Uploading GTAIV.exe.20240120165125.zip…]()
](url)

**Comment by charlesmckee47** [comment]
[GTAIV.exe.20240120165125.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14000920/GTAIV.exe.20240120165125.zip) here is the dmp

**Comment by ThirteenAG** [comment]
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14001294/GTAIV.EFLC.FusionFix.zip)

Check this build, does it fix the problem? If not, upload a new dump with this build.

**Comment by charlesmckee47** [comment]
that seems to have fixed it

**Comment by ThirteenAG** [comment]
Kindly asking to recheck with latest v2.5.2.

**Comment by charlesmckee47** [comment]
2.5.2 is working now in menu not crashing the game

**Comment by ThirteenAG** [comment]
Alright, thanks.

**Comment by MOnkeMan5009** [comment]
> Alright, thanks.

Hey, not sure but it worked for some time, but it once has crashed when fast scrolling through the options rapidly to Graphics menu, most of the time like 70% seems to not crash, but has its moments. Can you test again? For me it crashed

**Comment by ThirteenAG** [comment]
> Hey, not sure but it worked for some time, but it once has crashed when fast scrolling through the options rapidly to Graphics menu, most of the time like 70% seems to not crash, but has its moments. Can you test again? For me it crashed

Then provide a crash dump, what's the point in guessing?

**Comment by MOnkeMan5009** [comment]
> > Hey, not sure but it worked for some time, but it once has crashed when fast scrolling through the options rapidly to Graphics menu, most of the time like 70% seems to not crash, but has its moments. Can you test again? For me it crashed
> 
> Then provide a crash dump, what's the point in guessing?

[GTAIV.exe.20240123155814.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14026733/GTAIV.exe.20240123155814.log)
[GTAIV.exe.20240123150229.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14026743/GTAIV.exe.20240123150229.log)

DMP's : https://drive.google.com/file/d/1trvWS7cUCWH6EQcd3J2PBvq59yQ62Yse/view?usp=sharing

I sent 2 logs because i noticed i had them like 30 minutes gap between them, so thought i may send both, but i know for sure on one of them game crashed when went to Graphics menu

**Comment by MOnkeMan5009** [comment]
> Those are not from complete edition, and you have other incompatible plugins, so no wonder it doesn't work.

Which incompatible plugins? Also i didn't say it doesn't completely work, for now it has, but gotten 1 crash when switched to graphics menu. i only have a trainer and project 2dfx, the rest is fusion and variousfixes
