### ISSUE TITLE
Game crashes when scrolling through options at "Graphics" Menu

### ISSUE THREAD

**Issue by MOnkeMan5009** [ThirteenAG/GTAIV.EFLC.FusionFix#418]
### Game version this happens in

v1.2.0.59

### What area of the game

Pause menu - graphics menu

### What should happen

Getting to the main game works n all but when i press ESC and select the graphics menu it crashes. It doesn't crash when you just click on it, it crashes when you scroll through it, like from audio - display - graphics, then it crashes

### CrashDumps and logs

[GTAIV.exe.20240121170918.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14001768/GTAIV.exe.20240121170918.log)

https://drive.google.com/file/d/11Y-_T8qk8gsLtouvjziDGNg-YC_CbfoZ/view?usp=sharing DMP

### Last working version

Last i tested was around 1.9 or 2.0  either way, before this one

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/416#issuecomment-1902614060

**Comment by ThirteenAG** [comment]
Crash dump is not v1.2.0.59, and the asi is not even downloaded from this repo, closing.
