### ISSUE TITLE
Truck Hustle QTE on high Framerates

### ISSUE THREAD

**Issue by sammy2142** [ThirteenAG/GTAIV.EFLC.FusionFix#419]
### Game version this happens in

v1.2.0.59

### What area of the game

There's another quick time event on the Truck Hustle mission where you have to mash the spacebar to get on the back of the truck. Like the heli QTE, having a high fps messes with the timing and becomes difficult/impossible to complete.

### What should happen

Should be playable on high framerates

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by juicermv** [comment]
How high of a framerate are we talking about? My game runs at 70-90 fps and the QTE works fine for me

**Comment by RecklessGlue540** [comment]
QTEs are generally affected by high framerates, tho vanilla game issues are best reported here: https://github.com/GTAmodding/GTAIV-Issues-List/issues

Or better yet, I think I'll just add this to the [frame rate issues list](https://github.com/GTAmodding/GTAIV-Issues-List/issues/112)

**Comment by RecklessGlue540** [comment]
Updated the list. This issue can be closed.
