### ISSUE TITLE
[Feature Request] Add an apply option to each new graphical setting

### ISSUE THREAD

**Issue by RecklessGlue540** [ThirteenAG/GTAIV.EFLC.FusionFix#423]
### What should happen

Yeah... title basically.
It's a good quality of life improvement imo.
Of course, when a solution is found. Heard it's not possible yet.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by hammerfist11** [comment]
so instead of automatically changing, you click apply? Wouldn't that just add an extra step?

**Comment by RecklessGlue540** [comment]
> so instead of automatically changing, you click apply?

Yes.

> Wouldn't that just add an extra step?

I mean, it's closer and more accurate to how the game does it, and a lot of other games do this...
