### ISSUE TITLE
[Feature Request] Correct reflection projection/parallax 

### ISSUE THREAD

**Issue by juicermv** [ThirteenAG/GTAIV.EFLC.FusionFix#424]
### What should happen

In GTA IV, the reflection cubemap for buildings is captured from the camera's position, which causes incorrect reflections and artifacts. This can be seen on basically any building, where as you move closer to it the reflections get more accurate since the camera is basically at its position, but as you get further away the reflection starts to get messed up, usually causing the building to be reflected within itself. In general this causes buildings to reflect things they shouldn't like objects close to the player.

I think this is one of the glaring issues with the game, I'm not sure how this could be fixed exactly. Maybe somehow offset the building's position from the camera's when doing the reflection pass in the shader?

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
Quite annoying, yes. I support this.

**Comment by juicermv** [comment]
Yeah it's a technique they used in multiple games

**Comment by Otheucarvalho** [comment]
I understand you. It is true that the reflections in the game are not very detailed and only the buildings and bridges are reflected. The trees, poles, and objects with physics are not reflected, which can be a bit strange. However, adding these details to the reflections would require more processing power and could affect the game’s performance. I hope that the developers will take this into account and find a way to improve the reflections without compromising the game’s performance.

**Comment by juicermv** [comment]
No, that's not at all what I'm talking about here.
