### ISSUE TITLE
[Feature request] more Motion blur options/slider

### ISSUE THREAD

**Issue by MOnkeMan5009** [ThirteenAG/GTAIV.EFLC.FusionFix#425]
### What should happen

Basically like the title says. Something like low - medium -high  - very high  or a slider to select ur amount

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by valentyn-l** [comment]
Motion blur intensity was made independent from framerate by essentially doing this: (current fps × (original motion blur intensity/30) = new motion blur intensity). A multiplier could be added to this equation to increase/reduce the intensity while keeping it independent from framerate.

**Comment by RecklessGlue540** [comment]
Yeah this could be a good feature to add...
A Motion Blur Strength slider just like in GTAV.

**Comment by UnknownLITE** [comment]
I think it is nice to add an option to enable motion blur only when in vehicle and a slider for motion blur strength
What it might look like:
Motion Blur: "Off"/ "Only in vehicle" / "On"
Motion Blur Strength: [▅▅     ]

**Comment by RecklessGlue540** [comment]
It's probably too hard to do the only in vehicle thing, not to mention none of rockstar's games do that, imo, it's useless. People who hate motion blur will disable it anyway.
But the motion blur strength is definitely needed. Although added sliders seem to suffer from [this small nitpick](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/478).
