### ISSUE TITLE
[Feature request] Allow shooting from stationary police vehicles on kmb without holding E

### ISSUE THREAD

**Issue by charlesthobe** [ThirteenAG/GTAIV.EFLC.FusionFix#426]
### What should happen

If possible, this should be at least allowed while using keyboard/mouse.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by anthoncast** [comment]
What you mean by this??

**Comment by charlesthobe** [comment]
When you're in a police car, you cannot shoot unless the car is moving, I think this limitation was due to xbox360/ps3 controllers not having enough buttons so rockstar made the L-trigger (which is normally used for shooting) access the police computer instead of shooting while the car is stationary, this doesn't make sense for PC as you access the police computer by pressing "E" by default.

**Comment by Tomasak** [comment]
Actually, even on gamepad you can shoot while the police car is stationary if you hold LB long enough.

**Comment by Tomasak** [comment]
issue should stay open if holding E "fixes" it

**Comment by Tomasak** [comment]
moved here https://github.com/GTAmodding/GTAIV-Issues-List/issues/151
