### ISSUE TITLE
Distance Blur and Depth of Field settings in Display tab don't do anything

### ISSUE THREAD

**Issue by Echo-Phyber** [ThirteenAG/GTAIV.EFLC.FusionFix#427]
### Game version this happens in

v1.2.0.59

### What area of the game

It did work after installing the mod for some time but stopped all of a sudden, tried reinstalling the mod with different versions, nothing helps.

![20240125212440_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/118754819/9c66ea4c-19eb-4a72-ae1b-7a15a60aa4d0)
![20240125212449_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/118754819/cdea08e3-ca43-47f1-90bf-7be0d0e54777)
![20240125212458_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/118754819/23b66aad-d222-43eb-88cb-0e66b97a3303)

### What should happen

Settings should change the DoF

### Last working version

v2.5.2

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by RecklessGlue540** [comment]
Distant Blur does not engage at night.

**Comment by Echo-Phyber** [comment]
@RecklessGlue540 it also doesn't work in the day. I can provide more screens

**Comment by Echo-Phyber** [comment]
![20240125214214_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/118754819/77103d3c-c685-40b1-89cf-007a1a8c21a5)
![20240125214221_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/118754819/9684eb24-ddf7-4fff-9e73-62cf0bdb4131)

**Comment by RecklessGlue540** [comment]
Are you using any timecycle mods?

**Comment by Echo-Phyber** [comment]
Looks like that was the problem, I forgot I've installed DayL's Natural Timecycle. Thx
