### ISSUE TITLE
Can you fix ScriptHookDotNet.asi and put ScriptHookDotNet.asi in FusionFix

### ISSUE THREAD

**Issue by GOOGORO** [ThirteenAG/GTAIV.EFLC.FusionFix#428]
### What should happen

Can the ScriptHookDotNet.asi file be repaired? Want to use previous mods. If you use ScriptHookDotNet.asi, you have all the rain problems. Is there a way to solve? Thanks

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
No. It's not the Fusion Team's job to fix other people's stuff.
Wait for IVSDK.NET to add support for Scripthook.net mods and CE support.
https://gtaforums.com/topic/986510-iv-sdk-net/?do=findComment&comment=1072317978

**Comment by GOOGORO** [comment]
> 不。修復別人的東西不是 Fusion Team 的工作。 等待 IVSDK.NET 新增對 Scripthook.net mods 和 CE 支援的支援。 https://gtaforums.com/topic/986510-iv-sdk-net/?do=findComment&comment=1072317978

Finally there is hope, there has been no news or repair for many years
THX
