### ISSUE TITLE
[Feature Request] Restore graphical effects and details from x360.

### ISSUE THREAD

**Issue by UserGit-2021** [ThirteenAG/GTAIV.EFLC.FusionFix#43]
Restore graphical effects and details from xbox 360.

On pc Less grass, more texture flickering, and weaker volumetric lighting.
https://youtu.be/8hku0q3P42Q

**Comment by valentyn-l** [comment]
Gonna throw-in a slight necro comment in here. I fully support and also request the restoration of these features and graphical effects, as it is quite jarring going back to the PC version after having played the 360 version. 

Unsure as to how feasible some of these shader restorations would be considering that unlike the console counterparts that used DirectX 10 level features, the PC version is limited to DirectX 9.

**Comment by Tomasak** [comment]
apart for water foam most is implemented. water foam is still wip
