### ISSUE TITLE
No option to skip intro

### ISSUE THREAD

**Issue by shaunre** [ThirteenAG/GTAIV.EFLC.FusionFix#430]
### Game version this happens in

v1.2.0.59

### What area of the game

This is supposed to be in the ini file right? I cant seem to find the option anywhere, but according to the description, this feature was added. 

### What should happen

Option to skip intro should show up. 

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by RecklessGlue540** [comment]
Please check the "game" submenu in the options. You'll find it in there.
It's been changed to be in the .cfg instead. Don't know exactly why Skip Intro and Skip Menu have gotten this change but whatever... It'd be better if this was back in the .ini in my opinion to avoid confusion like this...

**Comment by shaunre** [comment]
Maybe I installed the thing wrong? I put the 3 files in the root directory of the game Steam\steamapps\common\Grand Theft Auto IV

I don't get anything showing up under the game  =menu

**Comment by RecklessGlue540** [comment]
That means the ASI is not loaded probably...

**Comment by shaunre** [comment]
I'm on Pc but I got it. Needed to move the files to Steam\steamapps\common\Grand Theft Auto IV\GTAIV

**Comment by shaunre** [comment]
Make sure install path is steam\steamapps\common\Grand Theft Auto IV\GTAIV
