### ISSUE TITLE
Game crashes after installing FusionFix, and bugs occur with older version

### ISSUE THREAD

**Issue by NanoFlowGaming** [ThirteenAG/GTAIV.EFLC.FusionFix#433]
### Game version this happens in

v1.2.0.43

### What area of the game

The whole game. The latest version of FusionFix does not function. The game installation is clean and there's nothing on it. I install it and then game doesn't launch. I found that Pre 2.0 versions work but there's a few issues. Look at the attached image below

<img width="1470" alt="Screen Shot 2024-01-30 at 9 09 19 pm" src="https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/103425193/6837cd90-e5b6-470f-911b-8dd5a8271da6">

As you can see, there are these weird lines on vehicle windows. These lines also occur on various other places. (This is much worse during gameplay, as it kinda shimmers and moves a lot. Because of the shimmering, it does not look as bad as it actually does in a still image. It occurred on every vehicle and a bit in the background but it's tough to see on a still image due to the shimmering.

There's also an issue with the loading screen, as theres no transition between images. There's also another issue which I don't know how to describe but an image of it is below.

<img width="1470" alt="Screen Shot 2024-01-30 at 8 43 13 pm" src="https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/103425193/1343a3ee-ccf6-4659-9bf8-7420f1d5dd52">
It's not supposed to look like that. Just launch the game and compare to see the difference. 

I'm using Parallels (it's macOS software to run Windows). I'm using Windows 11 Arm by the way. I assume this bug occurs due to Windows 11 Arm having to emulate x86 software and FusionFix not being emulated correctly but I assume this can be fixed. I understand that this issue will probably not be top priority due to nearly nobody playing this like me, but I hope this can get fixed soon. GTA 4 works fine without FusionFix though. 

If additional images and/or videos are needed, let me know.

Edit: It seems like v1.80 and below works fine, my bad for not testing them. There aren't any bugs with v1.80. DxWrapper also works just fine with v1.80 so I'm using that as of now. I've also got v2.0 and newer running by editing some emulation settings but the bugs I mentioned which occurred with v1.96 still persisted. I've tried v1.96 after editing it too but it just won't go away. Forgot to mention that the v1.96 bugs still occurred with v1.94. 

### What should happen

There shouldn't be these lines on the screen. It's hard to explain but they appear on various things, like fences and vehicles. There also should be the transition effect (fading out and fading in) when game is loading. The other issue I mentioned earlier also shouldn't happen.

### CrashDumps and logs

Crash dump and logs for latest version of FusionFix (v2.5.3) 
If it's needed, I can upload crash dump for the latest version as this is now outdated.

https://drive.google.com/drive/folders/1w4fHa3ztrLWgnpVzPH2ilNA1KvDHnXFe?usp=drive_link

### Last working versions

v1.96 (with bugs)
v1.80 (without any bugs)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by NanoFlowGaming** [comment]
Dxwrapper also doesn't work with the older versions of FusionFix.

**Comment by Sparrow63** [comment]
v1.2.0.59 Same problem.

> Dxwrapper also doesn't work with the older versions of FusionFix.

Everything works for me. Anyway, after installing DxWrapper there are no stutters.

**Comment by MagicAl6244225** [comment]
Thanks for trying this on your Mac. I've been wondering how it would work since I'm currently playing on one of the last Mac models with Intel chips, which can run Windows 10 normally and fully supported, but I'm thinking about the future.
