### ISSUE TITLE
Fall in performance while GPU usage increases 

### ISSUE THREAD

**Issue by nbp92** [ThirteenAG/GTAIV.EFLC.FusionFix#436]
### Game version this happens in

v1.2.0.59

### What area of the game

Anywhere outdoors. I just reinstalled the game and have been installing-uninstalling mods to see when the issue begins or under what circumstances. Doesn't matter if I am having a shootout with the whole LCPD or walking a street, the GPU utilization goes crazy and the higher it goes, the worse for my FPS. 
As Vanilla or with DXVK, the GPU utilization is at 36% or so with stable 60 FPS.
Aften installing FusionFix, the game runs on 60FPS with 50%-60% GPU utilization.
It will hold them for a time but out of nowhere, the GPU usage will skyrocket to 99% or 100% and the FPS will drop down to 40 with the "99% FPS" showing around 20. 
Is there maybe a setting that can be tweaked on the mod settings that may be spiking the GPU into doing this?

### Your Hardware configuration

x64-based PC
M/B: MSI - MS-7C56
CPU: AMD Ryzen 7 5800X 8-Core Processor, 8 Core(s), 16 Logical Processor(s)
RAM: 32,0 GB / DDR4 @3600MHz
GPU: GeForce RTX 3070 Ti GAMING OC 8G

### Game capture

![20240203_212829](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/158767990/e92606c7-bc92-4609-ae7b-89ee15361113)
![20240203_212934](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/158767990/cb245a17-b4c3-4302-b419-7cecd91f7dee)
![20240203_212948](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/158767990/68853816-e064-4dd8-841a-41090c8b2f00)
![20240203_213118](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/158767990/a1341318-5993-4666-9a59-c789dd39759e)

### Last working version

I haven't used any previous versions, only 2.5.4

### Graphics backend (3D API)

DXVK

### Any other notes or things you've tried

I'm not having any background processes running during that time. 
Also, I had to take the photos with a mobile device because the NVIDIA Performance Overlay wasn't included in any screenshots I've taken (even with the NVIDIA Overlay screenshot shortcut).
During the screenshots, the character is standing still.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.

**Comment by Ash-735** [comment]
The game DOES have higher usage settings under Fusion Fix compared to the default, if you want to claw back performance then putting the shadow settings one tier lower will match the old (e.g. Medium on Fusion Fix is the same as High on normal), you could also take a look at the INI to disable some of the extra shadow casting features fusion fix enables.

**Comment by nbp92** [comment]
![Στιγμιότυπο οθόνης 2024-02-07 080221](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/158767990/6e8c140d-9112-4ed0-81a5-45ef03258a19)
Ι have set these values and have "FlickeringShadowsFix" changed from 1 to 0, among other things.
I also disabled the "Console Shadows", on the Graphics menu and the game seems to run very good now. 
During the night, my GPU usage, doesn't get over 30%.
During the day, it maxes out at 60%.

Thanks a lot!!!

**Comment by Ash-735** [comment]
Yes, BudgetedIV is where you put in the values so you don't get the taxi bug.

As for the shadow options, in the above, set 0 for the following...
DynamicShadowsForTrees
FixCascadeShadowMapResolution

and in-game set your shadows to SHARP and Shadow Quality to one level below what you currently have. These options will restore the shadows to how they were in the base game without Fusion Fix.

**Comment by RecklessGlue540** [comment]
> P.S. Is there a great drawback in performance between "Sharp" and "PCSS" shadows?

Yes. A big one. However, between Sharp, Soft, Softer and Softest there is no difference in performance.

> I've also set the Tree Shadows to "PC+".

I'd recommend using Console TreeFX, since PC+ is mostly meant for modded and custom trees. 
The normal ones are not going to look pleasant with PC+.

I can also recommend setting FlickeringShadowsFix to 1 in the .ini as it improves performance even more when Console Shadows is disabled.

**Comment by nbp92** [comment]
It seems that I've found another thread were my "issue" is also mentioned on the following link: https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/235

Maybe a redirection between the two can help future players who might face the same FPS drops.

Additionally, I will give your solutions a try and see what difference will that make.

**Comment by RecklessGlue540** [comment]
Also, never use Very High shadows. In most cases, they take away half of the framerate.

Instead, use High shadows but with FixCascadedShadowMapResolution to 1 in the .ini. 
Doing this will make High and Very High shadows look exactly the same, but High will be a lot more performant.

**Comment by nbp92** [comment]
If someone would like to test the shadow performance, I've found 2 spots that are quite demanding:
1) The bar where you can play Darts, west of Dukes.
2) The fuel storages in Dukes, just west of Francis Int. Airport. (where you can get the Combat Pistol).

I will attach a screenshot.
![Στιγμιότυπο οθόνης 2024-02-08 215753](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/158767990/ce963735-5293-47cd-8c1c-1295feea2f18)

**Comment by RecklessGlue540** [comment]
You may also try setting View Distance to 42 and Detail Distance to 20. Those are double the console defaults (which are 21, 20). 
Expect some performance improvements doing this as well. This is mostly for stability though.
 
Otherwise, if you'd still like the distances to be higher, try 84 for View, and 40 for Detail. These can work too. 
Compare between 42, 20 and 84, 40 and see what is better for you.

Distances as well should never be maxed. Rockstar broke the game big time.

**Comment by nbp92** [comment]
I've been trying out these options as well but today, I didn't face any GPU spikes on my sessions. Even after multiple 4+ star police chases and 10+ car explosions (looks like cars had actual fuel tanks on this game-silly me). 
What I did was set the shadows to "Console" because it seems to be the one less demanding. 

I've also edited the DXVK.conf a bit with the following commands:
dxgi.maxFrameLatency = 1
d3d9.maxFrameLatency = 1
dxgi.maxFrameRate = 60
d3d9.maxFrameRate = 60

The only issue I've faced, is a drop to 57FPS at 2 occasions for about 3 seconds.

**Comment by shmadoinfers** [comment]
I've been having the same issue except none of the fixes here worked for me. My issue is slightly different as in the game will constantly be at 100% utilization making the frame rate suffer. 

I've found a fix in that on first launch with the mod installed it runs fine, only on subsequent runs will it run into the utilization glitch. What I do to counteract this is just have a folder with my mods saved in it, and before playing I delete the update and plugins folder along with the dinput8.dll file, then drag my mods back in. This fixes the issue for the first launch, but subsequent launches require me to redo the process.

For reference, without the glitch my GPU utilization is at 30-60% with fps averaging around 170 (before capping it at 60). But once the glitch happens, my utilization gets all the way up to 100% and my fps averages around 30. If its any use, my GPU is an AMD 6700XT, but I notice @nbp92 was having the same issue with an NVIDIA GPU so I'm not sure if that's the issue here.

I am also running various fixes, DXVK, radio downgrader, and console visuals. I know its not DXVK as the glitch remains with or without it. The weird part is that I didn't have this issue a few days ago, It just randomly appeared yesterday.

**Comment by RecklessGlue540** [comment]
Wait for the next update, then report. It's gonna be all about performance and optimization.

**Comment by shmadoinfers** [comment]
Will quickly add that for me the problem was with enabling SMAA 2x under the game settings. When I enable it the glitch happens right as I restart the game, but goes away once I turn it off and restart again. Hopefully the next update resolves the issue.

**Comment by RecklessGlue540** [comment]
> Will quickly add that for me the problem was with enabling SMAA 2x under the game settings. When I enable it the glitch happens right as I restart the game, but goes away once I turn it off and restart again. Hopefully the next update resolves the issue.

SMAA or SSAA2x?

SSAA is designed to do that, please don't use it for casual play.

**Comment by shmadoinfers** [comment]
Apologies, meant SSAA 2x. Yeah, figured that out the hard way. Could be useful to add a warning to the setting to help fellow naive people like myself. Thank you!

**Comment by Markie98** [comment]
> I'd recommend using Console TreeFX, since PC+ is mostly meant for modded and custom trees.
> The normal ones are not going to look pleasant with PC+.

That's subjective, I absolutely prefer how trees are shaded with PC+, after comparing it.

**Comment by strupset** [comment]
> Will quickly add that for me the problem was with enabling SMAA 2x under the game settings. When I enable it the glitch happens right as I restart the game, but goes away once I turn it off and restart again. Hopefully the next update resolves the issue.

You cracked the code bro. I fucking knew I wasn't seeing things when I first launched the game and it ran at 144 barely dropping under 120, and when I launched the game again with the slightest change it hardly held 60. If you restart your game with SSAA 2x ON it will kill your frames for some reason, but if you launch the game with it off and then turn it on in-game and play, it will run smoothly, just need to remember to turn it off before closing the game. This occurs on the current version (v2.5.6) of the mod, can't wait for the next update.


> Apologies, meant SSAA 2x. Yeah, figured that out the hard way. Could be useful to add a warning to the setting to help fellow naive people like myself. Thank you!

1000% they should. Thank YOU my brother!!!

**Comment by RecklessGlue540** [comment]
I mean, it's already mentioned on the main page that SSAA requires restart and affects performance... 

I have suggested to have In-game descriptions of things in the past, but it's honestly quite minor and with no real point... 
Of course, I'd still like having something like that, but I've also heard the UI stuff is very hard to understand and work with properly, so it's best we live with what we have.

**Comment by nbp92** [comment]
My thoughts exactly. 

@shmadoinfers you're a hero!! 

I knew that something was indeed off but couldn't put my finger on it!
Let's hope that this thread will help others in the future.

**Comment by juicermv** [comment]
> You cracked the code bro. I fucking knew I wasn't seeing things when I first launched the game and it ran at 144 barely dropping under 120, and when I launched the game again with the slightest change it hardly held 60. SSAA 2x affects frames drastically, dont put it on unless you have a high end PC.

I mean... it's mentioned multiple times throughout the readme that SSAA 2x renders the game at twice the resolution. What did you expect?

**Comment by Markie98** [comment]
> I mean... it's mentioned multiple times throughout the readme that SSAA 2x renders the game at twice the resolution. What did you expect?

Four times the resolution (twice on each axis).

**Comment by juicermv** [comment]
Fair but I don't think anyone really counts it like that since in newer games for example when you have a resolution scale slider it goes from 0.x to 2 so I apply the same logic here

**Comment by RecklessGlue540** [comment]
SSAA also breaks some effects too, in case u guys didn't know. Raindrops go back to being black, and Bloom gets more excessive. Probably depth of field too. Keep that in mind.

**Comment by Markie98** [comment]
> SSAA also breaks some effects too, in case u guys didn't know. Raindrops go back to being black, and Bloom gets more excessive. Probably depth of field too. Keep that in mind.

And it also doesn't scale the menus/HUD/UI so you don't get them to look smoother like you would with downsampling, which would be a nice improvement, though on the other hand performance is also a bit better because of that.

**Comment by RecklessGlue540** [comment]
> > SSAA also breaks some effects too, in case u guys didn't know. Raindrops go back to being black, and Bloom gets more excessive. Probably depth of field too. Keep that in mind.
> 
> And it also doesn't scale the menus/HUD/UI so you don't get them to look smoother like you would with downsampling, which would be a nice improvement, though on the other hand performance is also a bit better because of that.

Hmm, interesting. Feels like it should scale the whole framebuffer by default, and not having to use an extra pass... Though again, I'm no expert on the matter (at least not yet, I guess).

Anyways, DSR, DLDSR and VSR do a much less intensive job, so probably stick to those. I'm using VSR currently and it's wonderful.
