### ISSUE TITLE
GTA IV not starting at irregular intervals since v2.5.4

### ISSUE THREAD

**Issue by koboltzz** [ThirteenAG/GTAIV.EFLC.FusionFix#437]
### Game version this happens in

v1.2.0.59

### What area of the game

Directly after doubleclicking the game shortcut, Game exe stays in taskmanager and won't launch anything.
Latest Dxvk and scripthook are installed with 'CenteredCarCamera', 'LessOvertake.net' and 'Pickups2.0'. 

### What should happen

Game should start like it always do in v2.5.3.

### CrashDumps and logs

Since there ist no real 'crash', I can not provide anything. Even the dxvk and scripthook logs are empty. But in your fusionfix thread in gtaforums I am not the only one who experience this kind of 'stall'.

### Last working version

v2.5.3

### Checklist

- [x] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [ ] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
Upload a memory dump.

**Comment by ThirteenAG** [comment]
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14204033/GTAIV.EFLC.FusionFix.zip)

Test build with a possible fix.

**Comment by koboltzz** [comment]
Thx for your test build. Sadly it doesn't fix the issue.
Crash Dump https://gofile.io/d/8TfnnI

**Comment by ThirteenAG** [comment]
Thank you, that's very helpful. Please try the new build:
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14216759/GTAIV.EFLC.FusionFix.zip)

**Comment by koboltzz** [comment]
That seems to fix the issue, thank you :)
May I ask what was the cause of it?

**Comment by ThirteenAG** [comment]
I used stdcall instead unsafe_stdcall from safetyhook's api.
