### ISSUE TITLE
Увеличению дальности отражений ,быть или не быть?

### ISSUE THREAD

**Issue by Damierror** [ThirteenAG/GTAIV.EFLC.FusionFix#438]
### What should happen

Привет !, я тоже занимаюсь разработкой исправления и улучшения графики, но у меня нет навыков программиста. Я просто занимаюсь настройкой таймцикла и погодных эффектов ,короче говоря открытым кодом... Такой вопрос у меня назрел потому что тут параллельно работают ещё несколько человек. Конкретно сейчас я пользуюсь изменёнными шейдерами от robi29 (тут всё сыро, отражения оказывается тоже имеют свои лоды ,которые отрисовываются на определённой дистанции, но местами вполне годно), очень скоро свой решейд выставит vonum7(там судя по видосу выглядит всё просто супер, даже люди с машинами отражаются на дороге), Идут ли какието работы по этому направлению у вас в fusionfix?
![Снимок экрана (11027)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/6ec15ccc-8c9d-4547-b2c5-971d90e85d48)
![Снимок экрана (11127)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/1cc25494-a8b5-493f-924c-7ee5b4e2f41c)
![Снимок экрана (11128)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/361e9555-ecfe-4146-af66-8e54db49297d)
![Снимок экрана (11138)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/8cba9c35-5dfc-4a71-9c97-2306c845aea6)
![Снимок экрана (11293)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/12928fb2-242d-417c-8e3d-5bcbd08d47f7)
![Снимок экрана (11356)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/dc7ef8cf-21ec-4b44-a2c9-bf76ce5b6ca6)
![Снимок экрана (11419)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/179d91aa-8c98-42f8-ac02-2129929dd7ea)
![Снимок экрана (11472)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/453c5213-9163-4c1c-858b-c20c29fa16d8)
![Снимок экрана (11656)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/ab87e1ae-ec6a-422e-8caa-ff36ba649a06)
![Снимок экрана (11918)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/a1f22ab1-e2da-43fe-9d57-4733a0c36f2c)
![Снимок экрана (11938)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/42bd38e1-0451-45a5-9b26-3f4cae343474)
![Снимок экрана (11963)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/89b97835-3ce3-4174-918a-f582579936a2)
![Снимок экрана (11968)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/724c51b4-61a5-4f24-bfa4-6615c90dabbe)
![Снимок экрана (11978)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/1f136b8f-9b26-4b5c-a6bb-2ccc8d183988)
![Снимок экрана (12047)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/c1a30c42-b576-4794-b113-5f0c3e23cbc0)
![Снимок экрана (12076)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/50c7ab5b-c467-4784-ab4c-15bb8bcfc79d)

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by d3g0n-byte** [comment]
Привет! Мы очень рады, что вы подняли эту тему. Хоть я и атеист, но сегодня я пойду в церковь и помолюсь за вас и ваши навыки программирования. Даже всем коллективом FusionTeam мы пойдем в церковь ради вас. Ну и главное - купим свечу и поставим ее.

**Comment by Damierror** [comment]
я воспользовался патчем от zolika и теперь у меня практически полные отражения зданий и деревьев
![Снимок экрана (13496)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/146632112/34a1425d-5b07-4811-b0e9-64c05e17a4e0)
