### ISSUE TITLE
blood splash 

### ISSUE THREAD

**Issue by GOOGORO** [ThirteenAG/GTAIV.EFLC.FusionFix#439]
### What should happen

The blood splash effect is gone. Has it been cancelled?

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
No. It works fine.

**Comment by GOOGORO** [comment]
> No. It works fine. Blame it on the ENB you are trying to use with FusionFix.

Sorry, I still don’t see the effect. Does it have a switch? Thank you.

**Comment by RecklessGlue540** [comment]
Rain Droplets isn't included in FusionFix.
The game's default droplets have been restored and fixed properly now. Probably stick to those imo...
