### ISSUE TITLE
[Feature request] Possibility to disable glow of dropped weapons/money

### ISSUE THREAD

**Issue by koboltzz** [ThirteenAG/GTAIV.EFLC.FusionFix#441]
### What should happen

Fusion fix should have a setting to disable the immersion breaking item glow of dropped weapons and money.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by juicermv** [comment]
Nah. It's a staple of the GTA series.

**Comment by koboltzz** [comment]
Sorry, but that's not true. In the early '00s, it was still normal to add a glowing effect to dropped items in almost every game. Over time, all other franchises have deviated from this.


GTA IV in particular is the part with a focus on a very realistic presentation. No jetpacks, no tank control, boaty car controls with long braking distances, etc.

Red Dead redemption 2 doesn't have the glowing either.

According to your argument, the feature request should be that the dropped weapons rotate again like in GTA VC/SA. Even that rotating was too ridiculous for rockstar so they dropped that effect in IV.

**Comment by RecklessGlue540** [comment]
> Red Dead redemption 2 doesn't have the glowing either.

This is not really in scope for FusionFix, but we could have a separate mod that gets rid of the red glow around, and instead either give the weapons a white outline around their edges (like Max Payne 3) or give them a slight glint (like in GTAV and RDR2).

**Comment by juicermv** [comment]
> Sorry, but that's not true. In the early '00s, it was still normal to add a glowing effect to dropped items in almost every game. Over time, all other franchises have deviated from this.
> 
> GTA IV in particular is the part with a focus on a very realistic presentation. No jetpacks, no tank control, boaty car controls with long braking distances, etc.
> 
> Red Dead redemption 2 doesn't have the glowing either.
> 
> According to your argument, the feature request should be that dropped weapons should rotate again on the floor like in GTA VC/SA. Even that rotating effect was too ridiculous for rockstar so they dropped that effect in IV.

All I said is that it was a staple of the series. Even GTA V has flashing on its pickups.  Not that deep.

**Comment by MOnkeMan5009** [comment]
pretty sure theres standalone mods doing that

**Comment by Rombbb** [comment]
> Nope, there certainly isn't one. As a sideeffect of 'pickup 2.0' script you can only disable weapon glow, but that's not the main purpose of this script. And killed people still drop glowing money. Zolika's Trainer for the old 1.0.4.0 version had a feature to disable both, but that doesn't work in CE edition.

100% agree, it is ridiculous, such a believable world drowned in orange dots for no reason

I understand the series' cartoony roots but this really should be a toggle
Can't people see that weapon lying in the street ?

If there is one QoL mod that makes sense it's this one

**Comment by Rombbb** [comment]
ps, you can remove the glow easily via Reshade shader toggler but issue is that other glow effects in the world, like traffic lights, are the same shader and disabled as well

**Comment by usergithub64** [comment]
Please add the ability to disable pickups glow to Fusion Fix, like in Zolika's Trainer. Or at least make it a separate ASI script.

**Comment by RecklessGlue540** [comment]
Gonna be [here](https://github.com/RecklessGlue540/VolumetricLights) sometime soon.

**Comment by Rombbb** [comment]
> Gonna be [here](https://github.com/RecklessGlue540/VolumetricLights) sometime soon.

That would be amazing !!

Above you mention it could be replaced with a white weapon outline or slight glint but if possible it would be amazing to disable any glow at all.
For immersion it just doesn't vibe with the authentic world. Gamers know after 3 times what a wepaon looks like on the floor, no need to have it reapeatedly draw attention away via comicy effects like outlines or similar.

If there's anything I can do to help don't hesitate to ask, am no coder but if there is something that takes time to do, I am available.
Usually spent a lot of time modding stuff like this out of games (like e.g. the NPC outline in AC3 or the golden glow of chests in AC Unity) but the weapon and money glow in GTA4 is next level stubborn to get rid off for newbie modders.

We all depend on the real ones like yourself :-)

**Comment by usergithub64** [comment]
> Gonna be [here](https://github.com/RecklessGlue540/VolumetricLights) sometime soon.

In which version of VolumetricLights was this added?
