### ISSUE TITLE
Bowling First date doesn't work

### ISSUE THREAD

**Issue by Cartrigger** [ThirteenAG/GTAIV.EFLC.FusionFix#443]
### Game version this happens in

v1.2.0.59

### What area of the game

The bowling first date doesn't work due to the marker never coming up to pick a lane
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/81428538/bf967a42-328a-47ce-ad25-6d58890377fe)

### What should happen

It should just have a marker to pick which lane

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by RecklessGlue540** [comment]
> ### Game version this happens in
> v1.2.0.59
> 
> ### What area of the game
> The bowling first date doesn't work due to the marker never coming up to pick a lane ![image](https://private-user-images.githubusercontent.com/81428538/304293411-bf967a42-328a-47ce-ad25-6d58890377fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4Mjk5OTksIm5iZiI6MTcwNzgyOTY5OSwicGF0aCI6Ii84MTQyODUzOC8zMDQyOTM0MTEtYmY5NjdhNDItMzI4YS00N2NlLWFkMjUtNmQ1ODg5MDM3N2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDEzMDgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZGYzOTdhYzFjZmFhMDgxOTQwNjk2ZmYyZDBlZWZmN2M1YjY3MDY4Y2NhMzRmNGRiNjNmOGE3OTI3ZWYyY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y1nvF9Hped4A9Qdw0RcnRSVVUkhgG_eCC6dUI_AkHDY)
> 
> ### What should happen
> It should just have a marker to pick which lane
> 
> ### CrashDumps and logs
> _No response_
> 
> ### Last working version
> _No response_
> 
> ### Checklist
> * [x]  Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
> * [x]  [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
> * [x]  Include logs or screenshots of issue.

Do you have Alternate Dialogues enabled?

**Comment by Cartrigger** [comment]
No

**Comment by Tomasak** [comment]
Do you have legit latest game version?

**Comment by Gheysenbergh** [comment]
So I have this issue too. What is the workaround? Why so many mods and fixes but this game-breaking bug (can't continue the game) is not fixed?
