### ISSUE TITLE
[ Vehicle Reflections aren't as good now? ]

### ISSUE THREAD

**Issue by MOnkeMan5009** [ThirteenAG/GTAIV.EFLC.FusionFix#444]
### What should happen

I am not sure what caused the previous very interesting reflections, or if it was unintentional wrong reflections. 
But previously on like 1.80 fusionfix + console visuals ( like 0.8 version from nexusmods that mainly provided files for visuals ) 
the reflections insensity seemed better. Again, i am not sure if it was meant like that but they looked damn good. Heres some older screenshots i had vs the new ones now. They also seemed more console like, anyway they were more beautiful 
Older screenshots : https://steamcommunity.com/sharedfiles/filedetails/?id=3040052703 
https://steamcommunity.com/sharedfiles/filedetails/?id=3036387727
https://steamcommunity.com/sharedfiles/filedetails/?id=3035900976 ( a perfect example here )
https://steamcommunity.com/sharedfiles/filedetails/?id=3035215380 ( another one here, i am pretty sure if someone is experimented knows what im talking about )

Here are newer ones which arent as good : 
https://cdn.discordapp.com/attachments/889743907997487134/1198008915691049011/image-4.png?ex=65d9073f&is=65c6923f&hm=4bddaddffab8017cfe51d7c584e8fc31a8cc6f095d10bfec7cc670e03589994b&
https://cdn.discordapp.com/attachments/889743907997487134/1198008918199246908/image-5.png?ex=65d90740&is=65c69240&hm=306cdd0a640f73d572aab6583da2c7c8cf82af8e267b660f478845e2abfeabc0&

See the difference? I remember back then when i installed fusionfix then installed console visuals ( the version before this latest one  from nexusmods ) and it had those beautiful reflections

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by Ash-735** [comment]
Previously console visuals provided an edited vehicle IDE file which set all vehicles to be less dirty which tends to have stronger reflections, what you were getting in those earlier screenshots was the vehicles all acting as if they were constantly freshly washed, where as the updated code correctly scales this feature.

**Comment by MOnkeMan5009** [comment]
> Previously console visuals provided an edited vehicle IDE file which set all vehicles to be less dirty which tends to have stronger reflections, what you were getting in those earlier screenshots was the vehicles all acting as if they were constantly freshly washed, where as the updated code correctly scales this feature.

Are you sure? Even with this current console visuals thingy even when a vehicle is washed the reflections dont look nearly as good. And the previous i think had dirty vehicles too

**Comment by RecklessGlue540** [comment]
Yeah, previously, dirt level on cars affected reflection intensity, and dirt level in turn is affected by a threshold set in vehicles.ide or by the game's dirt level randomizing code for some vehicles (i.e when dirt level is set to 1 in vehicles.ide). 

That first part was properly fixed, so reflection intensity is decoupled from dirt level now, resulting in consistent reflections on all vehicles regardless of how dirty they may be.

In my opinion, reflections look the best now, so I don't quite see where this aspect can be improved any further.
