### ISSUE TITLE
Shadow's draw distance feature and shadow's far lod's like in GTA 5

### ISSUE THREAD

**Issue by NazarSurmay12** [ThirteenAG/GTAIV.EFLC.FusionFix#446]
### What should happen

GTA 4 have very small shadow distance even in buildings but what if make shadow's far lod's immitating something similar far illumination like in GTA 5?
![20240219012108_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/160436820/d3c45086-5cbb-46da-ab5e-7ba4cf8a6dcc)
![20240219005951_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/160436820/18065270-fba8-4de9-a27c-ec4da52b936f)
![20240219005809_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/160436820/acd05d11-8af2-47f8-ae05-db4657ca2eab)

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
Shadow distance cannot be increased any more than it already is, unfortunately. 
To make it a bit better, a fade in / out system was applied to them.

**Comment by MOnkeMan5009** [comment]
Can anyone make GTA V's shadow distance bigger tho? try going up in the air like with no clip in LS, u will see maze bank area shadows going away.. Oh and Shadows flickering at characters near neck-hair and eyes during cutscenes

**Comment by RecklessGlue540** [comment]
> Can anyone make GTA V's shadow distance bigger tho? try going up in the air like with no clip in LS, u will see maze bank area shadows going away.. Oh and Shadows flickering at characters near neck-hair and eyes during cutscenes

Oh, GTA V definitely needs some shader improvements too...
Shadows flickering is due to their filtering and somewhat low resolution, but mostly the filters. PCSS shadows are really bad there as well...
Although, I think a mod like FusionFix for GTA V would have much higher chances to get taken down by you know who...

On the other hand, maybe at one point we'll have working Long Shadows in GTA IV too... who knows.

**Comment by MOnkeMan5009** [comment]
> > Can anyone make GTA V's shadow distance bigger tho? try going up in the air like with no clip in LS, u will see maze bank area shadows going away.. Oh and Shadows flickering at characters near neck-hair and eyes during cutscenes
> 
> Oh, GTA V definitely needs some shader improvements too... Shadows flickering is due to their filtering and somewhat low resolution, but mostly the bad filters. PCSS shadows are really bad there as well... Although, I think a mod like FusionFix for GTA V would have much higher chances to get taken down by you know who...
> 
> On the other hand, maybe at one point we'll have working Long Shadows in GTA IV too... who knows.

no it wouldn't have chances of taken down. Theres plenty of mods out there doing graphical stuff. It absolutely wouldnt. also i am running softest shadows and 4k res max settings. It still happens altho less frequently but it does. AND Another thing, sometimes at certain spots shadows tend to continue appearing of like underneath a ledge of a building when u get closer
