### ISSUE TITLE
Shadow flickers 

### ISSUE THREAD

**Issue by LaupaMag338** [ThirteenAG/GTAIV.EFLC.FusionFix#450]
### Game version this happens in

v1.2.0.30

### What area of the game

In the Golf course in Meat Quarter, the shadows are flickering if you look around. 

### Your Hardware configuration

AMD Raedon Vega 8 Graphics 
16GB RAM

### Game capture

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/93017846/737b1521-5364-4e30-85be-220c8fa68f43

### Last working version

v2.5.5

### Does IV run better without FF installed?

No

### Graphics backend (3D API)

Direct3D 9

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.
- [x] Try resetting settings or older versions and include if the issue is related.
- [x] Try changing graphics settings to determine if one causes the slowdown.

**Comment by sTc2201** [comment]
Not an issue with FusionFix, this might be the result of aggressive object or [shadow culling](https://digitalrune.github.io/DigitalRune-Documentation/html/4058fb6c-8794-46cb-9d22-fb8558857179.htm), happens in the vanilla game, even on the console build too (see video below). 

Recorded on the xenia emulator:

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/41953894/5bc3dd8d-a198-47f9-af0f-1f0c392bd657

**Comment by RecklessGlue540** [comment]
Was able to reproduce that immediately too.
A proper Long Shadows implementation would fix this, I'm pretty sure. For now, we gotta live with it.

**Comment by MOnkeMan5009** [comment]
> Was able to reproduce that immediately too. A proper Long Shadows implementation would fix this, I'm pretty sure. For now, or forever : ( , we gotta live with it.

u know if theres any progress on regarding shadow popping and stuff when pressing C?

**Comment by RecklessGlue540** [comment]
> > Was able to reproduce that immediately too. A proper Long Shadows implementation would fix this, I'm pretty sure. For now, or forever : ( , we gotta live with it.
> 
> u know if theres any progress on regarding shadow popping and stuff when pressing C?

Who knows, they might be related...

**Comment by MOnkeMan5009** [comment]
> > > Was able to reproduce that immediately too. A proper Long Shadows implementation would fix this, I'm pretty sure. For now, or forever : ( , we gotta live with it.
> > 
> > 
> > u know if theres any progress on regarding shadow popping and stuff when pressing C?
> 
> Who knows, they might be related...

hm okay, what about light sources popping? same linked thing? like building or stuff like that, the lights from them

**Comment by RecklessGlue540** [comment]
> > > > Was able to reproduce that immediately too. A proper Long Shadows implementation would fix this, I'm pretty sure. For now, or forever : ( , we gotta live with it.
> > > 
> > > 
> > > u know if theres any progress on regarding shadow popping and stuff when pressing C?
> > 
> > 
> > Who knows, they might be related...
> 
> hm okay, what about light sources popping? same linked thing? like building or stuff like that, the lights from them

Those work fine. Just use Console Shadows. And that's a totally different thing anyway, related to the 16 dynamic shadows limit, if you mean lamppost shadows disappear depending on the camera angle. 
FlickeringShadowsFix also attempts to fix that, although has a minor issue, and is completely ignored when using Console Shadows because it disables headlight shadows entirely. 
Please however make sure that FlickeringShadowsFix is on when Console Shadows are set to off. It could bring modest performance enhancements. So yeah, keep that "fix" untouched, leaving it to 1.

If you mean the lights themselves, they fade in and out properly now, and their distance can be tweaked with View Distance and Detail Distance. (make sure you don't crank them up to 100, highest you should use imo is 84, and 40).

**Comment by LaupaMag338** [comment]
Will they ever fix the issues on FlickeringShadowsFix?

> > > > > Was able to reproduce that immediately too. A proper Long Shadows implementation would fix this, I'm pretty sure. For now, or forever : ( , we gotta live with it.
> > > > 
> > > > 
> > > > u know if theres any progress on regarding shadow popping and stuff when pressing C?
> > > 
> > > 
> > > Who knows, they might be related...
> > 
> > 
> > hm okay, what about light sources popping? same linked thing? like building or stuff like that, the lights from them
> 
> Those work fine. Just use Console Shadows. And that's a totally different thing anyway, related to the 16 dynamic shadows limit, if you mean lamppost shadows disappear depending on the camera angle. FlickeringShadowsFix also attempts to fix that, although has a minor issue, and is completely ignored when using Console Shadows because it disables headlight shadows entirely. Please however make sure that FlickeringShadowsFix is on when Console Shadows are set to off. It could bring modest performance enhancements. So yeah, keep that "fix" untouched, leaving it to 1.
> 
> If you mean the lights themselves, they fade in and out properly now, and their distance can be tweaked with View Distance and Detail Distance. (make sure you don't crank them up to 100, highest you should use imo is 84, and 40).

**Comment by RecklessGlue540** [comment]
> > > > > > Was able to reproduce that immediately too. A proper Long Shadows implementation would fix this, I'm pretty sure. For now, or forever : ( , we gotta live with it.
> > > > > 
> > > > > 
> > > > > u know if theres any progress on regarding shadow popping and stuff when pressing C?
> > > > 
> > > > 
> > > > Who knows, they might be related...
> > > 
> > > 
> > > hm okay, what about light sources popping? same linked thing? like building or stuff like that, the lights from them
> > 
> > Those work fine. Just use Console Shadows. And that's a totally different thing anyway, related to the 16 dynamic shadows limit, if you mean lamppost shadows disappear depending on the camera angle. FlickeringShadowsFix also attempts to fix that, although has a minor issue, and is completely ignored when using Console Shadows because it disables headlight shadows entirely. Please however make sure that FlickeringShadowsFix is on when Console Shadows are set to off. It could bring modest performance enhancements. So yeah, keep that "fix" untouched, leaving it to 1.
> > 
> > If you mean the lights themselves, they fade in and out properly now, and their distance can be tweaked with View Distance and Detail Distance. (make sure you don't crank them up to 100, highest you should use imo is 84, and 40).
> 
> Will they ever fix the issues on FlickeringShadowsFix?
> 

Only issues I know of with this fix is that single headlights (such as bike headlights or cars with one broken) still cast shadows.
