### ISSUE TITLE
[ Water barrel on the building fading out, popping ]

### ISSUE THREAD

**Issue by MOnkeMan5009** [ThirteenAG/GTAIV.EFLC.FusionFix#453]
### Game version this happens in

v1.2.0.59

### What area of the game

The area is right next to the hospital where the Jacob's shooting with Niko takes place, right near the police station. i'll leave a clip here : https://youtube.com/clip/Ugkxh0H0dXttIgOlSBp6pyibk8u9yQWF2Dia?si=qWvmuSr6U8LoTqSA   Look at the water container, Ned doesn't use Fusionfix but i do and same thing happens, except it doesnt instantly pop it fades. But cant it stay?

### What should happen

Fade/Pop in and out as u get closer or further

### CrashDumps and logs

None

### Last working version

Unknown

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by RecklessGlue540** [comment]
So you want the thing to fade in and out depending on the distance?
How does it behave with various fixes?

**Comment by Parallellines0451** [comment]
Not a bug.
