### ISSUE TITLE
Traffic lights not rendering properly

### ISSUE THREAD

**Issue by dan96kid** [ThirteenAG/GTAIV.EFLC.FusionFix#455]
### Game version this happens in

v1.2.0.59

### What area of the game

Happens anywhere there are traffic lights.

Image taken in Hove Beach just outside the safe house
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/14021093/86a3a088-1b56-4571-ac84-259fe369c1ae)
 Some additional details:
- Steam version of Grand Theft Auto IV: Complete Edition
- Happens with the latest (As of the opening of this issue) version of FusionFix, version 2.5.6

### What should happen

Traffic lights should be rendering properly, as shown in the below screenshot
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/14021093/1ddee078-75c4-4e6a-a2b9-3aa31d7ae416)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by RecklessGlue540** [comment]
![GTAIV 3_8_2024 4_44_13 PM](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143945383/d13cb952-68ca-4f3c-9279-d8480f57e173)

They work fine on my end here. Are you sure the GTAIV.EFLC.FusionFix.img archive is there in the update folder? It contains fixed models for the Z-Fighting fix.

**Comment by dan96kid** [comment]
... Turns out I screwed up with the install.

Close this issue.
