### ISSUE TITLE
[Development] Contacting the team

### ISSUE THREAD

**Issue by juicermv** [ThirteenAG/GTAIV.EFLC.FusionFix#459]
### What should happen

Hey, I'm looking to contribute an SDL Input implementation for FusionFix and I'd love to talk with the FusionFix team on the actual implementation and specifics but I have no idea how to reach you guys. Would love to talk with y'all :)

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by Tomasak** [comment]
Sorry but this it out of scope for this mod. Its cool though, you should release it as standalone asi.

**Comment by RecklessGlue540** [comment]
Does this fix the camera's frame rate dependency on gamepads? If it does, this should be a fix, and in scope.

**Comment by juicermv** [comment]
> Sorry but this it out of scope for this mod. Its cool though, you should release it as standalone asi.

This would add native support for newer controllers like the Dualsense without needing SteamInput. I don't really see how this is out of scope tbh. Either way I'd love to talk to y'all about the actual implementation since y'all are much more familiar with the game's internals :)

**Comment by juicermv** [comment]
> > > Does this fix the camera's frame rate dependency on gamepads? If it does, this should be a fix, and in scope.
> > 
> > I don't think it will. The basic idea is to pass SDL's controller values to the game so it processes them as it would any other supported controller. It doesn't have anything to do with the camera.
> 
> Can't SDL do some sort of raw input for the sticks too?
> 
> Yeah, really doesn't make much sense. If Logitech keyboard lighting was in scope (which imo is entirely useless), I don't see how native support for more controllers wouldn't be. 
> We definitely need some fixes for the gamepad input too tbh...


> Can't SDL do some sort of raw input for the sticks too?

In my implementation, the game would be reading the controller values directly from SDL. The prcoessing itself would still be done by the game (things like camera movement). That stuff can be modified separately though.


> If Logitech keyboard lighting was in scope (which imo is entirely useless), I don't see how native support for more controllers wouldn't be. 

In all honesty, 100%.

**Comment by juicermv** [comment]
So that's it then? Can't even talk to you guys?

**Comment by ThirteenAG** [comment]
If you refer to me, I have nothing to say on the matter. All my gamepads work with this game.

**Comment by juicermv** [comment]
They obviously do, since they utilize SteamInput, but this could add native support without needing a translation layer plus possible PS5 adaptive trigger support if someone really wanted to implement this. Again, I don't mind if you guys don't think this fits FusionFix but you have much more knowledge about the game's inner workings than I and I would love your help with finding out how to override the game's input-related code either way.

**Comment by juicermv** [comment]
By the way, this is basically required for people using RGL since it doesn't have SteamInput.

**Comment by Markie98** [comment]
> By the way, this is basically required for people using RGL since it doesn't have SteamInput.

You can use SteamInput in Non-Steam games:
https://steaminput.wiki/en/non-steam-games
Though ideally that shouldn't be a requirement of course.
