### ISSUE TITLE
Rockstar Games Launcher (RGL) overwrites FusionFix files

### ISSUE THREAD

**Issue by whoundd** [ThirteenAG/GTAIV.EFLC.FusionFix#46]
Hey,

I must be missing something really obvious, but RGL just overwrites the files from this mod the next time I open it to launch the game. How do I stop that from happening? Version 1.2.0.43

**Comment by Diegoch97** [comment]
Same thing keeps happening to me but only in tbogt.. Everytime I launch the game RGSC auto replaces/delete the files for the car light fix.

**Comment by stweedo** [comment]
I got this working with lutris. I added -scOfflineOnly to the arguments box and then added dinput8 with value n,b to the winedlloverrides box

**Comment by Popedigoz** [comment]
Is it because of RGL I can't seem to make Borderless Windowed mode to work? Its value ("BorderlessWindowed") in the GTAIV.EFLC.FusionFix.ini is 1. Or maybe it should be 0 or 2? These vakyes aren't explained anywhere.

**Comment by Popedigoz** [comment]
> I got this working with lutris. I added -scOfflineOnly to the arguments box and then added dinput8 with value n,b to the winedlloverrides box

what's that? tutorial plz.

**Comment by ThirteenAG** [comment]
Try now, latest version of the plugin doesn't overwrite any files.
