### ISSUE TITLE
Toggle to enable pre-fusion fix water texture.

### ISSUE THREAD

**Issue by SangalDigital** [ThirteenAG/GTAIV.EFLC.FusionFix#465]
### What should happen

Fusion fix offered the ability to disable the new console (medium setting) water texture size in the.ini file.. But Now I can't seem to find it. Is it possible to add a toggle or will the option be reverted to the.ini? 

I really like the small water texture when the settings are selected for very high water.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
I don't recall ever seeing that option in the .ini...
Though water definitely needs some more fine tuning sometime tbh, it's literally no different between quality settings now...

**Comment by SangalDigital** [comment]
Well is there a way for me to get the original PC version water?
