### ISSUE TITLE
Stuttering while using gamepad with FusionFix installed

### ISSUE THREAD

**Issue by puerquito44** [ThirteenAG/GTAIV.EFLC.FusionFix#467]
### Game version this happens in

v1.2.0.59

### What area of the game

There isn't a specific area. The stutters start randomly.

### Your Hardware configuration

CPU: Ryzen 5 5600
GPU: RX 6800 XT
16GB RAM

### Game capture

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/82246362/543eea92-9b46-44d7-bc70-ddc1d9aedca2

### Does IV run better without FF installed?

Yes

### Graphics backend (3D API)

Direct3D 9

### Any other notes or things you've tried

- The game runs fine with the controller connected and using only keyboard and mouse.
- The stutters happen with DXVK too.
- When using DXVK or DX9, the stutters can be fixed using alt+tab, but that only works temporarily.
- I don't have other mods installed.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.

**Comment by anthoncast** [comment]
Have you tried turning on Steam's overlay? That may fix it.

**Comment by Tomasak** [comment]
as said above, i recall someone having troubles with steam overlay/ steam input try turning that on or off and report if some combinations helps

**Comment by puerquito44** [comment]
Looks like enabling steam overlay fixed the stutters. Played for around 2 hours with no issues.

**Comment by puerquito44** [comment]
Looks like enabling steam overlay fixed the stutters. Played for around 2 hours with no issues.
