### ISSUE TITLE
After installing 2.5.6, the game crashes on start.

### ISSUE THREAD

**Issue by Plokhi** [ThirteenAG/GTAIV.EFLC.FusionFix#469]
### Game version this happens in

v1.2.0.43

### What area of the game

It crashes immediately on start.
I'm trying to run via parallels.
Parallels doesn't support vulkan

I tried running legit steam version that i bought, but unfortunately sign-in doesn't work, so i had to resort to FitGirl repack version.

Without fusion fix it starts and plays.
I'm badgering rockstar about the stuck sign in token, but i wouldn't hold my breath so please don't ask me to use the steam version because it simply doesn't work

### What should happen

It shouldn't crash

### CrashDumps and logs

[GTAIV.exe.20240404212305.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14876243/GTAIV.exe.20240404212305.log)
[GTAIV.exe.20240404211029.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14876244/GTAIV.exe.20240404211029.log)
[GTAIV.exe.20240404211029.dmp](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14876245/GTAIV.exe.20240404211029.dmp)
[GTAIV.exe.20240404212305.dmp](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14876246/GTAIV.exe.20240404212305.dmp)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Plokhi** [comment]
I tried redownloading from steam, but downgraded to 10.8 and renamed to xlive.dll but same crashes happen.
it worked initially with zolita + fusionfix (very old version) installed directly from downgrader.
then i removed zolita and install fusion fix and it stopped working

[GTAIV.exe.20240404235717.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14877561/GTAIV.exe.20240404235717.log)

[GTAIV.exe.20240404235717.dmp](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14877560/GTAIV.exe.20240404235717.dmp)

**Comment by Tomasak** [comment]
just install legit copy from steam and obtain "Fixed Files" for 1.2.0.59 from game  copy world

**Comment by Plokhi** [comment]
Tried this, but it doesn't even run unfortunately :/
The problem is I can't even know if FusionFix works on the steam version because rockstar launcher wont work. I'm not banned and i could run GTA V fine.

So far i could run mod-less Fitgirl repack 1.20.43, and modless steam version downgraded to 1.0.80.  Fusionfix 2.5.6 crashes on both. 1.0.8. downgrader with an ancient version of Fusion Fix that downgrader comes with somehow works.

**Comment by Plokhi** [comment]
I followed the manual downgrade guide to 1.0.8 over at GTAForums, and i can manage to get it to work even with DXWrapper and some mods. I added fusionfix and Xlive asiloader but it only works if i remove fusionfix files from the game folder. DXwrapper, Zolitka and XLiveless - runs fine, FusionFix crashes. 
DXWrapper crashed until i changed some settings in the .ini of it. Is there something in Fusionfix I need to change?

mind you it also crashes if i remove everything and just keep fusionfix.

[GTAIV.exe.20240405200614.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14889207/GTAIV.exe.20240405200614.log)

[GTAIV.exe.20240405200614.dmp](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14889206/GTAIV.exe.20240405200614.dmp)

**Comment by Plokhi** [comment]
Just tried with FusionFix 1.96 and it doesn't crash the game, even if i keep the folder structure

Steam CE, downgraded to V1.0.8 (because rockstar launcher)

any way to make latest version work?

**Comment by Plokhi** [comment]
okay then, i installed this:
https://github.com/ThirteenAG/d3d9-wrapper/releases

dxwrapper seems to load according to logs, i removed zolitka and fusionfix 2.5.6 now happily works and game looks friggin amazing. 
Thank you for this journey.
