### ISSUE TITLE
There's some visual glitches mostly on car windows

### ISSUE THREAD

**Issue by Plokhi** [ThirteenAG/GTAIV.EFLC.FusionFix#472]
### Game version this happens in

v1.2.0.59

### What area of the game

Steam 1.20.59 downgraded to V1.0.8
only running DXwrapper in parallel, no other mods

<img width="1140" alt="Screenshot 2024-04-06 at 10 35 56" src="https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/37208555/9ecfc3b7-1b71-46cb-9710-dabe4bdb960a">

### What should happen

probably no glitches

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Tomasak** [comment]
this is not general IV solution center, only for fusionfix related issues.

**Comment by Plokhi** [comment]
Sorry should've clarified: this only happens with FusionFix loaded.
I tried different settings but it doesn't change the behaviour.

It doesn't happen at all if i remove FusionFix.
DxWrapper has no effect.
Other than that i only have ASI loader and Xliveless installed.

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/37208555/0e1f2ca3-4875-4d6d-8395-701ed2d22608

**Comment by Tomasak** [comment]
While fusion fix is working with older game versions, Its support is only aimed for latest CE version.

**Comment by Plokhi** [comment]
ah. :/ until rockstar fixed my login unfortunately i need to use the 1.0.8 downgrade.

**Comment by Plokhi** [comment]
could it have anything to do wilth tile stippling? it looks as a grid most of the time.
Lowering definiton to classic seems to make it less present, but still present.

**Comment by RecklessGlue540** [comment]
Since you mentioned you're using ThirteenAG's DXWrapper, that may be the issue. It has not been updated in quite some time and no one really uses it for GTAIV...

Instead, I'd recommend using this one: https://github.com/elishacloud/dxwrapper
Or DXVK: https://github.com/sTc2201/dxvk

**Comment by Plokhi** [comment]
I use both, without ThirteenAG d3d9.dll, FusionFix wont load and without DxWrapper you linked i get stuttering.
DXVK unfortunately doesn’t work on Parallels :(

**Comment by RecklessGlue540** [comment]
> doesn’t work on Parallels

What do you even mean by this?

**Comment by Plokhi** [comment]
I'm running this on a Mac via Parallels virtualisation software 
(i know i know, but it really is playable aside the glitches).

I've broken everything somehow so i'm doing it from scratch again and i'll try this in addition https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders

**Comment by Plokhi** [comment]
reinstalled and same happens, it's making me go crazy lol

**Comment by Plokhi** [comment]
so, 1.9.6 works, but 2.0.0 immediately this start to happen. There's something changed between v1 and v2 that causes it

**Comment by Plokhi** [comment]
this is fusionfix v2.0 - everyyhing set to LOW or OFF, check top left corner of the window

<img width="1280" alt="Screenshot 2024-04-06 at 17 35 48" src="https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/37208555/58f62e4c-638f-4f17-bd50-5d1f797c6474">

**Comment by Plokhi** [comment]
it becomes much worse with "definition", but "classic" seems to make it by far the least offending.

**Comment by RecklessGlue540** [comment]
You should honestly expect issues like these on a Mac using translation software...

**Comment by Plokhi** [comment]
it seems to be "centered" around specific areas moreso than other things for some reason
![Uploading Screenshot 2024-04-06 at 17.51.53.png…]()

**Comment by Plokhi** [comment]
I mean, yeah - but there's something in FusionFix newer than 1.96 that triggers it :) since FusionFix isn't exaggerating something present in the game even running FusionFix 1.96

there also appears to be some specific areas that behave exceptionally worse than others

<img width="1728" alt="Screenshot 2024-04-06 at 17 51 53" src="https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/37208555/4aa18e2e-957a-4485-a9d5-eb3126f7d11d">

**Comment by Plokhi** [comment]
I removed rage_postfx.fxc from the shaders folder and the issue is gone... However, so are the windshields and all car windows :D

**Comment by Plokhi** [comment]
so i guess it's something with some shader? if i remove some other shader this doesn't happen, but i have no clue how to fix this. It's so hard to go back to non-fusionfix now lol, it looks broken

**Comment by Plokhi** [comment]
Nevermind, i just discovered the same pattern when disabling fusionfix. the only thing is it only appears from inside (i.e. taxi) and it's black and much less pronounced. 
So it's part of the issues outside the mod - the mod just exaggerates it. 

oh well

**Comment by Plokhi** [comment]
I managed to partially fix it by replacing the rage_postfx.fxc with the original one

**Comment by Plokhi** [comment]
So apparently i lose Bloom, DOF. (i mean, postfx,eh?)
I keep AA and most of other stuff.
What's odd is the issue is completely gone even in taxi through windows! 

wish i was smart enough to fix postfx shader myself :)
