### ISSUE TITLE
TBOGT slow texture streaming and missing models after long play session

### ISSUE THREAD

**Issue by Asneb** [ThirteenAG/GTAIV.EFLC.FusionFix#474]
### Game version this happens in

v1.2.0.59

### What area of the game

It happens during long play sessions or after flying at high speeds through Liberty City as shown in the screenshot textures fall back to lower resolution and lod models are loaded instead of the normal ones
![20230826031208_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/87947601/a3b27bcd-9822-4ca5-af44-967e3ce4b24f)

### What should happen

tlad and the base don't suffer from this issue as far as i know.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Asneb** [comment]
![20240413140741_1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/87947601/35c78298-cdc9-4a88-a347-8c0a4dfb9752)
managed to trigger it on lost and damned too , about an 1 hour play session 
command line settings: -forcehighqualitymirrors -norestrictions -nomemrestrict -availablevidmem 8192 -width 2560 -height 1440

**Comment by juicermv** [comment]
What are your specs? Is the game installed on an SSD or HDD and which exactly?

**Comment by Asneb** [comment]
> What are your specs? Is the game installed on an SSD or HDD and which exactly?

Processor Ryzen 7 3700x
Graphics Card RTX 3060ti
RAM DDR4 16GB(2*8 3200mhz CL14)
512gb gen 3 nvme boot drive
1tb sata 3 ssd (game is installed in that drive) 

I used gillians drag and drop archive , tried increasing the budget on fusionfix.ini to no avail.

**Comment by juicermv** [comment]
That's odd, your hardware seems fine. Can you verify this issue is specific to FusionFix?

**Comment by Asneb** [comment]
> That's odd, your hardware seems fine. Can you verify this issue is specific to FusionFix?

seems to happen when you use any kind of texture or vehicle mods, post from back from 2013 same issue 
https://gtaforums.com/topic/558441-gta-iv-texturespawning-issues/
this guy is running no mods though 
https://www.reddit.com/r/GTAIV/comments/18x1x1f/gta_iv_modding_texture_issues/

**Comment by Tomasak** [comment]
FusionFix not installed from here, or Radio Restoration mod (http://downgraders.rockstarvision.com/) or IV Fixer (https://gtaforums.com/topic/996609-iv-fixer/) are not supported here because they might contain outdated or anyhow modified FusionFix that might cause issues, or might be packed with incompatible mods/mods causing issues. Since you used Gilligan's guide, you should report bug to his own repo https://github.com/gillian-guide/GTAIV.EFLC.FusionFix-GFWL
