### ISSUE TITLE
Aiming Zoom Fix doesn't reflect on controllers

### ISSUE THREAD

**Issue by melody-cheung520** [ThirteenAG/GTAIV.EFLC.FusionFix#477]
### What should happen

Whenever I try to zoom aim on controller it won't remember the states like on Xbox. But when playing with mouse. The fix is perfectly fine. An inconvenience for controller players.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by melody-cheung520** [comment]
Hi there, 
Is this fix available in the new update yet? No rush but seeking for the feature on controller as soon as possible. Thanks ❤

**Comment by ThirteenAG** [comment]
Not yet available. Have to wait for the next release, whenever that might be.

**Comment by melody-cheung520** [comment]
Counting on you!😆
