### ISSUE TITLE
Centering Delay, FOV sliders don't save right

### ISSUE THREAD

**Issue by RecklessGlue540** [ThirteenAG/GTAIV.EFLC.FusionFix#478]
### Game version this happens in

v1.2.0.59

### What area of the game

When you set Centering Delay (both kbm and gamepad) or FOV options above 0, exit the game, delete just save data afterwards, and reboot the game (into a new game as it is by default), the respective options' sliders will look empty, while the options will still be in effect. It's just something visual, but I think it's worth pointing out.

Normal behavior:
![GTAIV 4_22_2024 1_42_21 PM](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143945383/40133e83-73fb-4d48-b9b5-196ce6c1b4bb)

After rebooting the game with only save data deleted (from both documents and appdata):
![GTAIV 4_22_2024 1_43_43 PM](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/143945383/3441bc5a-1374-4b02-ac16-6fb950eedf6b)

### What should happen

Just like the other options, the sliders visually should stay set to the value that is specified in the .cfg, and not look empty after save data is deleted.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by hammerfist11** [comment]
so its just tied to save data? ... don't see how its an issue tbh, its just how its implemented

**Comment by juicermv** [comment]
The issue is the implementation, yeah.
