### ISSUE TITLE
Borderless Windowed Mode doesn't work with FusionFix for Game Version 1.0.8.0 using XLivelessAddon

### ISSUE THREAD

**Issue by RedFalcon10** [ThirteenAG/GTAIV.EFLC.FusionFix#48]
Enabling Borderless Windowed Mode does nothing using XLivelessAddon configuration file. The game seems to still run in full screen. Can anyone please look into this issue? I know this issue could be fixed in the latest version of FusionFix, but I still run the old CD version of the game. I hope that this can be fixed for the old version too.

**Comment by Coldhaz** [comment]
The reason why is because xliveless already has this option so it will xliveless will overide this
