### ISSUE TITLE
[Feature Request] Better SSAA settings

### ISSUE THREAD

**Issue by ShinChaosBahamut** [ThirteenAG/GTAIV.EFLC.FusionFix#480]
### What should happen

Would like a SSAA setting that's more in-depth than a simple 2x SSAA toggle. Perhaps a Resolution Scale option that can go up to 200%? (which would be the same as 2x2 SSAA; more commonly referred to as 4x SSAA)

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by ElTioRata** [comment]
I'm getting jagged edges even with 2x SSAA, having an option to adjust it up to 8x SSAA would be great.

**Comment by juicermv** [comment]
profile picture brother
