### ISSUE TITLE
[Feature Request] Inherit Windows resolution onto game (DXVK)

### ISSUE THREAD

**Issue by rsm86** [ThirteenAG/GTAIV.EFLC.FusionFix#481]
### What should happen

Hey guys - quick preface -- this is very niche, but hopefully not too hard to implement and interesting to people.

I mainly game nowadays through streaming (sunshine + moonlight) through various client devices (my 16:10 display laptop, an nvidia shield hooked up to a 4k TV, my modded nintendo switch, among others). This basically means that it is very common for me to launch GTA IV with different resolutions and aspect ratios as I have sunshine set up in such a way that it auto matches my client resolution. For "modern" games this is not an issue. Playing with borderless window usually means that the game launches at the same desktop resolution I'm using.

For GTAIV (using FusionFix and DXVK of course), this is not the case. Every time I have to manually go into settings and pick the resolution of the device I'm currently streaming to. In my non developer mind, if there was a way for GTAIV to inherit the resolution set for the Windows Desktop, this would automatically solve the issue. Granted I have no idea how feasible or hard to implement this is, and I am acutely aware this is a 1st world problem.

Could this be done?

Thanks for reading!

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by MagicAl6244225** [comment]
Probably the way you should do this is make different desktop shortcuts to launch the game and specify your different resolutions in the launch options of each shortcut.
