### ISSUE TITLE
FusionFix settings problem!!

### ISSUE THREAD

**Issue by sudosu-arch** [ThirteenAG/GTAIV.EFLC.FusionFix#483]
### Game version this happens in

v1.2.0.59

### What area of the game

I installed a lot of versions of this mod in a clean "GTA IV: The complete edition" (v1.2.0.59 Steam+Rockstar) game and in all cases the mod does not work correctly except in an old version of the mod. 

The proccess is the next:
1º Installing the GTAIV.EFLC.FusionFix v2.5.6 to "C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto IV\GTAIV"
<img width="599" alt="image" src="https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/115696914/9704957e-b950-4015-879e-b3676020d28b">

2º Launch the game and go to Options menu:
Controls:
<img width="1382" alt="image" src="https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/115696914/cda65256-828d-44ba-8e5e-8a5ba0102ed5">
Screen:
<img width="1382" alt="image" src="https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/115696914/3cdf09cd-2f63-4961-bd88-6c7dead62ae9">
Graphics:
<img width="1382" alt="image" src="https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/115696914/b9f576ec-19a7-41ef-bf89-a9de0c6dc7d6">
Gameplay:
<img width="1382" alt="image" src="https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/115696914/19064d73-7452-4c1c-9f0f-2be0b8cdc9fb">

When a value is changed, all options are affect with the same value.

3º Delete the last version of the mod (v2.5.6) and install an old version (v1.7.7)
<img width="572" alt="image" src="https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/115696914/bce191b5-a734-4b9a-a5cf-3f221b963bd1">

4º When execute the game, automatically load the las savegame (skiping intro) and the options shows correctly:
Gameplay:
<img width="1716" alt="image" src="https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/115696914/7299a407-c91d-4941-abaa-7b98baf2d2c0">
Screen:
<img width="1716" alt="image" src="https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/115696914/1c2a1fb2-c110-46ab-9a20-ba70f521c38b">

I'm try to installing the last version of ASI Loader to the current version of the mod and shows the same problem.
Tested v1.96 and works too. 

From the FusionFix v2.0, the mod looks like with this problem.

### What should happen

The mod should works correctly in the last version of the game.

### Last working version

v1.96

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Gorphus** [comment]
I’m having the same problem unfortunately.

1.96 works indeed, from version 2.X the settings all change together.
