### ISSUE TITLE
Disable the FPS counter in menu

### ISSUE THREAD

**Issue by nomadspy** [ThirteenAG/GTAIV.EFLC.FusionFix#484]
### What should happen

Is there a command line that disables this feature? I'm looking for the ultimate vanila experience and I need it disabled. I can remove all the settings of Fusion but the FPS counter always remain in menu. Thank you to whomever answers and the developer for such wonderful fix.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
It's added in there so you can troubleshoot which settings affect your framerate the most, considering the fact it even respects the episodes' colors and the game's original font, I think it's pretty authentic...
