### ISSUE TITLE
[Feature Request]    Only Independence FM mode

### ISSUE THREAD

**Issue by PercyTheWolf** [ThirteenAG/GTAIV.EFLC.FusionFix#485]
### What should happen

When streamers and YouTubers do a playthrough on GTA IV all the radios will be turned off completely to avoid copyright claims. My idea is to have an option called only Independence Mode, which will replace all radios with just the custom radio called Independence FM

I understand that posting this is probably not the correct way to request a feature, but I feel like this would be a good feature for a future update.

### Checklist

- [x] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
> ### What should happen
> When streamers and YouTubers do a playthrough on GTA IV all the radios will be turned off completely to avoid copyright claims. My idea is to have an option called only Independence Mode, which will replace all radios with just the custom radio called Independence FM
> 
> I understand that posting this is probably not the correct way to request a feature, but I feel like this would be a good feature for a future update.
> 
> ### Checklist
> * [ ]  Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
> * [x]  [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

To be honest, I don't see any point in having something like this. It's very easy to turn off the radio, and same is switching to Independence FM manually. I doubt anyone gets copyright striked unless they let the copyrighted music play for too long...

**Comment by PercyTheWolf** [comment]
It's totally understandable if adding something like this doesn't seem ideal.
Since this project likes to add a ton of customization for anyone to toggle, I thought it be a good feature to suggest/request.

**Comment by Tomasak** [comment]
this is more of an audio dat editing, i might cook up something later, that would mute radio. but still, there is a lot of cutscenes with baked in licensed music
