### ISSUE TITLE
Alt tab causes black screen and freeze

### ISSUE THREAD

**Issue by Tophetei** [ThirteenAG/GTAIV.EFLC.FusionFix#486]
### Game version this happens in

v1.2.0.59

### What area of the game

Any moment when the game is focused, be it in game, in the pause menu, in the menu to select which game to play or even the intro. Sometimes I can alt tab once but not twice, other times I cant alt tab at all.

### What should happen

You should be able to alt tab in and out of the game with no issue.

### CrashDumps and logs

Dump : https://mega.nz/file/19JkgY5Q#9_WfeMEwsgNkXJXoGRzweUsXkR28gNoXLQI1ad9VmSk
Log : https://mega.nz/file/MtZRjIDD#uqa82m34xjoCYFlzX2Py-_mKSyoeJpO7AAAAAAAAAAA

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by RecklessGlue540** [comment]
Alt tabbing is pretty volatile in this game .
Can you maybe test placing this in a commandline.txt in the game's directory?

-noBlockOnLostFocus

If it still behaves the same, probably look into DXVK , it might behave differently.

**Comment by Tophetei** [comment]
Sorry for the late answer.
I just tested and it doesn't change anything. I dont have DXVK installed right now

**Comment by LaupaMag338** [comment]
> Sorry for the late answer. I just tested and it doesn't change anything. I dont have DXVK installed right now

Try using -windowed

**Comment by juicermv** [comment]
FusionFix has a borderless windowed option so this isn't even needed, just turn that on.

**Comment by ca5dx** [comment]
Yeah alt+tab crashes the game and If I change the resolution ingame it also crashes. Borderless windowed option does nothing.

**Comment by Tomasak** [comment]
really latest 1.2.0.59 or 1.0.7.0?

**Comment by ca5dx** [comment]
> really latest 1.2.0.59 or 1.0.7.0?

Both. I'm starting to think a Windows update fucked it up somehow.
