### ISSUE TITLE
Error 126 when launching game and settings are bugged. (Using Lutris) *FIXED*

### ISSUE THREAD

**Issue by Bastigonzales** [ThirteenAG/GTAIV.EFLC.FusionFix#487]
### Game version this happens in

v1.2.0.32

### What area of the game

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/42995601/dcd3de5a-5691-4e38-83b3-3641dd37b51c

![Screenshot from 2024-05-20 18-49-56](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/42995601/b73a346c-b139-4fe9-81fe-9234cbd856c7)

![Screenshot from 2024-05-20 18-50-39](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/42995601/83a44eb3-2868-41b0-a72b-ec83966a3823)

### What should happen

Game is completely playable but the settings are bugged after installing FusionFix.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Bastigonzales** [comment]
UPDATE: It's a simple fix all I have to do was open winetricks in Lutris and Install a missing dependency which is **VC 2012 Redist**

**Comment by juicermv** [comment]
Happy you found a fix but you should close the issue lol

**Comment by Bastigonzales** [comment]
> Happy you found a fix but you should close the issue lol

ayo my bad, all good now 🤣
