### ISSUE TITLE
[Feature Request] Disengage ingame VSync during loading screens

### ISSUE THREAD

**Issue by RecklessGlue540** [ThirteenAG/GTAIV.EFLC.FusionFix#493]
### What should happen

Just found out Max Payne 3 actually does this, possibly for faster loading... I think it'd be easy enough to implement it here too in that case...
But we'd also need extra fixes for the UI animation speeds then...
Also, since the ingame VSync is double buffered, maybe we could also have triple buffering as an option for it? Probably a bit useless since DXVK already provides this option, but oh well...

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by juicermv** [comment]
I don't think loading speed is related to framerate lol

**Comment by juicermv** [comment]
Is it? Interesting

**Comment by RecklessGlue540** [comment]
> Is it? Interesting

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/302

Actually, I think it's just the "starting a new game..." and benchmark tool loading depending on the framerate. 
Other stuff loads okay I guess...

**Comment by Tomasak** [comment]
Impossible in DirectX 9. Max Payne 3 doesn't disable it too if you play in DX9

**Comment by RecklessGlue540** [comment]
Interesting to know, thanks.
