### ISSUE TITLE
Issue: Complete Edition loads straight into GTA IV rather than the launcher

### ISSUE THREAD

**Issue by pheonix8905** [ThirteenAG/GTAIV.EFLC.FusionFix#494]
### Game version this happens in

v1.2.0.59

### What area of the game

After some testing, I've found that FF skips straight past the launcher, thus effectively disabling access to TLaD and TBoGT. I have no idea if this is user error, or if there are fundamental differences between EFLC and the Complete Edition. The legal screens show for a few frames, before showing the loading slides and loading into GTA IV, no Rockstar logos. I tested a fresh install of GTA then with just FusionFix

### What should happen

Usually it would show the legal screens and logos for a few seconds, then the launcher to choose between the main game and EFLC.

### CrashDumps and logs

[asilog.txt](https://github.com/user-attachments/files/15744018/asilog.txt)
[scripthook.log](https://github.com/user-attachments/files/15744020/scripthook.log)
[ScriptHookDotNet.log](https://github.com/user-attachments/files/15744021/ScriptHookDotNet.log)
[AdvancedHookInit.log](https://github.com/user-attachments/files/15744022/AdvancedHookInit.log)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by MagicAl6244225** [comment]
FusionFix has an option you may disable in the .ini file, in the plugins folder, to skip the launcher, which during a playthrough is great to speed up getting back to your current game's save. The launcher-free behavior is like the original console game's startup, where you can start a new game in any episode from the pause menu after the game has started.

**Comment by pheonix8905** [comment]
> FusionFix has an option you may disable in the .ini file, in the plugins folder, to skip the launcher

Thanks for the quick reply; I've looked into the ini, but don't see that option, is there something I'm missing?

**Comment by MagicAl6244225** [comment]
My mistake. These options have actually been moved to the custom pause menu in game. Skip intro and Skip menu.

**Comment by pheonix8905** [comment]
Ah, okay. I never bothered to check in-game, thank you
