### ISSUE TITLE
Gamepad sensitivity increases by using FusionFix

### ISSUE THREAD

**Issue by knerlington** [ThirteenAG/GTAIV.EFLC.FusionFix#5]
Using FusionFix the sensitivity using a gamepad becomes way too high while inside vehicles. Shouldn't be affected at all. Unsure if it's altered on foot.

This is with GTAIV version 1.0.8 with XLiveLess installed in order to utilize FusionFix.

**Comment by xDShot** [comment]
Happens when HandbrakeCamFix is enabled. Tested on Steam Complete Edition.

**Comment by ThirteenAG** [comment]
I know, but don't know what to do with it. Suggestions and pull requests are welcome.

**Comment by GoingToAruba** [comment]
Should probably add something like this to GTAIV.EFLC.FusionFix.ini in order to prevent people from running into this issue: 'Disable this feature when using a controller, it breaks/incorrectly increases camera sensitivity in vehicles while using one'
