### ISSUE TITLE
Mod not working with 1.0.8.0 version of the game

### ISSUE THREAD

**Issue by jonnyprogamer** [ThirteenAG/GTAIV.EFLC.FusionFix#500]
### Game version this happens in

v1.2.0.59

### What area of the game

Hello, im trying to use this mod on the 1.0.8.0 version of the game, basically i tried using it without adding xliveless (and i was told that FusionFix will be running in backwards compatibility mode, and i should rename Asi Loader as Xlive.dll and also use XLiveLessAddon) and the mod just didn't work in game, it showed nothing in the options, then i tried to actually use it the intended way with XliveLess, and nothing, it would still not show anything in game (the mod seems to be loading though cause the Intro gets skipped)
Then i tried to use FusionFix + the GFWL mod found here: https://github.com/gillian-guide/GTAIV.EFLC.FusionFix-GFWL to use FusionFix while keeping GFWL enabled, and my game would immediately crash after the first mission starts.
Things tried:
- Reinstalled the mod
- Reinstalled the game and tried to apply the mod again (i have the original files backed up but i reinstalled just in case)
- Used the latest version of Ultimate Asi Loader

The only version that worked for me is this (preCE): https://github.com/Zolika1351/GTAIV.EFLC.FusionFix

Im very confused because multiple guides say that this Mod works with the older versions (1.0.8.0 and 1.0.7.0) however in my case it just doesn't work (loads but no options in game), and only the "PreCE" fork seems to be working perfectly with no problems.

I would really like some help if possible, i tried everything to make it work, thanks.

Screenshot of game folder with only 1.0.8.0 and FusionFix are attached, with bundled "dinput8.dll" renamed as "xlive.dll", and "XLiveLessAddon" installed:

### What should happen

The options should show up in the menu or am i doing something wrong? (this is without the "GFWL" fix, im using XliveLessAddon)
![Grand Theft Auto 4 Screenshot 2024 06 16 - 14 22 50 82](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/93492418/0f5445e7-7764-4ace-bdd7-8176a7f73396)
![Grand Theft Auto 4 Screenshot 2024 06 16 - 14 22 54 34](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/93492418/765816a2-3720-4381-ae90-c74f82a342e7)

Game Folder:
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/93492418/3e2bff19-c767-4471-a5b0-01a920fde48b)

Plugins Folder:
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/93492418/bc751cda-c7d6-4e6f-a80b-39385cc31eeb)

Instead if i use "PreCE" version everything shows up in the options as expected:
![Grand Theft Auto 4 Screenshot 2024 06 16 - 00 06 41 38](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/93492418/6e412bb3-aa7c-4f75-a994-f98c399c89f4)

### CrashDumps and logs

No crash dump because the game doesn't crash, it just loads without showing options in game.
It only crashes if i apply the "GFWL" fork of this mod (https://github.com/gillian-guide/GTAIV.EFLC.FusionFix-GFWL) on top of it but since it's unrelated from this version (as far as i understood) i don't think that i should be reporting that issue here.

Latest build also has the same behaviour (Game loads, mod seems to load as intro is skipped, CFG file gets created, but there are no options showing up in game menu)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by jonnyprogamer** [comment]
@Tomasak Uh why was this closed? is it because 1.0.8.0 is not supported? Then why is the mod listed as supported here?
https://gillian-guide.github.io/essential-modding/fusionfix/#installation

**Comment by RecklessGlue540** [comment]
No support for downgraded versions is provided here. If you want support, ask somewhere else or just stay on CE. Downgrading isn't necessary after all...

**Comment by ThirteenAG** [comment]
> @Tomasak Uh why was this closed? is it because 1.0.8.0 is not supported? Then why is the mod listed as supported here? https://gillian-guide.github.io/essential-modding/fusionfix/#installation

Why are you asking here about things someone else made?
https://github.com/gillian-guide/GTAIV.EFLC.FusionFix-GFWL/issues
Good luck.

**Comment by jonnyprogamer** [comment]
> Why are you asking here about things someone else made? https://github.com/gillian-guide/GTAIV.EFLC.FusionFix-GFWL/issues Good luck.

Im not refering to that, i said that adding it crashes my game, im focussing on your work right now:

>It only crashes if i apply the "GFWL" fork of this mod (https://github.com/gillian-guide/GTAIV.EFLC.FusionFix-GFWL) on top of it but since it's unrelated from this version (as far as i understood) i don't think that i should be reporting that issue here.

Right now the problem is that with your mod the options do not show up, ingore the GFWL thing i shouldn't have mentioned it at all, but you can even see from my screenshot that it's not installed

**Comment by jonnyprogamer** [comment]
@ThirteenAG Look what i want to know is does your mod work on preCE or not? cause all these guides keep saying that your version works but it clearly doesn't in my case so am i wasting my time reporting this issue or what?

**Comment by jonnyprogamer** [comment]
> No support for downgraded versions is provided here. If you want support, ask somewhere else or just stay on CE. Downgrading isn't necessary after all...

Are you the guy from Reddit? If yes look then don't suggest me that this mod works on 1.8 when it clearly doesn't

**Comment by ThirteenAG** [comment]
Why are you asking me? Ask the authors of these guides.

If you install the official release on latest game version(CE) and have a problem with that, open another issue.

**Comment by jonnyprogamer** [comment]
> Why are you asking me? Ask the authors of these guides.
> 
> If you install the official release on latest game version(CE) and have a problem with that, open another issue.

Alright, yes i have no problem with you if you don't support the older version, it's clear that then this guy making this guide is spreading misinformation.
Is there any way for me to get this version without buying the game again?

**Comment by ThirteenAG** [comment]
https://support.rockstargames.com/

**Comment by Tomasak** [comment]
> Is there any way for me to get this version without buying the game again?

Active cd key from back of manual on rockstar games launcher
