### ISSUE TITLE
TLaD Brokes when installing FusionFix

### ISSUE THREAD

**Issue by IgLocoXD** [ThirteenAG/GTAIV.EFLC.FusionFix#502]
### Game version this happens in

v1.2.0.43

### What area of the game

When I start the first mission of TLaD the game crashes after the cutscene in the bar, it crashes specifically in this place https://www.youtube.com/watch?v=rl2b6rfXU9w (idk the name of the street sorry, but this video should work)
Also, when I try to load my save file that I already did this mission, it says its damaged/corrupted, but when I load it on a clean GTA IV copy it works perfectly.

NOTE TO ADD: Idk if the crash is so bad that it doesn't even generate any type of crash log, I tried using it with and without ASI Loader, and with and without Radio Downgrader

### What should happen

It shouldn't crash.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Tomasak** [comment]
I see your game is modified beyond radio restoration and fusionfix, the hud is clearly IV's with tlad grudge effect over it, try on clean game and check if it crashes.
