### ISSUE TITLE
[Feature Suggestion] GTAO (Not GTA Online lol)

### ISSUE THREAD

**Issue by juicermv** [ThirteenAG/GTAIV.EFLC.FusionFix#511]
### What should happen

With recent updates we now have WIP SSAO, I think it would be nice if the SSAO implementation we ended up with was GTAO since it's the most accurate currently. GTAO is also what's used in MartyMcfly's MXAO and DS2 Lighting Engine (which is a mod that completely overhauls Dark Souls 2's rendering pipeline and graphics.)

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
I mean, RaphaelK already said he might consider implementing HBAO or HDAO if he gets the main SSAO working first...
From a quick read on the net, GTAO seems to work on DX12 and higher shader model versions, but I can't confirm totally.
Even if it might be possible to backport to DX9, I think having HBAO and HDAO both, or even just one of these as additional options over the normal SSAO would suffice.

As we've seen with the PCSS removal (which is sad really), poor game just can't really take much anymore.

**Comment by juicermv** [comment]
And btw, if the FusionFix team manages to hook the DirectX code to the point of device creation (something DS2LE does), it is possible to utilize dx9on12, which creates a hybrid DX9 device on top of DX12 which can handle both DX9 and DX12 commands. dxwrapper already does this too, although it has some issues.
