### ISSUE TITLE
[Question] What happened with PCSS?

### ISSUE THREAD

**Issue by juicermv** [ThirteenAG/GTAIV.EFLC.FusionFix#512]
### What should happen

So after recent updates, PCSS has been completely removed from FusionFix. Is this permanent?

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by juicermv** [comment]
Is there any chance you guys could maybe look into a custom variable penumbra softening solution? The game really doesn't look the same without it unfortunately

**Comment by RecklessGlue540** [comment]
Does the recent increase in shadow distance make PCSS harder to work properly too? 
Would the calculations work better if OverrideCascadeRanges is disabled?

Asking because GTAV does this:
Once PCSS or CHS is enabled, the shadow distance gets a significant decrease, and I was wondering if that was done for performance reasons (on PC lol), or for them to even work at all...

**Comment by Parallellines0451** [comment]
```
Does the recent increase in shadow distance make PCSS harder to work properly too?
Would the calculations work better if OverrideCascadeRanges is disabled?
```
No. OverrideCascadeRanges shouldn't need to be disabled under any circumstances.

Firstly, PCSS was not removed from FusionFix for performance reasons. Robi29 did an excellent job working around the limitations of the game's horrible cascaded shadowmap implementation, but it came at the cost of artifacts whenever the penumbra got too large, and we couldn't find a practical way to avoid it.

Aside from that, the entire shadow code was rewritten for the next version of FusionFix to be much more clean, efficient, and produce [significantly better looking results](https://youtu.be/oVoAkUqZkSU), as well as to support the new ShadowSoftness and ShadowBias parameters, which replace the predefined "Shadow Filter" settings.

While most of these improvements could be adapted to accommodate for PCSS in some way, it would add significant unnecessary complexity to everything that was already done and on the way. With that in mind, and the aforementioned artifacts, the decision was made to instead focus on making normal shadows look as good as possible and to deprecate PCSS. 

While it may be upsetting to some people to see a feature that was added with FF 2.0 be removed, in return you'll get much better looking shadows overall, which are also more faithful to how they should look (in regards to consoles and versions prior to 1.0.6.0).

**Comment by juicermv** [comment]
I think the only issue is that that kinda compromises detail on characters, since they won't have sharper shadows anymore.

Although, I guess the question is whether screen-space shadows would be possible to implement in DX9?

**Comment by Parallellines0451** [comment]
I wouldn't call it a "compromise" as it's not a base game feature to begin with.
You can make shadows as sharp as you want with the new parameters if you so desire.

Screen space shadows are possible and there have been some talks about it, but nothing planned so far.

**Comment by juicermv** [comment]
Eh, it's not a base game feature but it was a feature that the mod had and was removed so still. 

Also, making all the shadows universally sharp kinda defeats the point lol. I do hope you guys manage to implement screen-space shadows, as that would be amazing. 

The time and work you guys are putting into preserving and modernizing this game is truly magnificent, there's no other way to describe it. 

Perhaps you guys could talk with the guy behind DS2LE, he's been doing very similar work (although for DX11)

**Comment by Joris-truly** [comment]
> 
> Aside from that, the entire shadow code was rewritten for the next version of FusionFix to be much more clean, efficient, and produce [significantly better looking results](https://youtu.be/oVoAkUqZkSU), as well as to support the new ShadowSoftness and ShadowBias parameters, which replace the predefined "Shadow Filter" settings.
> 
> While most of these improvements could be adapted to accommodate for PCSS in some way, it would add significant unnecessary complexity to everything that was already done and on the way. With that in mind, and the aforementioned artifacts, the decision was made to instead focus on making normal shadows look as good as possible and to deprecate PCSS.

I have to disagree with the quality thing. Been trying v3 Using the default config settings, the projected sun shadows are way more jittery and unstable in motion then the previous PCSS solution.
