### ISSUE TITLE
[Feature request] Don't set Skip Intro/Menu by default.

### ISSUE THREAD

**Issue by Yujah** [ThirteenAG/GTAIV.EFLC.FusionFix#513]
### What should happen

Thanks for FusionFix! Have been spamming a link to it into Steam's GTA4 forum daily for quite a while now. The Skip Intro/Menu options being set by default tend to confuse; worst when someone is experiencing a cutscene/fps hang directly when starting into the game. F.e. https://steamcommunity.com/app/12210/discussions/0/6918175569134985639/#c4514379280322560958. Also more generally confuses (some) users about not finding the DLCs. Would feel it better if those weren't on by default from a clean install.

While I'm here... another (small) thing is that some people install into the wrong folder. You specify "your GTAIV: The Complete Edition root directory" without making explicit that that's referring to e.g. on Steam (SteamLibrary)\steamapps\common\Grand Theft Auto IV\GTAIV\, i.e., to what can conceivably be considered the GTAIV subdirectory of said root directory. If you on Steam "Browse local files" it puts you into that directory one up.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by ThirteenAG** [comment]
> users about not finding the DLCs.

I propose rolling the credits right after startup. What if some users don't know how to walk, or shoot, or drive. That way everyone can play the game and get to the credits.

**Comment by Yujah** [comment]
The specific thing as to an initial hang for a completely new user as linked is the important one. Given that's it's (supposedly as pr your reply) easy to find anyway once the user actually gets there it's just the default which I find to be sub-optimal.

**Comment by ThirteenAG** [comment]
It will hang regardless of skip intro and skip menu. It doesn't for all testers we have here.

**Comment by Yujah** [comment]
Every few years I make this same mistaken again: post an issue onto some open-source project's bugzilla...

Best of luck with your thingy.

**Comment by ThirteenAG** [comment]
It's not a bug, that's the whole purpose this project exists: to skip that intro and to skip that useless menu. Other stuff is just extra.

**Comment by Yujah** [comment]
So it not being a bug is why I called it a feature request rather than a bug. But, seriously, best of luck otherwise.

**Comment by ThirteenAG** [comment]
It's not planned. As for the root directory, I will add "where exe is" to readme.
