### ISSUE TITLE
White bars when pausing and crash

### ISSUE THREAD

**Issue by Anesred** [ThirteenAG/GTAIV.EFLC.FusionFix#516]
### Game version this happens in

v1.2.0.59

### What area of the game

Sometimes when I pause, white bars appear in the menu (or a white box covering the map) when I unpause/load game, the game crashes
![20240721182854_1](https://github.com/user-attachments/assets/752bcef1-989d-477a-840c-1c9ed3f630ac)
![20240721182913_1](https://github.com/user-attachments/assets/c02bcb29-7f61-4aca-b353-57b9467d585c)

### What should happen

White box should not appear and it shouldn't crash

### CrashDumps and logs

[GTAIV.exe.20240721184055.dmp](https://github.com/user-attachments/files/16325302/GTAIV.exe.20240721184055.dmp)
[GTAIV.exe.20240721184055.log](https://github.com/user-attachments/files/16325304/GTAIV.exe.20240721184055.log)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Ash-735** [comment]
That looks like it's having issues with TBOGT's version of frontend.wtd, do you have a modded one?

**Comment by Anesred** [comment]
> That looks like it's having issues with TBOGT's version of frontend.wtd, do you have a modded one?
Haven't done anything to it, but I'll try to delete it and verify game cache and will let know if the issue persists

**Comment by Anesred** [comment]
Yeah, it seems like I did put a modded frontend.wtd in the update folder, seems to work now
