### ISSUE TITLE
Black Screen with the resolution of 2560x1440, 

### ISSUE THREAD

**Issue by EliTeSYB** [ThirteenAG/GTAIV.EFLC.FusionFix#524]
### Game version this happens in

v1.2.0.59

### What area of the game

When i installed fusionfix on my game while i had the resolution of 2560x1440 in the graphics settings when i try to start the game with PlayGTAIV.exe i get a black screen no intro, no menu just a infinite black screen what i did is uninstalled fusionfix changed the resolution for my game to 1920x1080 then reinstalled fusionfix it solved the issue hope this you guys update it to make it support 2k (2560x1440) also my game version is EFLC (  1.0.7.0  ) downgraded hope this gets fixed asap.

### What should happen

it shouldn't view a black screen

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by juicermv** [comment]
I have a 1440p screen and everything is fine for me, bold of you to assume they just didn't support this extremely common resolution, lol. 

Anyway, It's probably an issue on your end. As far as I know, the mod does not officially support 1.0.7.0 anyway.

**Comment by Ash-735** [comment]
Yeah sadly can't repro this one, maybe check your nvidia driver settings for any scaling issues, I've even tried off shoot resolutions like 1620p and the game scales fine to them.

**Comment by t-ro86** [comment]
I have similar problem with dxvk, without it everything is ok, dxvk with the last ffix doesn't allow me to use resolution above 1920x1080.

**Comment by RecklessGlue540** [comment]
You're using an older version of DXVK then.

2.4 fixed the resolution detection, grab it from the official link:
https://github.com/doitsujin/dxvk/releases/tag/v2.4

**Comment by t-ro86** [comment]
> You're using an older version of DXVK then.
> 
> 2.4 fixed the resolution detection, grab it from the official link: https://github.com/doitsujin/dxvk/releases/tag/v2.4

The same with 2.4 dxvk

**Comment by RecklessGlue540** [comment]
then idk, that command isn't necessary anymore for me.

**Comment by t-ro86** [comment]
I want to say that I fixed the problem by enabling Windowed Borderless. Now I can play with dxvk and with any resolution!
