### ISSUE TITLE
Check for updates option/ Vehicle headlight shadows

### ISSUE THREAD

**Issue by Adas8812** [ThirteenAG/GTAIV.EFLC.FusionFix#528]
### Game version this happens in

v1.2.0.59

### What area of the game

Firstly, what's the "check for updates " section in the options menu? Does it update the files (fusionfix master files) while the game loads? Is there any indication that stuff's updated? How does this feature work?

Secondly, in the .INI file changing (even though It's not rocommended I know) lines related to vehicle shadows/headlight shadows: from 0 to 1  - makes no 
difference while playing the game. Aka no dynamic vehicle headlight shadows appear. Is this intencional?

### What should happen

-

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by RecklessGlue540** [comment]
Check for updates should start working when the next release actually rolls out for us all.

Vehicle headlight shadows will have absolutely no effect if vehicle night shadows option is enabled. Turn it off and it'll work.
