### ISSUE TITLE
No option to disable camera centering in 2.5.6

### ISSUE THREAD

**Issue by s193067** [ThirteenAG/GTAIV.EFLC.FusionFix#530]
### Game version this happens in

v1.2.0.43

### What area of the game

N/A

### What should happen

The option to disable camera centering was added in 2.1, but I can't find it or see it (I checked controls > mouse and keyboard and everywhere else in-game and also .ini and .cfg files). All I can do is modify the centering delay, which does work properly.

I also don't see the option to disable auto centering in cover.

### Screenshots

![Grand Theft Auto 4 Screenshot 2024 08 05 - 03 07 52 62](https://github.com/user-attachments/assets/f648e577-b54f-489f-ac3a-435fa0a770cc)
![Grand Theft Auto 4 Screenshot 2024 08 05 - 03 08 14 92](https://github.com/user-attachments/assets/4173d8c1-22e3-4d5b-90b9-706feeaae5a1)
![Grand Theft Auto 4 Screenshot 2024 08 05 - 03 08 22 64](https://github.com/user-attachments/assets/91883764-4b7f-49ed-8368-bce44722ca9f)
![image](https://github.com/user-attachments/assets/353d267d-99bd-462a-bf81-1dcacaf49b8c)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [x] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by RecklessGlue540** [comment]
> The option to disable camera centering was added in 2.1, but I can't find it or see it

It's Centering Delay.

> I also don't see the option to disable auto centering in cover.

It's that Cover Centering option, although I have no idea why it was made a menu option tbh, as it's more of a fix and not a feature I feel?
