### ISSUE TITLE
What's the files "fixing" P90?

### ISSUE THREAD

**Issue by Sasha-gamer2011** [ThirteenAG/GTAIV.EFLC.FusionFix#541]
### What should happen

 Want to keep ability to drive-by from my P90

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by Tomasak** [comment]
fix is in asi
it wont be reverted as it is clearly oversight on rockstar toronto side, it is only selectable with previous weapon button and is lacking animation for drive by
