### ISSUE TITLE
[Performance Issue] Severe stuttering on midrange hardware. 

### ISSUE THREAD

**Issue by Motophan** [ThirteenAG/GTAIV.EFLC.FusionFix#542]
### Game version this happens in

v1.2.0.30

### What area of the game

Texture load in when turning the camera when exiting the brothers house and driving around

### Your Hardware configuration

 PC specs

    rtx 4080

    7950x3d

    win 11

    pcie 5.0 performance nvme on a pcie 5.0 slot (14GB/s in crystaldiskmark)

    SWAPPING to intel arc a750 (see additional information)

    dxvk 2.3, nvidia drivers latest (560.81)

    1440p want to play at 60 hz

I believe I have the minimum specs to run the game

### Game capture

![vvdsn5V](https://github.com/user-attachments/assets/5e2dd802-3875-4e4e-aee9-edc0f21d9006)
intel (bloom over saturation?)

### Last working version

n/a

### Does IV run better without FF installed?

no

### Graphics backend (3D API)

DXVK

### Any other notes or things you've tried

What I am doing

    Install dxvk 2.3

    steam launch options `-availablevidmem 8000 -nomemrestrict -norestrictions`

    install fusion fix

    install console visuals

    install various fix

What happens

    Nvidia -> massive lag spikes when turning around

    Intel a750 gpu -> performance fine but bloom is turned up to OVER NINE THOUSAND

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.

**Comment by Tomasak** [comment]
DXVK needs to run for some time to build cache to reduce the stutter.
While fusionfix tries to improve performance, it simply is not possible to fix all the issues without access to source code
and intel picture is fine.
