### ISSUE TITLE
Some objects are missing

### ISSUE THREAD

**Issue by viennaontheline** [ThirteenAG/GTAIV.EFLC.FusionFix#543]
### Game version this happens in

v1.2.0.59

### What area of the game

GTAIV.EFLC.FusionFix v3.0.0
The Ballad of Gay Tony near Luis appartments
Additional mods
Console Visuals (trees, cloth, fences, peds, anims)
Various Fixes
I also use Nvidia DSR to upscale from 2K to 4K

### What should happen

When I set detail distance to 100, some object like paper sheet or leafs on the roads are missing. When I set detail distance to about 53-54, apply it and set detail distance to 100 and apply it again objects will remains.

![100](https://github.com/user-attachments/assets/0c6f116e-1129-4d0a-a17e-57ca9e8298d0)
![53](https://github.com/user-attachments/assets/4e46ee40-a32c-4637-a4c3-4b2d4bbf9bb1)
![100 after set to 53](https://github.com/user-attachments/assets/383e2007-e718-44de-a9dd-a7cffd02689a)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Tomasak** [comment]
Maxing out detail and view sliders is not recommended as they are poorly implemented by Rockstar Toronto. Thats why there was warning added to bottom of the screen with recommended values.
