### ISSUE TITLE
[Feature Request] load specific content to any episode

### ISSUE THREAD

**Issue by TastyNut** [ThirteenAG/GTAIV.EFLC.FusionFix#544]
### What should happen

It would be pretty cool if you guys would make an option to have Fusion Fix load (selected) files and archives
from the DLCs by default into any episode.
Since the Game is now called ''The Complete Edition'' it absolutely should have this feature!!!

Example: 
Loading the Vehicles and Weapons from both TLAD and TBOGT by default into IV.
Now our loved Niko Bellic is able to jack vehicles from the DLCs spawning in regular traffic.

Manually merging all the needed DLC files into IV files is quite a pain to do.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
For what it's worth, those settings are meant for the next update of [The Actual Complete Edition](https://gtaforums.com/topic/967792-grand-theft-auto-iv-the-actual-complete-edition/#comment-1071460426) mod.
This will do all the work eventually, we just need to wait for it.

**Comment by TastyNut** [comment]
Yeah, but is that fully compatible with any other mod?

Neither the GTA Forums Page nor the Discord Server have a proper readme with a full feature list, a compatibility list and debug help.

It doesn't look very inviting if you get what I mean

**Comment by Tomasak** [comment]
not planned for fusionfix, as there is no way to add content without breaking saves.
