### ISSUE TITLE
PCSS feature with Sharp shadows combined

### ISSUE THREAD

**Issue by Joris-truly** [ThirteenAG/GTAIV.EFLC.FusionFix#546]
### What should happen

Love the PCSS filter option, it looks amazing (even if v3.0.0 removed it for some reason?) but is it possible that the closest contact shadow has the same sharpness as the 'Sharp' option?

I'll be using the downgraded version until PCSS returns (or is there some way to still enable it in the config?)

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by juicermv** [comment]
It looks like PCSS will not return. 
The FusionFix team has encountered issues with GTA IV's engine, severely limiting the implementation of PCSS. 

I agree with you though, the variable sharpness effect was really nice. Hopefully the team manages to find some kind of workaround/compromise.

**Comment by Joris-truly** [comment]
That kinda sucks, ngl. In my 40+ hours of playing with PCSS on, I didn't encountered any problems. (but it's probably a backend thing?)

Maybe there is a way to toggle it 'on' in the .ini as a legacy feature? Kind of a shame to just throw it away when it looked so good.

**Comment by Joris-truly** [comment]
> [Already addressed here.](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/512)
> 
> You can make shadows sharp by editing ShadowSoftness and ShadowBias in the ini, using the suggested values commented beside them.

thanks, already tried those value, but then the whole scene cascade is overly sharp. I personally thought the PCSS implementation hit a perfect balance of large object creating soft shadows in gameplay, and providing a sharp (more contact shadows) type of look closeups in cutscenes. It's a shame the feature got axed. I'll stick to a v2 in the meantime.
