### ISSUE TITLE
[Question] What happened with Supersampling?

### ISSUE THREAD

**Issue by homoverjoy** [ThirteenAG/GTAIV.EFLC.FusionFix#547]
### What should happen

As it is, 3.0.0 removed SSAA, why? Is there a chance it will be implented in an update?

I am not criticizing your work, I just wanted to point out that FF3.0.0 does look sub-console in that matter. And as far as I could read, It wasn't deprecated for itself (unlike PCSS)

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by Parallellines0451** [comment]
SSAA caused scaling problems with some post processing effects, such as bloom and depth of field, and made the implementation of new effects more difficult. Use your graphics card's native solution instead, such as AMD's VSR or Nvidia's DSR.

Consoles do not have SSAA. The X360 runs at 1280x720 with 2x MSAA, which is much worse than PC at something like 1080p with any kind of post processing anti aliasing.

**Comment by homoverjoy** [comment]
I see, I cannot use DSR or VSR neither.

They don’t, but they definitely look superior to 1080p with post-processing AA
