### ISSUE TITLE
[v3.0.0] Borderless windowed can't alt+tab with multi-monitor

### ISSUE THREAD

**Issue by Abbanon** [ThirteenAG/GTAIV.EFLC.FusionFix#552]
### Game version this happens in

v1.2.0.59

### What area of the game

This happens in any area, at any point. Even in the game selection menu before booting into IV/TLAD/BOGT.
I have a two-monitor setup. While the game is running, I can't seem to alt+tab to my second monitor, because the mouse is force-locked onto the monitor that the game is running on.
Screenshot of my game window configuration:
![12210_20240814194446_1](https://github.com/user-attachments/assets/855ca317-f117-48a1-8eb2-b4037bdfefca)

At the time of posting this, I have also tried the latest GitHub Actions [build #364](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/actions/runs/10395532646) -- The issue still persists.

### What should happen

I should be able to alt+tab and move my mouse over to my second monitor, while the game is running.

### Last working version

Pretty sure this worked earlier this year, in one of the v2.4.`*`-v2.5.`*` versions. That was the last time I played. 
This is a fresh re-install of the entire game and its patches/mods, nothing was overwritten from previous installations.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
Does it happen with raw input set to off?

**Comment by ThirteenAG** [comment]
No, but it constrains mouse pointer to a game window, though only when the window has focus.
https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/blob/0f8f76209fe1584eba30287f49c153dde2de29d0/source/rawinput.ixx#L132

**Comment by ThirteenAG** [comment]
That's just how the original game works.

[GTAIV.EFLC.FusionFix.zip](https://github.com/user-attachments/files/16632743/GTAIV.EFLC.FusionFix.zip)

Can try this build, I made a small adjustment to cursor clipping, but it works fine on my end even without it.

**Comment by ThirteenAG** [comment]
With that build, cursor is not clipped when the window is out of focus, so I don't know what else is there preventing it from moving between monitors. When I alt tab, I can move cursor anywhere.

**Comment by ThirteenAG** [comment]
Oh, I see, I can fix that as well then. I'll post a new build momentarily.

**Comment by ThirteenAG** [comment]
[GTAIV.EFLC.FusionFix.zip](https://github.com/user-attachments/files/16638366/GTAIV.EFLC.FusionFix.zip)

**Comment by ThirteenAG** [comment]
[GTAIV.EFLC.FusionFix.zip](https://github.com/user-attachments/files/16638671/GTAIV.EFLC.FusionFix.zip)

What about this build?
