### ISSUE TITLE
GTA 4 with FusionFix showing wrong buffer when using dgvoodoo2

### ISSUE THREAD

**Issue by Maximus961** [ThirteenAG/GTAIV.EFLC.FusionFix#557]
### What should happen

As the title says it shows the wrong view when using dgvoodoo2 but its fine if i remove fusionfix.
Based on my test it seems dgvoodoo2 interaction with the fusionfix shader name "rage_postfx.fxc" is the issue if i remove manually this specific shader it fixes it but then the problem is it also disables the fog and some other problems.

Dgvoodo2 with fusionfix default wrong main buffer seems like its using some sort of wrong normal map as main view
![GTAIV 2024-08-16 20-08-19](https://github.com/user-attachments/assets/6b979bb7-73fa-48b1-8ecb-e59c39a2379c)

With the rage_postfx.fxc file deleted from fusionfix no fog in distance
![GTAIV 2024-08-16 21-36-49](https://github.com/user-attachments/assets/7568c345-80f5-419d-8ef6-498240b36ed4)

Reason i wanna have dgvoodoo2 is to use reshade addon program 'rest reshade' dosent work in dx9 or with vulkan.To add effect behind ui,smoke,fog like screen space ray tracing or GTAO ambient occlusion.
Dgvoodoo2 with fusionfix and reshade also have to use shadertoggle(to disable corona depth bug with dgvoodo) is working fine if i remove that shader but no fog and some other small bugs and i find fusionfix mandatory experience not worth removing it for adding some other reshade addon features.

Update:
After further testing using and older version of only the rage_postfx.fxc file from https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/tree/384a861b496251fbe27b83eea676530f3a01a943 had to compile it seems its working fine,would be nice if you could fix it for future releases
### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by Parallellines0451** [comment]
Very bizarre issue. I have no idea what could cause it at the moment.
Dgvoodoo2 seems to cause other problems even without FusionFix though, as installing it broke corona depth test for me.
