### ISSUE TITLE
Cannot see inside of the Steinway Beer Garden

### ISSUE THREAD

**Issue by yuksel-kadir** [ThirteenAG/GTAIV.EFLC.FusionFix#566]
### Game version this happens in

v1.2.0.59

### What area of the game

Cannot see inside of the Steinway Beer Garden through the windows when the player is outside of the building.
![image](https://github.com/user-attachments/assets/c4fc8c05-7490-4276-993b-6a3f4874af95)

### What should happen

The inside of the Steinway Beer Garden building should be seen through the windows when the player is outside of the building. You can see the outside when the player is inside of the building.
![image](https://github.com/user-attachments/assets/da105dec-df28-4b21-8029-2322c3b7e9f2)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ca5dx** [comment]
They're like this on 360 as well, it's meant to look like the windows are darkly tinted or it was done for streaming reasons.

**Comment by Tomasak** [comment]
outside scope
use this https://gtaforums.com/topic/974099-more-visible-interiors/
