### ISSUE TITLE
[v3.0.1] "IMG Files" counter is broken/not displaying correctly

### ISSUE THREAD

**Issue by Abbanon** [ThirteenAG/GTAIV.EFLC.FusionFix#571]
### Game version this happens in

v1.2.0.59

### What area of the game

It seems that the "IMG Files" counter is broken in v3.0.1, as it's empty on the bottom of the graphics configuration page.
It worked fine in v3.0.0, and I installed v3.0.1 with drag-and-drop by replacing all existing v3.0.0 files.
This was tested by starting a new save in base GTA IV (with no previous save data present). I'm assuming the Episodes are the same.
![Screenshot_1](https://github.com/user-attachments/assets/50752543-74f6-4337-bb14-1e65f8920464)

### What should happen

The "IMG Files" counter should display correctly in v3.0.1, like it did in v3.0.0.

### Last working version

v3.0.0

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ca5dx** [comment]
Can confirm.

**Comment by ca5dx** [comment]
Yup, it's fixed now as of 3.0.2.
