### ISSUE TITLE
double lamppost lights disappear with lamp shadows enabled

### ISSUE THREAD

**Issue by duntwave** [ThirteenAG/GTAIV.EFLC.FusionFix#573]
### Game version this happens in

v1.2.0.59

### What area of the game

Primarily in the star junction and some places in Alderny where there are these double lamp posts the light they emit just disappears when you get close. may happen in other areas too Im not aware of
![steamwebhelper_xHCxEvPqzY](https://github.com/user-attachments/assets/809e2d4a-02cc-4103-9647-0a6bdfb4875c)

![steamwebhelper_YycUn7FtzL](https://github.com/user-attachments/assets/e7ef714c-b2c8-4e64-b71c-095c62245f3a)

### What should happen

the lights probably should not be disappearing 

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by MagicAl6244225** [comment]
I could not reproduce the issue with a game only modified by FusionFix v.3.0.1.

Please be sure there isn't any version of Console Lights or other lamppost mod installed, other than what's included with FusionFix. Lamppost models that are edited to disable dynamic shadow lights expose a PC game code issue of lights that go off when the player and camera are in certain positions.

FusionFix now includes lamppost models with dynamic shadow lights enabled, and uses a different method to optionally enable or disable lamppost shadows.
