### ISSUE TITLE
"...I'll take her" teleport

### ISSUE THREAD

**Issue by ReneSchimmelpfennig** [ThirteenAG/GTAIV.EFLC.FusionFix#578]
### Game version this happens in

v1.2.0.59

### What area of the game

When you start the mission "...I'll take her" by calling Gracie, you are teleported to her as soon as the phone call finishes, instead of getting the prompt to drive to her place.

https://github.com/user-attachments/assets/0d439c0e-0198-4039-8707-24743ca7d2a9

### What should happen

It should behave as shown in this video: https://www.youtube.com/watch?v=ztX5pwMEFKo

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Tomasak** [comment]
Do you use alternate dialogue option?
Did you fail mission before and saved after?

**Comment by ReneSchimmelpfennig** [comment]
> Do you use alternate dialogue option? Did you fail mission before and saved after?

Yes, I use alternate dialogues, but I tried turning it off as well which still resulted in this. 

I didn't fail the mission, I just saved the game after mailing Gracie in tw@, and when I returned to the game I called her.

**Comment by sTc2201** [comment]
How old is that save file where this issue occurred?

Because in commit https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/commit/707efba9245b682750f62eb95c9676f2ba79a561 (FusionFix v2.5.4) from 7 months ago this particular bug was fixed.

So if you saved the game with Alt. Dialogue enabled before the fix rolled out this save file might still have the bug since toggling off Alt. Dialogue with the bugfix does not fix save files already affected by this bug, only newly created save files.

Also, could you upload your save file for testing purposes?

**Comment by ReneSchimmelpfennig** [comment]
> How old is that save file where this issue occurred?
> 
> Because in commit [707efba](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/commit/707efba9245b682750f62eb95c9676f2ba79a561) (FusionFix v2.5.4) from 7 months ago this particular bug was fixed.
> 
> So if you saved the game with Alt. Dialogue enabled before the fix rolled out this save file might still have the bug since toggling off Alt. Dialogue with the bugfix does not fix save files already affected by this bug, only newly created save files.
> 
> Also, could you upload your save file for testing purposes?

Oh yep, I believe I've been on this save file for over 7 months.
[SGTA412.zip](https://github.com/user-attachments/files/16686973/SGTA412.zip)

**Comment by sTc2201** [comment]
If you haven't played through the mission yet, one way you can fix it is by using a FusionFix version before v2.5.4, toggling off Alt. Dialogues, save your game, then re-install the latest FusionFix version.

Personally I don't recommend it though, I'd just play through the mission as is with the instant teleport on mission launch, it doesn't affect the rest of the mission really.

Closing this now as this is fixed on the latest version when starting a new game.
