### ISSUE TITLE
Something like the GXT-Loader for certain other files e. g. carcols.dat

### ISSUE THREAD

**Issue by MiesThies** [ThirteenAG/GTAIV.EFLC.FusionFix#582]
### What should happen

When adding cars, it would be so helpful to not have to add carcols.dat, cargrp.dat and VehOff.csv settings to the existing files, but to be able to add them to a separate file. That way, you would have all your added car lines nice and clean in a dedicated space.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
That already works. You can do it via defining any new .dat or .ide as CARGRP, CARCOLS etc in default.dat, although I heard it can corrupt saves...

**Comment by MiesThies** [comment]
> That already works. You can do it via defining any new .dat or .ide as CARGRP, CARCOLS etc in default.dat, although I heard it can corrupt saves...

I'll try that out, thank you so much for the swift reply! :)

**Comment by RecklessGlue540** [comment]
You could try CARCOLS common and see if it works, if I remember that worked for me...

**Comment by MiesThies** [comment]
It did work! Thank you :) VehOff also seems to work.

But I think I can't get ("new")cargrp to work.. Can you confirm that it's working?
