### ISSUE TITLE
Daytime lamp Post shadow

### ISSUE THREAD

**Issue by MiesThies** [ThirteenAG/GTAIV.EFLC.FusionFix#584]
### Game version this happens in

v1.2.0.59

### What area of the game

probably multiple places, e. g. in front of the Algonquin Safe House

### What should happen

The lamp post should cast a shadow, instead only the cage around the light itself does so.

### CrashDumps and logs

![GTAIV_2024_08_24_23_34_26_902 (Groß)](https://github.com/user-attachments/assets/2da144b5-d2d4-489c-adda-6c23de22136e)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Tomasak** [comment]
looks like vanilla issue, report here https://github.com/GTAmodding/GTAIV-Issues-List/issues or to various fixes
