### ISSUE TITLE
[Bug Report?] Crashing at certain instances after updating to v3.0.3

### ISSUE THREAD

**Issue by Abbanon** [ThirteenAG/GTAIV.EFLC.FusionFix#587]
### Game version this happens in

v1.2.0.59

### What area of the game

I'm having a strange case where at random points, if I hit Esc to view the world map, the map itself is a solid white square. 
Attempting to do anything else after this point results in a crash to desktop.
I've noticed this happening after updating to Fusion Fix v3.0.3, but I'm not entirely sure if it's the root cause.
It tends to happen after completing a few missions. 
This is on GTA IV latest/CE.

Screenshot of the white map bug before a crash:
![Screenshot_1](https://github.com/user-attachments/assets/9290f5fb-df9f-412b-8faf-d8356c7799ea)

### What should happen

It just shouldn't have this happen.

### CrashDumps and logs

Most recent crashdump: [crashdumps.zip](https://github.com/user-attachments/files/16757361/crashdumps.zip)
Previous selection of crashdumps (same case): [crashdumps.zip](https://github.com/user-attachments/files/16751638/crashdumps.zip)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by RecklessGlue540** [comment]
If you can leave a full list of mods, maybe I could pinpoint.
Someone around reported the white minimap, and it turns out their problem was a mod that modified frontend.wtd.

**Comment by RecklessGlue540** [comment]
Well UHD Map and Radar does in fact play with the frontend.wtds as well, you may try taking these out of your game, or the mod altogether and see if you still get this issue.

**Comment by RecklessGlue540** [comment]
Also this may just mean that you're nearing the limitations of the game, I remember SA had a similar issue with it's minimap once you raised the streaming memory budget to 4gb with an unpatched .exe.
Maybe it's the same here. You've got so many mods that bump textures up, Ash's packs, the Radar, the Reticles, even Various Fixes which has some higher res stuff here and there, you may have just reached the game's 32bit limits.

I sincerely hope that we're gonna be able to have control and understanding over the game's memory management in the future in some mod, so we could figure out what is totally safe and what is not and even be able to control how much to concretely allocate for streaming and other processes, like in III / VC / SA's Open Limit Adjuster.
The game doesn't even need to be patched, it's already large address aware and it's a shame that it can't be used to it's full potential.

The crashing may just be that the game is either memory leaking or crashing out of lack of memory for it's other processes, you also have the vehicle budget set to 144mb which is also a factor...

**Comment by RecklessGlue540** [comment]
Oh, yikes, using the same value for both the vehicle budget and peds is not safe at all, they eat the memory of each other, on top of eating the core game memory of other functions.

I'd suggest trying with just the vehicle budget to 144, btw 144 is not mandatory for Ash's pack and can be lowered to 120mb safely, IVFixer actually packs the mod with an 120000000 vehicle budget now, previously it was indeed packed with an 144mb ini, but since it was safe with 120mb, it was lowered to that in a hotfix.

I'd still recommend 144 in this case since you also have a popcycle mod, but definitely try with 0 ped budget and 120mb vehicle budget first. If variety is bad with these, try 144 just for the vehicle budget.
Ped budget if I'm not mistaken works fine at the default 60mbs that it is, with Chunk's popcycle.

**Comment by ThirteenAG** [comment]
Your crash is inside CTxdStore::releaseData function, I'd be very surprised if it was related to fusion fix. Reproduce it on a clean install with fusion fix only, if it still happens, then some resource is invalid.

**Comment by HAYASHIDASEIYAKU** [comment]
Please check if the [map1/2/3/4] file in [fronted_360.wtd] is larger than 512x512.
If it is, then it is the problem.
Any texture larger than this size will cause a significant crash, and currently only lowering it can reduce the occurrence. yes 512x512 also has a chance of crashing.

**Comment by RecklessGlue540** [comment]
Very much feels like it. Though I think 2048x2048 is kinda overkill for stuff like this. How do the radar.img textures look, how big are they? 2048x2048 as well? 1024x1024 would sound safer.

**Comment by HAYASHIDASEIYAKU** [comment]
Yes, R* uses very little memory for maps, and if possible, it is best not to exceed the original resolution of 512x512. This is the resolution that is least likely to crash after my testing.

**Comment by valentyn-l** [comment]
> Well that's good at least. We'd need @valentyn-l to do a slight downgrade of the ones in frontend to 1024x1024 so it'd be safer I guess...

I have tested the game for over 600 hours now between modding and playing, and I have not encountered any issues with any of the mods that I have released. I've run into this issue before, but that was during the testing phase of a FF update. 

Try looking for the stream.ini files inside the GTA IV directory and change it to the following:

![image](https://github.com/user-attachments/assets/345f05e1-699d-4fea-8c65-4011e1ae45eb)

See if it helps :)

**Comment by RecklessGlue540** [comment]
> See if it helps :)

It shouldn't, since editing that file is completely placebo and setting these values to 8gb wouldn't work anyway, the game is 32bit and at max can support 4gb.
Actually if that file is related to the streaming budget, 2gb is completely optimal too, since it means 2gb for streaming and 2gb for other game tasks.

My guess is that it happens because there are so many hi res texture mods installed at the same time, and sadly there is indeed a limit that cannot be bypassed by no means.
Neither stream.ini nor for some reason the -heapsize commandline that some people recommend around work, and the memory management is probably something quite hardcoded.

**Comment by valentyn-l** [comment]
> > See if it helps :)
> 
> It shouldn't, since editing that file is completely placebo and setting these values to 8gb wouldn't work anyway, the game is 32bit and at max can support 4gb. Actually if that file is related to the streaming budget, 2gb is completely optimal too, since it means 2gb for streaming and 2gb for other game tasks.
> 
> My guess is that it happens because there are so many hi res texture mods installed at the same time, and sadly there is indeed a limit that cannot be bypassed by no means. Neither stream.ini nor for some reason the -heapsize commandline that some people recommend around work, and the memory management is probably something quite hardcoded.

I can't guarantee compatibility with other mods. I'll see if I can make a lite version when I have time, but everything else is every user's own responsibility and sadly, also the game's limitation.

**Comment by viennaontheline** [comment]
> It shouldn't, since editing that file is completely placebo and setting these values to 8gb wouldn't work anyway, the game is 32bit and at max can support 4gb. Actually if that file is related to the streaming budget, 2gb is completely optimal too, since it means 2gb for streaming and 2gb for other game tasks.

What about 4GB Patch?

**Comment by RecklessGlue540** [comment]
> > It shouldn't, since editing that file is completely placebo and setting these values to 8gb wouldn't work anyway, the game is 32bit and at max can support 4gb. Actually if that file is related to the streaming budget, 2gb is completely optimal too, since it means 2gb for streaming and 2gb for other game tasks.
> 
> What about 4GB Patch?

Useless, the game is already large adress aware, since a long time actually, since at least 1040
https://gtaforums.com/topic/934545-fusionfix/?do=findComment&comment=1072273620

**Comment by viennaontheline** [comment]
> Try looking for the stream.ini files inside the GTA IV directory and change it to the following:
Thanks! I've increased limits to 409600 and no one crash and white map in TBOGT. Also, here's list of my mods.

![image](https://github.com/user-attachments/assets/0ace5fd3-668f-4a77-8229-24d606a4adab)
