### ISSUE TITLE
[Feature Request+Bug Report] Some improvements for the little secret something, and a discovered bug

### ISSUE THREAD

**Issue by Abbanon** [ThirteenAG/GTAIV.EFLC.FusionFix#591]
### Improvement ideas:

In regards to the little secret, it would be nice if some additional tweaks were applied if possible.
For example...
- The ability for Niko to remember it, after finding it for the first time 
(So you can make "contact" with it whenever you wish, without having to remember what to do for it every time)

- For the life paths of road and foot to have better visual presence, maybe by using the existing visual presence of sand and grass
(It feels strange, not leaving tracks to tell of your travels)

- Improved attributes of discernible topiary ascertained at all distances, near and far
(Things seem a little... Bad here, very poor)

I'm of course being vague and wording things a little strangely on purpose.

### Bug report:
The following vehicles don't seem to have the effect applied properly to them when naturally spawned.
...Is this intentional? Because it's very jarring and feels out of place.
(There are likely more, these are just what I've managed to find)
- Huntley Sport
- Sentinel
- Vigero
- Cavalcade FXT
- PMP 600
- Fortune
- Habanero
- Peyote
- Turismo
- Rebla
- Banshee
- Stretch
- Feltzer

**Comment by RecklessGlue540** [comment]
Also got a small idea about one possibly easy tweak atm
To maintain the vague wording, I'll say that It'd be nice if, upon making contact 😉, we'd get a prompt in the top left corner that says that we made the right contact 😄 like the other contacts the game offers lmao
