### ISSUE TITLE
When using controller the game stutters

### ISSUE THREAD

**Issue by mikeydoom** [ThirteenAG/GTAIV.EFLC.FusionFix#593]
### Game version this happens in

v1.2.0.30

### What area of the game

When I play the game with mouse and keyboard the game runs perfect at 100+ FPS. When I play with my controller (Xbox Aries S) the games frame rate is cut in half and it stutters badly.

### Your Hardware configuration

i9 9900k
RTX 3090
32GB Ram
Windows 11

### Does IV run better without FF installed?

No

### Graphics backend (3D API)

DXVK

### Any other notes or things you've tried

I tested with and without controller connected. The game only stutters when my Xbox Series S is connected.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.

**Comment by mikeydoom** [comment]
I have fixed the issue in a roundabout way. Enabling steam overlay fixed the FPS issue. Not sure why, but I found the fix on reddit.

**Comment by Tomasak** [comment]
Ye, its some general issue with steam overlay, seems like vanilla issue on steam ver.
