### ISSUE TITLE
[Question] Does Fusionfix already include Shader Fixes Collection?

### ISSUE THREAD

**Issue by MOnkeMan5009** [ThirteenAG/GTAIV.EFLC.FusionFix#596]
### What should happen

So basically someone said it didn't, or at least not accurately, would i need shader fixes collection separately? or its just integrated into fusionfix? saw a comment on youtube

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
Those repositories are married to each other, any commit made in Fusion Shaders will ultimately end up in FusionFix as well.

Whoever told you that lied pretty much.. I'd never trust youtube comments like these

**Comment by sTc2201** [comment]
A random comment on YouTube is not the best source, don't you think? Also not providing a screenshot/link to said comment isn't useful either.

**Comment by MOnkeMan5009** [comment]
> A random comment on YouTube is not the best source, don't you think? Also not providing a screenshot/link to said comment isn't useful either.

i forgot to mention, but it fully includes the console visuals stuff as well right? like reflections too. i mean strictly visuals not assets or animations
