### ISSUE TITLE
Issues with Fusion Fix 3.0.x

### ISSUE THREAD

**Issue by GTAIVTESTER** [ThirteenAG/GTAIV.EFLC.FusionFix#599]
### Game version this happens in

v1.2.0.59

### What area of the game

Fusion Fix 3.0.x

### What should happen

1. Massive pop in issues with maxed sliders even with `-nomemrestrict` command due to Fusion Fix 3.0.x's **unnecessarily** restored console smooth fading (streaming issue caused by changes to restore it) 
2. Low quality reflections compare to v2.5.6
3. Less shadow and definition settings (I know those can increase the code complexity but removing those features from scratch is not good idea specially for people who did not care about it performance issues or broken stuff, I think there are better ways to reduce code complexity using architectures or some kind of design patterns or by separating code into standalone libraries)
4. Wire shadows are removed 

### Last working version

v2.5.6

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Parallellines0451** [comment]
Worthless issue.

1. Incorrect, it's unrelated to that and it's being looked at
2. That is just false, there were no changes
3. Incorrect, shadows are more customizable and only "Improved" definition was removed, because it's redundant; and PCSS, because it's problematic
4. False too, they weren't even there in the first place

**Comment by ThirteenAG** [comment]
> Massive pop in issues with maxed sliders even with -nomemrestrict command due to Fusion Fix 3.0.x's unnecessarily restored console smooth fading (streaming issue caused by changes to restore it)

I don't see it unfortunately, so feel free to debug this, all code is provided. If there's anything that needs fixing, debug, test and pull request a fix.

> Less shadow and definition settings (I know those can increase the code complexity but removing those features from scratch is not good idea specially for people who did not care about it performance issues or broken stuff, I think there are better ways to reduce code complexity using architectures or some kind of design patterns or by separating code into standalone libraries)

Please, show us the way! 

https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/pulls
https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/pulls

**Comment by GTAIVTESTER** [comment]
> Incorrect, it's unrelated to that and it's being looked at
> That is just false, there were no changes
about these two I can not agree with you , even if pop-ins are unrelated to console smooth fading, there are some streaming issues in v3.0.x due to some changes, and it should be solve because we have no such issue in vanilla game 
about reflections, I am not blind man, If I can I will share comparison screenshots later but trust me there is some differences between v2.56 and v3.0.x especially in vehicles reflections

> Please, show us the way!
I just submitted my own experience and there is no offense, but seems like you didn't interested in it, and I have no knowledge in game development stuff If I could I would help, but as who has experience in application development I can say there is always alternative ways to reduce your code complexity, removing is not always best solution

I know this port is **dogshit** and you have a difficult job to make the game more stable than vanilla, but please do not ruin already fixed or stable stuff for fixing or adding some other stuff

Thanks for your efforts anyway.

**Comment by ThirteenAG** [comment]
> About these two I can not agree with you , even if pop-ins are unrelated to console smooth fading, there are some streaming issues in v3.0.x due to some changes, and it should be solve because we have no such issue in vanilla game
about reflections, I am not blind man, If I can I will share comparison screenshots later but trust me there is some differences between v2.56 and v3.0.x especially in vehicles reflections

I'm not saying the issue doesn't exist, but I can't reproduce it for some reason. That means someone would have to identify the code responsible, don't you think? No matter how much you scream at me, there's nothing I can do without help.

**Comment by GTAIVTESTER** [comment]
> > About these two I can not agree with you , even if pop-ins are unrelated to console smooth fading, there are some streaming issues in v3.0.x due to some changes, and it should be solve because we have no such issue in vanilla game
> > about reflections, I am not blind man, If I can I will share comparison screenshots later but trust me there is some differences between v2.56 and v3.0.x especially in vehicles reflections
> 
> I'm not saying the issue doesn't exist, but I can't reproduce it for some reason. That means someone would have to identify the code responsible, don't you think? No matter how much you scream at me, there's nothing I can do without help.

yes you are right.

**Comment by Ash-735** [comment]
> I know this port is **dogshit** and you have a difficult job to make the game more stable than vanilla,

It's not even a job, this is done for free in our spare time :P
