### ISSUE TITLE
Inconsistent car movement (stutters)

### ISSUE THREAD

**Issue by r3538987** [ThirteenAG/GTAIV.EFLC.FusionFix#60]
Observed in 
v1.2.0.43.Complete.Edition, and 
v1.0.7.0.CE.Downgraded (above version used for downgrade)

If FusionFix installed (different versions for mentioned game variants) player's car sometimes 
https://webmshare.com/ZoMGO

Another example I encountered. Slow-mo frame by frame. 
https://www.youtube.com/watch?v=8qPXSQzSMLE

When FusionFix is removed, such problem is no more presented. 
In first sample it looks like there is almost consistent delay between each occurrence. 
With regular GTAIV 1.0.7.0 could not reproduce such issue. 

**Any suggestion which option I can play more, maybe to get some additional info for this case?** Like VSYNC, framerate limits...

**Comment by ThirteenAG** [comment]
Try turning them off one by one and see which causes it.

**Comment by r3538987** [comment]
It's _HandbrakeCamFix_. 
If you enable it, and play around with in-game HardbrakeCam parameter, there is no difference at all, in all cases car will have this effect.

**Comment by ThirteenAG** [comment]
https://github.com/GTAmodding/GTAIV-Issues-List/issues/10
