### ISSUE TITLE
GTA IV TLAD - 2 Game Breaking Missions Found [BUG REPORT]

### ISSUE THREAD

**Issue by NO84MADD** [ThirteenAG/GTAIV.EFLC.FusionFix#600]
### Game version this happens in

v1.2.0.30

### What area of the game

**GTA IV - TLAD ONLY!!** - The first one is in 

**Mission name**: Marta Full of Grace:-
**issue:** Game crash before cutscene
**description:** Game crashes as soon as you enter the blip marker before the cutscene. I had to rename dinput8.dll to dinput8 to get around & renamed it again after the mission.

The second one is in

**Mission name** : Shifting Weight:-
**issue**: camera locked stunt
**description**: During 2nd half of mission, DeSean performs a wheelie which causes the camera to get locked on Stunt Camera
**workaround:** Hold right click the entire mission to aim. 

### What should happen

Should not crash before cutscene, 
Stunt camera should belong to stunts only :) 

### Last working version

none

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
No CrashDumps - no crashes happened.
