### ISSUE TITLE
Some issues with the new Headlight Shadows toggle and possible ideas for the future

### ISSUE THREAD

**Issue by RecklessGlue540** [ThirteenAG/GTAIV.EFLC.FusionFix#602]
### Game version this happens in

v1.2.0.59

### What area of the game

1. It seems like the setting depends on the Lamppost Shadows setting to be on, to work without major bugs:

https://imgur.com/a/OmYwm3G

2. If Vehicle shadows under artificial lights is turned on, it seems like the switch does not work correctly, some cars still cast shadows under artificial lights while others do not. The player's car will also stop casting those when getting inside, as in this footage:

https://github.com/user-attachments/assets/503b1af1-1bf8-420e-a8ea-d50f2c209a7b

3. Some objects start casting shadows from headlights late, but I'm not sure if this happens even vanilla, or with the new code...

https://github.com/user-attachments/assets/577d2990-1c13-4f7c-9813-3ffdea621ea9

### What should happen

For 1.
Even in versions below 3.0.6, the HeadlightShadows option in the .ini used to only work with Lamppost Shadows on. 
Seems like it's still the case now, but instead it engages with major bugs if Lamppost Shadows is off.
What should happen here is that they should be completely separate from each other. Might be hard to achieve.

For 2.
Here's a theory. If we disable headlight shadows for all cars completely, except for the one the player is actively driving, like in GTAV, wouldn't headlight shadows + vehicle shadows from artificial lights + vehicle shadows from headlights be able to work all in tandem without flickering bugs? 
Might be worth a shot testing the above combination, but without the vehicle shadows from headlights if what I mentioned still goes over the 8 limit. 
In that case I don't know about the heli spotlight, since it still casts a shadow and it would have to stay too, having it's part of the limit as well when it's active.

Ideally the 8 dynamic shadows limit should be cracked, but I heard it's been hardcoded, so idk. Then everything could probably work "fine".

For 3.
Every shadow should load in, in time. But I don't know how the original game behaves atm, so I can't tell.

### Last working version

v2.5.6

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Parallellines0451** [comment]
Just a reminder: don't expect those "PC features" to ever work properly. The game was not built for lampposts and headlights to cast shadows.

The intended and ideal way to play is without both of them, and no bugs related to them will ever be fixed.

**Comment by RecklessGlue540** [comment]
At this point I think removing headlight shadows altogether might be for the best. And I fully agree and learned to not expect or hope too much for anything tbf.

As for lamppost shadows, they can be kept, however since the lamppost models have static shadows enabled and they look buggy in some or a lot of places I decided to go ahead and remove them from any lamppost / wall light model that had them, to sort of "minimize" any more bugs (minimize being a stretch because obviously, there's no saving those anyway). And it's how the previous versions of FusionLights were too, just with dynamic shadows enabled and therefore I came to this decision to get rid of those, plus any other unnecessary flags like unk18 or rays flags because they don't appear to be doing anything, and in the rays case they won't do without f2c or f30 tweaks anyway. 
If you agree, I can pull request those models. I also kept the flag (134,217,728) for the LamppostShadows toggle so no worries about that either. 
To clarify, I only changed the flags, and to be specific, any lights that were lighting at night only use flag 134,250,560 and any lights that were lighting all day use flag 134,250,592.

But for vehicle shadows, I think at the very least you guys could try to bring back the NPCs shadow casting in vehicles (because the recent tests for the headlight shadows toggle got rid of that) and making vehicle wheels cast shadows, since consoles have both of those "features" and you could at least spot that in the Booth Tunnel where vehicles always casted shadows there, even without those excuses of "PC features" turned on.
In my opinion those are the last two things that you guys could ever do to those beyond saving night shadows, but it's up to you guys at the end of the day.

**Comment by Parallellines0451** [comment]
Yes, restoring vehicle wheel shadows and fixing deformation self shadowing is a valid goal and reasonably within the realm of possibility.

As far as we know, only models from lamppost.img and headlights have had their flags changed on pc to cast shadows. Other shadow casting lights have no problems, as they're mostly in interiors, are small and have been carefully placed. FF models use the same .light params as consoles, with only some flags changed for the toggles to work.

All in all, any deviation whatsoever from intended/console behavior regarding night shadows is incorrect and produces countless issues, and they constitute one of the worst mistakes made by the development team for this pc port. The options to toggle them exist merely as a courtesy to prevent complaints.

**Comment by RecklessGlue540** [comment]
> As far as we know, only models from lamppost.img and headlights have had their flags changed on pc to cast shadows. Other shadow casting lights have no problems, as they're mostly in interiors, are small and have been carefully placed. FF models use the same .light params as consoles, with only some flags changed for the toggles to work.

Yep, exactly.
However my point was that the models bundled in FF right now, well they actually don't really seem to use the same light flags as consoles, because despite having dynamic shadows enabled (which is also required for the toggle to work I believe), they also have static ones too. I didn't find this an issue initially, in fact I found it as extra eye candy at first, as anyone would, but now I'm at the conclusion that because there are so many places reusing the same light models, well yeah of course things aren't perfect anyway, and as a result of them being there as well, we can end up with extra anomalies like this:
![GTAIV 9_5_2024 3_31_46 AM](https://github.com/user-attachments/assets/9911dafb-5289-4922-b8d8-116f8d3426d0)
Or this:
![GTAIV 9_5_2024 4_11_57 AM](https://github.com/user-attachments/assets/2c84f21a-b04e-4dc9-8073-7dd5e359feb8)

It's also inconsistent, some lights now have static shadows but others don't.

Also somehow, and I have no idea why, the classic behavior of the game going over the 8 shadows limit might also get a chance of happening more, with lights having static shadows enabled, as in the below footage:
(this is one place, but I'm sure it would happen in a couple of others as well)

https://github.com/user-attachments/assets/c70f6c82-92d3-4de0-a501-641ba254f5d1

This happens even in the vanilla game btw, and no idea why because it's fine if they only have dynamic shadows.

I don't know, I personally find at least those two kinds of issues i mentioned here easily avoidable, and I also don't think that FusionFix should expose those, don't you think?
Also the fact that these static shadow enabled lights weren't there, for example in FusionFix 2.5.6, well, yeah what's even the point imo. 
Actually I think it was MagicAl's idea to have vanilla PC light flags in, just as they've finally found the way of disabling lamppost self shadows, which do have static shadow flags for a big chunk of these lights, but as I'm trying to mention here, well, this decision comes with it's own downsides sadly.
I think removing just those static shadows would be "better", in theory, while issues or inconveniences would happen regardless regarding those shadows, removing a part of their shadows for "less" issues I think it might be better? lol.
And like I said, I already have the models ready so I just want to know if you guys are fine with this idea of no static shadows as it was before, because i don't really think it's worth having them at the end of the day. And that'd be the last thing for these anyway broken PC features...

And good to know about those things for VehicleNightShadows. Hopefully you guys manage to crack those easily :p    
Seriously best of luck with those. I heard it's a complete mess but honestly the development of the game wasn't any better, so they got their reasons. But yeah, some of their decisions were indeed strange in a lot of places.

**Comment by Parallellines0451** [comment]
> However my point was that the models bundled in FF right now, well they actually don't really seem to use the same light flags as consoles, because despite having dynamic shadows enabled (which is also required for the toggle to work I believe), they also have static ones too.

What do you mean? Console models don't have any shadow flags enabled, neither static or dynamic. We only added those flags according to PC models so that they could be toggled at runtime.

> Also somehow, and I have no idea why, the classic behavior of the game going over the 8 shadows limit might also get a chance of happening more, with lights having static shadows enabled, as in the below footage:

Static doesn't make a difference. If it casts shadows at all, it occupies a slot in the atlas.

> Also the fact that these static shadow enabled lights weren't there, for example in FusionFix 2.5.6, well, yeah what's even the point imo.

We went through that route because it doesn't really matter; dynamic only is inconsistent, static + dynamic misses everything with transparency, and both have a [myriad of other issues](https://i.imgur.com/4uDcoYm.jpeg). It's bad either way, so don't expect any semblance of quality or polish if you use that setting. It was going to be ini only even, but some folk really wanted it easily accessible in the menu, so we did that and added warnings instead.

People's attachment to those so called "PC enhancements" is pretty much Stockholm syndrome: they were never good, but they were the only thing that we had. Unfortunately, trying to convince people that they were playing the game wrong for over 15 years is, understandably, very difficult.

**Comment by HAYASHIDASEIYAKU** [comment]
Do shadows work properly during the day? If so, simply disable all shadows at night, this option will solve unnecessary discussions.

**Comment by RecklessGlue540** [comment]
Yeah I guess why even bother at this point lol, thanks for your time anyway.
