### ISSUE TITLE
Character shadow in vehicle disappear in latest update

### ISSUE THREAD

**Issue by LLIXXXIR** [ThirteenAG/GTAIV.EFLC.FusionFix#605]
### Game version this happens in

v1.2.0.59

### What area of the game

all game

### What should happen

Firstly i wanted to thank this team for awesome third update, i dreamed about this shadows for so long, respect.
But after installing 3.0.8 update i noticed, that character shadows just disapper in vehicle. I wasn't use headlight shadows cheat. (and why is this cheat now? why don't left it in a .ini file? Cheat is a interfere into the game, her own features, don't you think? Well, i think it will removed, cus it usable only for developers, i hope)
It quickly appers after out of the vehicle, then if get in disappear again, looks really bad at all.

First screenshot - 3.0.8
Second - 3.0.5
![GTAIV_2024_09_06_18_45_47_820](https://github.com/user-attachments/assets/4cec53cd-cca3-462a-a18a-a6149e5eaa77)
![GTAIV_2024_09_06_18_56_06_019](https://github.com/user-attachments/assets/42916f63-792f-4495-aef8-75e282fb845c)

And could be great to fix next thing, if it possible (i think for your team nothing impossible)), this is not a bag, but i don't want to write new issue, so here it is:
As i said, besides previous mistake shadows perfect, but vehicle shadows drawing distance not great, even at very high preset, at high preset it just awful. here are compariosions with 1.0.4.0: (with my cringe writings, don't have any redactor now, sorry) 

![GTAIV_2024_08_20_17_03_02_046](https://github.com/user-attachments/assets/baf80b15-9d97-40ed-9cb8-f6d481a28c96)
![GTAIV_2024_08_20_16_48_08_340](https://github.com/user-attachments/assets/5d93ece5-375c-4882-8246-e1a4bab2abfa)
![GTAIV_2024_08_24_09_57_45_416](https://github.com/user-attachments/assets/c799eb4b-9e2e-4197-a001-2f1778ac3808)

And, another feature i wanted to see - it console bloom. Many people don't like it, but with console gamma it looks not so dark, natural at that time, as it meant to be. I use visualsetting.dat from old version of console visuals, (still on nexusmods) which feels pretty close to consoles. FusionFix have a switcher of bloom, so why don't make a "console" preset same as treefx.
And sorry for my english, which still not good)

### Last working version

v3.0.5

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by mathadakshay** [comment]
Hello, 

Although I am a complete beginner in Github, can i take up this issue and contribute ?
Your response is appreciated

**Comment by Parallellines0451** [comment]
That's definitely not the high shadow quality preset in your screenshots, and bloom is already accurate to consoles with FF.

**Comment by LLIXXXIR** [comment]
> That's definitely not the high shadow quality preset in your screenshots, and bloom is already accurate to consoles with FF.

No, it was high preset, but with a changed softness settings in .ini. I test it again and only now noticed, that the higher the softness, the worse the range. If don't touch this settings draw distance fine. 
About bloom i think i just got paranoia) 
thanks for answer

**Comment by Parallellines0451** [comment]
Yeah, higher softness requires a higher bias to prevent shadow acne, and the higher the bias the more small scale detail you lose.

**Comment by ThirteenAG** [comment]
Have you really checked with latest developer build?

**Comment by LLIXXXIR** [comment]
> Have you really checked with latest developer build?

Yes, i rechecked 3.0.8 with deleted any mods from update folder and without dxvk, character shadow missing

**Comment by ThirteenAG** [comment]
3.0.8 is a released build, not a developer build.
https://ci.appveyor.com/api/buildjobs/dchnnlw439qxf9k8/artifacts/GTAIV.EFLC.FusionFix.zip

**Comment by LLIXXXIR** [comment]
> 3.0.8 is a released build, not a developer build. https://ci.appveyor.com/api/buildjobs/dchnnlw439qxf9k8/artifacts/GTAIV.EFLC.FusionFix.zip

{"message":"Artifacts download limit (1024 MB/day) exceeded."} 
another time, i guess

**Comment by ThirteenAG** [comment]
https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/actions/runs/10717021281/artifacts/1895218398

**Comment by LLIXXXIR** [comment]
Yes, it fixed in this build)
didn't know, that developers build available to users
![GTAIV_2024_09_07_10_06_32_818](https://github.com/user-attachments/assets/44b1432b-5e55-491c-97d7-12b0377b32d2)

**Comment by ThirteenAG** [comment]
Use that then, or wait for the next release, should be rather soon.
