### ISSUE TITLE
Problems with game start Wine (Proton) Arch Linux

### ISSUE THREAD

**Issue by cravvler9** [ThirteenAG/GTAIV.EFLC.FusionFix#607]
### Game version this happens in

v1.2.0.43

### What area of the game

Games do not run after install the mod. Just crashed after download screen. 

### What should happen

Crashed with wine error. After disable mod game works like regular.

### CrashDumps and logs

![image](https://github.com/user-attachments/assets/188fa64d-af94-4303-9bf6-f5ca20a7bc43)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ca5dx** [comment]
Right from the FAQ....
- Non-Windows users (Proton/Wine) need to perform a DLL override.

**Comment by cravvler9** [comment]
> Right from the FAQ....
> 
>     * Non-Windows users (Proton/Wine) need to perform a DLL override.

Im doing it 
![image](https://github.com/user-attachments/assets/b6a5738a-1715-4b6c-8a68-58c9a4e59b6b)
