### ISSUE TITLE
Crash at the Smackdown mission

### ISSUE THREAD

**Issue by mLithil** [ThirteenAG/GTAIV.EFLC.FusionFix#608]
### Game version this happens in

v1.2.0.59

### What area of the game

Mission **SMACKDOWN**. When i reach the destination marker, game starts loading SMACKDOWN in the right bottom corner and then one of two scenario happen:
**1. Hear the sounds, dialog, but after 15 seconds game crashes without any Error
2. Crashes immediately on loading of mission without any error**

Tried different saves, clothing, approach, few missions around and then tried - nothing helps. Have only FusionFix installed (last version) and Vulkan. 

PS: Cannot post DMP file as it is 75MB......so google disk link attached. EventViewer crash log on screenshot attached also.

### What should happen

The mission should start correctly as any other mission yet. 

### CrashDumps and logs

[GTAIV.exe.20240909223619.log](https://github.com/user-attachments/files/16936397/GTAIV.exe.20240909223619.log)
![EventViewer log ](https://github.com/user-attachments/assets/fe00a80f-1243-4b80-83ef-5e6c6ba14b29)
https://drive.google.com/file/d/1xJ38Mm7nHaPfUnthfS_jvWCTfe-zzmS4/view?usp=sharing

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by mLithil** [comment]
Tried without Vulkan -> same crash. Tried verify game files -> same crash. I am lost

**Comment by ThirteenAG** [comment]
Does it happen without fusion fix? I can't reproduce. The crash is inside the function that converts game's renderstate to d3d renderstate, and looks like the game's renderstate is corrupted.

**Comment by ThirteenAG** [comment]
[GTAIV.EFLC.FusionFix.asi.zip](https://github.com/user-attachments/files/16944357/GTAIV.EFLC.FusionFix.asi.zip)

Test this build.

**Comment by mLithil** [comment]
Works like a charm. What did you change ? Or what was the root cause ?

**Comment by mLithil** [comment]
Hey i just tried with the release version of fusion fix and i succesfuly continue via campaign, but mission Tunnel death - it crashes exactly same as Smackdown. Its on same spot in map, so propably its tied to location.

**Comment by ThirteenAG** [comment]
The build from above works?

**Comment by mLithil** [comment]
yes
