### ISSUE TITLE
Mouse fix activated also increase mouse sensitivity threshold

### ISSUE THREAD

**Issue by nonoash** [ThirteenAG/GTAIV.EFLC.FusionFix#61]
Hello,

I've installed GTA IV and Fusionfix to test the deadzone fix (which works) but before installing fusionfix i had the sensitivity in the settings at its lowest and the sensitivity was manageable.

After using Fusionfix, the sensitivity skyrocketed even though it's still unchanged in the settings. Disabling mousefix, gives back the low sensitivity.

It's a pity because now it's either "you get crazy sensitivity but proper aim without deadzone" OR "good sensitivity but deadzone when aiming"

Is there any solution to this ?
I would appreciate any infos, thanks.

**Comment by Tomasak** [comment]
fixed on 2.0
