### ISSUE TITLE
[Feature Request] Make radar zoom out button on controller be Left Button like on consoles

### ISSUE THREAD

**Issue by DeusMaveriX** [ThirteenAG/GTAIV.EFLC.FusionFix#611]
### What should happen

Make turn off radio button on controller be Left Button like on consoles so players don't accidentally keep turning off their radios while using radar zoom out with Down Button (pc default)

https://www.youtube.com/watch?v=izACweNM6tU

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by Tomasak** [comment]
It was change by R* toronto to allow players to skip songs on indepdence FM
