### ISSUE TITLE
Hide cursor when controller input

### ISSUE THREAD

**Issue by ProbablyWorth** [ThirteenAG/GTAIV.EFLC.FusionFix#619]
### What should happen

Is it possible to hide the game cursor when playing with controller? It's kinda annoying seeing the cursor in the middle of the screen after opening the menu.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
I support this, annoying. Much needed imo.

**Comment by NewtonThirdL** [comment]
agree
