### ISSUE TITLE
Shadows/Reflections stuttering when moving

### ISSUE THREAD

**Issue by xAphex** [ThirteenAG/GTAIV.EFLC.FusionFix#620]
### Game version this happens in

GTA IV Version: v1.2.0.59
FusionFix Version: v3.1.0

### What area of the game

Pretty much anywhere there is shadows/reflections.

### What should happen

Shadows/Reflections shouldn't stutter.

### CrashDumps and logs

https://www.youtube.com/watch?v=OxG-zG6B3Cg

Video showing the issue.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by xAphex** [comment]
On a closer view, idk if calling it stutter is the right word, sorry about that.

**Comment by RecklessGlue540** [comment]
That's because you're using low settings lol. If you can't use High settings then the only solution is a hardware upgrade sadly.

**Comment by xAphex** [comment]
> That's because you're using low settings lol. If you can't use High settings then the only solution is a hardware upgrade sadly.

im playing with a 3080 ti lmao, and even on highest settings it still does that.

**Comment by RecklessGlue540** [comment]
For water reflections, max water quality fixes it.
For shadows, use the HighResolutionShadowsOption in the .ini only. 

You can't have both HighResShadows and HighResNightShadows on because both of them at once will cause memory leaks. It's a limited game. Nothing can be done about that one.

**Comment by xAphex** [comment]
> For water reflections, max water quality fixes it. For shadows, use the HighResolutionShadowsOption in the .ini only.
> 
> You can't have both HighResShadows and HighResNightShadows on because both of them at once will cause memory leaks. It's a limited game. Nothing can be done about that one.

yup, 100% correct, turning on water to max and changing highresshadows in ini fixed them.

thank you.
