### ISSUE TITLE
Crash after 2nd cutscene of "The Master and the Molotov" mission

### ISSUE THREAD

**Issue by xtul9** [ThirteenAG/GTAIV.EFLC.FusionFix#622]
### Game version this happens in

v1.2.0.43

### What area of the game

When I start "The Master and the Molotov" mission, right after the second cutscene starts (the one after we park in front of Perestroika), the game crashes.

Oddly enough the same crash occurs when trying to do Brucie's first mission (Search and Delete) - reach the second cutscene, and the game will crash.

The log says `Unhandled exception at 0x01072C88 in GTAIV.exe (+0x352c88): 0xC0000005: Access violation reading location 0x0000000C.`

### What should happen

The game shouldn't crash

### CrashDumps and logs

[CrashDumps + Save.zip](https://github.com/user-attachments/files/17102805/CrashDumps.%2B.Save.zip)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
Use v1.2.0.59.

**Comment by xtul9** [comment]
@ThirteenAG Updating the game does work, thanks. 😅
