### ISSUE TITLE
Подмена пассажиров \\ substitution of peds and passengers

### ISSUE THREAD

**Issue by Damierror** [ThirteenAG/GTAIV.EFLC.FusionFix#623]
### What should happen

I would like the peds not to change when removed, it seems to me that because of this there are strong lags in the game that the pedestrians stupidly change, and this happens at insignificant distances from the player. This is especially noticeable when playing with a sniper rifle, In addition, cars lose traces of damage, etc., such as dirt and blood. / это вызывает сильное игровое отторжение\ This causes loss of interest in the game

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by MagicAl6244225** [comment]
Change visualSettings.dat values for ped.lod.distance.high from 15.00 to 25.00 to make the distance they change the same as in GTAV.

Similarly you may change car.lod.distance.high from 20.00 to 40.00 and car.lod.distance.low from 80.00 to 180.00.

**Comment by Damierror** [comment]
[MagicAl6244225](https://github.com/MagicAl6244225) хоть 1000 выстави, пассажиры в машинах дальше 50м не отображаются, а когда появляются то совсем другие. И пассажиры могут полностью исчезать и появляться случайным образом.
