### ISSUE TITLE
Game crash during first loading with ScripthookDotNet

### ISSUE THREAD

**Issue by manu90mala** [ThirteenAG/GTAIV.EFLC.FusionFix#625]
### Game version this happens in

v1.0.7.0

### What area of the game

during loading and before entering the game, the game crashes - this happens with the following combination:

- latest Scripthookdotnet by Tomasak
- Latest ASI Loader (7.7.0+)
- FusionFix 3+ 

I already reported this to TAG on the ASI loader GitHub, and to Tomasak on ScripthookDotNet github - as of today nobody was able to identify the issue on either side

this issue does not allow anyway to benefit from latest ScripthookDotNet and FusionFix together

### What should happen

game should start as it is working perfectly fine with FF 2.5.6, ASI loader up to version 7.2.0 and latest ScripthookDotNet

### CrashDumps and logs

[GTAIV.exe.20240926145332.dmp](https://github.com/user-attachments/files/17148781/GTAIV.exe.20240926145332.dmp)
[GTAIV.exe.20240926145332.log](https://github.com/user-attachments/files/17148782/GTAIV.exe.20240926145332.log)

### Last working version

2.5.6

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by manu90mala** [comment]
What do you mean you don’t want to find out? Like I am an expert modder like you? What are those issues for other than trying to ask for support? You really sound like on period

**Comment by Damierror** [comment]
[ThirteenAG](https://github.com/ThirteenAG) у меня игра вылетает при сворачивании игры или при изменении основных настроек графики таких как отражения или тени. на 1.0.7.0

**Comment by Tomasak** [comment]
unsupported game version
