### ISSUE TITLE
Radio Stations resetting after every cutscene

### ISSUE THREAD

**Issue by DAMNED117** [ThirteenAG/GTAIV.EFLC.FusionFix#626]
### Game version this happens in

v1.2.0.59

### What area of the game

This issue only seems to be present when FusionFix is installed.

When you first load into the game, every radio station is played at its own random timestamp, which is normal of course. However, when a cutscene is triggered (whether the cutscene is from a mission, another cutscene within said mission, or from a side mission), almost all of the radio stations reset back to 0:00 and they won't start playing unless you manually select them one by one to force them to play.

Below is a video for an example showing a few of the radio stations playing before and after a cutscene. Mind you, the video is **heavily** compressed to meet the 10MB limit requirement:

https://github.com/user-attachments/assets/08162d5b-e341-48e3-9e4a-8418a0b095dd

It also seems that the last radio station(s) that you played before triggering a cutscene won't reset (sometimes).

The video above was recorded with only FusionFix v3.1.1 (and the latest git build) installed on a clean copy of the game.

### What should happen

The radio stations shouldn't reset after every cutscene.

### Last working version

Not sure

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
> This issue only seems to be present when FusionFix is installed.

We have confirmed that this is incorrect statement. The asi doesn't cause such behavior.

However, as for the issue itself, can you try this build?

[GTAIV.EFLC.FusionFix.zip](https://github.com/user-attachments/files/17172200/GTAIV.EFLC.FusionFix.zip)

**Comment by DAMNED117** [comment]
Hello @ThirteenAG, I've used the build provided and can confirm that this issue is now fixed. All of the radio stations no longer reset after a cutscene.

Thank you for your work, we appreciate it.

Take care.

**Comment by ThirteenAG** [comment]
It is unclear if this breaks anything else though, so if you are able to test longer and report the result, please do.

**Comment by DAMNED117** [comment]
Will do, currently more than halfway through a TLAD playthrough.

Will report back after I finish the playthrough, just to make sure.

**Comment by DAMNED117** [comment]
Well that was quick.

Just finished my TLAD playthrough with the new build, no issues to report, fix is working as intended.

Thanks once again, @ThirteenAG.

**Comment by MOnkeMan5009** [comment]
has this been added to the pack of next update?

**Comment by ThirteenAG** [comment]
Can somebody test this again with latest dev build?

**Comment by DAMNED117** [comment]
Wth, I did not get any notifications from GitHub for the last few replies.

> Can somebody test this again with latest dev build?

I tested the public releases of v3.2.0 and v3.2.1, and the radio stations work as intended after a cutscene yet again on both of these versions.

However, if you're still concerned about the implemented fix, please let me know and I'll test more if needed.

Thanks for your work as always, @ThirteenAG.

**Comment by ThirteenAG** [comment]
I guess it's fine, it was either an oversight or an optimization of some sort. Seems like the code deliberately was resetting it, so not doing so shouldn't cause any problems.
