### ISSUE TITLE
Borderless windowed doesn't seem to work for me

### ISSUE THREAD

**Issue by ramseyone** [ThirteenAG/GTAIV.EFLC.FusionFix#63]
Maybe it's a problem I won't use, but other options can be used. Only Borderless windowed can't be used.
The borderless windowed value I set is 1.But it can't be used.Why?My version is The Complete Edition.

**Comment by Tomasak** [comment]
You have to use -windowed command line parameter, either add it via RGL, steam game properties or create commandline.txt in same folder as gtaiv.exe is and put it there
