### ISSUE TITLE
Make Zolikas Mods Work Again

### ISSUE THREAD

**Issue by SimonPhoenix96** [ThirteenAG/GTAIV.EFLC.FusionFix#632]
### What should happen

I saw zolika mention there's hardcoded exceptions for loading his mod files, frankly y'alls nerd' beefs is weird and childish, we (the consumers) demand full freedom to install which ever mod we want.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by SimonPhoenix96** [comment]
i added the misunderstanding and miscommunication part to the title of the issue - that is what this issue boils down to in the first place - a bunch of nerds talking past each other and then Zolika being a baby and fully leaving the scene while the creators/stealers of this fusionfix mod acting like nothing happened

**Comment by ThirteenAG** [comment]
We are an open source community, if you prefer anything else - leave. This is a website for hosting code, not your stupid rants.

**Comment by juicermv** [comment]
@SimonPhoenix96 afaik the hardcoded exceptions are not there purely out of pettiness, some of zolikas mods are straight up incompatible with ff, and he has refused to cooperate with the ff team in order to fix said issues or something like that.
