### ISSUE TITLE
Fatal Error SRCP10 in TLaD

### ISSUE THREAD

**Issue by ProbablyWorth** [ThirteenAG/GTAIV.EFLC.FusionFix#633]
### Game version this happens in

v1.2.0.59

### What area of the game

Entering the marker for Elizabeta's mission "Marta Full of Grace" instantly causes the game to crash and shows that error message for SRCP10. I found out this was resolved awhile ago so I'm guessing this new update brought it back. This occurs on 3.1.1 and latest git build (if they arent the same thing)

### What should happen

It shouldn't crash

### CrashDumps and logs

dmp file: https://drive.google.com/file/d/1uDGfXzrgzwbRXvq_XTridry1JaJeIi7L/view?usp=sharing

Unhandled exception at 0x00BB3BE0 in GTAIV.exe (+0x3be0): 0xC0000005: Access violation writing location 0x00000000.
    Register dump:
        EAX: 0x00000001  EBX: 0x7E204400  ECX: 0x64E2E099  EDX: 0x02AD0000  
        EDI: 0x00000000  ESI: 0x1BCBD06C  EBP: 0x1C322080  EIP: 0x00BB3BE0  
        ESP: 0x00B8E46C  EFL: 0x00010246  
        
        CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   
        ES: 0x0000002B   DS: 0x0000002B   
        
        ST00: 0x00000000 0xC6B75700 0x00003FFE 0xEB000000  [ 0.000000 -23467.500000 0.000000 -154742504910672534362390528.000000 ]
        ST01: 0x00000000 0xCE84EB00 0x0000C000 0x31000000  [ 0.000000 -1114996736.000000 0.000000 0.000000 ]
        ST02: 0x00000000 0xCEA63100 0x0000C000 0xA6000000  [ 0.000000 -1394114560.000000 0.000000 -0.000000 ]
        ST03: 0x00000000 0xFE46A600 0x00003FFE 0x00000000  [ 0.000000 -66012266110982531055322465081539690496.000000 0.000000 0.000000 ]
        ST04: 0x00000000 0x80000000 0x00003FFF 0x00000000  [ 0.000000 -0.000000 0.000000 0.000000 ]
        ST05: 0x00000000 0x80000000 0x00003FFE 0x00000000  [ 0.000000 -0.000000 0.000000 0.000000 ]
        ST06: 0x00000000 0x80000000 0x00003FFB 0x00000000  [ 0.000000 -0.000000 0.000000 0.000000 ]
        ST07: 0x00000000 0x80000000 0x00003FFB 0x002B0000  [ 0.000000 -0.000000 0.000000 0.000000 ]
        
        XMM00: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM01: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM02: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM03: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM04: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM05: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM06: 0x3F000000 0x00000000 0x00000000 0x00000000  [ 0.500000 0.000000 0.000000 0.000000 ]
        XMM07: 0x38800000 0x00000000 0x00000000 0x00000000  [ 0.000061 0.000000 0.000000 0.000000 ]
        
    Stack dump:
        0x00B8E46C:  0000FFFF 0126E10E 00B8E520 00B8E4B0 00B8E4A0 1ED24B40
        0x00B8E484:  00000001 BDB28B31 43AB0F9A BDB19C15 BC22D5DC 3F7F05D9
        0x00B8E49C:  012D1A12 3F169DA1 1C6213C0 00540047 00200041 00560049
        0x00B8E4B4:  00460020 00540041 004C0041 00450020 00520052 0052004F
        0x00B8E4CC:  0020003A 00520053 00500043 00300031 00000000 00000000
        0x00B8E4E4:  00000000 00000000 00000000 00000000 00000000 00000000
        0x00B8E4FC:  00000000 00000000 00000000 00000000 00000000 00000000
        0x00B8E514:  00000000 00000000 00000000 00000000 00000000 00000000
        0x00B8E52C:  00000000 00000000 00000000 00000000 00000000 00000000
        0x00B8E544:  00000000 00000000 00000000 00000000 00000000 00000000
        base: 0x00A90000   top: 0x00B8E46C   bottom: 0x00B90000
        
    Backtrace (may be wrong):
        =>0x00BB3BE0 in GTAIV.exe (+0x3be0) (0x00B8E46C) 
          0x0126E10E in GTAIV.exe (+0x6be10e) (0x00B8E498) 
          0x012D1A12 in GTAIV.exe (+0x721a12) (0x00B8E49C) 
          0x3F169DA1 in unknown (+0x3f169da1) (0x00B8E4A0) 
          0x1C6213C0 in unknown (+0x1c6213c0) (0x00B8E4A4) 
          0x00540047 in unknown (+0x540047) (0x00B8E4A8) 
          0x00200041 in unknown (+0x200041) (0x00B8E4AC) 
          0x00560049 in unknown (+0x560049) (0x00B8E4B0) 
          0x00460020 in unknown (+0x460020) (0x00B8E4B4) 
          0x00540041 in unknown (+0x540041) (0x00B8E4B8) 
          0x004C0041 in unknown (+0x4c0041) (0x00B8E4BC) 
          0x00450020 in unknown (+0x450020) (0x00B8E4C0) 
          0x00520052 in unknown (+0x520052) (0x00B8E4C4) 
          0x0052004F in unknown (+0x52004f) (0x00B8E4C8) 
          0x0020003A in unknown (+0x20003a) (0x00B8E4CC) 
          0x00520053 in unknown (+0x520053) (0x00B8E4D0) 
          0x00500043 in unknown (+0x500043) (0x00B8E4D4) 
          0x00300031 in unknown (+0x300031) (0x00B8E4D8) 
        
    

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
It's a resource error, meaning the files are causing it, not the code.

**Comment by DAMNED117** [comment]
Using a modpack? It could be conflicting mods.

**Comment by ProbablyWorth** [comment]
> Using a modpack? It could be conflicting mods.

Yeah im using the following mods:
Fusion Fix 3.1.1
Various Fixes 2.0.1
Latest ConsoleVisuals (all except suits)
EFLC Character Fixes
Ash Vehicle Pack
Ash High-Res Misc. Pack

I'm afraid that uninstalling one of these mods will break my save game. I think the safest option is to try with only Fusion Fix and Various Fixes. Uninstalling Character Fixes might corrupt my save tho

**Comment by DAMNED117** [comment]
> I'm afraid that uninstalling one of these mods will break my save game. I think the safest option is to try with only Fusion Fix and Various Fixes. Uninstalling Character Fixes might corrupt my save tho

Imo, based on the mods you use, you should give [Gillian's modpack](https://gillian-guide.github.io/drag-and-drop-archive/) a shot since it already includes all of these mods + more which will improve the game even more ofc.

I had this exact same issue and I reported it to Gillian since I was using his modpack and he fixed it. IIRC it was caused by some of Characters Fixes' files as they were overlapping. Pretty sure you're already aware of this step but it's best to install the modpack on a clean copy of the game (no mods) to have the best results.

Sorry if I couldn't help you with your current modpack as I don't know how to manually fix it, so recommending the modpack mentioned above is the least I could do.

**Comment by ProbablyWorth** [comment]
> > I'm afraid that uninstalling one of these mods will break my save game. I think the safest option is to try with only Fusion Fix and Various Fixes. Uninstalling Character Fixes might corrupt my save tho
> 
> Imo, based on the mods you use, you should give [Gillian's modpack](https://gillian-guide.github.io/drag-and-drop-archive/) a shot since it already includes all of these mods + more which will improve the game even more ofc.
> 
> I had this exact same issue and I reported it to Gillian since I was using his modpack and he fixed it. IIRC it was caused by some of Characters Fixes' files as they were overlapping. Pretty sure you're already aware of this step but it's best to install the modpack on a clean copy of the game (no mods) to have the best results.
> 
> Sorry if I couldn't help you with your current modpack as I don't know how to manually fix it, so recommending the modpack mentioned above is the least I could do.

This modpack looks interesting. Gonna install. Thanks!

**Comment by indianaliam1** [comment]
For future reference for anyone ALSO running into this, I'd bet it's character fixes as that's the only mod I installed apart from FusionFix

I had exactly the same repeatable crash at the same moment launching Marta Full of Grace
