### ISSUE TITLE
Excessive brightness of lamp posts

### ISSUE THREAD

**Issue by Damierror** [ThirteenAG/GTAIV.EFLC.FusionFix#635]
### What should happen

In addition to reducing the brightness, I would like them to work from 21:00 to 5:00, this can help improve performance and generally improve the picture in the twilight.
![Снимок экрана (17627)](https://github.com/user-attachments/assets/caee42f8-7812-429e-b3a0-60181bfd9660)
![Снимок экрана (17726)](https://github.com/user-attachments/assets/49aed4a4-9979-4eda-a4cc-c49878357b12)
![Снимок экрана (17737)](https://github.com/user-attachments/assets/746c8342-571a-4849-b817-7ca3450245c4)

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by Parallellines0451** [comment]
Both of your requests are out of FF's scope. You can easily tweak the lights' intensity by editing the lamppost models themselves.
