### ISSUE TITLE
Headlight shadows without vehicle shadows cause the drivers shadows to be cast

### ISSUE THREAD

**Issue by Tasosgemah** [ThirteenAG/GTAIV.EFLC.FusionFix#637]
This is a weird bug that doesn't exist in the non-fusion fix game. 

One fix is to enable vehicle shadows. But that also disables my own car;s shadow, even during the day, which looks really bad (like it's floating).

Can the the driver's shadows also be disables along with their vehicles?

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by Tasosgemah** [comment]
I tried some older versions and i think 3.0.5 was the last where Headlight Shadows worked properly. The drivers shadow didn't get cast and headlights from cars would cast your character's shadow. 

In later versions these don't work properly anymore.

**Comment by Tomasak** [comment]
Headlight shadows due to their buggy nature are unsupported
