### ISSUE TITLE
Pop in texture when zoom 

### ISSUE THREAD

**Issue by Dx360** [ThirteenAG/GTAIV.EFLC.FusionFix#638]
### Game version this happens in

v1.2.0.59

### What area of the game

https://github.com/user-attachments/assets/ac81f4d4-9205-4a45-b15d-a56a82fc37e8

### What should happen

Is there a way to solve it?   -availablevidmem 8192  happens 5-10 minutes after entering the game.
Slide = 25 31 33

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Dx360** [comment]
Various fix are problems i think

**Comment by Dx360** [comment]
Sorry for bad english

**Comment by Dx360** [comment]
https://github.com/user-attachments/assets/16ca32cd-554d-4db8-9380-bb6a9b3b4b34

**Comment by Dx360** [comment]
Auto graphic setting fix this

**Comment by ShinChaosBahamut** [comment]
Try setting -availablevidmem to a lower value. (read 3072.0's the highest you can go before getting this error) Game's 32-bit *albeit with the LAA Flag enabled* so it can't use more than 4 GB of total RAM anyways.

**Comment by RecklessGlue540** [comment]
This is an aggressive culling issue and happens regardless of anything. Even on console. It's probably something in the code.

**Comment by Tomasak** [comment]
vanilla game issue
https://github.com/GTAmodding/GTAIV-Issues-List/issues/13
