### ISSUE TITLE
Question: How "partial" is the emissive shaders fix?

### ISSUE THREAD

**Issue by philou-felin** [ThirteenAG/GTAIV.EFLC.FusionFix#64]
How "partial" is the emissive shaders fix? What has _not_ been fixed? Sorry for the short question. I'm just curious. 😅

**Comment by Tomasak** [comment]
Seems like emissive shader fix is complete, but gta_default shader is broken (and probably always was, even on lower patches). Bawsaq sign on vanilla is actually using gta_default shader for the sign and fusion fix forces it to use emissive thus making it working.

**Comment by philou-felin** [comment]
Thanks!
