### ISSUE TITLE
Install The latest version FusionFX v3.1.1 Game fail to open

### ISSUE THREAD

**Issue by Yellodog114** [ThirteenAG/GTAIV.EFLC.FusionFix#641]
### Game version this happens in

v1.2.0.59

### What area of the game

When launching the game, Rockstar laucher pops up. While loading the game the game just give me a error message.
The game doesn't have any mod install and without fusion fix, the game runs perfectly fine
![163b1cd7bc148c4cf59c3e40f26e3abf](https://github.com/user-attachments/assets/20a3c6f3-e634-4751-abd8-a7ffd2185bf5)

### What should happen

Really weird，Maybe is 3.1.1 have bugs? Or I need back to old version game

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
There's no other way to help unless you post crash dump **and** log.

**Comment by Yellodog114** [comment]
The problem is I don‘t have any crash happen，the game just fail to open.
And I'm very sorry，but I don’t know how to see the logs,Can you tell me how?

**Comment by ThirteenAG** [comment]
Read the text when you create new issue.
https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/new?assignees=&labels=&projects=&template=bug.yml

**Comment by Yellodog114** [comment]
![322fa6408c6407afa87b8f36d83d06d7](https://github.com/user-attachments/assets/31e24d64-e87a-4723-bef4-75289c71c70c)
Have I done something wrong? I still haven't generated any logs or dump.

**Comment by Yellodog114** [comment]
ahhh now I know. thanks let me try it

**Comment by Yellodog114** [comment]
weird , still doesn't have any dump appear

**Comment by ThirteenAG** [comment]
I don't know then, maybe try English version somehow.

**Comment by Yellodog114** [comment]
https://github.com/user-attachments/assets/beabe8c3-a97e-41e9-b528-5d2f9c467d82

doesn't have any dump or log appear

**Comment by Tomasak** [comment]
can you try without the advancedhook dll and asi?
and d3d9.dll is dxvk? Its quite old, you should update it.

**Comment by Yellodog114** [comment]
OMG now I can play the game，thanks a lot！！！
