### ISSUE TITLE
Incorrect overlapping of sprite textures

### ISSUE THREAD

**Issue by Damierror** [ThirteenAG/GTAIV.EFLC.FusionFix#642]
### Game version this happens in

v1.2.0.59

### What area of the game

when increasing in size 
![Снимок экрана (17999)](https://github.com/user-attachments/assets/97ee7814-4266-4f2a-90e1-81fbaa88f1d2)

### What should happen

alpha texture shader?

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Tomasak** [comment]
heavily moddified game with unclear problem.
