### ISSUE TITLE
Game crash after loading screen

### ISSUE THREAD

**Issue by t-ro86** [ThirteenAG/GTAIV.EFLC.FusionFix#651]
### Game version this happens in

v1.2.0.59

### What area of the game

Patch 1.0.7.0 here. Since 22nd of October all version off Fusion Fix makes the game crash after the loading screen. 

### What should happen

Everything is fine with previous version on 1.0.7.0.

### Last working version

v.3.11

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Tomasak** [comment]
unsupported game version
