### ISSUE TITLE
Missing shadows in Steinway park garden thing

### ISSUE THREAD

**Issue by juicermv** [ThirteenAG/GTAIV.EFLC.FusionFix#653]
### Game version this happens in

v1.2.0.59

### What area of the game

Garden/skate park in Steinway
![20241104210807_1](https://github.com/user-attachments/assets/48b5f3cb-0a67-490c-a507-db4e861b04f7)
![20241104210743_1](https://github.com/user-attachments/assets/8385c027-1e34-49f7-8f29-8b674a04bfd7)
![20241104210719_1](https://github.com/user-attachments/assets/3dd7ec69-d819-4664-bcfa-9dda2a46c80f)
![20241104210632_1](https://github.com/user-attachments/assets/9b432955-3dda-4fd9-a98b-0f021c3a79cd)

### What should happen

Terrain should be properly shaded here

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Tomasak** [comment]
vanilla bug
report it here https://github.com/GTAmodding/GTAIV-Issues-List/issues
