### ISSUE TITLE
Gives the logo and game info screens and loading animations a fixed 60fps instead of following the frame limiter setting.

### ISSUE THREAD

**Issue by HAYASHIDASEIYAKU** [ThirteenAG/GTAIV.EFLC.FusionFix#655]
### What should happen

Because of the limiter the logo and splash screen also follow that setting, which causes a lot of lag and incorrect animation playback speed. Can it be fixed to 60fps to play correctly?

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by HAYASHIDASEIYAKU** [comment]
I know about [UnlockFramerateDuringLoadscreens]
But it can only follow the frame rate of the monitor.
For example, my screen is 120fps
If I unblock it, it will speed up the interface to 120 instead of the 30 set in the ini, which destroys the animation.

**Comment by Tomasak** [comment]
There are limitations of dx9 related to locking/unlocking framerate, so no.
