### ISSUE TITLE
Add EFLC vehicles, weapons and content to base game and across both DLCs

### ISSUE THREAD

**Issue by OrganicOstrich** [ThirteenAG/GTAIV.EFLC.FusionFix#659]
### What should happen

This will help improve compatibility with trainers so spawning options. Will also help compatibility with mods that share content.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by Tomasak** [comment]
out of scope.no
