### ISSUE TITLE
Log In message on rockstar games logo screen

### ISSUE THREAD

**Issue by Luigi18737** [ThirteenAG/GTAIV.EFLC.FusionFix#66]
Installed FusionFix correctly, when i booted up the game after the copyright screens, on the rockstar games logo screen appeared a message that said something like: You have not logged in with a profile. logging in with a live profile allows you to save game progress along with any achievements earned and blahblahblah (used google translate to translate to english the message, english is not my native language) i cannot provide a screenshot of the message because i uninstalled the mod. i didnt think of the message during gameplay, but I realized that they did not give me the achievements, uninstalled the mod, message gone and got the achievements, lets see if anyone can provide a solution or explation.

bye bye

**Comment by Tomasak** [comment]
Open plugins\GTAIV.EFLC.FusionFix.ini
Edit SkipMenu = 0 to SkipMenu = 1
now game should have enough time to log in into social club
