### ISSUE TITLE
Improve wanted level system and police

### ISSUE THREAD

**Issue by OrganicOstrich** [ThirteenAG/GTAIV.EFLC.FusionFix#661]
### What should happen

Rockstar did not program the police correctly and left a lot of errors: LCPD driving Noose vehicles, Alderney State Troopers Driving LCPD vehicles, FIB and Noose unable to spawn in same wanted level, with Noose Stainer & Patriot having the same issue.

Area livery mod (or something similar) by default should be included in Fusion Fix

Diverse PD 4.5 works with Fusion Fix but does not appear to be supported 

https://www.lcpdfr.com/downloads/gta4mods/scripts/37188-diversepd/

This could be a basis for a fix? Maybe remove "FIB will spawn in unmarked vehicles (not FIB buffalos) and is not marked in the map. (5+ stars)", decrease the sawn frequency, and fix the issue where you see officers spawning in the rear seat, in patrolling  causing the vehicle to stop

My other suggestion about sharing content across all 3 games, means that Police Buffalo and Police Bike could be added to patrols and wanted system, and have the APC, Police Stinger, Prison Bus and Police Stockade spawning at relevant location(s)

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by Tomasak** [comment]
out of scope, no
