### ISSUE TITLE
Fix pause menu blip animations at high framerates

### ISSUE THREAD

**Issue by DAMNED117** [ThirteenAG/GTAIV.EFLC.FusionFix#662]
### What should happen

With the release of v3.4.0, the blip animations on the minimap at high FPS have been fixed, but not the animations in the pause menu (e.g. the cops' blip animations). Would love to see this getting fixed soon because I find it a little annoying that one is going a lot faster than the other with the latest release lol.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by ThirteenAG** [comment]
That's how it is with 30 fps, there's nothing left to fix.

**Comment by DAMNED117** [comment]
Understood, thanks for the awareness.
