### ISSUE TITLE
[Feature Request] Console's Anti-Aliasing

### ISSUE THREAD

**Issue by luigi98-beep4** [ThirteenAG/GTAIV.EFLC.FusionFix#665]
### What should happen

Since fusion fix's anti aliasing only have FXAA and SMAA, how about we add Xbox 360's 2x AA and PS3's QAA (Quincunx Anti Aliasing), that way we can finally have console equivalent graphics settings to the people who have low-mid end pc or people who prefer vintage than modern and high quality.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by Parallellines0451** [comment]
Not possible.
