### ISSUE TITLE
A weird but hopefully important request

### ISSUE THREAD

**Issue by GTAGamingChannel44** [ThirteenAG/GTAIV.EFLC.FusionFix#666]
### What should happen

This is an essential mod that fixes and improves the game in massive ways, I use it all the time in the Complete Edition of GTA IV. One day I wanted to downgrade to v1.0.8.0 of GTA IV, I wanted to test whether this mod works there but it doesn't work. 

My request is to make your mod fully supports 1070/1080 in the same way as the complete edition, I know that's a small or unwanted thing but making it full support for these old patches opens a huge window of oppurtunity and huge access to a lot of people who play on these patches for valid reasons.

This mod will be accessible for everyone and that's a benefit for you and everyone else. But of course, the decision is yours.

I hope I didn't bother you and I wish you the best.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by Tomasak** [comment]
It works tho. Just follow steps it tells you on screen

**Comment by GTAGamingChannel44** [comment]
Can you show me a picture of the steps, or it's located somewhere in the mod page
