### ISSUE TITLE
[Future request] Make an option to disable Lens Flares

### ISSUE THREAD

**Issue by hoolygunn** [ThirteenAG/GTAIV.EFLC.FusionFix#668]
### What should happen

Would be very nice.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by sTc2201** [comment]
What exactly do you mean with lens flares? More info perhaps e.g. screenshots? 
The game doesn't have any lens flare effects that I know of unless you mean sun shafts which already has a in-game toggle option or the corona (star shaped sprite) around light sources.
