### ISSUE TITLE
Short shadow distance on medium

### ISSUE THREAD

**Issue by Killian-cyber** [ThirteenAG/GTAIV.EFLC.FusionFix#674]
### Game version this happens in

v1.2.0.59

### What area of the game

I noticed that in GTAIV.EFLC.FusionFix.ini there is an option called OverrideCascadeRanges. I disabled it to make a difference between both disabled and enabled, but there is no difference. Im using medium shadow quality. On the ps3 the shadow distance looks similar to the one from very high but only the distance.

### What should happen

Doesn't this feature supposed to improve the shadow distance similar to very high or the console distance?
![Capture](https://github.com/user-attachments/assets/7f692dab-5814-48aa-8b36-60246fba9e5b)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Parallellines0451** [comment]
Yes, OverrideCascadeRanges increases the shadow draw distance up to console or pre patch 1.0.6.0 levels and it should never really be disabled.

What you're seeing is not a draw distance issue, but a shadow bias issue. The lower the shadow resolution / quality, or the higher the blur radius, the higher the shadow bias needs to be to prevent [artifacting](http://digitalrune.github.io/DigitalRune-Documentation/html/3f4d959e-9c98-4a97-8d85-7a73c26145d7.htm).

For medium quality, I recommend using "Sharp" shadow filter to make the bias as low as possible.

**Comment by Parallellines0451** [comment]
Not really. Medium shadows are 512x512 for each cascade, which is quite low res. Just use Sharp if you can't afford to run High or Very High quality.
