### ISSUE TITLE
how to use revive with fusionfix 

### ISSUE THREAD

**Issue by liuyankuan** [ThirteenAG/GTAIV.EFLC.FusionFix#677]
### What should happen

when i only use vegetation mod from revive the tree looks good but when i use fusionfix  the tree will turn to white game version 1.2.043and 1.2.059

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by liuyankuan** [comment]
![20241129_011206](https://github.com/user-attachments/assets/e5b06911-4f32-404a-9478-9016dad7c5a2)
fusionfix with revive

**Comment by Tomasak** [comment]
FusionFix and its part FusionShaders are open source, revive vegetation iirc is not even public, so there is absolutely zero reason from FusionFix to care about every single mod to be 100% compatible if it touches same files. So its up to revive author.
