### ISSUE TITLE
Can i only use game fast load and LimitAdjuster ?

### ISSUE THREAD

**Issue by CoresenYan** [ThirteenAG/GTAIV.EFLC.FusionFix#679]
### What should happen

FusionFix is a great mod, thanks for developer! 
I want to just use "game fast load" and LimitAdjuster for more handing.dat line, its possiable?

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by Tomasak** [comment]
its opensource, feel free to make a fork with only those two features.
