### ISSUE TITLE
[Feature Request] More accurate PS4 button icons.

### ISSUE THREAD

**Issue by kaleenlab** [ThirteenAG/GTAIV.EFLC.FusionFix#680]
### What should happen

The PS4 button prompts don't actually match up with the buttons you need to press, specifically, all the prompts that involve the touchpad that don't actually function. For example, when you die, it tells you to press the touchpad to save a clip, when it's actually the share button. Older PS4 button mods didn't have this issue, so I'm unsure why it exists now.

**Comment by Tomasak** [comment]
Actual PS4/5 use touchpad as a substitute for previously used select button, share button is solely used for the taking pics/social stuff.
Thus it's up to use to correctly map touchpad button as select button in software they use for their dualshock4/dualsense such as steam input or ds4windows.

So this won't be changed.
