### ISSUE TITLE
Radios still reset despite that bug supposedly being fixed

### ISSUE THREAD

**Issue by Tastycrabcakes41** [ThirteenAG/GTAIV.EFLC.FusionFix#681]
### Game version this happens in

v1.2.0.59

### What area of the game

When I exit a cutscene the radio still resets. This is strange as it is meant to be fixed on 3.4.0

This is most noticeable on stations like The Beat and Electro-Choc, this also happens on dynamic stations, but instead of resetting the the beginning of its playlist is just plays a random song that it wasn’t playing before it reset. I’m also on 1080 if that makes any difference

### What should happen

Radio stations should not reset after cutscenes.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Tomasak** [comment]
Unsupported version
