### ISSUE TITLE
when i change an option they all change

### ISSUE THREAD

**Issue by anasdev545** [ThirteenAG/GTAIV.EFLC.FusionFix#683]
### Game version this happens in

v1.2.0.30

### What area of the game

when i press on a button in the settings all the other option related to fusion fix change

### What should happen

it should change one option not all of them

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Tomasak** [comment]
get a proper clean legal copy of the game
