### ISSUE TITLE
Center driving camera?

### ISSUE THREAD

**Issue by Luc45** [ThirteenAG/GTAIV.EFLC.FusionFix#686]
### What should happen

1. Try to drive around without using a mouse, especially making corners, entering streets etc
2. See that it's impossible because the game FORCES you to constantly re-center the camera with the mouse

Is there any configurable option in this mod to fix this behavior? I tried increasing "Centering Delay" in Controller options but that didn't seem to change anything. Thanks.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by anthoncast** [comment]
Depends. What are your FPS capped at? Normally it works better at 30 tho.

**Comment by Luc45** [comment]
160 FPS, I have a 4090

**Comment by anthoncast** [comment]
Well, lock the FPS at 30 or 60 in the graphics tab. It's better to have it at 30 for a much better experience with bugs. That way the camera should auto center as intended.

**Comment by Luc45** [comment]
@anthoncast Yeah seems to be much worse at High FPS. https://www.youtube.com/watch?v=iEXAYSWN0GI

Is this something this mod can hopefully fix?

**Comment by anthoncast** [comment]
> Is this something this mod can hopefully fix?

Sadly no. There are even FPS bugs in GTAV! So I know you want to push this game with the power of your PC, but I really really really recommend to cap the FPS at 60 maximum, because beyond that it's unplayable.

**Comment by Luc45** [comment]
All right. Thanks a lot for your help! I'll be closing this and limitting my FPS to 60, which seems to be a good middle-ground.
