### ISSUE TITLE
Backward Compatibility issue 

### ISSUE THREAD

**Issue by LLIXXXIR** [ThirteenAG/GTAIV.EFLC.FusionFix#690]
### Game version this happens in

v1.2.0.59

### What area of the game

Whole game

### What should happen

Remember, i write issue about character shadow, which appears when climbing out from car animation ends with night vehicle shadows option turned on? Well, it was fixed, but only for newest steam version, while for 1.0.8.0 this problem wasn't solved. Despite all other new features work succesfully. 
I use original patched American license image with Xliveless.

Why don't i just play steam version? (yeah, i have purchased license steam version), well, there are many reasons:
First - long launch because of rockstar launcher, but that's ok
Second - what's not ok is that game sometimes just can't launch with mods installed, 1-3 times, randomly, i don't know why and when it happens, but after ANY small changes in game folder, or after rockstar's launcher update 100% game won't boot right away. 
Third - So, i launched the game, and i see, that it stuttering much more often, than 1.0.8.0, with both version with vulkan. Maybe, because steam and rockstar's launcher work in the background and load my ram, maybe because radio restorer causes it (i'm not sure yet, but have some suspicions). but i used one time pиrated steam version, and performance was much worse, than old versions, so the main reason just bad optimization, i think. 
My english not best, i apologize

https://github.com/user-attachments/assets/c93a3e38-c572-45a2-9305-d269b4ec0ff1

### Last working version

v3.0.5

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Tastycrabcakes41** [comment]
You know damn well Tomasak will politely tell you to go away. Why bother reporting this in the public repo if you're not using a better version of the game.

**Comment by ca5dx** [comment]
god if i had to take a shot of liquor for every retarded FF ticket that gets opened I'd of died of alcohol poisoning lord knows how many releases ago

**Comment by Tomasak** [comment]
Everyone is free to PR fixes backported to older versions, but as said above, noone from main FF team bothers to do so. So...
