### ISSUE TITLE
A bug with police hats

### ISSUE THREAD

**Issue by Andrey-Cutt** [ThirteenAG/GTAIV.EFLC.FusionFix#692]
### Game version this happens in

v1.2.0.59

### What area of the game

Police officers who are driving all the time do not have caps, but as soon as they get out of the car, sometimes they have caps, but if they get back into the transport, the caps will disappear again. At the same time, in the game you can meet patrolling policemen who walk and wear hats all the time. In some places, like the bridge to the closed city, the police don't wear hats all the time.
https://www.youtube.com/watch?v=TJA4ltBYfks
(Version FusionFix 3.5.0)

### What should happen

The police should always wear caps.

### Checklist

- [ ] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [x] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Tomasak** [comment]
1) this is not a bug caused by fusionfix
2) this is more of a design choice - either optimizations for consoles, or so that hats in general doesnt clip thru vehicle models.
