### ISSUE TITLE
Game textures turn white/snowy

### ISSUE THREAD

**Issue by PassTheBoof313** [ThirteenAG/GTAIV.EFLC.FusionFix#693]
### Game version this happens in

v1.2.0.32

### What area of the game

When I have fusion fix installed, all the textures turn white or snowy.
![Screenshot (6)](https://github.com/user-attachments/assets/6b875a65-6e9d-4f5a-8afd-7cf835c9ced9)
![Screenshot (5)](https://github.com/user-attachments/assets/51b9d83b-b95a-4faa-a128-8fd8182eb1c4)
I simply drag and dropped the files into the GTAIV directory, I'm running the Complete Edition on v1.2.0.32

### What should happen

The textures shouldn't be white/snowy

### Last working version

v3.5.1

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by juicermv** [comment]
It's christmas buddy

**Comment by Ash-735** [comment]
It's the snow feature, it gets automatically activated at end of December until New Years. To turn it off just do the same method you'd use to turn it on outside of Winter, dial the number on the phone. 766-555-0100

**Comment by SmithLam** [comment]
Damn this happens to me.
Thought it's a bug, cheers!
