### ISSUE TITLE
The opportunity to donate money to the homeless has been broken

### ISSUE THREAD

**Issue by Andrey-Cutt** [ThirteenAG/GTAIV.EFLC.FusionFix#696]
### Game version this happens in

v1.2.0.59

### What area of the game

If you give a homeless person money, he remains in the same begging animation. Money is taken away, but health is not replenished and the donation is not included in the statistics. The bug happens everywhere and does not depend on the place where the homeless person is located. 
https://www.youtube.com/watch?v=64RPXKJVBss

### What should happen

The character's health should be restored (the same will happen if you give money to a street musician) and the statistics will show that you donated money to a homeless person. The begging animation should also stop

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by sTc2201** [comment]
Not an issue with FusionFix.

Rockstar didn't include the animation necessary for the beggar interaction when they ported the game to PC.
Use [Various Fixes](https://gtaforums.com/topic/975211-various-fixes/), the mod restored the animation from the console version.
