### ISSUE TITLE
Pixel pavement textures

### ISSUE THREAD

**Issue by Andrey-Cutt** [ThirteenAG/GTAIV.EFLC.FusionFix#697]
### Game version this happens in

v1.2.0.59

### What area of the game

At a certain angle, the tile texture becomes highly pixilated
https://www.youtube.com/watch?v=AwDqkh0YTd4

### What should happen

It shouldn't be this way

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Ash-735** [comment]
That's not a Fusion Fix issue, just a general issue, it looks like the normal maps and spec maps used for that surface are pretty low res.
