### ISSUE TITLE
Overexposed road Textures

### ISSUE THREAD

**Issue by AOXsystems** [ThirteenAG/GTAIV.EFLC.FusionFix#699]
### Game version this happens in

v1.2.0.59

### What area of the game

It appears from version 3.0 and newer, on older versions there is no issue like this. Did clean install, tested few versions. All from 3 and newer have this, last working 2.5. From what I see textures are there, but they are just too bright. Same goes for dirt on vehicles. It isnt connected to assets themself, I tried combining(using assets from old version, and new .asi and config file)...the issue is in the .asi. 
setup:
- and radeon 6800xt 
- i9 10900k
![20241230034144_1](https://github.com/user-attachments/assets/b9121c3b-8276-47fd-a2a7-5135a3031734)
![20241230034908_1](https://github.com/user-attachments/assets/414d6fe1-a022-4283-a37d-ef9c47fd976d)

### What should happen

Load textures like before.

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by JB-Smiles** [comment]
I got the exact same issue, but I figure this must be some kind of bug/joke. Because this is just the snow mod being activated by FusionFix. To disable this type 766-555-0100 and the game will return to normal. Unfortunately, every time I restart the game I have to disable this effect again...

**Comment by IVorza** [comment]
Yeah. You can work around this by setting a date on Windows prior to December 30th and it will go back to normal. Maybe this is intended? Idk. Problem is that my game now crashes half of the times I try to launch it, with the snow enforced like this.

**Comment by AndrewJRichardson** [comment]
It would be nice to have the option to disable this in the menus. Otherwise you can't disable it till you get the phone from Roman and have to do it each time you boot the game.

I get that it's only on by default for a short period of time but it looks awful and makes it look like the game isn't rendering properly. It isn't documented either so I ended up uninstalling and reinstalling thinking it was broken. At which pointI realized it was coming from Fusion fix ,I still thought it was a bug causing textures to not render correctly rather than a feature though.

**Comment by AOXsystems** [comment]
> I got the exact same issue, but I figure this must be some kind of bug concerning an easter egg Fusion Fix added. It is just the snow mod being activated by FusionFix by default it seems. To disable this type 766-555-0100 and the game will return to normal. Unfortunately, every time I restart the game I have to disable this effect again...

Thanks, dialing  766-555-0100 fixed it. Guess it some kind of winter feature haha

**Comment by AOXsystems** [comment]
> It would be nice to have the option to disable this in the menus. Otherwise you can't disable it till you get the phone from Roman and have to do it each time you boot the game.
> 
> I get that it's only on by default for a short period of time but it looks awful and makes it look like the game isn't rendering properly. It isn't documented either so I ended up uninstalling and reinstalling thinking it was broken. At which point I realized it was coming from Fusion fix ,I still thought it was a bug causing textures to not render correctly rather than a feature though.

yea, spent over 2 hours combining files and trying to resolve this haha

**Comment by ThirteenAG** [comment]
A toggle for snow mode was planned after the "surprise" limited time event(similar to GTA online), although we are open to suggestions on how to implement it. Currently I think "Seasonal Events": On/Off would suffice, keeping the phone number as an easter egg. Alternatively, Snow: On/Off can be made directly.

**Comment by AndrewJRichardson** [comment]
Seasonal events on/off would be great :)

**Comment by P1casso** [comment]
Until which day? January 1st？

**Comment by ThirteenAG** [comment]
2nd.

**Comment by IVorza** [comment]
Love the seasonal events idea! 🤩
