### ISSUE TITLE
If possible, please port mouse deadzone fix to 1.0.8.0 compatible version of FusionFix

### ISSUE THREAD

**Issue by ImAciidz** [ThirteenAG/GTAIV.EFLC.FusionFix#7]
I have my game files from before the Steam update to The Complete Edition, so I still play on GFWL and such. I would seriously appreciate it if you could backport the mouse deadzone fix to the other branch of FusionFix compatible with 1.0.8.0. 

Sorry if this is not the correct place to ask, thank you for your time.

**Comment by ThirteenAG** [comment]
https://gtaforums.com/topic/934545-gta-iv-eflc-fusionfix/?do=findComment&comment=1071141450
