### ISSUE TITLE
Is this mod is compatible with Proton / DXVK / Linux / Steam Deck?

### ISSUE THREAD

**Issue by MartinPL** [ThirteenAG/GTAIV.EFLC.FusionFix#73]
Hello,

I dropped files like instruction tells / like in this [tweet](https://twitter.com/Ash_735/status/1672055233331994624/photo/1), but I don't get any FXAA toggle - maybe [DXVK](https://github.com/doitsujin/dxvk) and mod are not compatible?

Thanks!

**Comment by MehranAkbarii** [comment]
it is compatible with [DXVK](https://github.com/doitsujin/dxvk ) make sure that you are using latest release , native fxaa added in version 1.52

**Comment by ThirteenAG** [comment]
> Hello,
> 
> I dropped files like instruction tells / like in this [tweet](https://twitter.com/Ash_735/status/1672055233331994624/photo/1), but I don't get any FXAA toggle - maybe [DXVK](https://github.com/doitsujin/dxvk) and mod are not compatible?
> 
> Thanks!

Maybe the code that allows to use update folder gets overwritten by proton? Or you didn't enable asi loader?
Check this instruction: https://cookieplmonster.github.io/setup-instructions/#proton-wine

**Comment by MartinPL** [comment]
That's it, I didn't have a startup option on Steam
`WINEDLLOVERRIDES="dinput8=n,b" %command%`
