### ISSUE TITLE
MouseFix don't work

### ISSUE THREAD

**Issue by OgzYzc** [ThirteenAG/GTAIV.EFLC.FusionFix#8]
Hey, I just tried your fix on Complete Edition but whether I change "MouseFix" option between 1 or 0 it doesn't do anything. Other settings works perfectly though.

**Comment by ThirteenAG** [comment]
But um, what exactly did you expect it to do?

**Comment by OgzYzc** [comment]
Well, when I move my mouse slowly there is no registration in game.

**Comment by GlennMey** [comment]
The mouse fix works when aiming down sights, but camera movement and drive-by shooting doesn't. Hopefully this is fixable as well!

**Comment by kumikumi** [comment]
@ThirteenAG What do you mean, what did you expect it to do? How can you say you provide a mouse fix without knowing what it's supposed to do?!

Also, it did not work, and not when aiming down sights either.

**Comment by f0xeri** [comment]
Works only while aiming:(

**Comment by Naworm** [comment]
@ThirteenAG I guess can you can close the issue ;)
