### ISSUE TITLE
The cars headlights cannot cast a shadow of Niko.

### ISSUE THREAD

**Issue by b9348** [ThirteenAG/GTAIV.EFLC.FusionFix#83]
![1](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/41979647/79a4f80a-f0c0-4c90-aba5-72776f108005)
![2](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/41979647/fd6c79f3-4f60-4bb0-ad1b-c655cda9db29)

**Comment by RecklessGlue540** [comment]
This is due to FlickeringShadowsFix being enabled.
This disables the player and NPCs casting shadows under vehicle headlights.
It's to avoid the lamppost shadows disappearing at certain camera angles.
This can be closed.

**Comment by Tomasak** [comment]
As explained around, its a workaround
