### ISSUE TITLE
[Feature Request] Add mentions of RIL.Budgeted anywhere?

### ISSUE THREAD

**Issue by SandeMC** [ThirteenAG/GTAIV.EFLC.FusionFix#85]
It's not really hard to witness(moreso when you add mods):
![Taxi issue, visualized](https://steamuserimages-a.akamaihd.net/ugc/2003587608395382059/513826AE66059232F4F9D9AE102085531A93E108/)
Happens pretty much at any time during playing. There was a fix for that for the older patches - https://github.com/ClonkAndre/Simple-Traffic-Loader - but it obviously doesn't work on CE. Would it be possible to implement something of that sort for FusionFix?

**Comment by MagicAl6244225** [comment]
RIL.Budgeted is already in FusionFix. Add these lines to GTAIV.EFLC.FusionFix.ini and it will work.

`[BudgetedIV]
VehicleBudget=120000000
PedBudget=150000000`

VehicleBudget should be the size of vehicles.img plus any vehicle model and texture mods. Increase it when you see the taxi bug. Decrease it if you have the no-engine-sound bug.

**Comment by SandeMC** [comment]
Oh, thanks. It wasn't mentioned anywhere so I did miss it indeed. I'll close the issue after testing tomorrow, as I can't test at the moment.

**Comment by SandeMC** [comment]
So, yeah, the fix definitely works. But before closing the issue, consider adding mentions of RIL.Budgeted anywhere - as I doubt I'm the only one who completely missed this. So maybe either make it a part of the .ini by default, or mention it in the readme.md somewhere?

**Comment by ThirteenAG** [comment]
> Maybe just mention it on the readme.md for those who need it, then?

Then we will have people come in and complain they don't have car audio or something. I don't think original game requires this, so it's better to have a mention of this in the mods that make use of budget change. Also I heard that not using ped budget option doesn't introduce audio bug.

**Comment by SandeMC** [comment]
Fair, but then - how modders who make the vehicle.img mods are supposed to be aware of RIL.Budgeted being included into FFix? I personally think just mentioning it at the end somewhere with a sign of "be aware that this might cause issues" should be completely fine and people who shouldn't touch it, won't touch it - assuming they have enough braincells. Me personally, I'm not experiencing the audio bugs with the vehicle budget value set to 260000000

**Comment by MagicAl6244225** [comment]
Is it known what the default internal budgets in the game are? It might be helpful to include those values so users have a baseline of what normal is.

**Comment by SandeMC** [comment]
> ```
> [BudgetedIV]
> VehicleBudget = 0                          // may cause issues, set to e.g. 260000000 to increase budget limit
> ```
> 
> This fine?

I think some default values should be in there. Assuming the size of VehicleBudget should be in bytes, the default size of vehicles.img is `85622784` so maybe the default number should be around `100000000` or `86000000` for closest value to default size

**Comment by MagicAl6244225** [comment]
According to RIL.Budgeted's author [NTAuthority](https://gtaforums.com/topic/744584-reliv-rilbudgeted-population-budget-adjustertaxi-bug-fix/?do=findComment&comment=1066387282) the default limits were
`[BudgetedIV]`
`VehicleBudget=40000000`
`PedBudget=50000000`

**Comment by ThirteenAG** [comment]
What makes you think this value should be related to vehicles.img size at all?

**Comment by MagicAl6244225** [comment]
> What makes you think this value should be related to vehicles.img size at all?
You were in that GTAForums topic. 🙂
NTAuthority [said]([https://gtaforums.com/topic/744584-reliv-rilbudgeted-population-budget-adjustertaxi-bug-fix/?do=findComment&comment=1066513488)
> Set the vehicle count to the size in bytes of your vehicles.img, if you have sufficient VRAM to fit such.
What's included in the PedBudget is more vague.
>I'd assume it only includes componentpeds parts, and maybe playerped - at least, all dependencies of the ped modelinfo.<

I've understood it should be set approximately, not exactly. I adjust it in 10-million increments. Too high seems to encroach upon the audio budget for vehicles, so when engines go silent, go smaller.

It would be cool if realtime adjustments could be made in the settings menu based on need but IDK if it can take effect without restarting.

**Comment by ThirteenAG** [comment]
I see, then maybe it's just worth setting to vehicles.img size in runtime? Tho to me it doesn't make much sense, first of all because there's three vehicle.img the game uses, and second, we have cars in other imgs as well.

**Comment by MagicAl6244225** [comment]
Or perhaps more precisely, the default values plus the difference between vanilla .img and modded, based on just the asset load for the current game IV, TLAD, or TBoGT. A manual adjustment should remain in case there are issues. This method could also address the uncertainty of PedBudget, by using the default value plus the difference between ped/player mod asset total and vanilla total.

**Comment by Tomasak** [comment]
closing this, as it was readded to ini disabled by default and keeping opened [this issue](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/44)
