### ISSUE TITLE
Controller sniper Aim sensitivity too high with MouseFix = 1

### ISSUE THREAD

**Issue by davekho5454** [ThirteenAG/GTAIV.EFLC.FusionFix#88]
Seems like sniper aiming sensitivity was too high while im playing with Xbox Controller with MouseFix option on and the sensitivity back to normal with MouseFix off. Its just with sniper aiming issue other weapons didn't affected by the option.

**Comment by valentyn-l** [comment]
Also experiencing this on a controller

**Comment by Tomasak** [comment]
New RAW input option was added and mouse fix was removed, sniper seems to be behaving better now, comment in #263 for unlock if persist
