### ISSUE TITLE
GTAIV_ExtendVidMem does not work with Fusion Fix

### ISSUE THREAD

**Issue by Patrxgt** [ThirteenAG/GTAIV.EFLC.FusionFix#9]
Using Fusion Fix with GTAIV_ExtendVidMem is not possible because the file responsible for loading .asi files overwrites it. Maybe GTAIV_ExtendVidMem could be implemented in Fusion Fix?

**Comment by ThirteenAG** [comment]
1) Not my problem
2) Video memory detection is not broken (for me at least)
3) There's "-norestrictions" commandline

**Comment by ThirteenAG** [comment]
First, I can't fix bugs I don't have. Second, asi loader was made specifically so people would stop patching games from proxy dlls, what else do you expect me to do?

3) I heard otherwise, so I dunno.
