### ISSUE TITLE
Feature Request: Fix some visual bugs and restore some visual effects from the intro / loading screen.

### ISSUE THREAD

**Issue by anthoncast** [ThirteenAG/GTAIV.EFLC.FusionFix#91]
Already tried to notify Rockstar about this, but they are too busy updating GTA Online.

What visual issues am I finding? I posted this a time ago, and still happens. Even now that I switched to Windows 10. There's a weird shadow behavior where they render in front of you. Sometimes it renders miles away from you, and sometimes it renders in front of you, and you are more likely to see that when pressing C key to watch your back. Doesn't necessarily just happen when spamming the C key, it happens when you just do it once from time to time. Here's a video that could help (Although I played in 1080 version, this still happens in TCE): https://youtu.be/7rGNkm5Pqx0

In the other hand, something weird that happens when turning on the night shadows, is that, when the camera moves, especially can be seen during the first cut-scene, you can see how the water just flickers like crazy. This effect can be even noticed when the framerate is 60fps or lower, somehow higher fps hide this visual bug. You can see a video here (Again, it happens in TCE). https://youtu.be/SDjHoM9goJk

BTW, a restoration request I have is that, for some reason, in the intro cut-scene, you can see that text credits don't have transparency anymore, actually, they're solid white. Not a bad thing, but is an effect that I miss from older versions of the game. Also, have you noticed that the loading bar moves faster in newer versions too? I remember it was slower, and it wasn't that exaggerated in the newer versions.

**Comment by Tomasak** [comment]
and opened rest in issue list
