### ISSUE TITLE
minor but noticeable imperfections

### ISSUE THREAD

**Issue by Dr1Ft3RXII** [ThirteenAG/GTAIV.EFLC.FusionFix#97]
water tends to disappear flickering raindrops do not appear on the surface but you can see them in the pause menu and they fall through roofs and walls the blur is too big an option to adjust the intensity similarly with the depth of field would be useful and I would be very grateful if you could add an adjustable motion blur I really miss this effect from the console, thank you in advance

**Comment by MagicAl6244225** [comment]
Are you using scripthook? Rain problems are a known effect.

**Comment by Dr1Ft3RXII** [comment]
yes i use

**Comment by Dr1Ft3RXII** [comment]
> Are you using scripthook? Rain problems are a known effect.

yes i use

**Comment by Tomasak** [comment]
Rain bug is caused by scritphook or scripthook dotnet. Expanded DOF option was added
