### ISSUE TITLE
[Bug] Not related to FusionFix but a Reflection Bug

### ISSUE THREAD

**Issue by Vampire-Chan** [ThirteenAG/GTAIV.EFLC.FusionFix#98]
As far I remember, in past I used to play GTA 4 with reflection on, and everything used to shine. But now I tried playing the game, the Vehicles, Water and the Wet Roads (during rainy weather) doesn't reflect at all.

See the screenshot below:
https://cdn.discordapp.com/attachments/899555275076435968/1130483322888400927/image.png
Vehicle has no Relfection. (Settings are High, except Shadows (Medium).

https://cdn.discordapp.com/attachments/899555275076435968/1130484305697718383/image.png
But the Weapon (holding M4A1) has. 

https://cdn.discordapp.com/attachments/899555275076435968/1130484719264469093/image.png
No matter what reflection settings are, game decides to stick with this kind of Reflections.

https://cdn.discordapp.com/attachments/899555275076435968/1130484834020638750/image.png
https://cdn.discordapp.com/attachments/899555275076435968/1130490832236068934/image.png
https://cdn.discordapp.com/attachments/899555275076435968/1130490832647094364/image.png

If you have any solution, please let me know :)

**Comment by RecklessGlue540** [comment]
Pretty late, but blame the ENB for that.
